### ISSUE TITLE
Issue running zellij x86_64-unknown-linux-musl on Alpine Linux

### ISSUE THREAD

**Issue by lanceschi** [zellij-org/zellij#1000]
Hello,

and thanks :100: for the awesome application!

I'm facing an issue as soon as I launch `zellij` (x86_64-unknown-linux-musl target) on Alpine Linux v3.14.3 (docker image).

Here's the stdout/stderr log:
```shell
Error occurred in server:
Originating Thread(s):
1. ipc_server: NewClient
2. pty_thread: NewTab

Error: thread 'pty' panicked at 'Could not find the SHELL variable: NotPresent': zellij-server/src/pty.rs:273
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
```

Here's the `/tmp/zellij-1000/zellij-log/`:
[zellij.log](https://github.com/zellij-org/zellij/files/7837728/zellij.log)

```shell
INFO   |zellij_client            | 2022-01-10 09:02:12.677 [main      ] [zellij-client/src/lib.rs:118]: Starting Zellij client!
INFO   |zellij_server            | 2022-01-10 09:02:12.680 [main      ] [zellij-server/src/lib.rs:186]: Starting Zellij server!
INFO   |zellij_server::wasm_vm   | 2022-01-10 09:02:12.731 [wasm      ] [zellij-server/src/wasm_vm.rs:86]: Wasm main thread starts
INFO   |zellij_server::wasm_vm   | 2022-01-10 09:02:12.731 [wasm      ] [zellij-server/src/wasm_vm.rs:226]: wasm main thread exits
```

**Basic information**

`zellij --version`: 0.24.0
`tput lines`: 61
`tput cols`: 238
`uname -av`: Linux 47c214e9cc55 5.4.0-92-generic #103-Ubuntu SMP Fri Nov 26 16:13:00 UTC 2021 x86_64 Linux
`cat /etc/*release*`: 
```shell
3.14.3
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.14.3
PRETTY_NAME="Alpine Linux v3.14"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

Any help appreciated

**Comment by jaeheonji** [comment]
Hi, @lanceschi !

This issue related following code:
https://github.com/zellij-org/zellij/blob/49af892970163707774400df9ba271557e53ee5a/zellij-server/src/pty.rs#L270-L276

Zellij refers to the `SHELL` environment variable to launch the default shell.
Maybe, since Alpine Linux is a lightweight Linux, the `SHELL` variable is probably not specified.

So, manually set the `SHELL` variable and try again!

```sh
export SHELL=<specific-shell>
```

**Comment by lanceschi** [comment]
Hey @jaeheonji,

thanks for the prompt reply. I overlooked that log line regarding the missing `SHELL` variable.
Just like you've suggested, it sufficed issuing the following:

```shell
export SHELL=$0
```
