### ISSUE TITLE
Can we decrease the relative font size of status bar?

### ISSUE THREAD

**Issue by ivaquero** [zellij-org/zellij#1004]
The status bar is very helpful, however it has sort of large font size for a laptop.

Could you please add an option to tweak the font size?

**Comment by imsnif** [comment]
Hey, unfortunately the font size is uniform in the terminal and is dictated by the terminal emulator. If you decrease it, it will decrease the font size of anything in the terminal.

I am thinking of adding a layout for advanced users that would not include the key hints and would take up less space. Stay tuned!
