### ISSUE TITLE
TUI app crashes when using termion::screen::AlternateScreen

### ISSUE THREAD

**Issue by kyoheiu** [zellij-org/zellij#1006]
**Basic information**

`zellij --version`: zellij 0.5.1
`tput lines`: 50
`tput cols`: 99
`uname -av` or `ver`(Windows):
Linux archlinux 5.16.0-arch1-1 #1 SMP PREEMPT Mon, 10 Jan 2022 20:11:47 +0000 x86_64 GNU/Linux

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
alacritty 0.9.0 (fed349aa)
felix 0.3.1

**Further information**
[felix](https://github.com/kyoheiu/felix) is a TUI file manager I'm developing, based on [termion](https://github.com/redox-os/termion), and it crashes as soon as I run it inside Zellij (in alacritty); it works perfectly with terminal emulators like alacritty or WezTerm. After isolating the problem, it seems that Zellij may not work well with termion::screen::AlternateScreen.

For example, Here is the termion sample [code](https://github.com/kyoheiu/termion_zellij_test). `Cargo run`, and when I press 1 or 2, the screen switches. However, in Zellij, sometimes the switching does not occur.

I don't know if this is purely due to termion's screen implementation or zellij's, but the example app works in tmux for instance, so I suspect it has something to do with zellij's.

I hope this report helps you in some way with this project.

**Comment by imsnif** [comment]
Hey @kyoheiu - sorry about the experience! Zellij usually handles this case well, but there might be a specific edge case here.

To help us debug this, could you follow the instructions in our ISSUE_TEMPLATE (it's what you see when you open the bug) and attach the relevant logs as well as the `tput cols` and `tput lines` of the terminal pane? This will allow me to more easily debug this.

Thanks!

**Comment by auronandace** [comment]
@kyoheiu are you really runnig zellij 0.5.1? The current zellij release is 0.24.

I just installed felix and launched it in zellij. It works.

**Comment by imsnif** [comment]
Oh my! I did not notice the version. Yes, this might totally explain this. Thanks @auronandace !! @kyoheiu - if you can check the latest Zellij it would be great.

**Comment by kyoheiu** [comment]
Ah, that's right... it seems I built zellij from source a long ago, and forgot about it. Thanks for taking your time! felix works well in the latest zellij.
