### ISSUE TITLE
Rename pane/tab unexpected behaviour on some input

### ISSUE THREAD

**Issue by dswij** [zellij-org/zellij#1009]
On `RenamePane` or `RenameTab` mode, zellij acts weird on some unexpected input. Special input such as `^L` (CR-L) or `^[\n^[$` (ALT-ENTER) resulted in broken rendering. See screenshot for reference.

zellij.log does not show any interesting information:

```
INFO   |zellij_client            | 2022-01-15 12:41:48.738 [main      ] [/home/dswij/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-client-0.24.0/src/lib.rs:118]: Starting Zellij client!
INFO   |zellij_server            | 2022-01-15 12:41:48.747 [main      ] [/home/dswij/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.24.0/src/lib.rs:186]: Starting Zellij server!
INFO   |zellij_server::wasm_vm   | 2022-01-15 12:41:48.798 [wasm      ] [/home/dswij/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.24.0/src/wasm_vm.rs:86]: Wasm main thread starts
INFO   |zellij_server::wasm_vm   | 2022-01-15 12:42:12.172 [wasm      ] [/home/dswij/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.24.0/src/wasm_vm.rs:226]: wasm main thread exits
INFO   |zellij_client            | 2022-01-15 12:42:12.172 [main      ] [/home/dswij/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-client-0.24.0/src/lib.rs:342]: Bye from Zellij!
```

**Basic information**
`zellij --version`: 0.24.0

**Further information**

Repro:

1. Go to `RenamePane` or `RenameTab` mode
2. Hit keystrokes that send special chars (such as `CTRL-L`)
3. Weird lines drawn

---
*rename-pane*
![image](https://user-images.githubusercontent.com/44697459/149609345-0c6fdee9-2908-415f-8ac5-3724e3b60420.png)

*rename-tab* 
![image](https://user-images.githubusercontent.com/44697459/149609581-9ef8b731-4f4c-48c5-9437-6cf6339bd1d2.png)

**Comment by jaeheonji** [comment]
Good catch! I looked at the code that was causing the problem.

https://github.com/zellij-org/zellij/blob/6af419528f019ad603bedb8d0f564a569ba3e77a/zellij-server/src/screen.rs#L605-L615

The problem is that the `control code` is included in the process of matching the key code.
I'll take a look at this issue! Thank you 😸
