### ISSUE TITLE
Confusing tips on `RenamePane` or `RenameTab` mode

### ISSUE THREAD

**Issue by dswij** [zellij-org/zellij#1010]
When in `RenamePane` or `RenameTab` mode, the tips is `<Enter> when done / <ENTER> Select pane`, which is confusing since there are two `<ENTER>` action

![image](https://user-images.githubusercontent.com/44697459/149617878-a14c1454-519d-4767-aa2e-643fbfbc30e3.png)

**Comment by jaeheonji** [comment]
Obviously, the `<ENTER> Select pane` part can be confusing.
It seems that that phrase can be modified in the `status-bar` plugin.

In the details, the following functions in `seconds_line.rs`:
* `full_shortcut_list`
* `shortened_shortcut_list`
* `best_effort_shortcut_list`

I'll make this a **good first issue** for now!

**Comment by RobWalt** [comment]
@jaeheonji This can be closed
