### ISSUE TITLE
Request (completions): also complete sessions' names for 'attach' subcommand

### ISSUE THREAD

**Issue by FollieHiyuki** [zellij-org/zellij#1030]
This is pretty easy to do on the shell side. For example, in `fish`:
```fish
function __fish_complete_sessions
    zellij list-sessions | sed "/No active zellij sessions found./d"
end
complete -c zellij -n "__fish_seen_subcommand_from attach" -f -a "(__fish_complete_sessions)" -d "Session"
```

`zellij` generates completions from subcommands instead of providing the completion files and I don't know Rust :( so I'll leave this feature request here.

**Comment by a-kenji** [comment]
@FollieHiyuki,
Thank you for this awesome hint. I would love to integrate something like this.
Is there a way to get the same behaviour without sed?

**Comment by FollieHiyuki** [comment]
The sed command is just a hacky way to suppress the output when there is no active session (so that zellij only completes `options` and `help`).

Without sed, I'd suggest we move the `No active zellij sessions found.` output to stderr (make `zellij list-sessions` throws error and exit 1 when there is no session) and the function above can be changed to `zellij list-sessions 2>/dev/null` or something similar. This suggestion changes the behavior of zellij so it is subjective.

I can't come up with any better idea right now sadly.

**Comment by a-kenji** [comment]
@FollieHiyuki,
No, that is a great idea. Thank you.

> Without sed, I'd suggest we move the No active zellij sessions found. output to stderr

That is actually something I wrote on my whiteboard today, since I played around with the `attach` subcommand earlier. So it is quite awesome that this would also help this issue here.

**Comment by a-kenji** [comment]
@FollieHiyuki,
I just added it to main.
So you could try it out now, or wait for the next release.
Please don't hesitate reaching out again!

**Comment by FollieHiyuki** [comment]
@a-kenji I left some minor comments in the commit: https://github.com/zellij-org/zellij/commit/e2ce26121072adb8e4632f1f7de29a06f7e0662b#r68041355 and https://github.com/zellij-org/zellij/commit/e2ce26121072adb8e4632f1f7de29a06f7e0662b#r68041394

**Comment by a-kenji** [comment]
@FollieHiyuki,
Awesome, thank you so much!

**Comment by FollieHiyuki** [comment]
I think the same thing can be achieved with zsh since it can also take a command as argument list. I'm not familiar with zsh though.

Bash probably doesn't support this kind of completion.

**Comment by cyruseuros** [comment]
@a-kenji should this be opened as a separate issue for zsh
