### ISSUE TITLE
Zellij server crashes when killing X session

### ISSUE THREAD

**Issue by raphCode** [zellij-org/zellij#1040]
The zellij server crashes for me when the zellij session was startet from inside X and the X server is killed.

**Reproduction:**
The optional steps do not influence whether the crash happens.
1. Start X and a terminal emulator (I used alacritty)
2. from the terminal emulator, run `zellij`
3. (optional:) Detach from the session or close the terminal emulator
4. (optional:) Login to a framebuffer console (e.g. Ctrl + Alt + F2) and attach to session `zellij attach`
5. kill X server, I did `sudo systemctl restart lightdm` to restart my display manager
6. zellij session crashes

```
Originating Thread(s):
1. ipc_server: AttachClient
2. screen_thread: AddClient
3. plugin_thread: Update
4. screen_thread: Render
5. ipc_server: Render

Error: thread 'router' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })': /build/zellij/src/zellij-0.24.0/zellij-utils/src/ipc.rs:168
```
 
The crash does not happen when:
- zellij session was initiated from a framebuffer console (does not crash even if attached to an X terminal)
- the X session is exited gracefully by logging out (does not crash even if logging in again and killing X)

**Version information**
`zellij --version`: 0.24.0
`uname -av`: `Linux 5.15.12-arch1-1 #1 SMP PREEMPT Wed, 29 Dec 2021 12:04:56 +0000 x86_64 GNU/Linux`

**Comment by AutumnMeowMeow** [comment]
The error doesn't look like a signals thing, but on the off chance zellij is getting the signal that killed the X server, maybe 'setsid' could be part of a solution.  Some programs (e.g. 'script' grrr) send their kill to the entire process group.

**Comment by raphCode** [comment]
Mhh, systemd seems to kill all processes in the _control group_ when restarting services:
https://stackoverflow.com/questions/40898077/systemd-systemctl-stop-aggressively-kills-subprocesses
Also `man systemd.kill`

But from `systemd-cgls` it seems that `lightdm.service` is in another cgroup than the user sessions with the zellij server. Maybe I am reading this wrong, or both the user and lightdm cgroup are killed?
Simplified output:
```
-.slice
├─user.slice (#187)
│ └─user-1000.slice (#1870)
│   └─session-2.scope (#2068)
│     ├─   523 lightdm --session-child 12 19
│     ├─   549 xfce4-session
│     └─  1861 /usr/bin/zellij --server /run/user/1000/zellij/0.24.0/grieving-o…
└─system.slice (#55)
  └─lightdm.service (#1507)
    ├─ 445 /usr/bin/lightdm
    └─ 450 /usr/lib/Xorg :0 -seat seat0 -auth /run/lightdm/root/:0 -nolisten tc…
```
I am not sure if upon logout of the X session the zellij server process gets disconnected from the control group? Because after logout, X/lightdm restarts do not lead to the crash anymore.

**Comment by raphCode** [comment]
Amazing, even this issue should also be solved by https://github.com/zellij-org/zellij/pull/1351!
