### ISSUE TITLE
Zellij crash when selecting text

### ISSUE THREAD

**Issue by DMaxter** [zellij-org/zellij#1041]
Hello

I have detected a crash that is very simple to reproduce

**Basic information**

`zellij --version`: zellij 0.25.0 (`zellij-git` package on AUR)
`tput lines`: any
`tput cols`: any
`uname -av`: `Linux zirconium 5.16.5-arch1-1 #1 SMP PREEMPT Tue, 01 Feb 2022 21:42:50 +0000 x86_64 GNU/Linux`

List of programs you interact with as, `PROGRAM --version`:
`alacritty --version`: alacritty 0.10.0 (8a26dee0)

**Further information**
Steps to reproduce:
1. Open `zellij`
2. Select any area of the screen
3. CRASH

In the terminal we get these values
```
Error occurred in server:
Originating Thread(s):
1. stdin_handler_thread: AcceptInput
2. screen_thread: MouseRelease
3. plugin_thread: Update

Error: thread 'wasm' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeError { source: Trap(UnreachableCodeReached), wasm_trace: [FrameInfo { module_name: "<module>", func_index: 151, function_name: None, func_start: SourceLoc(87779), instr: SourceLoc(91222) }, FrameInfo { module_name: "<module>", func_index: 81, function_name: None, func_start: SourceLoc(48699), instr: SourceLoc(48883) }, FrameInfo { module_name: "<module>", func_index: 80, function_name: None, func_start: SourceLoc(48645), instr: SourceLoc(48693) }, FrameInfo { module_name: "<module>", func_index: 65, function_name: None, func_start: SourceLoc(41554), instr: SourceLoc(41675) }, FrameInfo { module_name: "<module>", func_index: 338, function_name: None, func_start: SourceLoc(210040), instr: SourceLoc(226578) }], native_trace:    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
 }': zellij-server/src/wasm_vm.rs:149
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: start_thread
  12: __GI___clone
  ```

I'm also attaching the log files generated
[zellij.log](https://github.com/zellij-org/zellij/files/8010677/zellij.log)
[zellij-9.log](https://github.com/zellij-org/zellij/files/8010678/zellij-9.log)

**Comment by tlinford** [comment]
Thanks for the report - there were some changes to the status bar plugin, I have a feeling we don't currently handle replacing plugins 100% correctly.

Can you try clearing your plugin directory  (by default `~/.local/share/zellij/plugins`) and see if that fixes it?

**Comment by DMaxter** [comment]
That fixed it, thank you
