### ISSUE TITLE
Add doc/user guide link in Readme

### ISSUE THREAD

**Issue by Enforcer007** [zellij-org/zellij#1055]
I haven't found user guide in Readme. Though there is a link that points to subsections like layout and plugin. Mentioning user guide link in Readme will be helpful for users to start from.

**Comment by a-kenji** [comment]
Hey! Thank you for reaching out.
There is a link to the documentation in the README, which is the user guide for us.

Here is a screenshot:

![image](https://user-images.githubusercontent.com/65275785/153717923-e03c5391-263f-42cc-beb9-770154fb0399.png)

**Comment by Enforcer007** [comment]
It skipped from my eyes 👀. Thanks for pointing 👉

**Comment by a-kenji** [comment]
No problem, that happens to everyone!
Please don't hesitate to contact us again, if you notice something.
