### ISSUE TITLE
Confusion around layouts, layout templates and global config

### ISSUE THREAD

**Issue by colemickens** [zellij-org/zellij#1058]
Can it be documented how global config, layouts and layout templates interact?

On #1039 there is an example given, but when I use it with `--layout-path`, it seems like the zellij plugins aren't active and thus I don't see the titlebars/ tab bars as hoped.

I tried to look at the docs to understand what I need to do, but I don't quite get it.

**Comment by colemickens** [comment]
>[configuration](https://zellij.dev/documentation/layouts.html#configuration)

> The layout supports all the configuration options from the [Configuration](https://zellij.dev/documentation/configuration.html) page.

I feel silly but I can't actually figure this out...

**Comment by colemickens** [comment]
Ohhh, it's just the bare config key name at the top level in the yaml. I was trying to do:

```
---
tabs:
  foo
  bar
configuration:
  pane_frames: true
```

**Comment by colemickens** [comment]
Last question: is there, or can we, set an env var inside the layout session?

I'd like to "hold" the terminal open after exit, and I figure I can just do that in the script I'm running, but maybe it's better as a feature req in zellij?

**Comment by colemickens** [comment]
Looks like that is: https://github.com/zellij-org/zellij/issues/707

**Comment by colemickens** [comment]
I can send a documentation update to show a tiny example snippet that will make this clear for all future folks.

**Comment by a-kenji** [comment]
> Ohhh, it's just the bare config key name at the top level in the yaml. I was trying to do:
> 
> ```
> ---
> tabs:
>   foo
>   bar
> configuration:
>   pane_frames: true
> ```

Oh, thanks! I will add an example to make it clearer.
