### ISSUE TITLE
byobu-enable Functionality

### ISSUE THREAD

**Issue by paulhey** [zellij-org/zellij#1091]
This is the continuation of a request from Reddit [direct link to comment](https://www.reddit.com/r/rust/comments/syodfg/comment/hxzapeb/?utm_source=share&utm_medium=web2x&context=3). I go by u/leftcoastbeard on reddit.

See the [byobu repo](https://github.com/dustinkirkland/byobu), specifically the scripts under /usr/bin/ . It looks like `byobu-enable` is a wrapper script that handles setting up byobu as a default login command with a chosen default shell. Not sure what this would look like for zellij.

**Comment by jaeheonji** [comment]
I don't know if I understood correctly. If you want to automatically run `zellij` when the shell starts, as in the purpose of `byeobu-enable`, you can create it with a simple shell script.

I'm `zsh` user, so I'm running it automatically through a simple script like this:
https://github.com/jaeheonji/zsh-zellij-plugin

**Comment by paulhey** [comment]
So your `zsh-zellij-plugin` is essentially what `byobu-enable` does, but just for `zsh`. `byobu-enable` works for a wide range of shells. One of the nice things about `byobu-enable` is that it's part of the `byobu` package and it more or less just "works" on most of the systems where I've used it without having to go and search the internet for a third party solution. I would imagine that if something like this were to be done for `zellij`, I would think it would likely be a combination of config-file options and command-line args/parameters/options that would do that work of creating the right simple shell scripts for the shell you're using for you.

**Comment by jaeheonji** [comment]
Yes, I understand. I looked again at`byobu-enable` and `byobu-launcher-install`.
Therefore, it seems that we can also provide an auto-start script corresponding to each shell using `zellij setup` command. (Even installing the script) I think this is a pretty good approach. How about this?

**Comment by paulhey** [comment]
That sounds good!

--
-- Paul Hey

**Comment by jaeheonji** [comment]
Cool! then, I will close this issue and open a new feature issue!
