### ISSUE TITLE
PATH / env variables seems to change when launching terminal with zellij

### ISSUE THREAD

**Issue by x4m3** [zellij-org/zellij#1093]
**Basic information**

`zellij --version`: `zellij 0.25.0` installed with cargo
`tput lines`: 45
`tput cols`: 183
`uname -av` or `ver`(Windows): Darwin m1ir.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101 arm64 (macos 12.2 on macbook air m1)

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
Homebrew 3.3.16
pass v1.7.4

**Further information**
Reproduction steps, noticeable behavior, related issues, etc

how to reproduce:
1. install homebrew the usual way (https://brew.sh)
1. install zellij via cargo
2. set zellij as the default command when opening a new terminal (i use iTerm2, but I got the same error with stock apple terminal)
3. attempt to use `brew` or any commands installed via homebrew for example `pass`

expected: the commands work
what i got (example): `zsh: command not found: pass`

After some search, it seems my PATH and some ENV variables change when I launch my terminal with Zellij, and it's fine with the default shell option.

here's a quick diff of `env` when I launch my terminal with and without zellij:

```diff
13c13
< PATH=/Users/phil/Library/Java/JavaVirtualMachines/liberica-1.8.0_302/bin:/Users/phil/Library/Android/sdk/platform-tools:/Users/phil/go/bin:/Users/phil/bin:/Users/phil/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/phil/.cargo/bin:/usr/bin:/bin:/usr/sbin:/sbin
---
> PATH=/Users/phil/Library/Java/JavaVirtualMachines/liberica-1.8.0_302/bin:/Users/phil/Library/Android/sdk/platform-tools:/Users/phil/go/bin:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Users/phil/bin:/Users/phil/.local/bin:/Users/phil/.cargo/bin
23,26c23,24
< ZELLIJ=0
< ZELLIJ_SESSION_NAME=cloistered-hate
---
36a35,39
> HOMEBREW_PREFIX=/opt/homebrew
> HOMEBREW_CELLAR=/opt/homebrew/Cellar
> HOMEBREW_REPOSITORY=/opt/homebrew
> MANPATH=/opt/local/share/man:/opt/homebrew/share/man::
> INFOPATH=/opt/homebrew/share/info:
```

If I launch my terminal with `tmux`, the commands work fine and the PATH and the ENV variables are there, so it seems to come from zellij, right? Unless I messed up somewhere, or homebrew is doing something unexpected.

So here's my question: does zellij touch the PATH/ENV variables in someway, or did I do something wrong? I'm expecting everything to work like before, since it works with `tmux` and the default shell (for me its `zsh`).

I'm happy to help if the issue comes from zellij, since it looks like a nice tool that I would use on a daily basis (I discovered it this morning on reddit on r/rust).

Thanks!

**Comment by jaeheonji** [comment]
> So here's my question: does zellij touch the PATH/ENV variables in someway, or did I do something wrong? I'm expecting everything to work like before, since it works with tmux and the default shell (for me its zsh).

Zellij does not directly access the `PATH` variable. Create only the `ZELLIJ` and `ZELLIJ_SESSION_NAME` variables.
It's probably due to settings related to homebrew. I'm using brew in a zsh environment like you. In my case, I run the following command in the `.zshrc` file:

```sh
...
# Homebrew for macOS
eval "$(/opt/homebrew/bin/brew shellenv)"
...
```

I'm using it with no issues in an environment like above.

**Comment by x4m3** [comment]
Thanks! That did the trick, sorry to open an issue for that if it was a problem in homebrew.

Cheers!
