### ISSUE TITLE
Send `Ctrl-b` to the pane when pressing `Ctrl-b` in tmux mode

### ISSUE THREAD

**Issue by OriginCode** [zellij-org/zellij#1095]
This behavior can help use the tmux inside zellij,for example:
![圖片](https://user-images.githubusercontent.com/17294071/155248746-e05f9370-311a-4978-b6a5-1c276b23cf7c.png)

**Comment by imsnif** [comment]
Just to be clear: this is a bug. I'm not sure why this isn't working right now and it bears some investigation. Thanks for reporting this!

**Comment by a-kenji** [comment]
> Just to be clear: this is a bug. I'm not sure why this isn't working right now and it bears some investigation. Thanks for reporting this!

It is not the locked mode, that's why it's not working.

**Comment by imsnif** [comment]
@a-kenji - I think we might be misunderstanding each other. In this case, as opposed to other modes, since we're trying to emulate tmux behaviour, we want to be able to send ctrl-b to the terminal itself. So that users would be able to (for example) run tmux inside a Zellij pane. I don't think it would be right to have ctrl-b toggle tmux mode itself. Do you disagree?

**Comment by a-kenji** [comment]
@imsnif,
No, I do agree. I was answering:

> I'm not sure why this isn't working right now and it bears some investigation.

Locked mode and normal mode are treated differently from the other modes.

In main it is now possible to send `^b` to the pane through `^b-^b`, I have added an action that does just that: #1095.

**Comment by imsnif** [comment]
Aha, I see! Why do we need a specific action though? If the key isn't mapped, why isn't it just sent through?

**Comment by a-kenji** [comment]
I think you even implemented it, since people were complaining about keys being sent through while in a different mode from the normal mode. That was before the locked mode was implemented.

**Comment by imsnif** [comment]
I don't think it's fair to hold me responsible for things I did ;P

I guess you mean this? https://github.com/zellij-org/zellij/blob/main/zellij-utils/src/input/keybinds.rs#L216
IMO this is a bug. I think everything should pass through unless we catch it... what do you think?

**Comment by imsnif** [comment]
Wait wait! It's coming back to me now. This would actually be bad UX. I don't want to be able to type arbitrary characters while in a mode. Okay, that makes sense now. I think your solution is best. Sorry for the roundabout on this :)

**Comment by a-kenji** [comment]
> Sorry for the roundabout on this

No problem, it is good thinking about things more than once.
I also think it is a good solution.

> I think everything should pass through unless we catch it... what do you think?

Ideally I would like to have an attribute  we can add to modes at some point that will be able to recreate the locked, or normal mode out of arbitrary modes. But that is not a priority atm IMO.

**Comment by OriginCode** [comment]
@a-kenji 
It seems I still can't send `^b` while in tmux mode. (zellij 0.29.1)
![圖片](https://user-images.githubusercontent.com/17294071/166517547-0fd09f45-8c48-405d-b485-487ef4e540fa.png)
