### ISSUE TITLE
bottom has odd artifact in highlight indicator

### ISSUE THREAD

**Issue by casonadams** [zellij-org/zellij#1097]
### Requirements:
[bottom](https://github.com/clementtsang/bottom)
[alacritty](https://github.com/alacritty/alacritty)
zellij 0.25.0

### Steps to reproduce
start `zellij`
run `btm` from command line

### Expected Results
<img width="766" alt="image" src="https://user-images.githubusercontent.com/17597548/155275912-4a0e9964-93fa-41cf-a84d-7d97f74ccdfa.png">

Actual Results
<img width="766" alt="image" src="https://user-images.githubusercontent.com/17597548/155275869-9f98ec3c-7bf8-4424-ad26-4f2a8716ad22.png">

Notice the highlight indicator isn't escaping correctly.

**Comment by tlinford** [comment]
can be minimally reproduced with the attached file.
[btm.log](https://github.com/zellij-org/zellij/files/8149145/btm.log)
