### ISSUE TITLE
New Features don't seem to work in version 0.25.0

### ISSUE THREAD

**Issue by devanlooches** [zellij-org/zellij#1104]
I upgraded zellij to the version 0.25.0 and I see the new commands in the status bar. However, when I press ctrl + p and then w for example nothing happens.
I installed zellij with homebrew and I'm on a 2015 15-inch Macbook Pro with version 12.0.1
Any idea why its not working?

**Comment by imsnif** [comment]
Could it be that you're upgrading from a previous version with a config that unbinds keybindings? If so, you can read more about it in the release notes under "Upgrading from previous versions": https://github.com/zellij-org/zellij/releases/tag/v0.25.0

**Comment by devanlooches** [comment]
Your right the default configuration keybindings from the old version were still in my config file. I just deleted them and now it works. Thank you!
