### ISSUE TITLE
UI looks weird when using floating panes

### ISSUE THREAD

**Issue by ozsay** [zellij-org/zellij#1110]
Hey,
I tried the new feature "Floating panes" and got this glitch (macos terminal app):
![Kapture 2022-02-24 at 11 41 19](https://user-images.githubusercontent.com/3464930/155499719-d207f824-32ef-4c63-af69-3928521c7a2f.gif)

here is how it looks in alacritty:
![Kapture 2022-02-24 at 10 35 35](https://user-images.githubusercontent.com/3464930/155500015-8a75374f-44ee-4016-b376-6eae6a3fb444.gif)

Tested it in a few terminal emulators:
Working properly: alacritty, hyper and wezterm
Glitched: macos terminal and iTem2.

Attaching some debug information (for the tests in alacritty and macos terminal):
`zellij --version`: 0.25.0
`uname -av`: Darwin IL-C02D122LML85 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64
`tput lines`: 30 (for both tests)
`tput cols`: 180 (for both tests)

the logs don't show anything special (just the usual start-end events)

**Further information**

I see this in the UI in macos terminal and iTem2 (when floating panes are glitched):

#### iterm

![iterm](https://user-images.githubusercontent.com/3464930/155512084-52dcd4be-9010-4298-8b56-abe008457043.png)

#### macos terminal

![terminal](https://user-images.githubusercontent.com/3464930/155512116-5242fa54-87fc-4e51-9758-5b872d053032.png)

**Comment by imsnif** [comment]
Thanks for the report! I'm pretty sure this is related to https://github.com/zellij-org/zellij/issues/816

**Comment by ozsay** [comment]
well, since I tested the other issue and confirmed the fix.. I tested it for floating panes and it fixes it as well :)

**Comment by imsnif** [comment]
Thanks for confirming @ozsay ! I hope to be able to get to this fix ASAP
