### ISSUE TITLE
Floating Panes doesn't work

### ISSUE THREAD

**Issue by jJit0** [zellij-org/zellij#1114]
Hello,

After upgrading to zellij latest version v0.25.0 it seems the floating panes doesn't work for me!

When I press `ctrl+p` then `w` OR `ctrl+p` then `e` nothing happens! panes are still stacked.

Any ideas ?

**Comment by devanlooches** [comment]
Could this be what happened to me where the old configuration keybindings override the new ones? This is the issue I opened: #1104

**Comment by jJit0** [comment]
You're right!!! :smile:
After deleting the old `config.yaml` it worked!!!

Thank you :wink:

**Comment by a-kenji** [comment]
Just a small correction:
The old configuration keybindings didn't overwrote the new ones, that couldn't have been the case - they were new.

This only happened if you explicitly [disabled](https://zellij.dev/documentation/keybindings.html#to-unbind-the-default-keybindings) every single default keybinding with:
```
keybinds:
    unbind: true
```
