### ISSUE TITLE
Multiple sessions/windows

### ISSUE THREAD

**Issue by Dhamma-valence** [zellij-org/zellij#1115]
Is there any way to have multiple sessions, sort of analogous to how in tmux you can do `new-session $name` and have session A and session B, each with their own separate windows and panes.

 A is for things like htop, nethogs, and anything else that is used infrequently but still useful to keep in the background, and B is for normal shell stuff. They can be quickly toggled by doing `prefix A - S` which opens a tui menu, move up or down, press enter and you're in the new session.

**Comment by casonadams** [comment]
Not sure if this is what you are asking for here but here goes:

`zellij list-sessions` will list any open sessions.  
Sessions will only be open if you created one and then detached.  `Ctrl + o` `d`
To name sessions `zellij -s <session-name>` see: `zellij --help` for more options

To attach to the session `zellij attach <session-name>`

If you like the tmux bindings of `Ctrl + b` `d` you can add the following to `~/.config/zellij/config.yaml`

```yaml
keybindings:
    tmux:
        - action: [Detach,]
          key: [Char: 'd',]
```

**Comment by Dhamma-valence** [comment]
Thank you mate, this works beautifully. I would love to someday contribute with a simple little TUI for listing and switching between sessions quickly, perhaps in the form of a plugin.
