### ISSUE TITLE
Clipboard copy with external command loses focus on Zellij

### ISSUE THREAD

**Issue by har7an** [zellij-org/zellij#1121]
Thank you for taking the time to file this issue! Please follow the instructions and fill in the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

**In Case of Graphical or Performance Issues**

Not the case here.

**Basic information**

`zellij --version`: 0.25.0
`tput lines`: 26
`tput cols`: 237
`uname -av` or `ver`(Windows): Linux taf 5.16.10-200.fc35.x86_64 #1 SMP PREEMPT Wed Feb 16 13:28:00 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

List of programs you interact with as, `PROGRAM --version`:

- `wl-copy --version`: wl-clipboard 2.0.0

**Further information**

In the `config.yaml`, input `wl-copy` as `copy_command`. I assume that this works with other copy commands as well. As soon as the child process is spawned in `zellij-server/src/tab/copy_command.rs`, the terminal running zellij briefly loses focus. I only realize because I use `ddterm` as drop-down terminal and set it to minimize itself when it loses focus.

The result of making a selection with this setup is that as soon as I release the mouse, my terminal minimizes (because it loses focus). But the text is copied as expected. So the copying works nicely, but it somehow briefly loses focus... I'm not really sure what to do about it.

I tried adding `tempfile` to have the child read the input from the file rather than a pipe, but that isn't the cause of the problem. The focus is already lost after the child was spawned in the first place.

**Comment by imsnif** [comment]
@tlinford - any ideas?

**Comment by tlinford** [comment]
hey, that's pretty strange - I managed to quickly reproduce this, and noticed it also happens when doing something like `echo 'test' | wl-copy` directly in ddterm.
Did a little digging and found: https://github.com/bugaevc/wl-clipboard/issues/12, https://github.com/bugaevc/wl-clipboard/issues/91, so it seems like this may not be on us.

**Comment by har7an** [comment]
Oh right, now I remember... I was initially trying to use `wl-clipboard-rs`, but had to realize that it didn't work due to some ["focus-stealing hacks"][1] which explicitly are implemented only in the original `wl-clipboard` for compatibility. I think I just found out what that actually means... Alright, so this is definitely not related to Zellij. Sorry for the noise!

[1]: https://github.com/YaLTeR/wl-clipboard-rs/issues/8#issuecomment-542306717
