### ISSUE TITLE
How to share a plugin?

### ISSUE THREAD

**Issue by casonadams** [zellij-org/zellij#1125]
I modified the default `tab-bar` plugin to be a more simple tmux style status line.

https://github.com/casonadams/z-tab-bar

Wondering how to share this with the world?

**Comment by a-kenji** [comment]
Hey! This looks nice, maybe add a screenshot?

I have added it to our plugins overview [page](https://zellij.dev/documentation/plugin-overview.html).

**Comment by casonadams** [comment]
Maybe the plugin name isn't great and it should be `tmux-tab-bar`?
