### ISSUE TITLE
Missing documentation of default keybindings

### ISSUE THREAD

**Issue by johann-petrak** [zellij-org/zellij#1127]
One of the most annoying properties of tools like screen, tmux etc is that they have their own default keybindings for standard operations like e.g. just scrolling back in the output buffer. But with those at least the man page will tell me how to do it.

With zellij I was unable to find a complete documentation of which actions are supported by default and which default keys are used. 

Especially with scrolling through the output buffer this is annoying, there is no scroll bar to use with the mouse and apparently page up/down does now work either to scroll through a large output buffer.

**Comment by a-kenji** [comment]
Here is a link to the documentation:
![image](https://user-images.githubusercontent.com/65275785/155837966-e223b0de-191e-4d79-aa45-e54fdeaf99d5.png)

Here is a link to the configuration: https://zellij.dev/documentation/configuration.html
The keybindings: https://zellij.dev/documentation/keybindings-keys.html
The actions: https://zellij.dev/documentation/keybindings-actions.html
An example configuration: https://zellij.dev/documentation/keybindings-examples.html

```
zellij setup --dump-config
```

Will show you the default configuration.
Is there something specific you are looking for?

**Comment by johann-petrak** [comment]
I guess I was looking for a documentation page that basically contains what `zellij setup --dump-config` in a more human-readable format, but `zellij setup --dump-config`  is good enough.
