### ISSUE TITLE
Could we get shorter subcommand aliases? Esepcially "ls"  instead of "list-sessions"?

### ISSUE THREAD

**Issue by johann-petrak** [zellij-org/zellij#1128]
Seems a bit much to type such a long command for something needed so often.

**Comment by a-kenji** [comment]
Thank you for reaching out and opening an issue!
This indeed possible, try running:
```
zellij ls
```
I have even zellij aliased to zj, so for me that would be:
```
zj ls
```

**Comment by johann-petrak** [comment]
Thanks - sorry, I was just starting to use it and the documentation does not mention this: in "zellij --help/help" it would be good to show the possible aliases.

**Comment by a-kenji** [comment]
No problem, thanks for reaching out! 
There is already an issue that want's to implement the shortcuts into the help page.

**Comment by a-kenji** [comment]
Here is the issue: #918.
