### ISSUE TITLE
Session restore after detach always default to first tab

### ISSUE THREAD

**Issue by casonadams** [zellij-org/zellij#1132]
Steps to reproduce
- `zellij -s 0`
- create 2nd tab
- detach
- reattach

Expected results
Reattach in same state as just before detachment (Tab #2)

Actual results
Reattached in (Tab #1)

**Comment by jaeheonji** [comment]
Yes, you are right. I've been aware of this for a long time and tried to improve it, but couldn't because of some other problems.
And I recently resolved a related problem, and it appears that this can now be improved. Please be patient 👍
