### ISSUE TITLE
suggestion: missing tmux bindings

### ISSUE THREAD

**Issue by mimoo** [zellij-org/zellij#1152]
I really love the attention to details and the interface of zellij. I've always wondered how a terminal tool could be new user friendly and have tips and helpers on shortcuts, I think you found the perfect solution!

I would suggest a few things:

* If I press `ctrl-O`, for example, I would expect that `ctrl-G` would take me back to the menu instead of locking the interface (usually it's used to cancel the last pressed command).
* in tmux mode, I usually use `ctrl-O` to change tab, and `ctrl-space` to change the layout. They don't seem to work anymore.

**Comment by a-kenji** [comment]
Hey! Thank you for reaching out.
This is currently a limitation of a library that we are using.
We plan on addressing this at some point, but this will be quite an undertaking.

There are already a few issues that track it, namely: #357.
So I'll link the two issues.

Here you can see the combinations of keys that are being supported: https://zellij.dev/documentation/keybindings-keys.html#valid-character-combinations .

**Comment by a-kenji** [comment]
The last suggestion was quite clever I think,
if you are willing to rebind the keys of your terminal you can configure zellij to have close to the behaviour you are imagining.
