### ISSUE TITLE
Add: `action` to copy selected text

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#1153]
More discussion here: #627 .

Make it possible to persist the selection after a mouse release and then in turn copy the selection.

**Comment by tlinford** [comment]
Some infrastructure for for this should already be there, initially the mouse support pr had copy bound to an action.
I'm thinking the main thing would be to add an option to not copy and clear the current selection on mouse release.

**Comment by a-kenji** [comment]
Wow, that the infrastructure is already there is pretty exciting! That could set us up for a lot of awesome functionality.

> I'm thinking the main thing would be to add an option to not copy and clear the current selection on mouse release.

Yes, that would be a welcome option, I am just not sure what an ergonomic solution here could be.

**Comment by tlinford** [comment]
Just checked, the action is already in place - will add an option as discussed in #1192 to be able to have selection persist after mouse release.

**Comment by a-kenji** [comment]
Awesome, thanks! That sounds great.
