### ISSUE TITLE
Possible to detach other clients?

### ISSUE THREAD

**Issue by max-sixty** [zellij-org/zellij#1155]
I occasionally connect to my main Zellij session with a client on a machine with a smaller screen. When I return to my main machine, Zellij's window is smaller than the full terminal size.

Is there a way to detach the other clients? Here's the SO answer for tmux: https://superuser.com/questions/610608/detach-the-other-tmux-clients

Thank you very much for the excellent tool!

**Comment by jaeheonji** [comment]
> Is there a way to detach the other clients? Here's the SO answer for tmux: https://superuser.com/questions/610608/detach-the-other-tmux-clients

Does this mean that there is a feature to **detach** the client in specific session using zellij command?

If this meaning is right, unfortunately, that feature does not currently exist.

**Comment by a-kenji** [comment]
Hey! Thanks for reaching out, this does indeed not exist yet.
This is related to #413. If #413 is implemented, then this is possible.

**Comment by farcaller** [comment]
It looks like this feature is still not in 0.42.1?

**Comment by imsnif** [comment]
This is possible through the session manager (`Ctrl o` + `w` by default). There we can press `Ctrl x` to detach other clients. The above feature was never actually released because it had some design problems stemming from Zellij's architecture (namely that the CLI has no way of knowing which client is which and would inevitably end up making wrong decisions).

**Comment by YoraiLevi** [comment]
> This is possible through the session manager (`Ctrl o` + `w` by default). There we can press `Ctrl x` to detach other clients. The above feature was never actually released because it had some design problems stemming from Zellij's architecture (namely that the CLI has no way of knowing which client is which and would inevitably end up making wrong decisions).

Oh. welp I was looking for a kick all option
