### ISSUE TITLE
Home and End keys do not work in `helix` while using `zellij`

### ISSUE THREAD

**Issue by dannasessha** [zellij-org/zellij#1182]
`zellij --version`: `zellij 0.25.0`
`tput lines`: `45`
`tput cols`: `unknown terminfo capability 'col'`
OS: `arch linux` `5.16.11-arch1-2`

List of programs interacted with: 
HELIX `helix --version`
`helix v0.6.0`
ALACRITTY `alacritty --version`
`alacritty 0.10.1 (2844606d)`

log displays all `INFO` events, nothing stands out as wrong.

Running `helix` in `alacritty` without `zellij` I am able to use `Home` and `End` keys while in `helix`'s insert mode to navigate the cursor to the beginning and end of the line I am editing. Running `zellij` and then `helix`, using those keys in the same way appear to do nothing. I also tried locking `zellij`, but this does not change the behavior.

**Comment by colemickens** [comment]
I had opened one on the helix side a while back too, just to link them:  https://github.com/helix-editor/helix/issues/1694

**Comment by colemickens** [comment]
I use zsh, and it seems like I have manually set these bindkeys... at some point in forgotten history (in case its related):
```
bindkey "^[[H"    beginning-of-line
bindkey "^[[F"    end-of-line
bindkey "^[[3~"   delete-char
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
```

**Comment by a-kenji** [comment]
Some more information:

* alacritty:
`HOME`:
```
^[[H 	 27 0033 0x1b
 	 91 0133 0x5b
 	 72 0110 0x48
```
`END`:
```
^[[F 	 27 0033 0x1b
 	 91 0133 0x5b
 	 70 0106 0x46
```

* alacritty & tmux:
 `HOME`:
```
^[[1~    27 0033 0x1b
         91 0133 0x5b
         49 0061 0x31
        126 0176 0x7e
```

`END` :
```
^[[4~    27 0033 0x1b
         91 0133 0x5b
         52 0064 0x34
        126 0176 0x7e
```

* alacritty & zellij:
`HOME`:
```
^[OH     27 0033 0x1b
         79 0117 0x4f
         72 0110 0x48
```
`END`:
```
^[OF     27 0033 0x1b
         79 0117 0x4f
         70 0106 0x46
```

**Comment by tlinford** [comment]
Interesting, referring again to the xterm docs it looks like since https://github.com/zellij-org/zellij/pull/815 we are sending the `SS3 H` and `SS3 F` versions instead of the `CSI H` and `CSI F`  that we are getting from `alacritty` (https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-PC-Style-Function-Keys).
On the other hand tmux is sending the vt220 variants `CSI 1 ~` and `CSI 4 ~` (https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-VT220-Style-Function-Keys).
