### ISSUE TITLE
Ranger issues and then crash [compatibility]

### ISSUE THREAD

**Issue by 5c077m4n** [zellij-org/zellij#120]
https://user-images.githubusercontent.com/35409124/102870177-571eca80-4445-11eb-8487-aebcd6f35d2d.mov

When opening ranger and just pressing the down arrow key once the lines start to skip.
When pressing some more the program panics.
(This is done over a SSH connection, I hope that it shouldn't make a difference...)

**Comment by imsnif** [comment]
I think this should now be fixed. Could you please check, @5c077m4n ?

**Comment by 5c077m4n** [comment]
@imsnif Now that navigation works, but when I try to open a file then it shows and error: `[Errno 2] No such file or directory: 'file'`
(again this is over ssh)

**Comment by imsnif** [comment]
Hmm... I don't think the ssh should change things. This seems a little odd to me. Could you tell me a little bit more about your setup? This seems like an error from the application itself. Does it happen outside mosaic? Am I missing something?

**Comment by imsnif** [comment]
@5c077m4n ? Any thoughts?
