### ISSUE TITLE
Zellij eats part of prompt when command ends with (white)space

### ISSUE THREAD

**Issue by jovandeginste** [zellij-org/zellij#1206]
**Basic information**

`zellij --version`: 0.25.0
`tput lines`: 57
`tput cols`: 237
`uname -av` or `ver`(Windows): `Linux jo-desktop 5.13.0-30-generic #33-Ubuntu SMP Fri Feb 4 17:03:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
- `nvim --version`: NVIM v0.6.1
- `bash`: `5.1`

**Further information**
Reproduction steps, noticeable behavior, related issues, etc

* start zellij, with bash as shell (`/bin/bash --norc --noprofile`)
* echo a wide character (or have it in your prompt), some string, and end with a space
  * `echo 🕙 helloworld ` (there is a space after `helloworld`)
* start & quit vim (no need to open any file)
* all lines with a space *at the end*, are missing the last non-space characters
* this is not only the prompt-lines:
    if you `echo "🕙 helloworld "`, then that line itself will remain (final char is a `"`), but the echo'ed line will miss the `d`
* it's not only vim; it happens with any tool that goes fullscreen, and then returns to your previous content (eg. `nload`)

Before vim:

![image](https://user-images.githubusercontent.com/3170771/157864262-185434f7-9c25-4c31-bf0e-20078080592a.png)

After vim:

![image](https://user-images.githubusercontent.com/3170771/157864349-10bb8b6a-224e-4da1-a713-4c9a063920f2.png)

Probably related to #943 (which seems to be solved for me)

[zellij.log](https://github.com/zellij-org/zellij/files/8231704/zellij.log)
[zellij-9.log](https://github.com/zellij-org/zellij/files/8231706/zellij-9.log)

**Comment by tlinford** [comment]
Thanks for the detailed report. Did a little digging and it looks like this was introduced in 0.25.0, bisected it down to 821e7cbc5a9711173061a272dc0378fff1fe5596.

**Comment by imsnif** [comment]
> Thanks for the detailed report. Did a little digging and it looks like this was introduced in 0.25.0, bisected it down to [821e7cb](https://github.com/zellij-org/zellij/commit/821e7cbc5a9711173061a272dc0378fff1fe5596).

Yeah, we were doing some really wrong stuff with wide characters when rendering. I had to change lots of stuff there. All in all it fixed a lot of bugs, but makes sense that it also introduced others (likely by exposing them rather than creating them).

This is probably one of those "counts the number of characters in the row" rather than "counts the width of the row" issues. I must have missed it. Will try to take a deeper look sometime next week (unless @tlinford is feeling adventurous :) ).

**Comment by jovandeginste** [comment]
Have fun 😊

**Comment by jovandeginste** [comment]
Is there any progress here? Just curious.

**Comment by imsnif** [comment]
Honestly, I forgot about this. I do batches of bug fixes every week or two, will be sure to include this in the next one.

**Comment by jovandeginste** [comment]
Great, it's probably the most annoying issue I have (which says a lot about the great general quality of this tool!)

**Comment by jovandeginste** [comment]
It saddens me to see this has not made it in the 0.30.0 release :cry:

**Comment by imsnif** [comment]
Apologies! Thank you for bringing this it up though, I promise I have not forgotten. There's some pretty cool other stuff in the release though, so I hope it partially makes up for it.

**Comment by jovandeginste** [comment]
I will go through the release notes! However, since I use it for long running tasks, I can't just update it - I need to wait for a good moment.

And for clarity: I appreciate all your (plural you) work! As I said, this issue is the most annoying issue I'm facing, so.... :wink:

**Comment by imsnif** [comment]
Hey @jovandeginste - thank you very much for your patience (and the excellent troubleshooting as always). I issued a fix for this in main and ti should be released in the next version.
