### ISSUE TITLE
zellij session freezes after some time

### ISSUE THREAD

**Issue by fansari** [zellij-org/zellij#1209]
Normally I open some tabs (about twelve) and detach from my session after work.

The next day I attach the session again.

A typically thing that happens is in the course of the second day there is no response anymore from the keyboard. First I thought this might be some network issue.

But this is not the case: I can still ssh the VM.

I close PuTTY and try to attach again. Then this works for some minutes but then hangs again.

When I then ssh into the VM and try to attach the session it hangs at this point.

I can only kill the zellij process and start zellij with a fresh session.

As a workaround I now close the zellij session after work.

But this minimized the benefit of zellij sessions a lot since this would be my use case.

I have experienced this so far with zellij 0.25.0 and older versions.

**Comment by imsnif** [comment]
@fansari - there is a chance that `0.26.0` fixes this. If not, the main thing that I can think of that might cause this behaviour is some part of STDIN that we're not handling correctly (eg. some key combination or mouse movement/click). Can you maybe think of anything you did right before this happened?

**Comment by fansari** [comment]
No, I cannot remember anything special I did before this happened. But I will keep zellij 0.26.0 attached next week and check whether this will happen again.

**Comment by imsnif** [comment]
Sure, yeah - I hope @fansari will give us a ping if this happens again and we'll reopen.

**Comment by fansari** [comment]
So far freezing did not happen anymore.
