### ISSUE TITLE
copy content in mysql connection promt insert ~ at beginning and at the end

### ISSUE THREAD

**Issue by enigmarong** [zellij-org/zellij#1216]
when I paste `update table xxx set col = 'newval' where key = 'key1';` it become: `0~update table xxx set col = 'newval' where key = 'key1';1~`

![image](https://user-images.githubusercontent.com/97727141/158154626-966f6f15-931a-4633-b647-beecd5773efa.png)

**Comment by raphCode** [comment]
probably related / duplicate issue: https://github.com/zellij-org/zellij/issues/1218

**Comment by imsnif** [comment]
This should be fixed in `0.26.1`.
