### ISSUE TITLE
Panic on Tab open: PreopenedDirectoryNotFound

### ISSUE THREAD

**Issue by raphCode** [zellij-org/zellij#1217]
I tried to open a new tab, and the server crashed.
I was attached to the session from two clients at the same time, both running locally on the same computer as the server.
I did not update zellij between starting server and client.
```
Error occurred in server:
Originating Thread(s):
1. stdin_handler_thread: AcceptInput
2. pty_thread: NewTab
3. screen_thread: NewTab
4. plugin_thread: Load

Error: thread 'wasm' panicked at 'called `Result::unwrap()` on an `Err` value: PreopenedDirectoryNotFound("/tmp/zellij-1000")': zellij-server/src/wasm_vm.rs:282
```

zellij 0.25.0, installed from Arch repos
`uname -av`: Linux 5.16.10-arch1-1 #1 SMP PREEMPT Wed, 16 Feb 2022 19:35:18 +0000 x86_64 GNU/Linux

**Comment by tlinford** [comment]
was this a long running session (like more than 10 days)?

**Comment by a-kenji** [comment]
`/tmp` directories are not expected to be persistent on reboots, but until a reboot they are expected to be, or?

**Comment by tlinford** [comment]
Can reproduce this easily by starting zellij,  removing the `/tmp/zellij-1000` directory, and then opening a new tab.

**Comment by tlinford** [comment]
@a-kenji thought so too, but just found out about [systemd-tmpfiles](https://wiki.archlinux.org/title/systemd#systemd-tmpfiles_-_temporary_files)

**Comment by a-kenji** [comment]
@tlinford 
Thanks, that is interesting. I would have thought it would be better to specify which directories can safely be deleted, rather than blindly deleting everything unless a system specific safeguard is put in there.

We should recover from this error regardless, since we don't really rely on the data there.

**Comment by raphCode** [comment]
> was this a long running session (like more than 10 days)?

Measured in wall time most likely yes, although the computer was in suspend mode for some days so it depends on how you count it.

> I would have thought it would be better to specify which directories can safely be deleted, rather than blindly deleting everything unless a system specific safeguard is put in there.

I can understand the motivation, otherwise /tmp/ may fill up unbounded. That being said, it looks like setting the sticky bit on **files** is enough to omit them from cleanup:
https://github.com/systemd/systemd/blob/c7f0d9e5acef3f62db3640d5ab7446241c022b35/src/tmpfiles/tmpfiles.c#L720
https://github.com/systemd/systemd/blob/c7f0d9e5acef3f62db3640d5ab7446241c022b35/src/tmpfiles/tmpfiles.c#L744

---

> just found out about [systemd-tmpfiles](https://wiki.archlinux.org/title/systemd#systemd-tmpfiles_-_temporary_files)

I even found this some day about the XDG_RUNTIME_DIR:
https://wiki.archlinux.org/title/XDG_Base_Directory#User_directories

- May be subject to periodic cleanup.
- Modified every 6 hours or set sticky bit if persistence is desired.
- Can only exist for the duration of the user's login.

Not sure if this can lead to a problem sometime, maybe set the sticky bit there too?

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by tlinford** [comment]
nice find, thanks for looking into it, I can try and get the sticky bit set sometime in the next days, unless you want to give it a go?

**Comment by raphCode** [comment]
Not sure where all the relevant files are created, so I'll leave this one for you.

**Comment by a-kenji** [comment]
> I can understand the motivation, otherwise /tmp/ may fill up unbounded. 

I don't understand it. If you do it the other way around the `/tmp` will also not fill up unbounded. If you just delete the files that are safe to be deleted at runtime. But it doesn't matter we need to fix it regardless.

> I even found this some day about the XDG_RUNTIME_DIR:

This is an incredible find!
I think we should fix it there too.
I suspect this could be related to the bug, that leaves sessions unresponsive after a week of running #1209.

**Comment by raphCode** [comment]
> This is an incredible find!

Glad it is useful!

> If you do it the other way around the `/tmp` will also not fill up unbounded. If you just delete the files that are safe to be deleted at runtime.

Imagine a shared system with many (probably human) users, each of them might save lots of temporary data to /tmp. If I understand to your proposal correctly, these files cannot be deleted automatically unless they are explicitly marked as "safe to delete", thus filling up the drive?

> just found out about [systemd-tmpfiles](https://wiki.archlinux.org/title/systemd#systemd-tmpfiles_-_temporary_files)

This seems not even to be a systemd-only thing: `man 7 hier` says about `/tmp`:
This directory contains temporary files which may be deleted with no notice, such as by a regular job or at system boot up.

**Comment by a-kenji** [comment]
It's less of a proposal, but yes that would make more sense to me. To delete files that are safe to be deleted and only the files that are not safe would fill up the drive.

Even when setting the sticky bit, we should ideally recover from that situation.
