### ISSUE TITLE
Zoom in / zoom out, changing text size results in weird behavior 

### ISSUE THREAD

**Issue by denismaxim0v** [zellij-org/zellij#122]
I'm using gnome terminal so I'm going to give an example with it. If I do Ctrl Shift + i see the following
![Screenshot from 2020-12-22 16-50-23](https://user-images.githubusercontent.com/11789381/102901059-29cd1f00-443b-11eb-9c3c-a31ef4eb3d6f.png)
And then if I zoom out
![Screenshot from 2020-12-22 16-50-35](https://user-images.githubusercontent.com/11789381/102901094-318cc380-443b-11eb-86ca-dcd2e4b457d4.png)

**Comment by TheLostLambda** [comment]
Just a guess, but this might be a product of #34 ? I think that changing the text-size is effectively "resizing" the window by changing the number of columns and rows. I'm not sure if it's the same signal, but it certainly might be

**Comment by denismaxim0v** [comment]
Yes I think that is the case. Also as far as I see, most of the bugs/weird behaviors I'm encountering are related to resizing. I can take a look if no one is on it yet

**Comment by imsnif** [comment]
I think @5c077m4n is working on resizing

**Comment by imsnif** [comment]
Fixed in main
