### ISSUE TITLE
Git tagging is broken since `v.0.21.0`

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#1222]
Our current main is still tagged with `v.0.21.0` as opposed to `v.0.27.0`.

**Comment by a-kenji** [comment]
Maybe that is a problem on my side then,
when running:
```
git describe --dirty --tags
```
I get:
```
v0.21.0-252-g08d2014c
```
on the current main,
and pre `v0.21.0` the prefix was always the correct tag.

Maybe I don't understand tags well enough yet.

**Comment by a-kenji** [comment]
Maybe we are creating non release tags for releases?

From `git tag`
>  Tag objects (created with -a, -s, or -u) are called "annotated" tags; they contain a creation date, the
       tagger name and e-mail, a tagging message, and an optional GnuPG signature. Whereas a "lightweight" tag is
       simply a name for an object (usually a commit object).
       Annotated tags are meant for release while lightweight tags are meant for private or temporary object
       labels. For this reason, some git commands for naming objects (like git describe) will ignore lightweight
       tags by default.

**Comment by imsnif** [comment]
`git describe --dirty --tags` works as expected for me: "v0.26.0-11-g08d2014c"
Maybe it's about fetching the tags from the remote? (I think `git fetch --tags` should do the trick)
IF not... if you reclone the repo, do you have the right tags?

**Comment by a-kenji** [comment]
> Maybe it's about fetching the tags from the remote? (I think git fetch --tags should do the trick)

Oh yes, thanks that did do the trick!
