### ISSUE TITLE
Auto-start of Zellij results in infinite loop

### ISSUE THREAD

**Issue by leontepe** [zellij-org/zellij#1268]
I tried auto starting zellij in Alacritty (with `alacritty -e zellij`) but it creates an infinite loop.

I tried the same with tmux instead and it worked as expected.

Why is this?

I know this is not a "bug" per se with Zellij, but it makes me wonder what the architectural differences between Tmux and Zellij are that essentially make Zellij unsuited for terminal emulator auto-starts.

**Comment by imsnif** [comment]
`alacritty -e zellij` works for me... would you like to go into more details about the infinite loop you're seeing? Maybe we can find the cause?

**Comment by a-kenji** [comment]
In case you somehow configured your shell to autostart zellij, here is an example of how you can automatically do it in a shell: https://zellij.dev/documentation/integration.html .
