### ISSUE TITLE
Autostart not working with alacritty

### ISSUE THREAD

**Issue by jorian** [zellij-org/zellij#1273]
Very happy with Zellij, but one thing isn't working as expected. When I start Alacritty, I want it to open Zellij automatically.

I use ZSH and oh-my-zsh, and have the Zellij plugin installed and enabled in .zshrc. It's there where I also define `ZSH_ZELLIJ_AUTOSTART` to be set to true. However, Zellij isn't automatically started in Alacritty.

It does however work on VS Code. Zellij _is_ automatically started in VS Code, which is a bit annoying.

When I check the ENV `ZSH_ZELLIJ_AUTOSTART` in Alacritty, it is set to true, so that isn't the issue.

I use [this](https://github.com/jaeheonji/zsh-zellij-plugin) plugin.

Anybody have an idea what I'm missing?

**Comment by jaeheonji** [comment]
Hi! Actually, I'm not the Alacritty user, so I don't know the exact reason. However, I have confirmed that the latest version of `zellij` works well with wezterm, windows terminal, iterm2, etc.

So I think this is a problem related to setting up Alacrity.

**Comment by ken-matsui** [comment]
Hi @jorian,

How about setting the `shell` option on your `alacritty.yml`?

Here is my configuration:
https://github.com/ken-matsui/dotfiles/blob/5426a08732a79711ccd77e573e6c781ed3a3e207/.config/alacritty/alacritty.yml#L133-L138

This lets Zellij attach the first created session if exists or create a new session if no session exists.

**Comment by jorian** [comment]
Thanks, that seems to work, although I had to remove the arguments to `zellij` to make it work. Alacritty crashes when I leave the arguments in.

Now I still need to figure out how to prevent VS Code from opening zellij and just run a separate zsh session

**Comment by jaeheonji** [comment]
Try to check the `$TERM_PROGRAM` variable. If it's a vscode terminal, `$TERM_PROGRAM` will be "vscode".

**Comment by imsnif** [comment]
Hey, can we close this issue?

**Comment by jorian** [comment]
Yes, everything is fine now!
