### ISSUE TITLE
After disconnecting the only other client from a session, Zellij act as if there's still another connected client

### ISSUE THREAD

**Issue by colemickens** [zellij-org/zellij#1301]
The gist is:

Create a zellij session.
Attach to it from a second client.

Notice the UI changes to show focus from the extra client.

Disconnect the second client.

Notice the UI does not change back and still shows focus indicators as if multiple clients are connected.

**Comment by auronandace** [comment]
I get the same with the current release (0.27).

In my case I start a zellij session on my linux machine (inside alacritty 0.10.1).
On my windows laptop (Win10) I open a terminal (alacritty 0.10.1) and ssh to my linux box.
After disconnecting from the session it still appears as someone else is connected.
