### ISSUE TITLE
clicking the left mouse button will cause neovim inside zellij to enter visual mode

### ISSUE THREAD

**Issue by wertasy** [zellij-org/zellij#1309]
**Basic information**

`zellij --version`: zellij 0.27.0 (default config)
`tput lines`: 41
`tput cols`: 187
`uname -av` or `ver`(Windows):
Linux wert 4.19.112-2.el8.x86_64 #1 SMP Web Jun 10 09:04:49 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`nvim --version`: NVIM v0.7.0-dev+1400-g233014f92   (used the appimage release, with `set mouse=a`)
`xfce4-terminal --version`: xfce4-terminal 0.8.8 (Xfce 4.14)

**Further information**

Reproduction steps:
1. nvim --clean --cmd='set mouse=a' /tmp/zellij-45190034/zellij-log/zellij.log
2. click any word with the left mouse button

Noticeable behavior:
clicking the left mouse button will cause neovim inside zellij to enter visual mode.
![1649602074(1)](https://user-images.githubusercontent.com/28420454/162625171-b87599eb-d371-4bed-a441-ec18937dc07e.png)

**Comment by imsnif** [comment]
For me this behaves the same way as it does with vim open (with the `set mouse=a` setting) even without Zellij. I think this is a vim thing.

**Comment by wertasy** [comment]
> For me this behaves the same way as it does with vim open (with the `set mouse=a` setting) even without Zellij. I think this is a vim thing.

It seems that zellij converts the mouse single-click event to a double-click event, because double-clicking without zellij will make nvim enter the v mode, which is consistent with the situation of single-clicking in zellij.

**Comment by wertasy** [comment]
> For me this behaves the same way as it does with vim open (with the `set mouse=a` setting) even without Zellij. I think this is a vim thing.

It seems that zellij converts the mouse single-click event to a double-click event, because double-clicking without zellij will make nvim enter the v mode, which is consistent with the situation of single-clicking in zellij.

**Comment by tlinford** [comment]
as far as I can tell this changed between 0.26.1 and 0.27.0, I'm guessing the termwiz refactoring might have something to do with it.

**Comment by tlinford** [comment]
Debugged this a little, and what is happening now is that mouse button press events are getting repeated as well as mouse hold events.

**Comment by imsnif** [comment]
> Debugged this a little, and what is happening now is that mouse button press events are getting repeated as well as mouse hold events.

Ah, just saw this now. Could we maybe rig the repeater to only repeat mouse hold events then?
