### ISSUE TITLE
Clicking on tab bar starts scrolling up

### ISSUE THREAD

**Issue by raphCode** [zellij-org/zellij#1325]
Since v0.27.0, clicking on the tab bar starts scrolling up in the scrollback buffer. Alternatively, in vim with mouse mode enabled (`set mouse=a`), this starts scrolling up in the document.

Previously, the scrolling on the tab bar was only initiated when clicking and dragging on the tab bar. This behavior seems not right too, but wasn't a problem for me since nothing happened on simple clicks without moving the mouse.

The new behavior make switching tabs by clicking very annoying. As a workaround, using the scrollwheel on the tab bar works fine.

**Comment by tlinford** [comment]
Same problem as #1309

**Comment by imsnif** [comment]
As I mentioned in the other issue - wouldn't rigging the repeater to only send mouse hold events solve this?

**Comment by tlinford** [comment]
> As I mentioned in the other issue - wouldn't rigging the repeater to only send mouse hold events solve this?

Yes, except for the clicking and dragging part.

**Comment by imsnif** [comment]
Alright, I have a feeling we could tweak it to work - but it's not that important. We can totally disable it (or remove it altogether if you don't see us devoting time to this in the future).
