### ISSUE TITLE
Mouse-up event missed sometimes when selecting with click + drag

### ISSUE THREAD

**Issue by raphCode** [zellij-org/zellij#1334]
From https://github.com/zellij-org/zellij/issues/1322#issuecomment-1099216545

While clicking and dragging to select, in some cases zellij fails to detect the mouse-up event. The selection rectangle remains visible even though the physical mouse button has been released.
I found these hangs to occur more likely when dragging the mouse and releasing while still moving the mouse.

I am using alacritty.

This pairs badly with #1322 since CPU usage increases while zellij thinks the mouse is down.

**Comment by imsnif** [comment]
Do you have a way of reproducing this?

**Comment by tlinford** [comment]
I think I figured out what is happening here. Sometimes two mouse events arrive in the same read from stdin: HOLD and RELEASE.

The processing of the first HOLD event, starts the loop that will rebroadcast the events, and that prevents the callback being called again for the second RELEASE event. Only when stdin becomes readable again the poller loop exits and the RELEASE event is processed normally.

**Comment by matu3ba** [comment]
The most viable and standard strategy is to disable all external interrupts on default and only enable them in a controlled code section written to handle all sorts of interrupts interrupting interrupts and stuff like that or mask them accordingly.
Those sections also need atomic guards.

The alternative is to use a dedicated thread to handle interrupts like how pthread signaling works internally and most likely other code dealing with runtimes.
