### ISSUE TITLE
MacOS nerdfonts don't work

### ISSUE THREAD

**Issue by zbraniecki** [zellij-org/zellij#1344]
Hi,

I'm trying to get zellij to work on macos and I can't get the nerdfonts to work. I installed all of them via homebrew following https://gist.github.com/davidteren/898f2dcccd42d9f8680ec69a3a5d350e

Log:
```
zibi@bcd074196718 ~ % cat /tmp/zellij-504/zellij-log/zellij.log
INFO   |zellij_client            | 2022-04-25 20:04:26.783 [main      ] [zellij-client/src/lib.rs:123]: Starting Zellij client!
INFO   |zellij_server            | 2022-04-25 20:04:26.792 [main      ] [zellij-server/src/lib.rs:189]: Starting Zellij server!
INFO   |zellij_server::wasm_vm   | 2022-04-25 20:04:26.847 [wasm      ] [zellij-server/src/wasm_vm.rs:87]: Wasm main thread starts
INFO   |zellij_client            | 2022-04-25 20:04:29.191 [main      ] [zellij-client/src/lib.rs:357]: Bye from Zellij!
INFO   |zellij_server::wasm_vm   | 2022-04-25 20:04:29.191 [wasm      ] [zellij-server/src/wasm_vm.rs:165]: Bye from plugin 0
INFO   |zellij_server::wasm_vm   | 2022-04-25 20:04:29.192 [wasm      ] [zellij-server/src/wasm_vm.rs:165]: Bye from plugin 1
INFO   |zellij_server::wasm_vm   | 2022-04-25 20:04:29.192 [wasm      ] [zellij-server/src/wasm_vm.rs:213]: wasm main thread exits
```
**Basic information**

`zellij --version`: zellij 0.28.1
`tput lines`: 24
`tput cols`: 80
`uname -av` or `ver`(Windows): Darwin bcd074196718.ant.amazon.com 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

After installing all of the nerd fonts, I still don't see arrows (showing terminal and allacrity screens):

<img width="563" alt="Screen Shot 2022-04-25 at 8 09 40 PM" src="https://user-images.githubusercontent.com/449986/165148536-68689e90-f1af-49f6-9fa5-e6eb54e45716.png">
<img width="676" alt="Screen Shot 2022-04-25 at 8 09 54 PM" src="https://user-images.githubusercontent.com/449986/165148539-e0243f30-b68d-403b-8382-6f01cb4534dd.png">

**Comment by tlinford** [comment]
Just to make sure, did you configure your terminal emulator to use one of these fonts?

**Comment by zbraniecki** [comment]
ah, no, of course I did not. :) Might be a good addition to this doc - https://zellij.dev/documentation/compatibility.html#the-status-bar-fonts-dont-render-correctly

Switching to the nerd font indeed fixes the issue. 🤦 
Thanks!

**Comment by imsnif** [comment]
Can we close this issue?

**Comment by jinfagang** [comment]
@zbraniecki Hi, how do u switch to nerd in terminal? I ddin't find it even I installed it.

<img width="187" alt="image" src="https://user-images.githubusercontent.com/21303438/184473780-204d5c9c-9753-4e43-821d-f27a8c2439ab.png">
