### ISSUE TITLE
Zellij UI corruption with random bytes 

### ISSUE THREAD

**Issue by raphCode** [zellij-org/zellij#1345]
With the "correct" bytes written to the terminal it seems possible to corrupt the zellij UI :)

1. open zellij
2. split pane right
3. in the left pane run `cat /dev/urandom`
4. enjoy the show, after some seconds text spills over in the right pane

Example screenshot with an additional split below. This shows that it is only possible to corrupt the remainder of a line.

![image](https://user-images.githubusercontent.com/15750438/165165639-dde24bf0-b1e4-4721-9b61-bc66fcc51a36.png)

**Comment by imsnif** [comment]
This is a regression. It likely happened when we added floating panes. Hard to test all the edge cases here. I'll do a go-over this week and fix it.
