### ISSUE TITLE
Unwrap in `link_handler.rs`

### ISSUE THREAD

**Issue by totikom** [zellij-org/zellij#1354]
# Behavior:
After a long period of normal working (up to several days) zellij randomly crashes with this message:
```Error occurred in server:

  × Thread 'screen' panicked.
  ├─▶ Originating Thread(s)
  │   	1. screen_thread: Render
  │   
  ├─▶ At zellij-server/src/panes/link_handler.rs:55:51
  ╰─▶ called `Option::unwrap()` on a `None` value
  help: If you are seeing this message, it means that something went wrong.
        Please report this error to the github issue.
        (https://github.com/zellij-org/zellij/issues)
        
        Also, if you want to see the backtrace, you can set the `RUST_BACKTRACE` environment variable to `1`.
        
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })', /build/zellij/src/zellij-0.27.0/zellij-utils/src/ipc.rs:170:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The last time it happen on `paru -S`, so it can be caused by its output.

**Basic information**

`zellij --version`: `0.27.0`
`tput lines`: `106`
`tput cols`: `118`
`uname -av` or `ver`(Windows): `Linux Main-pc 5.10.105-1-MANJARO #1 SMP PREEMPT Fri Mar 11 14:12:33 UTC 2022 x86_64 GNU/Linux`

List of programs you interact with as, `PROGRAM --version`:
`alacritty --version`: `0.10.1 (2844606d)`
`guake --version`: `3.8.6.dev0`

**Further information**
Reproduction steps, noticeable behavior, related issues, etc

**Comment by tlinford** [comment]
Thanks for the report, and sorry for the crash - will try to get a fix out asap
