### ISSUE TITLE
Pasting certain text from clipboard into vim makes zellij freeze

### ISSUE THREAD

**Issue by har7an** [zellij-org/zellij#1366]
**In Case of Graphical or Performance Issues**

1. Delete the contents of `/tmp/zellij-1000/zellij-log`, ie with `cd /tmp/zellij-1000/` and `rm -fr zellij-log/`
2. Run `zellij --debug`
3. Recreate your issue.
3. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.

[zellij.log](https://github.com/zellij-org/zellij/files/8603420/zellij.log)
[zellij-11.log](https://github.com/zellij-org/zellij/files/8603423/zellij-11.log)

**Basic information**

`zellij --version`: 0.29.0, but happened on 0.28.1 as well
`tput lines`: 30
`tput cols`: 237
`uname -av` or `ver`(Windows): `Linux XXXXX 5.17.4-200.fc35.x86_64 #1 SMP PREEMPT Wed Apr 20 15:37:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
- `vim --version`: `Vi IMproved 8.2 (2019 Dec 12, compiled Apr 22 2022 00:00:00)`

**Further information**
Reproduction steps, noticeable behavior, related issues, etc

- Open any empty file in vim
- Enter insert mode
- Paste the content of the GNU GPLv3
- zellij freezes and never comes back

**Comment by har7an** [comment]
Some more information:

- OS: Fedora Silverblue 35 (35.20220429.0)
- Terminal: `ddterm` (GNOME extension, see here: https://github.com/amezin/gnome-shell-extension-ddterm)

- When pasting the GPLv3 into the plain terminal this doesn't happen. My terminal stutters for a short while, but zellij recovers and continues as normal (May be caused by zsh plugins though)
- Doesn't happen in nano at all
- Pasting the content of the GPLv3 paragraphs 1-7 causes the freeze, only pasting 1-6 works fine

**Comment by har7an** [comment]
@imsnif Sounds reasonable, thanks. Any ideas what else I should try to reproduce this?

**Comment by imsnif** [comment]
If you'd like to put some work into this (personally I'm not reproducing this yet, but haven't tried your exact setup), it would be cool to find out if this is about the length of text pasted or a specific character. Or a combination thereof.

**Comment by imsnif** [comment]
Also if it happens in other terminal emulators for you as well.

**Comment by har7an** [comment]
- The length of the text plays a role, but it isn't deterministic. When I repeatedly paste the same text (of specific length) some times it works, other times it doesn't. This calls for a statistical analysis...?
- Tried GNOME Terminal (Flatpak), same behavior.

I'll try to get back to this soon, I have some containers to play with for today.

**Comment by imsnif** [comment]
Thanks! No need to do a statistical analysis, I don't think it'll help us much :)

**Comment by raphCode** [comment]
Can reproduce on v0.29.0, Arch and alacritty. Needs about 3/4 of the GPL to produce a hang.
Hangs with `vim`, [`helix`](helix-editor.com/), but not `nano`, `emacs`. Weird.

**Comment by raphCode** [comment]
bisect:
first bad commit: [843bf58f513934e630c54706a762d230163cd438] fix(input): handle discontiguous STDIN input (#1119)

Tested with vim+alacritty+pasting the GPL
Before that commit, the performance doing that was horribly bad, but at least it did not lock up.
Not sure how much the unoptimized debug build influenced, but this what I experienced:
- zellij hangs for 2 seconds
- text is starting to appear slowly in vim, taking up to a minute for the whole GPL
- zellij needs another 30s - 1minute to catch up with mouse events, window resize events etc and may display graphic glitches while that
- all that with 100% single core utilisation

**Comment by tlinford** [comment]
Made some progress on this, some notes on what I found:

- could not reproduce with alacritty + vim, but noticed that vim was not enabling bracketed paste.
Something like `env TERM=xterm vim` makes vim enable bracketed paste and allowed me to reproduce.
- the bug does not happen if one skips writing the bracketed paste delimiters here:
https://github.com/zellij-org/zellij/blob/7b0a46f812f0c0f60068742ea2984b88b6ad8ed5/zellij-client/src/input_handler.rs#L109-L117

Did some debugging and found that when zellij freezes:

-  the screen thread  when handling the `ScreenInstruction::WriteCharacter` containing the pasted text, in `Tab::write_to_pane_id`, ends up calling and blocking on: https://github.com/zellij-org/zellij/blob/7b0a46f812f0c0f60068742ea2984b88b6ad8ed5/zellij-server/src/os_input_output.rs#L293-L295.
- while the screen thread is doing the write, the pty thread starts receiving bytes and sending them to the screen thread on a bounded channel (currently with capacity set to 50), eventually this fills up and causes the pty thread to block as well: https://github.com/zellij-org/zellij/blob/7b0a46f812f0c0f60068742ea2984b88b6ad8ed5/zellij-server/src/pty.rs#L217
- deadlock :)

I think this can happen even before 843bf58f513934e63, if one pastes a sufficiently large amount of text, but have not checked it out in depth.

I'm not sure why bracketed paste causes this change in behavior, and why the write would block in this manner until the pty read side gets emptied.

Also tried a couple of workarounds, that improve the situation, but don't solve it completely:

- writing the pasted text in chunks: improvement, but unreliable and stops working if pasting the gpl multiple times in a row for example
- increasing the bounded channel capacity: same problem

The real fix appears to be offloading the writing to a separate thread, to avoid blocking the screen thread and be able to keep processing screen instructions.
