### ISSUE TITLE
Clicking on the Tab Bar no longer switches Tabs in v0.29.0

### ISSUE THREAD

**Issue by raphCode** [zellij-org/zellij#1367]
Switching to different Tabs by clicking on them no longer works in v0.29.0

(Still an improvement over #1325 :D)

**Comment by imsnif** [comment]
@tlinford - is this a quick fix? We might want to release a patch version on this one

**Comment by tlinford** [comment]
oops!
> is this a quick fix? We might want to release a patch version on this one
yep, found the mistake!

**Comment by imsnif** [comment]
Thanks for the super quick turnaround on this @tlinford !!
