### ISSUE TITLE
Middle or right click creates weird persistent selections

### ISSUE THREAD

**Issue by raphCode** [zellij-org/zellij#1371]
Clicking right selects the clicked pane and displays a selection starting from the top until the clicked position. The selection persists, it is even possible to create multiple selections in different panes:
![image](https://user-images.githubusercontent.com/15750438/166438187-c889d677-2f1d-4747-af95-2da3a9e2a796.png)

Clicking with the middle mouse button does a similar thing, except it does not switch the active pane, so you can manipulate the selection in the active pane by middle-clicking in another pane. In the screenshot, middle-clicking in the right pane causes all lines down to the cursor position in the left pane to be selected.

In both cases, this only happens when the mouse button is released.
v0.29.1

**Comment by tlinford** [comment]
Thanks for the report, guess the previous fix was too hasty :(

**Comment by raphCode** [comment]
No worries, it doesn't break any functionality as far as I observed :D
