### ISSUE TITLE
Clicking on pane border sends mouse events to application

### ISSUE THREAD

**Issue by raphCode** [zellij-org/zellij#1376]
I tried to switch focus to a pane running vim with mouse mode enabled (`:set mouse=a`), but did not want to move the cursor position inside vim, so I avoided clicking in the pane and clicked on the pane border. This triggered some action in vim.

Maybe the underlying "problem" can even be transformed into a nice feature: Ctrl+clicking into a pane switches the focus to it, but does not send any mouse events to the application?

**Comment by imsnif** [comment]
I think we solved this, right?
