### ISSUE TITLE
Better document the Tab|Sync command

### ISSUE THREAD

**Issue by dwvisser** [zellij-org/zellij#1377]
I had to stumble my way through #395 to even realize that this is possible in Zellij. The issue text even steers me to Pane commands rather than the correct Tab commands. 

I would like this feature to be documented properly on zellij.dev, so others are aware of it.

**Comment by imsnif** [comment]
This has been implemented (thanks @dwvisser !) and is now even part of the built-in random tips to be discovered at runtime.
