### ISSUE TITLE
Characters written to console when Terminal.app is resized

### ISSUE THREAD

**Issue by al3xandru** [zellij-org/zellij#1381]
I can't tell if this is specific to my setup or not given I just noticed it today. When resizing the Terminal.app on macOS the following string is printed out `10;rgb:c5c5/c8c8/c6c6`

<img width="908" alt="image" src="https://user-images.githubusercontent.com/290841/166938906-e79b0008-c594-4773-8066-0b0ad83c39ce.png">

**Comment by al3xandru** [comment]
For the record (I've mentioned this on discord), after downgrading to 0.28.1, this behavior disappears so it is related to 0.29.1

**Comment by imsnif** [comment]
Hey, just a heads up - @tlinford and I debugged this and found a fix. PR to come soon. Thanks for reporting this and sorry once again for the experience!
