### ISSUE TITLE
When will Zellij support Windows?

### ISSUE THREAD

**Issue by zstg** [zellij-org/zellij#1391]
First of all, my heartfelt kudos to the dev(s) ! 

Zellij looks stunning, and I have it installed on all of my 3 WSL instances and my 2 Hyper-V machines 

**When will Zellij support Windows natively** ? Is it possible to compile it from source using Cygwin/MSYS?

**Comment by imsnif** [comment]
Hey, glad you like Zellij!

I suspect getting Zellij to work on windows will be a bit more involved than getting it to compile. Windows terminals (as far as I heard - I am no expert) work a little bit differently and we'll need to adapt Zellij to that.

At the moment, as far as I am aware, none of the maintainers even has a windows machine. So it's not very likely we're going to put time and do this work. That being said - I'm always happy to mentor someone from the outside who's willing to work on this provided they show enough commitment beforehand (this will be quite a task after all).

**Comment by zstg** [comment]
Thanks a lot!
Let me see if i can help

**Comment by humphreylee** [comment]
Apparently Wezterm has Windows version, with GUI some more. :)

**Comment by heaths** [comment]
Not sure which features you might be missing, but conpty - a pseudoterminal that unpins both conhost and Windows Terminal - is very capable. It was basically a fresh start for Windows 10 (at least any supports instances, maybe around TH2). Newer vims, for example, assume most of the features that other terminals had, and I've overridden some other config where its assumptions were a bit too conservative with no problems e.g., alternate screen buffers.

I think you'll find built-in terminals on Windows have greatly improved and should be on par with other terms in alt platforms.

**Comment by imsnif** [comment]
Thanks for the pointers! I don't think we're missing features, just working hands to implement them and working eyes to review them. More info in the sister issue (which I hope you'll all excuse, I'll close this one in favor of): https://github.com/zellij-org/zellij/issues/316

**Comment by balls-6g** [comment]
i think make a special shell for windows zellij may be easier
