### ISSUE TITLE
Load plugins from the web

### ISSUE THREAD

**Issue by imsnif** [zellij-org/zellij#1393]
Right now we are able to load plugins from the local filesystem. We should also be able to load plugins from an http(s) link leading to a compiled wasm file.

**Comment by keogami** [comment]
Hey! I am checking out zellij and found this tracker through the roadmap. I am interested learning how you plan on plugging up this potential attack vector where a user might load malicious plugins?

With `curl | sh` scripts, its fairly easy to check what the script does. But with a compiled binary, it will be much harder to see what the plugin does.

**Comment by imsnif** [comment]
Good question! This depends on https://github.com/zellij-org/zellij/issues/1395 - to give the user transparency into what the plugin will be allowed to do.

Otherwise, it's about the same answer as running any sort of compiled software on your machine. Don't run software you do not trust.
