### ISSUE TITLE
Create a plugin permission system

### ISSUE THREAD

**Issue by imsnif** [zellij-org/zellij#1395]
As we add more and more capabilities to Zellij plugins, we should create a permission system that will give users transparency into which permission this plugin requires (eg. file system access, session management, scrollback reading and manipulation) and the ability to grant them or not.

Depends on: #317, #771

**Comment by imsnif** [comment]
Now that this has become relevant, I'd like to flesh it out a bit more.

## A `request_permission` API call needs to be implemented
This will be an API call similar to the calls here: https://github.com/zellij-org/zellij/blob/main/zellij-tile/src/shim.rs
As its payload, it should receive a new `PluginPermission` enum:
```rust
// pseudocode
enum PluginPermission {
    ReadScrollback,
    ReadKeyboardInput,
    ReadCursorPosition,
    // ...
}
```

Whenever a plugin calls `request_permission(Vec<PluginPermission>)`, the plugins should render a special screen instead of the plugin UI, something like:
```
Plugin <plugin_name> would like permission to:
1. Read the viewport and scrollback from all panes
2. Read keyboard input
3. Read cursor position

Would you like to grant these permissions? (y/n)
```
Once the user presses `y` or `n`, the plugins should re-render themselves, and receive a new `Event::PermissionsGranted` or `Event::PermissionsDenied` event in their `update` method.

To render this temporary UI, we could utilize the `LoadingIndication` struct (and hopefully give it a better name!): https://github.com/zellij-org/zellij/blob/main/zellij-server/src/ui/loading_indication.rs

To receive user input when the permission request screen is open, we could implement the `adjust_input_to_terminal` pane method for `PluginPane`: https://github.com/zellij-org/zellij/blob/main/zellij-server/src/tab/mod.rs#L202

## We should check for permissions for the relevant `zellij_exports` API calls
We should place a `plugin_permissions` attribute (which will be a `HashSet<PluginPermission>`) in `PluginEnv`: https://github.com/zellij-org/zellij/blob/main/zellij-server/src/plugins/plugin_map.rs#L193

Which we should fill up with the granted permissions if the user pressed `y` to grant them. We should then check against these permissions in zellij_exports whenever we call the relevant method: https://github.com/zellij-org/zellij/blob/main/zellij-server/src/plugins/zellij_exports.rs

## Caching the user response
Once the user has granted permissions, we do not want them to have to do it every time the plugin loads (or requests permissions). To do this, we should cache the response in our cache and read it every time before we request permission. If there is a response, we should use it.

**Comment by alex35mil** [comment]
@imsnif Hi, I'm trying to update my little status bar plugin, and I'm not sure how to handle user input to accept the permission request as the plugin isn't supposed to have any user input.

![CleanShot 2023-09-16 at 19 57 57@2x](https://github.com/zellij-org/zellij/assets/4244251/9caa5ed6-d6c7-4a3a-8fd2-028d9b9c91a5)

**Comment by imsnif** [comment]
Hey @alex35mil - this is indeed a bit of a tricky issue which I'm not 100% sure about the best way to get around (since the `set_selectable` command is something the plugin does explicitly and I would like to respect it).

The best way would probably be to use `set_selectable(false)` only after permissions were granted/denied using the [PermissionResult](https://docs.rs/zellij-tile/latest/zellij_tile/prelude/enum.Event.html#variant.PermissionRequestResult) event.

**Comment by alex35mil** [comment]
@imsnif What about introducing a command line argument? Something like: `--grant=</PATH/TO/PLUGIN>:Permission1,Permission2`?

**Comment by imsnif** [comment]
I'm a little wary of granting permissions to plugins in a non-explicit way by the user... these sorts of things can be sneaked into unrelated scripts.

Does the workaround not work well for you?

**Comment by alex35mil** [comment]
I haven’t looked into the suggestion tbh (afk atm). I think cli way is how it is usually handled when it’s impossible to interact, so I suggested that. I’ll look into your suggestion when I’m back to my machine. Thanks!

**Comment by alex35mil** [comment]
@imsnif [Worked](https://github.com/alex35mil/dotfiles/commit/60263dca635452a2650409a3c16fbac3fafb9ee3), thanks!
