### ISSUE TITLE
Strider plugin panics when double clicking in empty directory

### ISSUE THREAD

**Issue by jdygert** [zellij-org/zellij#1423]
- `mkdir empty && cd empty`
- `zellij --layout strider`
- double click in strider pane

Looks like it checks for `!self.files.is_empty()` with the key press but has no corresponding check with the mouse clicks, so it calls `traverse_dir_or_open_file` when you double click within an empty directory.

zellij 0.29.1

**Comment by jaeheonji** [comment]
Thanks for the reporting! I will fix it asap.
