### ISSUE TITLE
The default layout is not loaded.

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#1431]
The default layout is not loaded on the current main branch.

`zellij --version`: zellij 0.30.0

To reproduce:
- create a `default.yaml` inside the `ZELLIJ_LAYOUT` directory.
- run `zellij`

**Comment by imsnif** [comment]
How does it work then? Can you pinpoint where this issue comes from?

**Comment by jaeheonji** [comment]
@a-kenji

I think it seems to be related to #1413. I'll check it out too.
