### ISSUE TITLE
Characters dumped in terminal whenever I open Zellij

### ISSUE THREAD

**Issue by serain** [zellij-org/zellij#1439]
Whenever I open Zellij, I get some characters (related to setting colours) dumped:

<img width="612" alt="Screenshot 2022-05-29 at 18 52 49" src="https://user-images.githubusercontent.com/8275749/170884718-15c34350-ef6c-4c1d-990f-66582b75dbba.png">

From the logs:
```
❯ cat zellij-8.log
^[]11;rgb:2727/2828/2222^G^[]10;rgb:ffff/ffff/ffff^GWelcome to fish, the friendly interactive shell
Type help for instructions on how to use fish

~/.config/zellij 
❯ ]11;rgb:2727/2828/2222]10;rgb:ffff/ffff/ffff
^[]11;rgb:2727/2828/2222^GWelcome to fish, the friendly interactive shell
Type help for instructions on how to use fish

~/.config/zellij 
❯ ]11;rgb:2727/2828/2222]10;rgb:ffff/ffff/ffff⏎                                                                                                                                                             
```

**Basic information**

`zellij --version`: zellij 0.29.1
`tput lines`: 57
`tput cols`: 204
`uname -av` or `ver`(Windows): Darwin users-MacBook-Air.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
`fish --version`: 3.4.1

**Further information**
I use the Terminal.app shipped with MacOS, with `fish`

**Comment by serain** [comment]
I switched to Alacritty and no longer face this problem.

I still don't know what caused it.

**Comment by tlinford** [comment]
looks like you came across #1381, was already fixed in main.
