### ISSUE TITLE
Breaking zellij scroll while `ack -ir ls` with in the zellij root project

### ISSUE THREAD

**Issue by qballer** [zellij-org/zellij#1441]
Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.

**Basic information**

`zellij --version`: 0.29.1
`tput lines`:54
`tput cols`:186
`uname -av` or `ver`(Windows): Darwin C02FX1QMMD6R 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

`alacritty --version`: alacritty 0.10.1 (2844606)

**Further information**
```bash
git clone git@github.com:/zellij-org/zellij
cd zellij # no need if you have it
ack -ir ls # from this point scroll doesn't seem to work
```
![image](https://user-images.githubusercontent.com/1002622/171052824-0f43155f-1e86-4860-9cff-ffacdccf149e.png)
[zellij-9.log](https://github.com/zellij-org/zellij/files/8800550/zellij-9.log)
[zellij.log](https://github.com/zellij-org/zellij/files/8800551/zellij.log)

**Comment by imsnif** [comment]
This is not a bug, it's a feature :)

But in all seriousness - this works as expected. The Zellij repo has lots of snapshot files with ANSI codes we use for the tests. Some of those snapshot files include instructions such as `<ESC>[?1049h` which instructs your terminal to enter an alternative screen (which has no scroll), and do lots of other stuff. You can fix this (in this case) by doing `echo -e "\033[?1049l"` - or better yet - `reset`.

This also happens with bare alacritty/xterm/etc. without Zellij. It means the terminal is working properly.

**Comment by qballer** [comment]
that might explain some issues in my workflow :)
