### ISSUE TITLE
Feat: Log Reason, why Empty Message is send from a client.

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#1445]
Log Reason, why Empty Message is send from a client.

**Comment by raphCode** [comment]
As far as I understood the problem, noone really knows why this happens.
In the past we only ever saw messages like [`Io(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })`](https://github.com/zellij-org/zellij/issues/1326)

But yes, we could log that exact message.
