### ISSUE TITLE
Question: is there a way to persist session through reboot?

### ISSUE THREAD

**Issue by dycw** [zellij-org/zellij#1468]
Thanks for a great multiplexer!

I am wondering if `zellij` has some of the features of [`tmux-continuum`](https://github.com/tmux-plugins/tmux-continuum)?

**Comment by a-kenji** [comment]
Hey! 
This is not yet implemented, but it is already tracked here #575 
and it is on our roadmap: https://zellij.dev/roadmap/

Please don't hesitate reaching out in the future!

**Comment by dycw** [comment]
Thank you @a-kenji ! Feel free to close this issue, I'll be keeping track of #575 !
