### ISSUE TITLE
Feature Request: Support copy-mode-vi like tmux in Scroll mode

### ISSUE THREAD

**Issue by Xuyuanp** [zellij-org/zellij#1486]
Have read the doc and src, but not found the way to select and copy text using keys in Scroll mode.

Really appreciate your great work! I spent the whole day migrating my workflow from tmux, and this is the last things stops me fully switching to zellij.

**Comment by imsnif** [comment]
Hey @Xuyuanp - we just added a feature that lets you open the pane scrollback in your default editor. Then if eg. it's vim you can do all the copy/pasting with it (that's how I work now and it's a real pleasure). Do you think this can work for you as an alternative? It just feels to me like no matter how good we get the controls for a vim-like copy mode, it will never be good as using vim directly for this.

More info about the feature here: https://zellij.dev/news/edit-scrollback-compact/

**Comment by Xuyuanp** [comment]
Thanks!
