### ISSUE TITLE
put themes in a folder

### ISSUE THREAD

**Issue by omaya127** [zellij-org/zellij#1491]
I found that they put their theme script in a config.yaml, but can I put all the themes in a **themes** folder and add `theme: darcula` in my config.yaml?
```
├── config.yaml
└── themes
    ├── dracula.yaml
    ├── gruvbox.yaml
    ├── molokai.yaml
    ├── nord.yaml
    ├── one-half.yaml
    ├── solarized.yaml
    └── tokyo-night.yaml
```
It's somthing like this [example](https://github.com/zellij-org/zellij/tree/main/example), but it don't work.

**Comment by a-kenji** [comment]
This is a directory that contains example themes, layouts and configurations.
The directory itself is not the example.

https://zellij.dev/documentation/themes.html

The configuration should reside in your configuration file.

If in doubt you can check it with `zellij setup --check`

**Comment by omaya127** [comment]
Thank you, and could it be a new feature?

**Comment by omaya127** [comment]
@a-kenji Thank you, and could it be a new feature?

**Comment by a-kenji** [comment]
Hey @omaya127,

I can see value in having that as a feature.
If someone want's to contribute that, then I am sure we would consider merging it.

**Comment by jaeheonji** [comment]
I'm interested in this feature. I would like to implement it. I'll try to make a draft in the near future.

**Comment by omaya127** [comment]
@jaeheonji Thank you jaeheonji, I'm expecting for that!
