### ISSUE TITLE
always crashes on resize

### ISSUE THREAD

**Issue by dmd** [zellij-org/zellij#1551]
Is zellij supposed to do something reasonable if you resize the terminal? I find that it always, 100% of the time, crashes if you resize the terminal.

```
Error occurred in server:

  × Thread 'screen' panicked.
  ├─▶ Originating Thread(s)
  │   	1. stdin_handler_thread: AcceptInput
  │   	2. screen_thread: TerminalPixelDimensions
  │
  ├─▶ At zellij-server/src/screen.rs:490:46
  ╰─▶ attempt to divide by zero
  help: If you are seeing this message, it means that something went wrong.
        Please report this error to the github issue.
        (https://github.com/zellij-org/zellij/issues)

        Also, if you want to see the backtrace, you can set the `RUST_BACKTRACE` environment variable to `1`.
```

**Basic information**

`zellij --version`:0.29.1
`uname -av` or `ver`(Windows): Linux micc 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by raphCode** [comment]
Uh, that is pretty bad and should not happen. Thanks for reporting!

What terminal emulator are you using?

Crash location:
https://github.com/zellij-org/zellij/blob/a7ddfe1acc798adb4c8dfba2b674fd9e133b4c15/zellij-server/src/screen.rs#L490

**Comment by dmd** [comment]
Latest iTerm2 on Mac.

**Comment by dmd** [comment]
Sorry, same behavior in 0.30.0.

Here is an interesting clue:

1) start zellij
2) resize window
3) It crashes
4) start zellij
5) IMMEDIATE crash, without resizing

I have to logout/in of that ssh session before zellij works again.

**Comment by raphCode** [comment]
Between step 4 and 5, can you run `tput cols; tput lines`?
I suspect these are reset to zero size.

I can reproduce the same error message by running `stty rows 0 cols 0` before starting `zellij`.

**Comment by dmd** [comment]
Nope, they're not zero: https://shot.3e.org/ss-20220630_173722.mp4

**Comment by raphCode** [comment]
Mhh, even with my own reproducer with `stty rows 0 cols 0` `tput` reports non-zero values afterwards even though zellij crashes.
Not sure where tput gets its data from, it seems to make a TIOCGWINSZ ioctl like zellij.

You could try something like `stty rows 20 cols 20` after a crash, maybe zellij works again after this command?

**Comment by dmd** [comment]
Yes, zellij works after that command.

**Comment by imsnif** [comment]
Zellij seems to be getting a bad terminal window size report from the machine for some reason. We should handle it more gracefully, for sure.

@dmd - could oy help us out by testing some cases?

Could you issue `tput cols; tput lines` when:
1. Logging into the remote machine with ssh before starting Zellij
2. Logging into the remote machine with ssh, resizing the terminal window before starting Zellij
3. Immediately after the crash
4. After the crash and after resizing the terminal window

Thanks!

**Comment by raphCode** [comment]
I am still pretty sure a window size of zero is reported, just tput is doing more than we asking for: It queries the terminal database and reports a default size of 80x24 if the size read is zero. (Thanks @tlinford for noticing) This is also what happens in your screencast.

A better command is `stty size`. Just for the fun, you can try running it after a resize/crash and compare the output to `tput`.

Also please try the `resize` command (likely part of the xterm package) to see if it can recover the correct size after a window resize. If yes, we can implement its behavior and make zellij work for your case.

**Comment by imsnif** [comment]
Quite peculiar. I'm very curious how tmux works with this. Does it react properly to window changes? As in, expands or shrink to the window size?

**Comment by dmd** [comment]
Yes, tmux responds properly.

**Comment by tlinford** [comment]
no clue! I was more thinking of wether we should handle the case of rows/cols = 0 in a similar way by falling back to defaults, to avoid crashes?

**Comment by imsnif** [comment]
For sure! I just would also like us to be able to handle this as gracefully as tmux by just continuing to work :)

**Comment by raphCode** [comment]
> Oddly, _I have no idea how this could have ever worked_, because rows and cols are actually getting set to the empty string!

On my end, stty 9.1 does not even accept this:
```bash
$ stty rows '' cols ''
stty: invalid integer argument: ‘’
```

> @raphCode - any guesses?

Nothing really conclusive, but some thoughts on how it is possible to recover the correct terminal size despite the tty set to zero columns / rows:

There are sometimes window pixel sizes reported in addition to the terminal size in characters:
`ioctl(0, TIOCGWINSZ, {ws_row=19, ws_col=78, ws_xpixel=0, ws_ypixel=0}) = 0`
Here they are zero but I definitely saw non-zero values there on another machine. By diving by the pixel per character value the chracter size can be calculated.

The `resize` command in the man page describes that it uses a combination of tty ioctls ("stty syscalls") and "asking the terminal for size" using escape codes. Those CSI escape codes are answered by the terminal returning the size.
