### ISSUE TITLE
Alternative to Discord for development chat server

### ISSUE THREAD

**Issue by GPery** [zellij-org/zellij#1580]
Hello!
I've previously had success chatting in the Discord server, but recently Discord has been requiring me to input a phone number to use a "temporary" account. I'm not okay with providing such information to Discord given their [terrible privacy policy](https://discord.com/privacy), so I wanted to suggest an additional / alternative chat server.
I've really enjoyed other communities' Matrix servers, or Zulip (like rust-lang uses). It shouldn't be difficult to set one up and also allow a Discord bridge.
Any thoughts on the matter?

**Comment by a-kenji** [comment]
Thank you for reaching out.
I agree with you.
We do have a matrix space:
https://matrix.to/#/#zellij_general:matrix.org


It is advertised at the top of the `README.md`:
![header](https://user-images.githubusercontent.com/65275785/178151794-114ad1fd-f513-416b-a01f-9b66322e7bdc.png)

Do you have suggestions on how we can make this more clear?

**Comment by GPery** [comment]
Ah, you're right, I didn't notice.

- Under [How do I get involved?](https://github.com/zellij-org/zellij#how-do-i-get-involved) there's a link to the Discord chat, and not to Matrix
- In [Contributing to Zellij](https://github.com/zellij-org/zellij/blob/main/CONTRIBUTING.md#contributing-to-zellij) the Discord server is listed
- In the [Zellij home page](https://zellij.dev/) there's a link only to the Discord chat
- In the [plugin documentation](https://zellij.dev/documentation/plugin-other.html) there's a link to the Discord chat

I think these are all the references I saw to Discord while looking for an alternative, definitely weird that I didn't notice the links at the top of the README :sweat_smile:

**Comment by a-kenji** [comment]
@GPery,
Thank you for the information, I updated some of these links.
