### ISSUE TITLE
panic in server/src/screen.rs

### ISSUE THREAD

**Issue by matthiasbeyer** [zellij-org/zellij#1590]
**Basic information**

`zellij --version`: 0.29.1
`stty size`: 80 319
`uname -av` or `ver`(Windows): `Linux REDACTED 5.10.124 #1-NixOS SMP Wed Jun 22 12:13:21 UTC 2022 x86_64 GNU/Linux`

* konsole 22.04.1

**Further information**

![image](https://user-images.githubusercontent.com/427866/179253934-46c05b09-e72f-4bde-8984-e77512eec2db.png)

**Comment by nextzhou** [comment]
same issue for me
```
Error occurred in server:

  × Thread 'screen' panicked.
  ├─▶ Originating Thread(s)
  │   	1. ipc_server: AttachClient
  │   	2. screen_thread: AddClient
  │
  ├─▶ At zellij-server/src/screen.rs:664:14
  ╰─▶ called `Option::unwrap()` on a `None` value
  help: If you are seeing this message, it means that something went wrong.
        Please report this error to the github issue.
        (https://github.com/zellij-org/zellij/issues)
```

zellij version: 0.30.0
os: macOS Monterey 12.4
shell: zsh 5.9

**Comment by imsnif** [comment]
Does one of you have a way to reproduce this? consistently or not?

**Comment by matthiasbeyer** [comment]
Unfortunately no, me not at least.

**Comment by har7an** [comment]
The latest zellij release, 0.32.0, should now at least output descriptive errors when an error occurs in this part of the code (and some others). I'm closing this for now.

If you see it reappear with the new release, feel free to reopen it!
