### ISSUE TITLE
Feature: ESC should only bring the user one level up, rather than always to Normal mode

### ISSUE THREAD

**Issue by imsnif** [zellij-org/zellij#161]
Eg. when the user is in "resize input mode" (ctrl-g + r), right now pressing ESC leads back to the initial "normal input mode". Instead, it should lead back to "command input mode". Then, when the user is in "command input mode" - it should lead back to "normal input mode".
The locked state (mode_is_consistent in the codebase) should be maintained as-is until the initial normal state is reached.

A good place to start in the code base (at the time of writing): https://github.com/mosaic-org/mosaic/blob/main/src/common/input/keybinds.rs#L29

This will also require some changes in the tests, for example here (at the time of writing): https://github.com/mosaic-org/mosaic/blob/main/src/tests/integration/close_pane.rs#L359

**Comment by categorille** [comment]
short comment so that i can be assigned :)
