### ISSUE TITLE
after opening two horizontal panes sometime extra line remains on bottom

### ISSUE THREAD

**Issue by fansari** [zellij-org/zellij#1612]
Sometimes when I open two horizontal panes (Ctrl-p d)  and login into two devices and close the lower pane an extra line with prompt of the lower pane still as bottom line. Ctrl-L does not fix this.

An example where I can reproduce this behaviour is opening two horizontal panes and login into two Mikrotik routers . When I close the bottom pane I have still the prompt from this router as last line. Only fix I found is to close the tab and open a new one.

tested with v0.31.0

**Comment by fansari** [comment]
When will this be fixed? Today I had this issue even without logging into a router or switch.

**Comment by imsnif** [comment]
@fansari - I think it would be easier to fix (and thus also means we'll get to it sooner) if we have a way to reproduce this. I unfortunately don't have access to Mikrotik routers. It will be really helpful if you can:

1. Add a screenshot
2. Possibly (if I can't fully understand and reproduce this from the screenshot) follow the instructions in the issue template to add logs from each pane (be sure to include the size in colums/rows of each pane as explained in the template).

**Comment by fansari** [comment]
![zellij-pane-closed](https://user-images.githubusercontent.com/7888607/188454406-0a48c4a0-51a3-48ce-a008-8a2fb03eb28f.png)

In this case I have opened two vertical panes and logged in into two Arista switches. Then I logged out and closed the lower pane.

**Comment by fansari** [comment]
This only happens if:
- I produced some output on the screen (e.g. "show int status" for a swtich).
- I close the pane when on the lower tab. Closing the pane when on upper tab does not lead to this issue.

**Comment by mike-kfed** [comment]
I cannot reproduce that on 0.37.2 - that is after resizing my terminal window, see issue #2570 where I describe my weird behaviour with those routers.

**Comment by fansari** [comment]
I was unable to reproduce it with 0.37.2. Maybe this was fixed in some version.
