### ISSUE TITLE
UI shows old mapping

### ISSUE THREAD

**Issue by Integralist** [zellij-org/zellij#1614]
**Basic information**

`zellij --version`:zellij 0.30.0
`stty size`: 27 238
`uname -av` or `ver`(Windows): Darwin D3496LK9V7 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

**Further information**
I have the following configuration that unbinds the 'session' mapping from `Ctrl+o` (as Vim uses that for jumping back in its file history) but I noticed that the UI still shows `<o> Session`?

https://github.com/Integralist/dotfiles/blob/main/.config/zellij/config.yaml#L8-L10

<img width="132" alt="Screenshot 2022-07-29 at 14 17 50" src="https://user-images.githubusercontent.com/180050/181769631-5a2f7e20-fa45-4eaf-b0ea-f7c32178e3fa.png">

I would have expected this to change to the new mapping of `<v> Session`.

**Comment by a-kenji** [comment]
Thanks for reaching out @Integralist,
this should be fixed in the latest release `v31.0`.

**Comment by Integralist** [comment]
Thanks! 👍🏻
