### ISSUE TITLE
Box characters rendered very thin on alacritty

### ISSUE THREAD

**Issue by tranzystorekk** [zellij-org/zellij#1626]
Thank you for taking the time to file this issue! Please follow the instructions and fill in the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

**In Case of Graphical or Performance Issues**

1. Delete the contents of `/tmp/zellij-1000/zellij-log`, ie with `cd /tmp/zellij-1000/` and `rm -fr zellij-log/`
2. Run `zellij --debug`
3. Recreate your issue.
3. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.

**Basic information**

`zellij --version`: 0.31.0
`stty size`: 22 114
`uname -av` or `ver`(Windows): Linux vmware 5.18.14_1 #1 SMP PREEMPT_DYNAMIC Sun Jul 24 05:20:02 UTC 2022 x86_64 GNU/Linux

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`konsole --version`: konsole 22.04.3
`alacritty --version`: alacritty 0.10.1

**Further information**
Reproduction steps, noticeable behavior, related issues, etc

When using zellij on alacritty, I get thin and unappealing pane frames:
![obraz](https://user-images.githubusercontent.com/5671049/182118230-7828bc05-ae54-4c36-9375-21cd9b8a20d1.png)

For reference, this is how it looks on konsole:
![obraz](https://user-images.githubusercontent.com/5671049/182118363-83649f3e-379d-4a88-b4cf-935fbba61d64.png)

**Comment by raphCode** [comment]
To my understanding, the appearance depends on the font settings and rendering of the terminal emulator?
Zellij always sends the same unicode characters to draw its frames.

Maybe you can try setting the same font in alacritty as in konsole?

**Comment by tranzystorek-io** [comment]
> Maybe you can try setting the same font in alacritty as in konsole?

That's what I did, I tried to replicate my konsole config, and then tried tweaking the alacritty font settings further, but to no avail

**Comment by raphCode** [comment]
After some discussion, I gained more info around the bug:
Zellij sends escape codes to make the pane frame characters bold. alacritty seems to ignore this compared to konsole.

**Comment by tranzystorek-io** [comment]
https://github.com/alacritty/alacritty/commit/d9c6c8d53e95be2fe40162a1fcfe21b93fa0444b looks like this has been fixed and is pending release

**Comment by tranzystorek-io** [comment]
A workaround is to disable builtin box chars in alacritty config (`alacritty.yml`):

```yaml
font:
  builtin_box_drawing: false
```

**Comment by raphCode** [comment]
Oh nice, this wasn't even our fault :D

Should we close this then?

**Comment by tranzystorek-io** [comment]
I guess this warrants maybe a bug or feature request to alacritty upstream
