### ISSUE TITLE
lunch not working

### ISSUE THREAD

**Issue by somera** [zellij-org/zellij#1632]
**Basic information**

I wanted check zellij without installing it

`bash <(curl -L zellij.dev/launch)`

on Ubuntu and Kali Linux. But I get this

```
bash <(curl -L zellij.dev/launch)

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    40  100    40    0     0    184      0 --:--:-- --:--:-- --:--:--   185
100   699  100   699    0     0   1870      0 --:--:-- --:--:-- --:--:-- 20558
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     9  100     9    0     0     19      0 --:--:-- --:--:-- --:--:--    19

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
/proc/self/fd/11: Zeile 40: /tmp/zellij/bootstrap/zellij: Datei oder Verzeichnis nicht gefunden
```

error.

**Comment by imsnif** [comment]
We are just in the middle of a release right now, so the latest binary might need 20-30min to build. I think this is just bad luck with the timing! Can you try again in ~1 hour?

**Comment by somera** [comment]
> We are just in the middle of a release right now, so the latest binary might need 20-30min to build. I think this is just bad luck with the timing! Can you try again in ~1 hour?

Ok. Bad timing.

I try this later.

**Comment by imsnif** [comment]
This should work now. Please tag me if it doesn't and I'll reopen.

**Comment by somera** [comment]
It works. Thx!

**Comment by raphCode** [comment]
Falling back to the previous release would be the best option, but I am not sure how that can be achieved.
Currently the script relies on the `latest` link redirect of github to find the newest release, but I don't know of a functionality of finding the second-newest release.

In the mean time, I added some quick error handling: https://github.com/zellij-org/zellij/issues/1632
