### ISSUE TITLE
Default keyboard shortcuts conflict with shells' default keyboard shortcuts

### ISSUE THREAD

**Issue by jab** [zellij-org/zellij#1634]
Popular shells such as `bash` and `fish` come with a common set of keyboard shortcuts that are set up by default, and that users such as myself rely on constantly while using the shell in order to be more productive. Some of zellij's default keyboard shortcuts conflict with some of the default keyboard shortcuts that are common across these shells.

As a productivity enthusiast, I just heard about zellij for the first time and am really excited about it, but after trying it I immediately hit this issue. The first shortcuts I hit this with were Ctrl+P and Ctrl+N, which I use all the time to navigate backward and forward through my command history. (The up and down arrow keys can also be used for this, but these require taking your hand away from the home row on most keyboards, and so these are much slower, especially for users who touch-type like myself.)

Here is a list of bash's default keyboard shortcuts I just found, in case it helps: https://github.com/fliptheweb/bash-shortcuts-cheat-sheet 

If it's too late to change zellij's conflicting default keyboard shortcuts, would you consider offering users an easy way to enable a non-default, non-conflicting set of keyboard shortcuts?

(I searched the tracker and didn't find an issue about this, sorry if I missed it. Thanks for working on zellij and for your consideration!)

-----

**Basic information**

`zellij --version`: 0.31.1
`stty size`: (not relevant)
`uname -av` or `ver`(Windows): (not relevant but) `Darwin tsmbp.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Apr 18 21:50:40 PDT 2022; root:xnu-6153.141.62~1/RELEASE_X86_64 x86_64`

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`bash --version`: 5.1.16
`fish --version`: 3.5.1
`zsh --version`: 5.9

**Comment by imsnif** [comment]
Hey @jab - glad to hear you're excited about Zellij. We are very much aware of this issue and totally intend on devoting time to solve it one way or another in the not too distant future. There are of course some workarounds for the time being until we find a good default solution.

More info here: https://zellij.dev/documentation/faq.html#zellij-overrides-certain-key-combinations-that-i-use-for-other-apps-what-can-i-do

**Comment by jab** [comment]
Thanks for the link, will give that a shot! And good to know this is on your radar already. Is there an open issue I can watch to follow progress on this (and potentially chime in with any ideas that might help)?

**Comment by imsnif** [comment]
Sure, you can follow along here: https://github.com/zellij-org/zellij/issues/1399
