### ISSUE TITLE
New tabs/panes don't keep the current working directory

### ISSUE THREAD

**Issue by Integralist** [zellij-org/zellij#1641]
**Basic information**

- `zellij --version`: zellij 0.31.1
- `stty size`: 57 118
- `uname -av`: Darwin D3496LK9V7 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

**Further information**
I'm almost certain this _used_ to work (as not only would the current behaviour become immediately noticeable to me and annoying, but also I can see from [this PR](https://github.com/zellij-org/zellij/pull/691) that the expected behaviour was indeed implemented into Zellij) but it suddenly stopped, and I'm not sure what in my configuration ([here](https://github.com/Integralist/dotfiles/blob/main/.config/zellij/config.yaml)) would cause this.

**Comment by imsnif** [comment]
Hum - so, for me this still works in 0.31.1. Both in new panes and in new tabs.

Does it work for you if you load with the default config? (eg. if you do a `zellij setup --dump-config > /tmp/default.yaml && zellij --config /tmp/default.yaml`)

**Comment by Integralist** [comment]
OK looks like when I updated to the latest version the configuration had changed and so by dumping the new config and adding back in my own changes the problem disappeared.

**Comment by imsnif** [comment]
That's good to hear, though honestly I'm still a little worried about this. I wonder which part of the old config was causing this? If you feel like hunting it down that'll be great. Otherwise I'll try to find time for it myself.

**Comment by imsnif** [comment]
This is... very peculiar.

I'll try to dig into this more if I find the time. Thanks for the diff!
