### ISSUE TITLE
Crash when attaching when only "Tab 2" exists

### ISSUE THREAD

**Issue by Lucretiel** [zellij-org/zellij#1645]
Thank you for taking the time to file this issue! Please follow the instructions and fill in the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

**Basic information**

`zellij --version`: 0.31.1
`stty size`: 64 252
`uname -av` or `ver`(Windows): Linux ********** 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux

**Further information**

1. Run zellij.
2. Create a new tab, then close the first tab. There should be only 1 tab, called `Tab #2`.
3. Detach ungracefully by force-closing the terminal window
4. Launch a new terminal window, attempt to attach
5. Zellij crashes:

```
Error occurred in server:

  × Thread 'screen' panicked.
  ├─▶ Originating Thread(s)
  │     1. ipc_server: AttachClient
  │     2. screen_thread: AddClient
  │
  ├─▶ At /home/lucretiel/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.1/src/screen.rs:719:14
  ╰─▶ called `Option::unwrap()` on a `None` value
         0: <unknown>
         1: <unknown>
         2: <unknown>
         3: <unknown>
         4: <unknown>
         5: <unknown>
         6: <unknown>
         7: <unknown>
         8: <unknown>
         9: <unknown>
        10: <unknown>
        11: <unknown>
        12: <unknown>
        13: <unknown>
        14: <unknown>
        15: start_thread
        16: clone

  help: If you are seeing this message, it means that something went wrong.
        Please report this error to the github issue.
        (https://github.com/zellij-org/zellij/issues)

        Also, if you want to see the backtrace, you can set the `RUST_BACKTRACE` environment variable to `1`.
```

In case it matters, I'm running zellij on a server that I access via ssh from Windows Terminal on a Windows machine. The server itself is real hardware, not a VM.

**Comment by har7an** [comment]
Thank you for filing this issue!

I can reproduce this issue locally on a Linux machine, so it doesn't seem to be related to ssh.

Other things I noticed:

- If you leave the first tab open (have 2 tabs), kill the terminal and reconnect, everything works
- If you close the first tab and detach from the session, reattaching triggers the same error (So the terminal needn't be forcefully killed)

**Comment by Lucretiel** [comment]
> If you close the first tab and detach from the session, reattaching triggers the same error (So the terminal needn't be forcefully killed)

Oh interesting; I did a graceful detach (ctrl-o, d) and it seemed to be okay. Glad to hear it was easier to reproduce.
