### ISSUE TITLE
fonts not right

### ISSUE THREAD

**Issue by jinfagang** [zellij-org/zellij#1652]
<img width="280" alt="image" src="https://user-images.githubusercontent.com/21303438/184472863-a8419e2a-f1c5-4f1a-a852-2be654818b34.png">

already sintaleld powerline fonts.

Betteer mention the fonts in readme?

**Comment by jaeheonji** [comment]
Hi! There is already information about this in the [documentation](https://zellij.dev/documentation/compatibility.html#the-status-bar-fonts-dont-render-correctly).

If you have any other suggestions or issues, please re-open this issue.
