### ISSUE TITLE
[Question] Moving tabs

### ISSUE THREAD

**Issue by TornaxO7** [zellij-org/zellij#1654]
Is it possible to move the tabs around? Like if I have the following in my top statusbar:

```
<tab 1> | <tab 2>
```

is it possible to move `<tab 2>` to the left so it'll look like this?

```
<tab 2> | <tab 1>
```

**Comment by jaeheonji** [comment]
Unfortunately, zellij doesn't currently offer that feature.

But I think this is a nice feature. thanks!

**Comment by TornaxO7** [comment]
Ah good to know, I'll quickly look, if I could possibly add this feature.

**Comment by jaeheonji** [comment]
I will close this issue. Please leave any additional comments in the feature Issue!

**Comment by TornaxO7** [comment]
@jaeheonji Is it fine if I'm also trying to refactor a little bit the `Screen` struct? I'd like to move the `tabs` attribute to an extra-struct and move some methods of `screen` as well.
