### ISSUE TITLE
No umlauts on linux

### ISSUE THREAD

**Issue by geri1701** [zellij-org/zellij#1655]
I use a us keymap with the x11 variant altgr-intl so that I can write umlauts with the right alt key. Unfortunately, that doesn't work as soon as I start zellij, because then instead of the umlaut I only get  `<ffffffff><ffffffff>` .

**Comment by imsnif** [comment]
Hey @geri1701 - sorry for taking some time to get to this issue.
To reproduce this issue, I'm going:
1. `setxkbmap us altgr-intl`
2. Pressing `Alt` + `y` and getting ü

This works for me both inside and outside of Zellij. Are you doing something differently? Maybe there's another element in this setup we need to consider?

**Comment by geri1701** [comment]
Hey @imsnif,
 I'm using Arch here and using alacritty as the terminal. Configured the keyboard with the `setxkbmap -layout us -variant altgr-intl -option nodeadkeys` command here. Outside of zellij everywhere I get an `ü` if I press the `right Alt key and y`, the left one doesn't work here to get umlauts. As soon as I start zellij, when I press the key combination, only the string: `<ffffffff><ffffffff>` is output. Strange that it works for you, maybe we're actually missing something, but since the error only occurs in zellij, I suspect the solution to the problem would be found here.

**Comment by geri1701** [comment]
OK! I've gotten a step closer to the issue, it seems curiously to only occur in the combination `zsh` and zellij.

**Comment by geri1701** [comment]
No idea how that can be, but the error is triggered by having `export LANG=de_DE.UTF-8` in my `.zshrc`, as soon as I comment it out the umlauts also work in zellij.

**Comment by geri1701** [comment]
It was primarily a configuration error on my part, I had entered `export LANG=de_DE.UTF-8` in `.zshrc` but `de_AT.UTF-8` in `/etc/locale.gen`. Still strange that it only affected `zellij`.
