### ISSUE TITLE
Alt + <arrow keys> and Alt + <hjkl> don't override keybindings in Terminator 

### ISSUE THREAD

**Issue by seamyb88** [zellij-org/zellij#1657]
In the "terminator" terminal, switching panes using the Alt key doesn't work and I believe this is because it doesn't override the keybindings I have in Terminator.

I like the idea of being able to lock the keybindings, but if they're not being overridden it somewhat defies the purpose.

**Comment by imsnif** [comment]
Hey @seamyb88 - do you mean the keybindings that are part of Terminator itself? If so, unfortunately we can't really access them - as the terminal emulator runs Zellij and not the other way around...

**Comment by seamyb88** [comment]
Yes, but now I think these are keybindings I set myself a long time ago. I'll close this, it's the second issue I raised which isn't really an issue. I apologise.

Love the application though, looking forward to more!
