### ISSUE TITLE
zellij crashes when trying to open a file in strider and no $EDITOR is set

### ISSUE THREAD

**Issue by cvemys** [zellij-org/zellij#1667]
hello,
steps to reproduce:
1- ```unset EDITOR```
2- load strider plugin  with ``` zellij --layout strider```
3- try to open any  file 
![image](https://user-images.githubusercontent.com/48558638/184686081-fdcd97bd-fdd7-4efb-9f85-ba7c77793541.png)

**Comment by jaeheonji** [comment]
Thanks for leaving the issue.. However, this is an intended error at this point.
https://github.com/zellij-org/zellij/blob/d9d7ef3aefa568a1ddee7a40a9f622c7fda9bf0d/zellij-server/src/os_input_output.rs#L204-L211

If you have a good idea to cover this, please create a new issue or PR!
