### ISSUE TITLE
Strider Panics Opening File when Editor not Set

### ISSUE THREAD

**Issue by kapinga** [zellij-org/zellij#1672]
I just started trying out zellij today. I'm liking it generally, but ran into a repeatable crash in the strider plugin.

**Basic information**

`zellij --version`: `zellij 0.31.2`
`stty size`: `41 120`
`uname -av`: `Linux <hostname> 5.10.0-16-amd64 #1 SMP Debian 5.10.127-2 (2022-07-23) x86_64 GNU/Linux`

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`fish --version`: `fish, version 3.1.2`
zellij is running on a headless server, I'm accessing through ssh in Windows Terminal (Version: 1.14.1962.0).

**Further information**
I installed zellij from the latest GitHub release page this morning. I copied the binary into my $PATH.

To reproduce:
1. Make sure that `DEFAULT_EDITOR`, `$EDITOR`, and `$VISUAL` are not set
2. Run zellij with strider (e.g., `zellij --layout strider`)
3. Open any file in strider
4. Instant panic:
```
Error occurred in server:

  × Thread 'pty' panicked.
  ├─▶ Originating Thread(s)
  │     1. stdin_handler_thread: AcceptInput
  │     2. screen_thread: WriteCharacter
  │     3. plugin_thread: Update
  │     4. pty_thread: SpawnTerminal
  │
  ├─▶ At zellij-server/src/pty.rs:78:22
  ╰─▶ called `Result::unwrap()` on an `Err` value: "No Editor found, consider setting a path to one in $EDITOR or $VISUAL"
         0: <unknown>
         1: <unknown>
         2: <unknown>
         3: <unknown>
         4: <unknown>
         5: <unknown>
         6: <unknown>
         7: <unknown>
         8: <unknown>
         9: <unknown>
        10: <unknown>
        11: <unknown>
        12: <unknown>
        13: <unknown>
```

I recognize that this setup is misconfigured, but a panic (especially in the as-installed condition) is not the most desirable behavior.

Final note: I only knew to try the strider layout because it is shown in one of the [screenshots](https://zellij.dev/screenshots/). If it's not ready out-of-the-box, I would strongly recommend changing that page.

**Comment by jaeheonji** [comment]
Hi! @kapinga 

This is deuplicate of #1667, #973. But, This is an intentional panic, but we know it causes inconvenience to users.
The best way is to do nothing unless $EDITOR is set, but there is still no way to output an error to the user.

If you have a good plan or idea, please create a new issue. thanks!

**Comment by kapinga** [comment]
Sorry for the duplicate - I searched for relevant issues, but didn't find those. I'll see if I can come up with any ideas.
