### ISSUE TITLE
when select, if no input, arraw up is not work

### ISSUE THREAD

**Issue by jinfagang** [zellij-org/zellij#1674]
In zsh, we need arraw up to call histroy commond ,but zellij just doens't work

**Comment by jpldcarvalho** [comment]
More details on this: It seems that arrow up is mapped to arrow right (tested on htop)

**Comment by imsnif** [comment]
This was a regression introduced in the latest patch. Apologies for this! I'm just now releasing a patch :)

**Comment by jinfagang** [comment]
thank u sir, when could I update via `cargo install zellij`?

**Comment by imsnif** [comment]
You already can! (be sure to use the `--locked` flag when installing from cargo though)

**Comment by imsnif** [comment]
Fixed in 0.31.3 - sorry about the inconvenience!
