### ISSUE TITLE
Feature: the status bar should indicate that a pane is in full screen and mention how many hidden panes there are

### ISSUE THREAD

**Issue by imsnif** [zellij-org/zellij#168]
When placing a pane in full screen (`<ctrl-g> + p + f`), it would be useful if this is indicated in the status bar. Also, if the status bar indicated how many panes are "hiding" behind the full screen pane.

Something like: `FULLSCREEN (+ 3 hidden panes)` on the right side.

### To get started
1. Add a new plugin API that would find out if the pane is in fullscreen here (at the time of this writing): https://github.com/zellij-org/zellij/blob/main/src/common/wasm_vm.rs#L35
2. Add a new API (or combine with point 1?) that would find out how many panes there are currently on screen.
3. Change the UI here: https://github.com/zellij-org/zellij/tree/main/default-tiles/status-bar

**Comment by takezyou** [comment]
Hello, @imsnif. 
I would like to start contributing the project from the simplest.
Can I start with this issue?

**Comment by a-kenji** [comment]
Hello, @takezyou.
We are happy to have you tackle this issue!
If you have any questions please don't hesitate to ask.

**Comment by takezyou** [comment]
Hi, @a-kenji.
Thank you!
I have  question already if that's ok.
How can I check the value of this API?

**Comment by a-kenji** [comment]
@takezyou 
Here should be a good start:
https://github.com/zellij-org/zellij/blob/413a24b77fd78f19385522f96137e80f146f2485/src/client/tab.rs
https://github.com/zellij-org/zellij/blob/main/src/common/screen.rs

Sure, thats always ok!

**Comment by takezyou** [comment]
@a-kenji 
Do you know where to change to show the status bar in full screen?

**Comment by a-kenji** [comment]
@takezyou 

I think this could be a good start:
https://github.com/a-kenji/zellij/blob/6e5600efc8a9ae2136128c0c4f348d45ee739203/src/common/screen.rs#L235 ,

but there needs to be a way in order to tell that the active plugin, in this case the status-bar should stay, even in fullscreen.

Maybe a good way would be to have a flag in the layout file, that marks this plugin as always there?
Or else maybe just check for the status bar and resize to lines up to the status bar.

**Comment by TheLostLambda** [comment]
I you can add a flag to always show a `Pane` in Zellij, then it should be easy for plugins to set that as a setting – much like they set their `max_height` at the moment :)

**Comment by takezyou** [comment]
@TheLostLambda @a-kenji 
Thank you!!
> I you can add a flag to always show a Pane in Zellij, then it should be easy for plugins to set that as a setting

Should it implement something similar to set_max_height?
Is my understanding correct?

**Comment by a-kenji** [comment]
@takezyou 
Yes, that is correct!

**Comment by imsnif** [comment]
@takezyou - the status bar and tab bar are now always shown in full screen, so implementing this should be a lot easier.

**Comment by TheLostLambda** [comment]
Additionally, if you are feeling brave, I'd like to add a more general "minibuffer" feature to the status bar, similar to how Emacs displays messages to the user. That way this feature, the startup tips, and the "Text has been copied" messages can all share a single system and adding new status messages in the future will be trivial.

I'm happy to chat more about the idea if you are interested!

**Comment by takezyou** [comment]
@imsnif 
Thank you.
I'll try this challenge again.

@TheLostLambda 
I'm very interested in the "minibuffer" feature, but I'd like to try it after I've accomplished the current task first.

**Comment by takezyou** [comment]
@imsnif 
#450 
Please review. This pull request.

**Comment by takezyou** [comment]
@imsnif 
 #450
I've been merged. Please close.
