### ISSUE TITLE
"ENOTTY: Not a typewriter" when trying to autostart in bash

### ISSUE THREAD

**Issue by suimong** [zellij-org/zellij#1682]
Thank you for taking the time to file this issue! Please follow the instructions and fill in the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

**In Case of Graphical or Performance Issues**

1. Delete the contents of `/tmp/zellij-1000/zellij-log`, ie with `cd /tmp/zellij-1000/` and `rm -fr zellij-log/`
2. Run `zellij --debug`
3. Recreate your issue.
3. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.

**Basic information**

`zellij --version`: 0.31.3
`stty size`: 52 119
`uname -av` or `ver`(Windows): Linux pop-os 5.18.10-76051810-generic #202207071639~1659108431~22.04~c9172fb SMP PREEMPT_DYNAMIC Fri J x86_64 x86_64 x86_64 GNU/Linux

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`alacritty --version`: alacritty 0.10.1-rc1

**Further information**
The error only occured when I try to login to POP OS GUI with the following lines in `.bashrc`: 

```
eval "$(zellij setup --generate-auto-start bash)"
```

Otherwise, everything works fine: either when I login to tty (i.e. by pressing ctrl+alt+f4, I sourced `.bashrc` from `.profile` so even in tty `.bashrc` gets executed), or just run `zellij` in gnome-terminal or alacritty.

**Comment by jaeheonji** [comment]
Hi!, @suimong 

Autostart scripts are simple shell scripts. Therefore, most errors can be related to the version or setting of the shell.
Could you share your bash version and settings?

**Comment by suimong** [comment]
> Hi!, @suimong
> 
> Autostart scripts are simple shell scripts. Therefore, most errors can be related to the version or setting of the shell. Could you share your bash version and settings?

Hi @jaeheonji
Thank you for looking into it! Kindly find below my `.profile` and `.bashrc` settings. I had a very long `.bashrc` but during investigation of this issue I removed everything else and only kept the zellij command and the issue can be reproduced. However I haven't tried stripping off commands from `.profile`.

``` bash
❯ bash --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

```
❯ cat .profile
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# >>> linuxbrew setup >>>
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
# <<< linuxbrew setup <<<

# >>> pyenv setup >>>
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
# <<< pyenv setup <<<

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
. "$HOME/.cargo/env"

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# Created by `pipx` on 2022-06-18 15:09:05
# export PATH="$PATH:/home/ben/.local/bin"


# Added by Toolbox App
export PATH="$PATH:/home/ben/.local/share/JetBrains/Toolbox/scripts"

# opam configuration
test -r /home/ben/.opam/opam-init/init.sh && . /home/ben/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

# >>> coursier install directory >>>
export PATH="$PATH:/home/ben/.local/share/coursier/bin"
# <<< coursier install directory <<<

# >>> deno configuration >>>
export DENO_INSTALL="/home/ben/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
# <<< deno configuration <<<
```

```
❯ cat .bashrc
# >>> zellij configuration >>>
eval "$(zellij setup --generate-auto-start bash)"
# <<< zellij configuration <<<
```

**Comment by jaeheonji** [comment]
I had a chance to reinstall my Linux machine, so I tried to reproduce this problem during the installation.

Of course, I'm an Arch user, so all the conditions couldn't be perfect. After installing OS, I set up `bashrc` and `profile` with only zelij installed. (the bash version is the same.) 

But I couldn't reproduce the problem.

I don't know the exact reason yet, but would you like to set the raw script on your bashrc?
```bash
if [[ -z "$ZELLIJ" ]]; then
    if [[ "$ZELLIJ_AUTO_ATTACH" == "true" ]]; then
        zellij attach -c
    else
        zellij
    fi

    if [[ "$ZELLIJ_AUTO_EXIT" == "true" ]]; then
        exit
    fi
fi
```

**Comment by suimong** [comment]
I had a chance to perform a few extra trial-and-errors, and unfortunately the issue remains with the following configuration (I kept the linux brew initialization command in `.profile` because that's where I installed zellij from):

```
❯ @ben@pop-os:~$ cat .profile
# >>> linuxbrew setup >>>
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
# <<< linuxbrew setup <<<


# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi
```

```
@ben@pop-os:~$ cat .bashrc
echo "This is start of .bashrc..."

if [[ -z "$ZELLIJ" ]]; then
    if [[ "$ZELLIJ_AUTO_ATTACH" == "true" ]]; then
        zellij attach -c
    else
        zellij
    fi

    if [[ "$ZELLIJ_AUTO_EXIT" == "true" ]]; then
        exit
    fi
fi

# eval "$(zellij setup --generate-auto-start bash)"

echo "This is end of .bashrc..."
```

I don't know this would help your investigation, but I realized that during login through GUI, some component of the OS (I'm not sure if it's GNOME or some other desktop management component) seems to have loaded `.profile`. This behavior contrasts my understanding that login to GUI Desktop is considered opening a "interactive non-login shell", therefore only the `.bashrc` series files should be loaded. 

I've only migrated to a Linux desktop environment not long ago so I'm not sure if this is a standard behavior and if not, might have something to do with the current issue.

Let me know how I can help further.

**Comment by jaeheonji** [comment]
> but I realized that during login through GUI, some component of the OS (I'm not sure if it's GNOME or some other desktop management component) seems to have loaded .profile. This behavior contrasts my understanding that login to GUI Desktop is considered opening a "interactive non-login shell", therefore only the .bashrc series files should be loaded.

Yes, This is pretty weird. If you don't have a lot of content in the `.bashrc` configuration, at this point it seems to be one of the ways to delete the `.bashrc` source from the `.profile`.

**Comment by suimong** [comment]
@jaeheonji Got it. I'll remove zellij auto start script for now, and it actually feels nice to stroke a few keys to start enjoying zellij. Thank you for making such a wonderful program!
