### ISSUE TITLE
Zellij crashed with Broken Pipe

### ISSUE THREAD

**Issue by cosminadrianpopescu** [zellij-org/zellij#1684]
Thank you for taking the time to file this issue! Please follow the instructions and fill in the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

**In Case of Graphical or Performance Issues**

1. Delete the contents of `/tmp/zellij-1000/zellij-log`, ie with `cd /tmp/zellij-1000/` and `rm -fr zellij-log/`
2. Run `zellij --debug`
3. Recreate your issue.
3. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.

**Basic information**

`zellij --version`: zellij 0.31.3
`stty size`: 44 175
`uname -av` or `ver`(Windows): Linux ns3091726.ip-5-135-143.eu 4.19.80-xxxx-std-ipv6-64 #943710 SMP Fri Oct 18 08:31:15 UTC 2019 x86_64 Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz GenuineIntel GNU/Linux

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`nvim --version`:

NVIM v0.8.0-dev-885-ga5ed89c97
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az36-83
                                                                                                                                                                               
Features: +acl +iconv +tui
See ":help feature-compile"
                                                                                                                                                                               
   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
                                                                                                                                                                               
Run :checkhealth for more info
[zellij.log](https://github.com/zellij-org/zellij/files/9393113/zellij.log)

**Further information**
Reproduction steps, noticeable behavior, related issues, etc

I have a long running session to which I keep connecting and disconnecting. A lot of times the ssh session will be killed by a bad internet connection.

Zellij keeps crashing with the error:

```
ERROR  |zellij_server::route     | 2022-08-22 10:14:34.422 [server_router] [zellij-server/src/route.rs:646]: Received empty message from client
ERROR  |zellij_utils::errors     | 2022-08-22 10:14:34.422 [main      ] [zellij-utils/src/errors.rs:94]: Panic occured:
             thread: main
             location: At /project/zellij-utils/src/ipc.rs:161:69
             message: called `Result::unwrap()` on an `Err` value: InvalidValueWrite(InvalidDataWrite(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))

```

See attached the log

**Comment by cosminadrianpopescu** [comment]
[zellij.log](https://github.com/zellij-org/zellij/files/9393119/zellij.log)

**Comment by raphCode** [comment]
Thank you for your report!
Happened to me as well with zellij v0.31.1, will investigate.

**Comment by raphCode** [comment]
repro:
- start zellij session
- start program which produces much output (e.g. `yes`)
- kill zellij client (SIGKILL)
- observe server panic in logfile

**Comment by imsnif** [comment]
Hey @raphCode - thanks for the excellent reproduction steps. With this I was finally able to reproduce the problem and fix it.

The issue was that whenever the client crashes (eg. when the SSH session dropped or with SIGKILL), the server would not register the client as disconnected - since it did not receive any message from it. It would then try to send it messages (eg. render), and crash when it was unable to.

I issued a fix in #1710 that instead of crashing in this case, would assume the client has crashed and remove it from its state.

**Comment by raphCode** [comment]
I also started to work on this a little bit, but did not come far.
I didn't had time to finish it yet, so I am glad you took care of it :)

**Comment by imsnif** [comment]
Oh, my apologies!

**Comment by raphCode** [comment]
No, I am genuinely glad you did it because I did not have the time finishing  the work :)
