### ISSUE TITLE
Ctrl-Shift-v not working for git SSH key passphrase

### ISSUE THREAD

**Issue by Dr-Kristau** [zellij-org/zellij#1687]
`zellij --version`: zellij 0.31.3
`stty size`: 36 160
`uname -av`: Linux jupiter 5.18.17-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Aug 11 14:36:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

`gnome-terminal`: Version 3.44.1 for GNOME 42
`bash`: GNU bash, version 5.1.16(1)-release (x86_64-redhat-linux-gnu)
`git`: git version 2.37.2
`openssh`: OpenSSH_8.8p1, OpenSSL 3.0.5 5 Jul 2022

I discovered this issue when attempting `$ git pull` on one of my repos—I cannot paste (using Ctrl+Shift+v) my passphrase into zellij when the `Enter passphrase for key '/home/xxx/.ssh/id_edxxx':` prompt appears. When I quit zellij (Ctrl+q) and retry, it works as expected.

**Comment by tlinford** [comment]
could it be that the key is not getting copied into the clipboard?

**Comment by Dr-Kristau** [comment]
Thanks for the suggestion @tlinford. Just to clarify then, that when I say 'when I quit zellij (Ctrl+q) and retry' I don't copy anything new to the clipboard—I use what was already there and that should have been pasted into the passphrase prompt within zellij.

**Comment by tlinford** [comment]
and apart from this can you can paste normally?

**Comment by Dr-Kristau** [comment]
Yes. I can paste my SSH key password into the default prompt `[xxxx@yyyy ~]$` and it will appear as expected. In my experience, this issue only happens at the SSH key passphrase prompt as described.

**Comment by raphCode** [comment]
Maybe this is related to bracketed paste?
Like somehow we send a bracketed paste where ssh doesn't expect it disallows pasting. Pasting without bracketed paste involves the terminal emulator sending the text as if the user typed it, so there are no problems.
If my theory is correct, this can be caused by:
- a bug in zellij's bracketed paste tracking logic
- an application which requested bracketed paste earlier on the same terminal, but it crashed / exited without a chance to disable bracketed paste again

**Comment by Dr-Kristau** [comment]
> an application which requested bracketed paste earlier on the same terminal, but it crashed / exited without a chance to disable bracketed paste again

fyi @raphCode: to make sure I could reproduced the issue, I logged out of my account before running the test. On login I opened the GNOME terminal (with `eval "$(zellij setup --generate-auto-start bash)"` in .bashrc), navigated to the git repo and ran `$ git pull` directly. Which is to say that that while possible that a crash had happened in the same terminal before I ran `$ git pull` and tried to paste my password into the passphrase prompt, I would say that it is unlikely.

**Comment by ovitor** [comment]
I'm also having the same issue. Every time I try to use ssh inside zellij it "doesn't allow" me to paste my ssh key's passphrase.

```
vitor in ~ ❯ zellij --version                                                                                                          
zellij 0.31.3
```

**Comment by tlinford** [comment]
Couldn't reproduce it, then I noticed it was still on 0.31.0.
Turns out there was a regression in 0.31.2 due to some code cleanup, that slightly broke the bracketed paste handling.
