### ISSUE TITLE
Crash at start because of background color

### ISSUE THREAD

**Issue by Zykino** [zellij-org/zellij#1696]
**Basic information**

`zellij --version`: zellij 0.31.3
`stty size`: 38 189
`uname -av` or `ver`(Windows): `Linux zykino-pop-os 5.19.0-76051900-generic #202207312230~1660780566~22.04~9d60db1 SMP PREEMPT_DYNAMIC Thu A x86_64 x86_64 x86_64 GNU/Linux`

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`fish --version`: fish, version 3.3.1
`alacritty --version`: alacritty 0.10.1-rc1

**Further information**
It happend once at loggin I did click on alacritty shortuct in my shortcut bar.
Starting zellij again on another window did not reproduce the crash.

```
Error occurred in server:

  × Thread 'server_router' panicked.
  ├─▶ Originating Thread(s)
  │   	1. stdin_handler_thread: AcceptInput
  │
  ├─▶ At /home/zykino/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/route.rs:561:34
  ╰─▶ called `Option::unwrap()` on a `None` value
  help: If you are seeing this message, it means that something went wrong.
        Please report this error to the github issue.
        (https://github.com/zellij-org/zellij/issues)

        Also, if you want to see the backtrace, you can set the `RUST_BACKTRACE` environment variable to `1`.
```

**Comment by raphCode** [comment]
I also have these occasional crashes at startup. All subsequent starts are usually fine until I restart the computer.

What do you mean with the background color?

**Comment by Zykino** [comment]
The error points here: https://github.com/zellij-org/zellij/blob/v0.31.3/zellij-server/src/route.rs#L561 which is in the middle of getting the background color?
Re-reading it seams to say it is oriented around messaging between the client and server not "getting the background color" like I first understood.

```rs
                        ClientToServerMsg::BackgroundColor(background_color_instruction) => {
                            rlocked_sessions
                                .as_ref()
                                .unwrap() // This is line 561
                                .senders
                                .send_to_screen(ScreenInstruction::TerminalBackgroundColor(
                                    background_color_instruction,
                                ))
                                .unwrap();
                        },
```
