### ISSUE TITLE
img2sixel with flatpak Contour showing broken images

### ISSUE THREAD

**Issue by roadriverrail** [zellij-org/zellij#1697]
**Basic information**

`zellij --version`: 0.31.3 (used via the "try it out" bash script
`stty size`: 111 125
`uname -av` or `ver`(Windows): Linux downhome 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`flatpak run org.contourterminal.Contour --version`: 0.3.
[zellij.log](https://github.com/zellij-org/zellij/files/9447226/zellij.log)
[zellij-9.log](https://github.com/zellij-org/zellij/files/9447227/zellij-9.log)
2-2022-07-07

**Further information**

Repo:

1. Launch Contour (e.g. `flatpak run org.contourterminal.Contour`)
2. Display SIXEL image with `img2sixel`, note result:
![image](https://user-images.githubusercontent.com/614752/187277780-52f65dd1-030e-426e-ab0b-9ae7c99f9b26.png)
3. Launch zellij via copy/paste bash script.
4. Perform same command, note corrupted result:
![image](https://user-images.githubusercontent.com/614752/187278082-1bd1f516-a4cd-4315-91e4-c5e080de4b06.png)

I will attach the zellij log files as suggested.

**Comment by imsnif** [comment]
Hey @roadriverrail - while I didn't run Contour from Flatpak (honestly, I spent the better part of an hour trying to, maybe I just don't get Flatpak), I ran version `Contour Terminal Emulator 0.3.2-unreleased-master-77d7f46b` installed from the AUR.

There were a a few sixel-related issues there with or without Zellij (eg. images are cut if they exceed the terminal scrollback, sixel-scrolling is on by default, etc.) But I couldn't reproduce this particular one.

This might be image specific... would you be willing to share this specific image so we can be sure we're talking about the same issue?

**Comment by roadriverrail** [comment]
I confess that as a cranky old 90s UNIX type, I also "don't get" Flatpak, installed it only to try out Contour, and promptly removed it all after this little tryout.  This issue report is mostly a courtesy note in case I'd uncovered a bug, since Contour appears to be one of the bigger sixel terminal emulators out there.  I'll attach a copy of the image; it's a pretty unassuming PNG I use as a headshot in a couple of places online.

I'll also note, in case it matters, that I use i3 (specifically as part of Regolith); I've found some programs cope with being tiled better than others.

I'll also note that wezterm appears to work better for all my setups than Contour will, and this issue does not repro on wezterm and Zellij.
![unknown](https://user-images.githubusercontent.com/614752/188181073-cb8462aa-b9f7-4481-9689-f655e6e80c33.png)

**Comment by imsnif** [comment]
Hey, thanks for this @roadriverrail - I think I managed to narrow this issue down and opened a relevant issue on the Contour side (https://github.com/contour-terminal/contour/issues/809). There might of course still be other related issues on the Zellij side, but I'm 90% sure the Contour fix will fix this particular behaviour.

**Comment by roadriverrail** [comment]
@imsnif Thanks a bunch for the follow-up here, pushing it through to its probable source is great for everyone.  As I have no particular stake at this point, and as this is now moved over to Contour, I will close the issue.

**Comment by christianparpart** [comment]
> Hey, thanks for this @roadriverrail - I think I managed to narrow this issue down and opened a relevant issue on the Contour side ([contour-terminal/contour#809](https://github.com/contour-terminal/contour/issues/809)). There might of course still be other related issues on the Zellij side, but I'm 90% sure the Contour fix will fix this particular behaviour.

Sorry for the inconveniences over here. We're about to fix it this week and also release a new version containing a couple of more bug fixes. :)
