### ISSUE TITLE
Other sessions' cursor indicators flicker on output / change ordering

### ISSUE THREAD

**Issue by raphCode** [zellij-org/zellij#1700]
When 3 or more clients are connected to a session and they focus the same pane, the pane title shows the other's cursors as colorful rectangles:
![image](https://user-images.githubusercontent.com/15750438/187442195-9c586546-b770-4773-b3ea-1110f0caa8b0.png)
On any render / output the ordering of these cursor indicators seems to change, resulting in some flickering:
![Recording 2022-08-30 at 14 59 26](https://user-images.githubusercontent.com/15750438/187443186-7b707de2-cb5e-4b71-81ce-6fdd0b0ac83b.gif)

Reproduction steps:
- open new zellij session
- attach 2 more clients to this session
- type or start program that produces terminal output: e.g. `yes`

**Comment by imsnif** [comment]
Disco!! :D
