### ISSUE TITLE
Crash at startup (after fresh boot)

### ISSUE THREAD

**Issue by Zykino** [zellij-org/zellij#1705]
**Basic information**

```sh
$ zellij --version && fish --version && alacritty --version && stty size && uname -av
zellij 0.31.3
fish, version 3.3.1
alacritty 0.10.1-rc1
38 189
Linux zykino-pop-os 5.19.0-76051900-generic #202207312230~1660780566~22.04~9d60db1 SMP PREEMPT_DYNAMIC Thu A x86_64 x86_64 x86_64 GNU/Linux
```

**Further information**
```
Error occurred in server:

  × Thread 'server_router' panicked.
  ├─▶ Originating Thread(s)
  │   	1. stdin_handler_thread: AcceptInput
  │
  ├─▶ At /home/zykino/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/route.rs:561:34
  ╰─▶ called `Option::unwrap()` on a `None` value
  help: If you are seeing this message, it means that something went wrong.
        Please report this error to the github issue.
        (https://github.com/zellij-org/zellij/issues)

        Also, if you want to see the backtrace, you can set the `RUST_BACKTRACE` environment variable to `1`.


Bienvenue dans fish, le shell amical et interactif
Type help for instructions on how to use fish
zykino@zykino-pop-os ~> ]10;rgb:f2f2/f2f2/f2f2\]0;rgb:3333/3333/3333\]1;rgb:cccc/0000/0000\]2;rgb:4e4e/9a9a/0606\]3;rgb:c4c4/a0a0/0000\]4;rgb:3434/6565/a4a4\]5;rgb:7575/5050/7b7b\]6;rgb:0606/9898/9a9a\]7;rgb:d3d3/d7d7/cfcf\]8;rgb:8888/8080/7c7c\]9;rgb:f1f1/5d5d/2222\]10;rgb:7373/c4c4/8f8f\]11;rgb:ffff/cece/5151\]12;rgb:4848/b9b9/c7c7\]13;rgb:adad/7f7f/a8a8\]14;rgb:3434/e2e2/e2e2\]15;rgb:eeee/eeee/ecec\]16;rgb:0000/0000/0000\]17;rgb:0000/0000/5f5f\]18;rgb:0000/0000/8787\]19;rgb:0000/0000/afaf
```
The log continue with a LOT of gibberish so I cutted it for brevity (and also because I resized the window and the prompt appeared multiples time at random point so, it was a bit broken).

Is it another manifestation of the same bug as #1696 ?
This one happened twice to me and both time it was at first startup of any console after a startup. Can I add the `env RUST_BACKTRACE=1` in the fish config file somehow? :thinking: Will try that and comment with the result if it happens again.

**Comment by imsnif** [comment]
Hey @Zykino - you are exactly right. This is another instance of #1696 and the gibberish you're seeing on screen are the ANSI instructions that caused this race and crash (Zellij crashed so they were sent directly to the terminal's STDIN).

I fixed both this and #1696 now and merged to main - this will be released in the next version. Thanks for bringing this up!
