### ISSUE TITLE
Thread 'wasm' panicks in `wasm_vm.rs` on startup on macOS

### ISSUE THREAD

**Issue by niilz** [zellij-org/zellij#1707]
After updating `zellij` with `cargo install zellij` I am not able to launch it anymore.

I have tried:
- to uninstall it with `cargo uninstall zellij` and reinstalling it via `cargo`
- update the the toolchains and binaries with `rustup update`
- delete `/tmp/zellij-${UID}`
- elevating permission to `/tmp` and `/tmp/zellij-${UID}`
- starting with `zellij --data-dir /tmp/foo-zellij`

But unfortunately nothing seems to help I always get the `Permission denied` error, which stems from `wasm_vm.rs:250:47`.

The logs under `/tmp/zellij-${UID}/zellij-log/zellij.log` say the following after starting with `zellij --debug`:
```
INFO   |zellij_client            | 2022-09-02 11:06:59.061 [main      ] [/Users/myUser/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-client-0.31.3/src/lib.rs:129]: Starting Zellij client! 
INFO   |zellij_server            | 2022-09-02 11:06:59.068 [main      ] [/Users/myUser/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/lib.rs:195]: Starting Zellij server! 
INFO   |zellij_server::wasm_vm   | 2022-09-02 11:06:59.121 [wasm      ] [/Users/myUser/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/wasm_vm.rs:87]: Wasm main thread starts 
ERROR  |zellij_utils::errors     | 2022-09-02 11:06:59.451 [wasm      ] [/Users/myUser/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-utils-0.31.3/src/errors.rs:94]: Panic occured:
             thread: wasm
             location: At /Users/myUser/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/wasm_vm.rs:250:47
             message: called `Result::unwrap()` on an `Err` value: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" }) 
ERROR  |zellij_utils::errors     | 2022-09-02 11:06:59.453 [screen    ] [/Users/myUser/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-utils-0.31.3/src/errors.rs:94]: Panic occured:
             thread: screen
             location: At /Users/myUser/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/tab/mod.rs:491:41
             message: called `Result::unwrap()` on an `Err` value: RecvError

```

Only if I start with root privileges `sudo zellij` the program starts.

`zellij --version`: 0.31.3
`stty size`: 49 157
`uname -av`: Darwin Kernel Version 21.6.0 X86_64

`nvim --version`: NVIM v0.7.2 (Build type RELEASE)
`alacritty --version`: alacritty 0.10.1

**Further information**
I've already looked at #1695, which might be a similar problem (plugin version, although to my knowledge I have not installed any plugins for `zellij`).
And I've checked out #1130, but I am not building from source and I'm not having a permission-denied-problem with `installer.rs` but with `wasm_vm.rs`.

**Comment by imsnif** [comment]
Hey @niilz - could you paste the output of `zellij setup --check`? I think it'll help us troubleshoot this.

**Comment by niilz** [comment]
Absolutely. It looks like this:
```
[Version]: "0.31.3"
[CONFIG DIR]: "/Users/myUser/Library/Application Support/org.Zellij-Contributors.Zellij"
[CONFIG FILE]: "/Users/myUser/Library/Application Support/org.Zellij-Contributors.Zellij/config.yaml"
[CONFIG ERROR]: IoError: No such file or directory (os error 2), File: /Users/myUser/Library/Application Support/org.Zellij-Contributors.Zellij/config.yaml
[DATA DIR]: "/Users/myUser/Library/Application Support/org.Zellij-Contributors.Zellij"
[PLUGIN DIR]: "/Users/myUser/Library/Application Support/org.Zellij-Contributors.Zellij/plugins"
[LAYOUT DIR]: "/Users/myUser/Library/Application Support/org.Zellij-Contributors.Zellij/layouts"
[THEME DIR]: "/Users/myUser/Library/Application Support/org.Zellij-Contributors.Zellij/themes"
[SYSTEM DATA DIR]: "/usr/share/zellij"
[ARROW SEPARATOR]: 
 Is the [ARROW_SEPARATOR] displayed correctly?
 If not you may want to either start zellij with a compatible mode: 'zellij options --simplified-ui true'
 Or check the font that is in use:
 https://zellij.dev/documentation/compatibility.html#the-status-bar-fonts-dont-render-correctly
[MOUSE INTERACTION]:
 Can be temporarily disabled through pressing the [SHIFT] key.
 If that doesn't fix any issues consider to disable the mouse handling of zellij: 'zellij options --disable-mouse-mode'
[DEFAULT EDITOR]: Not set, checked $EDITOR and $VISUAL
[FEATURES]: []
[DOCUMENTATION]: zellij.dev/documentation
```

**Comment by imsnif** [comment]
Thanks!

The most likely thing that is happening here is that this folder:
`[PLUGIN DIR]: "/Users/myUser/Library/Application Support/org.Zellij-Contributors.Zellij/plugins"`
Is a folder your user doesn't have permission to write to (which is why it works with sudo). Do you think that might be the issue?

**Comment by niilz** [comment]
You were absolutely right. As stated in your email, the problem originated from `${CONFIG_DIR}/plugins` not having enough permissions.
`chmod 770 ${CONFIG_DIR}/plugins` resolved the issue.
(Maybe even less rights would be fine as well, but I haven't tried that)

I am closing the issue for it being resolved.
