### ISSUE TITLE
Copy&Paste of SSH passphrase does not work anymore

### ISSUE THREAD

**Issue by fansari** [zellij-org/zellij#1708]
This was tested with PuTTY on Windows 10.

When I copy&paste my SSH passphrase this does not work anymore.

When I paste the passphrase to the command line it looks normal though. But the ssh-agent rejects it.

This issue started with v0.31.2. Until v0.31.1 it is still working.

I have downgraded to v0.31.1.

**Comment by imsnif** [comment]
This is a regression that has already been fixed in main. I'm hoping to release a version with it soon. Sorry for the inconvenience!
