### ISSUE TITLE
Documentation: plugin api and create an example plugin repository

### ISSUE THREAD

**Issue by imsnif** [zellij-org/zellij#171]
At the time of writing we have two plugins, the status-bar and strider. Both of them are default plugins. Since we want to allow anyone to write plugins, it would be great if we write documentation for the plugin api (can be found at the time of writing here: https://github.com/zellij-org/zellij/blob/main/src/common/wasm_vm.rs#L35) and to create an example plugin in a separate repository that people can copy/paste in order to create their own.

**Comment by a-kenji** [comment]
Can that be closed?

**Comment by qballer** [comment]
done by @TheLostLambda
