### ISSUE TITLE
Scroll count not reset to zero with 'clear' command in pwsh

### ISSUE THREAD

**Issue by Dr-Kristau** [zellij-org/zellij#1714]
`zellij --version`: zellij 0.31.3
`stty size`: 25 128
`uname -av`: Linux jupiter 5.19.6-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Aug 31 17:58:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

`pwsh --version`: PowerShell 7.2.6
`alacritty --version`: alacritty 0.10.1

In the pane on the right I've sshed into a Windows machine running Powershell.

![Screenshot from 2022-09-06 13-09-08](https://user-images.githubusercontent.com/32355001/188623280-7ef8c6f0-194b-42c3-bf8f-88874c350bf7.png)

When I type the `clear` command into both panes, the Scroll count is not set to zero in the Windows pane.

![Screenshot from 2022-09-06 13-09-31](https://user-images.githubusercontent.com/32355001/188623300-5f00f2ee-3975-4928-af91-11f49239ea27.png)

**Comment by imsnif** [comment]
Hey, a few questions:
1. What happens when you scroll up on the windows machine?
2. How about on a normal ssh session into that machine? After the clear command, can you scroll up?

I'm mainly asking because I don't know powershell very well myself, but in bash and other POSIX shells the `clear` command usually only clears the screen itself and not the scrollback. So I'm curious what's the intended behaviour here.

**Comment by Dr-Kristau** [comment]
Hello @imsnif!

> I'm mainly asking because I don't know powershell very well myself, but in bash and other POSIX shells the clear command usually only clears the screen itself and not the scrollback. So I'm curious what's the intended behaviour here.

Using bash:
```
$ clear h
Usage: clear [options]

Options:
  -T TERM     use this instead of $TERM
  -V          print curses-version
  -x          do not try to clear scrollback
```
So `clear` also clears the scrollback by default, but doesn't when you use `-x`. The `clear` command in PowerShell 7 maps to `Clear-Host`, whose documentation makes no mention of scrollback. However, it does say:
> Because the behavior of the Clear-Host function is determined by the host program, Clear-Host might work differently in different host programs.

To answer:
> 1. What happens when you scroll up on the windows machine?
> 2. How about on a normal ssh session into that machine? After the clear command, can you scroll up?

On my Windows machine using Windows Terminal and PowerShell scrollback is cleared, but using gnome-shell or alacritty on my Linux machine (Fedora 36) it isn't. According to [this question](https://stackoverflow.com/questions/52127653/how-to-clear-the-entire-terminal-powershell) and its answer, the clear command also doesn't work in the Visual Studio shell but does work in Ubuntu (which?). 

So, I don't think it's a zellij issue. I'll comment and close, thank you.
