### ISSUE TITLE
Normal key binding Ctrl+a Ctrl+e Ctrl+f doesn't work

### ISSUE THREAD

**Issue by namlee** [zellij-org/zellij#1717]
**Basic information**

`zellij --version`: zellij 0.31.3
`stty size`: 24 80
`uname -av`: Darwin Nams-MacBook-Pro.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64
`kitty --version`: 0.26.1

**Further information**
Please watch the video below to reproduce the error. I have tested it with default Mac terminal (video 1) and kitty terminal (video 2). Both terminal work normal without entering zellij. Steps to reproduce:
1. Type a command. i.e. `rm -rf`
2. Press `Ctrl+a` to move to the start of the line. Press `Ctrl+e` to move to the end of the line. `Ctrl+f` to move forward each character. Everything works just fine.
3. Do the same step and apply same key binding within zellij. Result: it doesn't work.

Mac default terminal

https://user-images.githubusercontent.com/14086792/189036458-775790a3-accf-45e8-aa03-c0ee9729dceb.mov

Kitty terminal

https://user-images.githubusercontent.com/14086792/189036506-a766e7e3-e34e-40c2-b7d8-606aaff5ca4e.mov

**Comment by imsnif** [comment]
Hey @namlee - I unfortunately cannot reproduce this. I don't have a mac, but I tried with Kitty + zsh. Do you have any custom configuration for zsh? Maybe the clue is there?

**Comment by namlee** [comment]
Hi @imsnif - I have no clue what's wrong with my config since it works without entering zellij. After disable all the configs and re-enable them one by one I figured out the root cause. These 2 lines break the key binding in zellij.
```
export EDITOR="nvim"
export VISUAL="nvim"
```
Thank you so much for taking time answer my question. I will close this bug.

**Comment by imsnif** [comment]
Hey @namlee - I still think this might be a Zellij issue... I tried adding these two lines to my ~/.zshrc and I still can't reproduce it. If you feel like helping me troubleshoot this a little more (maybe others will benefit from a fix in the future, if it's something Zellij can do anything about?) that would be great. But only if you feel like investing the time of course.

**Comment by namlee** [comment]
Hi @imsnif , I reopen this issue to chat with you. I couldn't comment when it is closed. No problem. Whatever you need to help you troubleshoot this problem please tell me. Do you need my .zshrc file so I could post it here.
