### ISSUE TITLE
Cannot enter git credentials due to bracketed paste

### ISSUE THREAD

**Issue by Kushagra-0801** [zellij-org/zellij#1727]
**Basic information**

`zellij --version`: 0.31.3
`stty size`: 29 147
`uname -av` or `ver`(Windows): Linux fa061866 5.14.0-1045-oem #51-Ubuntu SMP Mon Jul 4 06:41:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful.
git - version 2.34.1
ssh - OpenSSH_8.9p1 Ubuntu-3, OpenSSL 3.0.2 15 Mar 2022

**Further information**
1. Do not set a credential manager in git (so that it asks for username/password)
2. Enter the username as usual
3. Copy the github PAT and paste in place of password
4. Observe the bracketed paste characters `^[[200~ ^[[201~` appear around the PAT
5. Git fails because github assumes those characters are part of the input.

I can set a credential manager on my local machine but setting one with my credentials on a shared corporate server is not a possibility. Hence, we use PATs for git stuff on the servers.

Edit: I would be fine if I can just disable bracketed paste completely. If there is an option for that, please refer me to it.

**Comment by tlinford** [comment]
Hey, thanks for the report,  this was fixed in v0.31.4 (https://github.com/zellij-org/zellij/pull/1689).
