### ISSUE TITLE
Feature: add an option to display panes with "gaps"

### ISSUE THREAD

**Issue by imsnif** [zellij-org/zellij#173]
Right now the panes are drawn in a grid. It can be cool if they will be drawn as boxes instead (or if we provide that option to the user to be toggled with a key).

**Comment by cswinter** [comment]
This seems like a worthwhile direction to explore. When drawing as boxes, would each border take up one additional char or is there a way to make it work with a single char? I guess the box characters for double borders exist but is possible to color just only a portion to show the selected pane? Or is the idea to keep the current divider lines and draw an outer border?

**Comment by imsnif** [comment]
My idea was to have them as boxes, so yeah - every border would take up one additional char. So if people mind that, we could make this toggle-able. I don't think it's possible to color one terminal character with two different colors, unless you want to use something like https://en.wikipedia.org/wiki/Sixel (please no :) )

**Comment by imsnif** [comment]
> Maybe this issue can now be closed due to #643.

Yes, thank you!
