### ISSUE TITLE
Possible to remap all 'Alt' Keys to 'Ctrl'

### ISSUE THREAD

**Issue by djc01** [zellij-org/zellij#1744]
I use SecureCRT on a windows system - and the 'Alt' key mappings are a bit problematic, as in many cases, the Alt key mapping is already in-use by SecureCRT. While I have successfully remapped most of the Alt key-bindings, these are universally problematic:

```
        - action: [MoveFocusOrTab: Left,]
          key: [ Ctrl: 'H', Ctrl: Left]
        - action: [MoveFocusOrTab: Right,]
          key: [ Ctrl: 'l', Ctrl: Right]
        - action: [MoveFocus: Down,]
          key: [ Ctrl: 'j', Ctrl: Down]
        - action: [MoveFocus: Up,]
          key: [ Ctrl: 'k', Ctrl: Up]
```

I believe this might be related to Issue #1053 indicates as the error message is the same:
```
Deserialization error: keybinds: data did not match any variant of untagged enum KeyActionUnbind
```

**Comment by har7an** [comment]
Hi and thanks for reporting this!

Unfortunately this is a shortcoming in the current code and indeed the same situation as #1053. The technical background is that we have a special handling for the arrow keys in combination with the `Alt` modifier (for the quick-navigation), but unfortunately not for the `Ctrl` modifier. At the moment, `Ctrl` can only be combined with ASCII chars and the arrow keys aren't ASCII.

**Comment by djc01** [comment]
Thank you for the info! 

This implies a full solution for my setup; I can map the ```Alt: '<char>'``` to some ```Ctrl: '<char>'``` and retain the ```Alt: '<arrow>'``` key mappings, such as:
```
        - action: [MoveFocusOrTab: Left,]
          key: [ Ctrl: 'a', Alt: Left ]
        - action: [MoveFocusOrTab: Right,]
          key: [ Ctrl: 'd', Alt: Right ]
        - action: [MoveFocus: Down,]
          key: [  Ctrl: 's', Alt: Down ]
        - action: [MoveFocus: Up,]
          key: [ Ctrl: 'w', Alt: Up ]
```
Thanks!
