### ISSUE TITLE
Flooding panes kills scrolling and blinking caret

### ISSUE THREAD

**Issue by har7an** [zellij-org/zellij#1746]
**Basic information**

`zellij --version`: 0.31.4
`stty size`: 59 237
`uname -av` or `ver`(Windows): Linux 5.19.9-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep 15 09:49:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`rg --version`: ripgrep 13.0.0

**Further information**
Reproduction steps, noticeable behavior, related issues, etc

This has occured a few times to me now, and I don't quite understand where it comes from. When I use `ripgrep` with some very common search terms (that I know will produce lots of matches), I can see that the scrollback (10k in my case) fills up **very** fast and then disappears. The scroll indicator is gone, I can no longer scroll in my session. Also the caret in my shell stops blinking and won't recover, not even if I `reset` the shell.

To reproduce it: Navigate to the `zellij` source folder and type `rg "\("`, or `rg e`. I haven't seen this with any other program yet, I guess barely anything produces text as quick as `rg`...

**Comment by imsnif** [comment]
If you exclude the snapshots from ripgrep, does this still happen? I'm pretty sure what's happening here is that our snapshots include ANSI instructions that are being literally interpreted by zellij when you ripgrep through them, and so this is by design.

**Comment by har7an** [comment]
@imsnif Snapshots are all files ending in `.snap`, right? In that case the call should be: `rg -g '!*.snap' e`, unless I'm mistaken, which leads to the same behavior. Even if I `cargo clean` the whole directory, ripgrep still floods the pane.

Here's a summary of some experiments:

- `rg -g '*.rs' e` works
- `rg -g '!*.snap' e` fails
- `rg --no-binary e` fails

**Comment by imsnif** [comment]
Then it's probably literal ANSI codes inside code. We have some of those too here and there.

**Comment by har7an** [comment]
You're right, I can reproduce it with regular `grep`, too. Sorry for the noise!

**Comment by imsnif** [comment]
All good, friend :)
