### ISSUE TITLE
Feature: mouse support

### ISSUE THREAD

**Issue by imsnif** [zellij-org/zellij#175]
We should allow switching pane focus as well as resizing panes with the mouse.
We should also allow copying text from within a pane (and not including the text from the surrounding panes) when marking it with a mouse.

Other mouse suggestions are of course very welcome :)

**Comment by a-kenji** [comment]
Trying to get together the possible issues:
- [ ] handle mouse input at all -> use the suggested NoOp 
- [ ] make it possible to pass through mouse input
- [ ] switching pane focus
- [ ] resizing panes
- [ ] copying text, not just from the terminal, but just inside the focused pane

**Comment by miguelraz** [comment]
After poking @imsnif on Discord I would like to also suggest 
- [ ] mouse scrolling

**Comment by imsnif** [comment]
> After poking @imsnif on Discord I would like to also suggest
> 
>     * [ ]  mouse scrolling

Added, thank you!

**Comment by zareami10** [comment]
Note sure if it is discussed but it would be great if we could also switch (and maybe at some point reorder) tabs with mouse.

**Comment by a-kenji** [comment]
@zareami10 
Thank you for the input, yes that is definitely planned,
a prerequisite for that would be #607.

**Comment by icyJoseph** [comment]
What is the mouse support status? 

I have a bad habit of using my touchpad to click on `vim`, and it really prevents usage of zellij to develop, instead I use it to monitor logs in Alacritty. Is there anything I can do already?

I've tried to google and navigate the issues looking for mouse support, and it seems that the information is kinda fragmented, most likely because the feature is not fully supported yet.

**Comment by imsnif** [comment]
Hey @icyJoseph - right now Zellij has mouse support for some of its own UI (eg. changing pane focus, scrolling inside a pane). There's work being done to make it send mouse events to the programs running inside the terminal (eg. to vim) here: https://github.com/zellij-org/zellij/pull/624

**Comment by benruijl** [comment]
I'd love to have mouse support to change tabs. Would that be difficult to add?

**Comment by imsnif** [comment]
That would be cool... @TheLostLambda - where are we on accepting mouse events in plugins? I'm out of the loop on this one I'm afraid.

**Comment by a-kenji** [comment]
@imsnif 
He seems to be saying this could be quite close to being merged #629.
I don't know if qepasa has still some reservations here though.

**Comment by qepasa** [comment]
Hey @TheLostLambda, sorry for being unresponsive lately! Can you give me some time (this week) to get back to your comments and rebase? I'll dedicate time this week to finalize the PR and make changes based on your review. Thanks for the patience! :)

**Comment by imsnif** [comment]
The only thing left is resizing panes with the mouse, which has its own issue. Everything else has been implemented and working for a long while. Closing this issue.

**Comment by ixzh** [comment]
hi is it possible to have the focus follow mouse?
