### ISSUE TITLE
When `xonsh` is set as the `default_shell`, opening the scrollback in `nvim` editor causes everything to have underline visual artifact

### ISSUE THREAD

**Issue by taranlu-houzz** [zellij-org/zellij#1760]
**Basic Information**

`zellij --version`: zellij 0.31.4
`stty size`: 59 167
`uname -av` or `ver`(Windows): Darwin PAC02YR0PBLVCH 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

**Programs**
`nvim --version`:
```
↓2 ~ via 🐍 v3.9.6
❯ nvim --version
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@iMac-Pro

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.2_1/share/nvim"

Run :checkhealth for more info
```
`wezterm --version`:
```
↓2 ~ via 🐍 v3.9.6
❯ wezterm --version
wezterm 20220905-102802-7d4b8249
```

**Further information**
Setting the `scrollback_editor` to `vim` makes the issue go away, as does using `fish` as the `default_shell`, so I think that there is something going on with the interplay of `neovim` and `zellij`. Also, this same issue appear when using `kitty`.

Sometimes the lines do not appear when the scrollback is opened in `nvim` the first time, but after that, they always appear (this happens rarely; usually the lines always appear).

![image](https://user-images.githubusercontent.com/52425255/193374058-921da3fb-9788-4d0f-84c6-0a21d7792340.png)

**Comment by taranlu-houzz** [comment]
It seems that having this setting in my `config.yaml` causes this issue:
```yaml
ui:
  pane_frames:
    rounded_corners: true
```

**Comment by adrianord** [comment]
I am getting this issue even just opening neovim normally

**Comment by taranlu-houzz** [comment]
@adrianord Yeah, I am also seeing it when opening `nvim` normally as well.

**Comment by adrianord** [comment]
@taranlu-houzz I've found that setting any colorscheme seems to fix this issue for some reason, even if it's `default`. I tested using `nvim --cmd "colorscheme default"` and can be set more permanently by putting `colorscheme default` in your `init.vim`.

**Comment by taranlu-houzz** [comment]
@adrianord Great, thanks! That appears to work for me as well.

**Comment by ThomasFrans** [comment]
For me, the issue also happens, but not always. It doesn't seem to depend on anything in particular. Sometimes I open NeoVim and it works normally, and then literally one second later after a restart, there are the horizontal lines.

**Comment by ThomasFrans** [comment]
Some extra information: There is a similar issue #2037 that mentions Alacritty, but it also seems to happen in Gnome Terminal, which would make it seem like it's not related to the terminal emulator at all...
![image](https://user-images.githubusercontent.com/48214567/212339273-d862676d-469d-4146-baa0-b386b805371d.png)

**Comment by imsnif** [comment]
Fixed in https://github.com/zellij-org/zellij/pull/2204
