### ISSUE TITLE
[Feature] Add a setting that would set Command mode to be persistent by default

### ISSUE THREAD

**Issue by categorille** [zellij-org/zellij#178]
### Current behaviour
Right now, pressing Ctrl-g always rotates between Normal mode, Command mode, and Persistent Command mode. There is no way to change this behaviour.

### What should change?
A command-line setting (`--always-locked`?) should be added which makes it so Ctrl-g rotates between Normal mode and Persistent command mode. This could eventually be changed to a config-file setting (when we'll have support for that) or even the default.

### Other considerations and tips
Currently, there exists a `InputMode` enum variant for each input mode, regardless if they are "main" modes (i.e. Normal and Command modes) or submodes of Command mode (i.e. Pane, Resize, Tab, ...). It may be interesting to refactor the code so that it reflects the actual structure of input modes, with two main `InputMode`s and another enum for Command mode submodes. This would both make the code clearer and make it easier to work with command mode persistency.

### Relevant source files
- the [input](https://github.com/zellij-org/zellij/tree/main/src/common/input) module

**Comment by categorille** [comment]
I guess I am assigning myself to both this and #161, given that they are highly related. May even be worth it to work on this before #161 as the refactoring that I am suggesting here will make it easier for that issue to be fixed as well.

**Comment by imsnif** [comment]
The refactor idea sounds good. I have a feeling that starting with it and then making the functional changes here and in #161 would be the longer path, but I definitely might be wrong on this one. In any case, do what you think is right and best. :)
Github unfortunately would not let me assign you to these issues, so if you could write a short comment on #161 as well that you're on it so no one else would do double work on it, that would be great.
Looking forward to the pull requests.

**Comment by categorille** [comment]
Is this still needed, or do we prefer going with the current keybinds (command mode always persistent) without an option?

**Comment by imsnif** [comment]
If it existed, I know I would use it :)

**Comment by categorille** [comment]
Alright, so it's still relevant :) I won't take care of it right now so if anyone else does, plase give it a try (and you can contact me w.r.t. the input module, which is going to see some changes)

**Comment by imsnif** [comment]
So, re-reading this I think I made a mistake and thought this was a different issue. This is actually how things are right now (we only have persistent mode for all modes). So closing this issue (please correct me if I misunderstood @categorille and I'll re-open).

**Comment by categorille** [comment]
> So, re-reading this I think I made a mistake and thought this was a different issue. This is actually how things are right now (we only have persistent mode for all modes). So closing this issue (please correct me if I misunderstood @categorille and I'll re-open).

@imsnif well, we have the behaviour cited in the title as default, but we don't have a setting to change it to not be persistent by default. But yea, maybe closing this and opening a new updated issue is better
