### ISSUE TITLE
Layout defined in default.yml file is not rendered

### ISSUE THREAD

**Issue by Enforcer007** [zellij-org/zellij#1782]
Layout defined in `default.yml` is not loaded by zellij.

Zellij considers only files with `.yaml` extension. 

Need support for '.yml' extension

**Comment by imsnif** [comment]
Hey, this is by design. Mostly to remove ambiguities when both files are present. In any case though, in `main` we already moved to a KDL configuration which only has the "kdl" file ending - so this should not be an issue anymore.
