### ISSUE TITLE
Cannot copy text from pane

### ISSUE THREAD

**Issue by Enforcer007** [zellij-org/zellij#1783]
Unable to copy paste the text from a pane. Running zellij in a gnome terminal.

I can copy text and paste in a gnome terminal but doesn't work in zellij.

Version: 0.31.4
Os: Ubuntu 22.04

**Comment by PGBastien** [comment]
Hi @Enforcer007 use shift before.

**Comment by tlinford** [comment]
Please see https://zellij.dev/documentation/compatibility.html#clipboard-not-working.

**Comment by Enforcer007** [comment]
Hi @tlinford, Thanks for the pointing to the docs. It works.
