### ISSUE TITLE
high memory usage , zellij may has memory leak?

### ISSUE THREAD

**Issue by TYZRPVX** [zellij-org/zellij#1789]
<img width="896" alt="image" src="https://user-images.githubusercontent.com/7645818/195237500-8cd3862d-f6dc-489f-a217-6dff52f39d4c.png">

Basic information

zellij --version: 0.31.4
stty size: 24 109
uname -av or ver(Windows): Darwin C02FRH5KMD6M 20.6.0 Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64 x86_64
alacritty --version: alacritty 0.10.1 (2844606)

**Comment by har7an** [comment]
Thanks for reporting this!

I think this is the same as #1625, so I'll go ahead and close this one.
Would you mind sharing a little more information on the circumstances in which you see this high memory usage over in #1625? Something like: How long has your zellij session been running? Did you open/close panes/tabs a lot? And do you have a scrollback limit set?
