### ISSUE TITLE
Latest zellij release doesn't work on aarch64

### ISSUE THREAD

**Issue by dbrodie** [zellij-org/zellij#1796]
Running the latest launch script, or just downloading the latest binary release and running it, on Raspberry Pi4  linux aarch64 doesn't work. I get a blank screen, and when kill-ing the process I get the message:
`Received empty message from server`

Running `zellij --debug` does not provide more information.

Some more information:
`$ stty size
70 182`

`$ ./zellij --version
zellij 0.31.4`

`$ uname -av
Linux norm 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux`

**Comment by raphCode** [comment]
Hi, thank you for contributing!

Can you please post the log files from `/tmp/zellij-*/zellij-log/`? :)

**Comment by dbrodie** [comment]
Sorry for the delay. My RasbPi4 died. Now it seems to be working properly. :)
