### ISSUE TITLE
`search term` in scroll mode can only be used once

### ISSUE THREAD

**Issue by naosense** [zellij-org/zellij#1817]
**Basic information**

zellij --version:zellij 0.31.4
stty size:22 100
uname -av or ver(Windows):Darwin ZBMAC-C02C21EH2.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Apr 18 21:50:40 PDT 2022; root:xnu-6153.141.62~1/RELEASE_X86_64 x86_64

**Further information**
`search term` in scroll mode can only be used once, see below.  First i type `file`, it worked, then i type `will`, it didn't work any more.

https://user-images.githubusercontent.com/2225426/196627313-09edce28-29ac-462b-9351-4bd6e08f5423.mp4

**Comment by imsnif** [comment]
Hey - I think this behavior makes sense if you see the UI (eg. with pane frames enabled), no?

**Comment by imsnif** [comment]
I think there's a misunderstanding here that comes from part of the UI being disabled (the pane frames).
Could you try doing the same thing with pane frames enabled (eg. `ctrl+p` + `z`) and seeing if it makes more sense to you? If you do that you see the search term still on the pane frame and see that you're actually just adding to it and not replacing it.

**Comment by naosense** [comment]
Ah, I see it after the panel frames enable. But the keyword is not clear when the panel frames are disabled, does it have a better way to show the keyword?

**Comment by imsnif** [comment]
I agree we should probably show this in the status bar's tooltip as well

**Comment by naosense** [comment]
To display the keyword in the status bar or to press `s` to clear the previous keyword like `/` in vim? I think the latter is more intuitive. How do you think?

**Comment by naosense** [comment]
Fixed by #1853 , close this issue.
