### ISSUE TITLE
KDL layouts: Empty command string causes cryptic error message

### ISSUE THREAD

**Issue by raphCode** [zellij-org/zellij#1823]
version: main, roughly 12d35bded55756c951e86212a3c72305a26043d6

```
layout {
    pane {
        command ""
    }
}
```
No crash, but the command pane shows this:
`fatal runtime error: assertion failed: output.write(&bytes).is_ok()`
Not sure if users may hit this case otherwise, but it looks like a scary error message.

**Comment by imsnif** [comment]
Fixed in https://github.com/zellij-org/zellij/pull/1831
