### ISSUE TITLE
[Bug/Feature] In all non-Normal modes, user input should never be written to the focused pane

### ISSUE THREAD

**Issue by categorille** [zellij-org/zellij#184]
### Current behaviour
In all modes (including Normal mode, technically), user input that isn't bound to any sequence of action is written to the focused pane.

### Desired behaviour
When in command mode, no user input should ever be written to the terminal, as this is highly confusing (some characters get written but others are bound to actions, like splitting the focused pane, resizing panes, etc).

### Technical considerations
The current behaviour is due to [this line of code](https://github.com/zellij-org/zellij/blob/c74e2ef27356257c45c6a7bdb24c51a7ae390d8f/src/common/input/keybinds.rs#L176). I have considered creating a `NoOp` [`Action`](https://github.com/zellij-org/zellij/blob/c74e2ef27356257c45c6a7bdb24c51a7ae390d8f/src/common/input/actions.rs#L15), which would replace `Action::Write(input)` as the default action. Sadly, this doesn't work, as the input logic is the same in Normal mode as any other mode: Normal mode has very few keybinds (only [one](https://github.com/zellij-org/zellij/blob/c74e2ef27356257c45c6a7bdb24c51a7ae390d8f/src/common/input/keybinds.rs#L31), in fact, which allows switching to Command mode), and relies on the rest of the unrecognized inputs to be written to the focused pane.

This can probably be considered a part of the general revision of the input module.

**Comment by imsnif** [comment]
Yes please! Do you think we can achieve this with the `NoOp` Action you mentioned and a match? Something like:

```rust
match mode {
    InputMode::Normal => {
            mode_keybinds
                .get(key)
                .cloned()
                .unwrap_or(vec![Action::Write(input)])   
    },
    _ => {
            mode_keybinds
                .get(key)
                .cloned()
                .unwrap_or(vec![Action::NoOp])   
    }
}
```
