### ISSUE TITLE
Close pane after command exit

### ISSUE THREAD

**Issue by Mo8it** [zellij-org/zellij#1846]
Lets say that I have this layout:

```
layout {
    default_tab_template {
        children
        pane size=1 borderless=true {
            plugin location="zellij:compact-bar"
        }
    }

    tab {
        pane {
            command "fish"
            args "-C" "ls"
        }
    }
    tab {
        pane {
            command "fish"
            args "-C" "git status"
        }
    }
}
```

After exiting the shell in one of the panes, I want the pane to be closed. Currently, the pane stays open after exiting the shell and presents me with the options to rerun with Enter or exit with Ctrl+C. This breaks my workflows before the update to `v0.32.0`.

An option like `close_after_exit true` would be really awesome!

Thank you very much for the update, it did simplify a lot for layouts, but this issue is very annoying. Especially because I have the frames hidden. Therefore, I don't even see if the command did exit or not. The options to rerun or exit are displayed in the frame.

**Comment by imsnif** [comment]
First - apologies for breaking your workflow! I think the way I intended these to be used is to do something like this instead:
```kdl
pane command="git" {
    args "status"
}
```
Then doing a single `Ctrl-c` would exit the pane. Or do you count on the shell being available in the pane after `git status` exits?

That being said - I very much agree there should be a `close_after_exit` attribute, as well as a `do_not_run_initially` (or some such). I'll whip them up in a patch version in the coming week or two.

**Comment by Mo8it** [comment]
Yes, I count on the shell being available in the pane after that the command exits.

What do you mean with `do_not_run_initially`?

Thank you!

**Comment by imsnif** [comment]
Hey @Mo8it - the latest version includes a `close_on_exit` (https://zellij.dev/documentation/creating-a-layout.html#close_on_exit) and a `start_suspended` (https://zellij.dev/documentation/creating-a-layout.html#start_suspended) properties for panes in layouts.

For your use case, I think you should be able to do something like:
```
layout {
    pane command="bash" close_on_exit=true {
        args "-ic" "git status; bash"
    }
}
```
You can adjust it to your own shell if you use something else.

Hope this helps!

**Comment by Mo8it** [comment]
Thank you very much! 😍
