### ISSUE TITLE
Expand path

### ISSUE THREAD

**Issue by Mo8it** [zellij-org/zellij#1847]
Currently, paths in the configuration are not expanded. If I enter a path with `~`, then the home directory is not expanded.
Would it be possible to use a function like the following internally? https://docs.rs/expanduser/latest/expanduser/fn.expanduser.html

Thanks!

**Comment by imsnif** [comment]
Hum - I get where you're coming from, but I'm a little wary of this tbh. I think this is a good behaviour for the shell - where by definition you're on the same machine. But layouts can be transferred from one person to another, and this would essentially mean that absolute paths will be different from machine to machine.

Layout paths can also be specified as relative paths, with `cwd` composition - maybe this can help you out? https://zellij.dev/documentation/creating-a-layout.html#cwd-composition

If you're opening a layout with the `new-tab` action, you can even give it a custom `cwd` that will replace the layout's global `cwd`. Something like: `zellij action new-tab --layout layout.kdl --cwd ~/some/folder`

**Comment by Mo8it** [comment]
Thanks for the tips!
It was just a suggestion, but I can understand that it is an unneeded overhead.
