### ISSUE TITLE
The theme file in the themes directory is not recognized

### ISSUE THREAD

**Issue by jaeheonji** [zellij-org/zellij#1849]
**Basic information**

`zellij --version`: zellij 0.32.0
`stty size`: 30 120
`uname -av` or `ver`(Windows): Linux Julian 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux
`windows terminal`: 1.15.2875.0

**Further information**

After the config is converted to KDL, the theme file existing in the themes directory is not recognized.
Currently, only themes declared directly in `config.kdl` are recognized.

**Comment by imsnif** [comment]
Hey @jaeheonji - this works for me:

```kdl
// ~/.config/zellij/themes/dracula.kdl
themes {
    dracula {
        fg 248 248 242
        bg 40 42 54
        black 0 0 0
        red 255 85 85
        green 80 250 123
        yellow 241 250 140
        blue 98 114 164
        magenta 255 121 198
        cyan 139 233 253
        white 255 255 255
        orange 255 184 108
    }
}
```

```
$ zellij options --theme dracula
```

Could you tell me more about your setup? Maybe we can find out what exactly isn't working?

**Comment by jhseu** [comment]
Can confirm that after 0.32, it only works if:

- There's only one theme in the file.
- The file is named after the theme.

**Comment by imsnif** [comment]
Hey - apologies for this bug. I didn't know more than one theme in a custom theme file was possible :(
I think @jaeheonji said he is fixing it - right?

**Comment by jaeheonji** [comment]
@imsnif Yes, I will fix it ASAP :)
