### ISSUE TITLE
feature request: send focus/unfocus events to panes

### ISSUE THREAD

**Issue by colemickens** [zellij-org/zellij#1851]
The end goal is to be able to have helix change the cursor when it's unfocused, another small indicator for me to know where I'm focused.

* in helix's room:
  * https://matrix.to/#/!zMuVRxoqjyxyjSEBXc:matrix.org/$KW8iPeQ4w0g61HRez8X_-lbZe2vv91VTVmQBrFJGgOk?via=matrix.org&via=mozilla.org&via=tchncs.de
  *  specifically:
     > Helix gets terminal focus events. We use it to autosave on focus lost currently: https://github.com/helix-editor/helix/blob/master/helix-term/src/ui/editor.rs#L1434
     > I'm not sure if Zellij emits them when you change panes. If you want to check, you can clone crossterm, Helix's underlying terminal library, and run `cargo run --example event-read` in that clone. It'll print out whatever terminal events its getting, including focus events
     > If Zellij does emit them, you could use that to swap cursors
* in zellij's room
  * https://matrix.to/#/%23zellij_general%3Amatrix.org/%241MvDPhe_yuwt6qAVIH1NTYEiSuEQMI5OuA0JEnCUXx8?via=matrix.org&via=der-fetzer.de&via=pixie.town&via=fedora.im
  * specifically:
    >Hah, nice! I did not know these existed: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-FocusIn_FocusOut

**Comment by imsnif** [comment]
Yay, this has been implemented
