### ISSUE TITLE
tab-bar plugin version mismatch at 5793af76

### ISSUE THREAD

**Issue by jwbowen** [zellij-org/zellij#1852]
I just built zellij from the current state of the repo (commit 5793af76 is the latest at time of writing) on a new machine which hadn't had zellij installed in any way.

When I started it by running `zellij`, I got the following (re-run with `RUST_BACKTRACE=full`):
```
$ RUST_BACKTRACE=full zellij

Error occurred in server:

  × Thread 'wasm' panicked.
  ├─▶ Originating Thread(s)
  │   	1. ipc_server: NewClient
  │   	2. pty_thread: NewTab
  │   	3. screen_thread: NewTab
  │   	4. plugin_thread: Load
  │
  ├─▶ At zellij-server/src/wasm_vm.rs:454:9
  ╰─▶ If you're seeing this error the plugin versions don't match the current
      zellij version. Detected versions:

      - Plugin version: 0.32.0

      - Zellij version: 0.33.0
      - Offending plugin: tab-bar

      If you're a user:
          Please contact the distributor of your zellij version and report this error
          to them.

      If you're a developer:
          Please run zellij with the updated plugins. The easiest way to achieve this
          is to build zellij with `cargo make install`. Also refer to the docs:
          https://github.com/zellij-org/zellij/blob/main/CONTRIBUTING.md#building

      A possible fix for this error is to remove all contents of the 'PLUGIN DIR'
      folder from the output of the `zellij setup --check` command.


      Panic backtrace:
         0: <unknown>
         1: <unknown>
         2: <unknown>
         3: <unknown>
         4: <unknown>
         5: <unknown>
         6: <unknown>
         7: <unknown>
         8: <unknown>
         9: <unknown>
        10: <unknown>
        11: <unknown>
        12: <unknown>
        13: <unknown>
        14: <unknown>
        15: start_thread
        16: __clone3

  help: If you are seeing this message, it means that something went wrong.
        Please report this error to the github issue.
        (https://github.com/zellij-org/zellij/issues)

        Also, if you want to see the backtrace, you can set the `RUST_BACKTRACE` environment variable to `1`.


$
```
If I revert one commit back to f23ea515, then everything works as expected.

**Comment by har7an** [comment]
Hello,

this arguably shouldn't happen! I have a few questions:

- Have you tried applying the fix that's mentioned in the error message?
- I assume you compiled zellij from `main`: Which command did you use to build it?

I just spun up a fresh rust container and installed zellij from main (5793af7), it compiled and launched without issues.

**Comment by jwbowen** [comment]
I get a build error when trying `cargo make install` on 5793af7
```
...<snip>...
[cargo-make][2] INFO - Project: tab-bar
[cargo-make][2] INFO - Build File: Makefile.toml
[cargo-make][2] INFO - Task: build-release
[cargo-make][2] INFO - Profile: development
[cargo-make][2] INFO - Skipping Task: legacy-migration 
[cargo-make][2] INFO - Execute Command: "cargo" "build" "--release"
   Compiling tab-bar v0.1.0 (/home/jbowen/bld/zellij/default-plugins/tab-bar)
    Finished release [optimized] target(s) in 4.31s
[cargo-make][2] INFO - Build Done in 4.91 seconds.
[cargo-make][1] INFO - Build Done in 41.44 seconds.
[cargo-make] INFO - Running Task: wasm-opt-plugins
[cargo-make] ERROR - Error while running duckscript: Source: Unknown Line: 9 - No such file or directory (os error 2)
[cargo-make] WARN - Build Failed.
{1}[jbowen@hesperus zellij]$
```

I get that build error as well on the latest main commit (at time of writing, eed9541a).

I'll go ahead and close this, though, as it just seems to be a me problem.

**Comment by har7an** [comment]
> I get a build error when trying `cargo make install` on

Yeah, unfortunately, these are the woes of the current build and plugin system. You must have the `wasm-opt` executable installed on your PC, you can grab that for example from the releases of [binaryen](https://github.com/WebAssembly/binaryen), but it should also be packaged for most common Linux distributions. Sorry for all the inconvenience we've caused you so far!



> I'm guessing that's what would handle re-building the plugins?

Yes it does. I'm not 100% sure what steps the `cargo install ...` goes through. It's mostly supported to allow direct installation from crates.io. We recommend anyone building from source uses `cargo make`.

Hope you can get it all sorted out now! Feel free to reopen the issue if your problems persist.

**Comment by jwbowen** [comment]
It would be nice if the error/warning said something about binaryen being a dependency. I'm used to building C projects and needing to grab a development header package.
