### ISSUE TITLE
ENODEV: No such device

### ISSUE THREAD

**Issue by Lilja** [zellij-org/zellij#1861]
**Basic information**

`zellij --version`: `0.32.0`
`stty size`: `46 137`
`uname -av`: `Darwin Eriks-MBP 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64`

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`nvim --version`: `NVIM v0.7.2`
`wezterm --version`: `wezterm 20220807-113146-c2fee766`
`env | grep ZE`: `ZELLIJ_SESSION_NAME=delicious-paste
ZELLIJ=0`

**Further information**
I'm trying to do some work for #967, and I'm writing a neovim plugin to do so. What I'm trying to do in neovim is to use the `vim.fn.system`-API to call `zellij CLI`.

This is going fine:
`:lua print(vim.fn.system("zellij --help"))`
`:lua print(vim.fn.system("zellij --version"))`

But what I'm actually trying to do is to run `zellij action move-focus-or-tab right` to make zellij move to the next pane. Doing so, I'm getting the error in the title.
![image](https://user-images.githubusercontent.com/6134511/198115440-8bada44d-313b-46fd-a65d-69541bafc2f0.png)

![image](https://user-images.githubusercontent.com/6134511/198115465-712f7a36-d763-41b1-8607-3805ff15c089.png)

I'm running fish shell if that matters...

**Comment by Lilja** [comment]
I've done some debugging, the problem lies in `termios::tcgetattr(0)?;` of `zellij-client/src/os_input_output.rs`. I suppose that because I'm executing the code in a non-interactive terminal you can get attributes of the current executing terminal?

**Comment by imsnif** [comment]
Merged a fix for this, but wanted to say - good find @Lilja !
