### ISSUE TITLE
Status-bar - Hide tip line when plugin is configurer with `size=1`

### ISSUE THREAD

**Issue by welcoMattic** [zellij-org/zellij#1864]
Actually, with a layout like this:

```kdl
pane size=1 borderless=true {
    plugin location="zellij:status-bar"
}
```

It renders only the "tip line"
![image](https://user-images.githubusercontent.com/773875/198249784-7872419d-5436-44bc-ac4a-e4d1c5aea6cf.png)

Could it be possible to change it to render only the "controls line"?

Or better, add an option to configure the plugin from the layout like:

```kdl
pane size=2 borderless=true {
    plugin location="zellij:status-bar" options="lines:tip,controls"
}
```

```kdl
pane size=1 borderless=true {
    plugin location="zellij:status-bar" options="lines:controls"
}
```
Where we can choose the rendered line when size=1?

Thanks

**Comment by imsnif** [comment]
Hey, we can definitely add this as an option - but have you maybe considered the `compact-bar` instead?
https://github.com/zellij-org/zellij/blob/main/zellij-utils/assets/layouts/compact.kdl#L4

**Comment by welcoMattic** [comment]
compact bar is about displaying tabs, right? It adds the display of the current mode, but not the controls list?

**Comment by imsnif** [comment]
True - I guess you still want the mode+shortcuts display?
In that case we can make the status bar "do the right thing" depending on its size. Shouldn't be super difficult to change

**Comment by welcoMattic** [comment]
Yes, exactly. I'm super newbie in Rust. I guess I found the right place to do the trick, but not sure.

I guess we have to add some condition right there https://github.com/zellij-org/zellij/blob/main/default-plugins/status-bar/src/main.rs#L225-L233 ?

**Comment by imsnif** [comment]
> I guess we have to add some condition right there https://github.com/zellij-org/zellij/blob/main/default-plugins/status-bar/src/main.rs#L225-L233 ?

That seems right, yes! Would you like to give it a shot? If so, be sure to follow the build instructions in CONTRIBUTING.md - otherwise the plugins won't build and it could be very frustrating to figure out why your changes aren't taking effect.

**Comment by welcoMattic** [comment]
@imsnif Pr is open ;)

**Comment by imsnif** [comment]
Thanks again @welcoMattic !
