### ISSUE TITLE
IoError: The layout was not found

### ISSUE THREAD

**Issue by Dentrax** [zellij-org/zellij#1867]
I was reading the [Layout](https://zellij.dev/documentation/layouts.html#example) doc and created a simple layout as following:

```
$ cat ~/.config/zellij/layouts/default.kdl
layout {
    pane
    pane split_direction="vertical" {
        pane
        pane command="htop"
    }
}
```

Run:

```
$ zellij --layout ~/.config/zellij/layouts/default.kdl
IoError: The layout was not found, File: /Users/furkan/.config/zellij/layouts/default.kdl
```

_I'm running with default configs._

Am I missing something? Maybe related with: https://github.com/zellij-org/zellij/issues/1412. Is `layout` is a _plugin_?

**Comment by imsnif** [comment]
@Dentrax - a quick guess going by the other issue you opened, are you maybe running a Zellij version pre `0.32.0`?

**Comment by Dentrax** [comment]
Oh, it was `0.26.1`, my bad! 🙈 I think there was a small conflict between cargo vs brew. Thanks, I will check this out!

**Comment by imsnif** [comment]
All good! This error is a little misleading.

**Comment by Dentrax** [comment]
It seems error changed:

```
$ zellij -V
zellij 0.31.4

$ cat ~/.config/zellij/layouts/layout_file.kdl
layout {
    pane
    pane split_direction="vertical" {
        pane
        pane command="htop"
    }
}

$ zellij --layout ~/.config/zellij/layouts/layout_file.kdl
Deserialization error: invalid type: string "layout { pane pane split_direction=\"vertical\" { pane pane command=\"htop\" } }", expected struct LayoutFromYamlIntermediate at line 1 column 1
```

On `--help` flag:
```
-l, --layout <LAYOUT>            Name of a predefined layout inside the layout directory or the
                                     path to a layout file
```

It mentions `layout directory` but I don't know where it is or how to set. I couldn't see related config on `~/.config/zellij/config.kdl`. 🤔 

I was so hyped on this after saw this tweet: https://twitter.com/Zellij_dev/status/1585259738782044160?s=20&t=IvPmisl4WLKo065A54V1Og 🤩

**Comment by imsnif** [comment]
@Dentrax - we are almost there! You need Zellij `0.32.0` - that's when the KDL layout system was introduced :)
I know you have a problem installing it from cargo, but maybe you can download a pre-compiled version from our release? 
https://github.com/zellij-org/zellij/releases/tag/v0.32.0

**Comment by Dentrax** [comment]
Ohhh! I see now. 🙈 It worked like a charm! Thank you so much!

I also loved how `convert-X` commands are designed! Pretty life-saving to tackle breaking changes stuff. 😍 Cool idea!
