### ISSUE TITLE
Add rust-toolchain.toml file.

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#187]
I think it would be valuable to add a rust-toolchain file,
if it is powerful enough.
That way our rust versions and components could be in sync.
```
[toolchain]
channel = "Strings"
components = [ "Strings" ]
targets = [ "Strings" ]
```
https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

**Comment by imsnif** [comment]
Sounds good! @TheLostLambda - what do you think? As our resident build/cargo/rustup expert? :D

**Comment by TheLostLambda** [comment]
I think I commented on this in the Discord, but I think this is a great idea! I didn't know about it until @a-kenji  mentioned it!

**Comment by a-kenji** [comment]
Awesome! I suggested a small basic toolchain file.
I was not sure especially which targets are supported. 
So would be happy about some input.

**Comment by TheLostLambda** [comment]
So far as I'm aware, we should build on macOS and Linux, x86, x86_64, and aarch64. wasm32-wasi is also what the plugins are built for.

**Comment by a-kenji** [comment]
Cheers. 
Maybe it makes sense to not define the targets in the file then if we decide to use it at all -
they could be a lot and hard to maintain? 

I can build the project with just the file, but maybe I have some stuff thats still cached left over.
