### ISSUE TITLE
How to resize pane only vertically

### ISSUE THREAD

**Issue by naosense** [zellij-org/zellij#1893]
I checked the key map, and found `Alt+=/-`, but this key resizes the pane bottom right horizontally and vertically at the same time, i want resize the pane only vertically, how to do that?

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/2225426/199205469-0bae90c2-2196-4e84-83fd-98ddaaba0d71.png">

**Comment by imsnif** [comment]
Check out the `resize` mode, there you can resize in whichever direction you like.

**Comment by naosense** [comment]
> Check out the `resize` mode, there you can resize in whichever direction you like.

Oh, I see it, thanks!
