### ISSUE TITLE
Feature request: ability to change type of auto-generated session name

### ISSUE THREAD

**Issue by linuscm** [zellij-org/zellij#1907]
Been using Zellij at work and set it auto starts with my terminal, however been having an issue with the auto generated session names. Kinda inappropriate ones like "longing-children" and "ruthless-grandfather" were the highlights of the last few days. Funny at home, hard to explain to your coworkers.

**Comment by jaeheonji** [comment]
Sorry @linuscm 😭 
Sometimes, `names` auto-generate weird names.

Instead you can specify the session name like this:
```bash
$ zellij -s <SESSION_NAME> # Specify name of a new session
```

I hope this was the feature you wanted.

**Comment by raphCode** [comment]
I once got insulted as `jobless-pig` :(

**Comment by adigitoleo** [comment]
Is there a config option for that or does it have to be a CLI arg?
