### ISSUE TITLE
Lock interface except for navigation?

### ISSUE THREAD

**Issue by matthiasbeyer** [zellij-org/zellij#1920]
Is there a way to lock the interface, except for some things? For example, navigation with `Alt-HJKL` should not be locked, because it does not interfer with my other bindings (of my shell or whatever), but all `Ctrl-` bindings should be locked.

Is there a way to do this currently? If not, feel free to consider this a feature request :laughing:

**Comment by imsnif** [comment]
Definitely! You can add the keys you'd like to keep to `locked` mode in the config: https://zellij.dev/documentation/keybindings.html

**Comment by matthiasbeyer** [comment]
Awesome!
