### ISSUE TITLE
zellij is too fast

### ISSUE THREAD

**Issue by matthiasbeyer** [zellij-org/zellij#1921]
**Basic information**

`zellij --version`: 0.32.0

---

This title seems weird, but well. So here is what I am trying to do:

I want to spawn a new floating window in zellij and then send a command to it, which should be executed.

It goes like this:

```commandline
zellij action toggle-floating-panes
zellij action write-chars "some command"
zellij action write 10 # enter
```

My problem is, though, that `toggle-floating-panes` gets send and _immediately after_ the `write-chars` get send. But the write-chars does not write the chars to the new floating pane, but to the old non-floating, because zellij _is just too fast_ when doing this.

Would be nice if the action `toggle-floating-panes` would have a flag ... for example `--wait`, so I am able to wait until the floating pane is actually opened and then continue. My current workaround is to `sleep 0.1` between the two commands, but that's obvoiously not nice.

**Comment by imsnif** [comment]
I see what you're trying to do, and I agree that the `sleep 0.1` is not a very nice solution. We do have an atomic way of doing this however in the form of `zellij run --floating -- some command` or `zellij action new-pane --floating -- some command`. Will these fit your use case?

**Comment by matthiasbeyer** [comment]
Thanks for the fast reply.

It does not solve my issue entirely, because I need to pipe some stuff in there. So my actual command is more like:

```bash
git branch --all | grep -v HEAD | some_sed | some_awk | sort -u | fzf | some_awk | xargs git checkout
```

Sending that seems not to be possible... but I guess I can easily script around that, so thanks for your input (and again thanks for implementing zellij, it is awesome)!

**Comment by imsnif** [comment]
@matthiasbeyer - yeah, I get what you're saying. This doesn't work because Zellij doesn't spawn your shell, but rather just the command you send it, so the shell doesn't have a chance to interpret the various commands and pipes.

You should be able to do this with:
```
zellij run --floating -- bash -c "git branch --all | grep -v HEAD | some_sed | some_awk | sort -u | fzf | some_awk | xargs git checkout"
```

If this works, we provide an optional alias that does all of this for you, so then you'd do:
```
zrf git branch --all | grep -v HEAD | some_sed | some_awk | sort -u | fzf | some_awk | xargs git checkout
```
and it should just work.

You can check it out here: https://zellij.dev/documentation/controlling-zellij-through-cli.html#completions

**Comment by imsnif** [comment]
Also - if this doesn't work - I'd be happy to know so that we can find a solution for it. I don't want users to be forced to script for this use case.
