### ISSUE TITLE
Feature: support clipboard to text input

### ISSUE THREAD

**Issue by jaeheonji** [zellij-org/zellij#1922]
Related #1915

The following actions receive text input from the user.
* `PaneNameInput`
* `TabNameInput`
* `SearchInput`

These inputs currently only accept string inputs. And currently, the clipboard input is not considered at all.

However, the internal implementation of the these actions is very similar.
So if clipboard input is implemented, all of them can be applied.

**Comment by naosense** [comment]
seems easy, I would like give it a try if no one take it

**Comment by jaeheonji** [comment]
@naosense Thank you! You can take it if you want :)

**Comment by naosense** [comment]
Excuse me, is your log still works fine? I can't print logs after updating the latest code. Before I can see logs print out in `/tmp/zellij-uid/zellij-log/zellij.log` after I type `cargo make run`

**Comment by jaeheonji** [comment]
@naosense 

I haven't checked yet, but it seems to be related to this [PR](https://github.com/zellij-org/zellij/pull/1898).
Perhaps the location has been changed from the absolute path to another temp_dir.

**Comment by naosense** [comment]
Thank you @jaeheonji .Confirmed, it is indeed caused by this PR
