### ISSUE TITLE
Bug: cursor incorrectly lands on the frame when floating an embedded pane

### ISSUE THREAD

**Issue by xJonathanLEI** [zellij-org/zellij#1930]
This only happens when `pane_frames` is set to `false`.

Using the current `master` branch (`342d1629`).

**In Case of Graphical or Performance Issues**

[zellij.log.txt](https://github.com/zellij-org/zellij/files/9995129/zellij.log.txt)
[zellij-9.log.txt](https://github.com/zellij-org/zellij/files/9995130/zellij-9.log.txt)
[zellij-14.log.txt](https://github.com/zellij-org/zellij/files/9995131/zellij-14.log.txt)

**Basic information**

`zellij --version`: zellij 0.34.0
`stty size`: 35 116
`uname -av` or `ver`(Windows): Linux dev 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Reproduction steps**

First, set Zellij config to:

```kdl
pane_frames false
default_layout "compact"
```

Then, after launching Zellij:

`Ctrl-p` `w` `Ctrl-p` `e` `Ctrl-p` `e`

Expected result: The floated pane comes with a frame (like when it's first created), and the cursor lands _inside_ the pane.

Actual result: The cursor incorrect lands on the frame (see screenshot below). The frame is gone when any further input is made.

![Screenshot_20221112_221202_Termux](https://user-images.githubusercontent.com/19556359/201478091-90106b2c-a7fc-4652-a839-253516cbad2f.jpg)

Here's also an asciinema recording for your reference:

[![asciicast](https://asciinema.org/a/537156.svg)](https://asciinema.org/a/537156)

_Please ignore the excessive frame lines on the right. It seems to be an asciinema issue._

**Comment by imsnif** [comment]
I'm reproducing this! I missed this one in the previous fix. Will issue a fix for this next week. Are there any other cases you're having similar trouble with? (thanks for the troubleshooting help here, I just work with frames so don't see these)

**Comment by xJonathanLEI** [comment]
That's great! That's the only issue I'm experiencing right now. Thanks!
