### ISSUE TITLE
can't find alias cmd in command pane

### ISSUE THREAD

**Issue by naosense** [zellij-org/zellij#1932]
**Basic information**

zellij --version:zellij 0.33
stty size:22 100
uname -av or ver(Windows):Darwin ZBMAC-C02C21EH2.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Apr 18 21:50:40 PDT 2022; root:xnu-6153.141.62~1/RELEASE_X86_64 x86_64
zsh 5.9 (x86_64-apple-darwin19.6.0)
iterm2 v3.4.16
**Further information**
Reproduction steps, noticeable behavior, related issues, etc
1. add alias to .zshrc: 
```
alias ll='lsd -l'
alias zrf='zellij run -f --'
```
2. type `ll` works fine
3. zrf ll reports error below
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/2225426/201566033-8f892d94-cb9b-43ae-be43-ec16de7a4277.png">

**Comment by imsnif** [comment]
I'm not sure if this can be solved, honestly. In fish I'd have to do something like `funcsave ll` so that other terminal windows will have access to it too... maybe there's an equivalent in zsh?

**Comment by naosense** [comment]
Thanks for your reply@imsnif , but I got one question, what's the difference between floating pane and command pane? I test that cmd in floating pane, works nicely.

**Comment by imsnif** [comment]
I'm not sure I understand the question...

**Comment by naosense** [comment]
Sorry for not making it clear. I mean the command pane looks very much like a floating pane, `ll` could be found in a floating pane, why not in a comand pane?

**Comment by imsnif** [comment]
Can you find `ll` in a floating pane after defining it like you did above, or after saving it to the global aliases of zsh?

**Comment by naosense** [comment]
I think I found the cause of the problem, every time you open a floating pane  it runs the `$shell` command, while cmd pane doesn't

**Comment by imsnif** [comment]
For sure, but the `zrf` alias should do that for you...

**Comment by naosense** [comment]
Sry, my bad. I don't use config from `
$ zellij setup --generate-completion zsh`, but alias by myself

**Comment by imsnif** [comment]
All good! Glad it's working for you.
