### ISSUE TITLE
Ctrl + hjkl does not work

### ISSUE THREAD

**Issue by dahmc** [zellij-org/zellij#1935]
In vim, I use `Ctrl + h/j/k/l` to navigate my splits.

However, when I run vim inside zellij, these keys just don't register. 

Others like `Ctrl + w` work without a problem.

I tried unbinding every single key in the config, but still nothing happens.

Not sure what is happening, how can I fix this?

**Comment by dahmc** [comment]
Nevermind, it was my terminal that ate it up

**Comment by akiranguyenvni** [comment]
Sorry guys,
I'm using Iterm2 and Alacritty on Mac.
When I use Vim in Zellij on Iterm2 or Alacritty, I can not use `Ctrl + h/j/k/l`. How should I do?
@cd-a How did you solve it?

**Comment by cd-a** [comment]
I actually had explicit bindings set in my terminal config that overrode it. Once I removed that, it worked.

**Comment by akiranguyenvni** [comment]
Thank @cd-a . Seems that it's not my case.
My config for Alacritty is such simple:
<img width="1056" alt="image" src="https://github.com/zellij-org/zellij/assets/105026206/4d013c8a-46e2-4d7f-9971-6eed4e2be0ad">

And Vim works correctly in Alacritty and iTerm2 and TMux also.
Just if I open Zellij in Alacritty or iTerm, `Ctrl + h/j/k/l` not work.
Not sure reason why?!?
