### ISSUE TITLE
zellij with empty session name will be blocked forever

### ISSUE THREAD

**Issue by oraoto** [zellij-org/zellij#1939]
**Basic information**

`zellij --version`: 0.33.0
`stty size`: 43 91
`uname -av` or `ver`(Windows): Linux zj16 6.0.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 10 Nov 2022 21:14:24 +0000 x86_64 GNU/Linux

**Further information**

Simply run `zellij -s '' `, the zellij process will be blocked forever.

I think it should validate the session name and print an error message instead.

**Comment by jaeheonji** [comment]
@oraoto Good find! Thank you for reporting. I'll fix it ASAP.
