### ISSUE TITLE
Add ScrollToTop and assign default key bindings

### ISSUE THREAD

**Issue by cmpute** [zellij-org/zellij#1940]
Hi, thanks for your great work! I'm wondering why there is not a `ScrollToTop` action paired with `ScrollToBottom`. If that's just because no one has requested, I would like to request this feature. I usually opens a new panel to run a new command, and it's convenient if I can jump to the top with one key press to see the original command.

Besides, I would also like to propose adding two default key bindings: `Home` key in scroll mode for `ScrollToTop`, `End` key in scroll mode for `ScrollToBottom`.

Thanks!

**Comment by naosense** [comment]
afaik，there is a scroll-to-bottom action for now, and the shortcut key is Ctrl+c

**Comment by cmpute** [comment]
> afaik，there is a scroll-to-bottom action for now, and the shortcut key is Ctrl+c

Yes I'm aware of that, but it seems more intuitive to use the home and the end key to navigate.

**Comment by naosense** [comment]
There is a configuration item in config.kdl that can modify the shortcut, because I don't use this action very much, I haven't confirmed it

**Comment by DianaNites** [comment]
I also want this feature.

There is currently no way to scroll to the *top* of scrollback, only the bottom, because a `ScrollToTop` action does not exist, only a `ScrollToBottom` action.
