### ISSUE TITLE
Problems with repeatedly attaching to session - leaks memory and finally crashes

### ISSUE THREAD

**Issue by raphCode** [zellij-org/zellij#1948]
Just some stress testing with rapid attaching and detaching yielded this possible server crash locations:

```
Error occurred in server:

  × Thread 'server_listener' panicked.
  ├─▶ At .../zellij-utils/src/ipc.rs:213:37
  ╰─▶ called `Result::unwrap()` on an `Err` value: EMFILE
```

My build is at dc922907eb3aed6fd7a1ae6a2e23f03042801b28

**Comment by matu3ba** [comment]
My gut feeling tells me that there is a fork without CLOEXEC used (either no OCLOEXEC set or no execv being used leading to file descriptor leaking into the child process), but this does not explain the memory leaks.

**Comment by mfasold** [comment]
I ran into this issue in practice. We had a number of users running zellij on a single machine until all instances crashed at some point of time. The logs showed the same `EMFILE` error. 

Later I checked the number of open files, and found that zellij was using about 50k open file descriptors! The majority (85%) of them were Unix socket files for the server-client communication. About half of them were used by the "async-std" thread. 

Any ideas on how to get to the root of this issue? Would it be of any merit to build a server-client toy example that uses a LocalSocketListener in a separate thread?

**Comment by gbrigandi** [comment]
Just submitted a PR that fixes this issue, see #2322 .

**Comment by raphCode** [comment]
Nice! It fixes the crashes.

I fear we might still have a small memory leak tho:
- zellij, default layout with 1 tab, 1 pane, statusbar and tabbar
- directly after start + detach: 631MB resident set size
- 1000x `zellij ls`: 655MB

**Comment by imsnif** [comment]
@raphCode - these might not strictly be leaks, I think @tlinford has done some digging into the rust allocator and might have a relevant link handy?

**Comment by tlinford** [comment]
> @raphCode - these might not strictly be leaks, I think @tlinford has done some digging into the rust allocator and might have a relevant link handy?

Here is what I found about allocators in another issue: https://github.com/zellij-org/zellij/issues/1625#issuecomment-1411735893

**Comment by raphCode** [comment]
I am aware of the allocator playing a role, but this case looks like a leak to me:
Memory rises linearly with attach count, no anomalies. I performed 5000 attach repetitions. Or 5 repetitions of the '1000x attach' case, if you want.

Tell me if any of these would be helpful:
- rechecking with jemalloc branch
- running it under valgrind
- letting the test run longer
