### ISSUE TITLE
Feature: display current path in strider

### ISSUE THREAD

**Issue by imsnif** [zellij-org/zellij#195]
Right now, the strider plugin (a filesystem tree explorer) only displays the contents of the current directory. It can be very useful if it also displays the relative/full path of the current directory as a title or some other visible UI element.

**Comment by yhung119** [comment]
Hey :) can I help with this issue?

**Comment by a-kenji** [comment]
Hey @yhung119 
Yes that would be awesome!
Please don't hesitate to ask if you have some questions!

**Comment by imsnif** [comment]
A good place to display it would be the pane title (we didn't have pane titles when the issue was originally opened).

**Comment by RobWalt** [comment]
Hey, I'd like to contribute. Can anyone give me some hints on how the PluginPane and the plugins themselves communicate? I'm particularly interested in how I get information from the plugin to the pane.

**Comment by knidarkness** [comment]
Hey,

I've been playing around with `zelij` for a while now and would like to help on this issue, potentially using RobWalt's initial implementation.

**Comment by imsnif** [comment]
Sure thing @knidarkness - let us know if you need any help.

**Comment by imsnif** [comment]
Implemented in https://github.com/zellij-org/zellij/pull/3200
