### ISSUE TITLE
Feature: move current pane to new tab

### ISSUE THREAD

**Issue by imsnif** [zellij-org/zellij#196]
Similar to the tmux `break-pane` command.

**Comment by Monkeyanator** [comment]
Anybody working on this one? If not I'd like to give it a try :)

**Comment by a-kenji** [comment]
@Monkeyanator Awesome! 
Afaik, noone is working on it, so you should be free to to tackle it.
Please feel free to ask any Questions you have!

**Comment by imsnif** [comment]
I just want to mention that I really miss this feature in my day-to-day usage of Zellij. I unfortunately don't have time to devote to it myself right now, but @Monkeyanator - if you still have time for this and I can do anything to guide or help you, I'd be happy to.

**Comment by prscoelho** [comment]
Taking a look at this, seems like we can reuse the Tab::close_pane function by having it return the Pane, and it's good because that takes care of the shifting around of space that should happen when a pane is removed from the tab.

However I'm unsure how to go about creating a new tab with a specific Pane. We want to create a new tab with the provided layout but without any terminal panes, right?

**Comment by imsnif** [comment]
I haven't looked deeply at the code, but to give you a direction, I'd try to create an additional constructor for `Tab` that would allow this (or use the builder method as something like Tab::new(..).with_pane(pane)` if you want to be more rusty).

Getting the pane from `close_tab` sounds promising, but I'd be a little worried about doing this every time even when we don't need it. Perhaps we can duplicate the logic somehow?

**Comment by wviana** [comment]
Started using Zellij in my flow. Just missed this feature. Move a panel into its own tab.
Any updates on that?

**Comment by imsnif** [comment]
Implemented finally! Will be released in the next version.

**Comment by imsnif** [comment]
Incidentally, thanks @tlinford for laying down the groundwork for this.

**Comment by utkarshgupta137** [comment]
This is not visible in the documentation, had to search github to find it!

**Comment by JimitSoni18** [comment]
can someone please tell what keybind does this
