### ISSUE TITLE
Add possibility to define a layout to use when opening a new tab with a keybinidng

### ISSUE THREAD

**Issue by aschleifer** [zellij-org/zellij#1967]
Hi,

it would be nice to have a way to pass the path to a layout file to the `NewTab` keybinding action. In that layout the layout of the new tab can be defined. 

Not sure how to handle it if the layout config file defines multiple tabs or if you can prohibit that.

**Comment by jaeheonji** [comment]
Thanks for your opinion.

This feature seems to have a dependency on #742

**Comment by jaeheonji** [comment]
@aschleifer Oh I got it. I'll try to find out if that's possible with keybindings.

**Comment by aschleifer** [comment]
@jaeheonji is there also documentation about how this new feature can be used? Also do you know when a new version of zellij is being released which contains this?

**Comment by jaeheonji** [comment]
@aschleifer A simple example is specified in CHANGELOG, but the document will be added to the official website later. A new version of zellij will be released within this week! Thank you for waiting.

**Comment by aschleifer** [comment]
@jaeheonji thanks for the implementation and the fast response. i will await the release with anticipation

**Comment by bluss** [comment]
Just a note, `NewTab { name "SomeName"; }` causes the tab to open with the default layout, while just `NewTab` causes a new tab with whatever layout was passed on the commandline  (-l compact). From the outside, this is surprising and the latter behaviour would be the preferred one.
