### ISSUE TITLE
--layout working differently with different actions

### ISSUE THREAD

**Issue by TheCodeLamp** [zellij-org/zellij#1969]
Hello, I really like this project and wanted to help/offer a suggestion.

I like to start my shell in Zellij but when I do this there is no easy way to apply a layout.
I have a layout called `'my-layout'` in `.config/zellij/layouts/`
`zellij --layout 'my-layout'` will open the right layout but nested inside another Zellij instance inside the already open instance.
`zellij action new-tab` has a --layout argument but this doesn't see `'my-layout'`.

I'm not sure what the right way would be, but I would like it of there was a way to change layouts while inside Zellij.

**Comment by zolrath** [comment]
I'm seeing this as well, it appears the `zellij action new-tab --layout` command isn't aware of the default template directory and needs the full path to function.
I'd expect it to respect the same default path as the primary `zellij --layout` command

**Comment by imsnif** [comment]
This was fixed in: https://github.com/zellij-org/zellij/issues/1969

Will be published in the next release, hopefully in the next week or two.
