### ISSUE TITLE
Font size per pane

### ISSUE THREAD

**Issue by Javier-Romario** [zellij-org/zellij#1991]
First of all thank you all for this awesome tool! 

Noticed today that we (using zellij 0.33.0) cant have a font size per pane, is that something that could be possible or should this be an enhancement issue?

**Comment by raphCode** [comment]
Any terminal application can just send text (and some standardized control codes for cursor location / color) to the terminal, which is responsible for actually turning the text data into images.
Decades ago, this even worked without monitors, using computerized typewriters typing on physical paper. This evolved to the graphical terminal emulators that are commonly used today.
The common baseline is that terminals still use a single font size and assume monospace fonts, so I am afraid that with the current terminal architecture that is used this is not possible, even if zellij wanted to.

**Comment by Javier-Romario** [comment]
Thank you for your succinct answer, I understand. Closing this issue now.
