### ISSUE TITLE
change <Ctrl> key to <Command> key on Macos

### ISSUE THREAD

**Issue by 3Xpl0it3r** [zellij-org/zellij#2007]
Im set <super t> or <command t> to  replace <ctrl t> , but is doesn't work.
Is zellij does't support change this ? 
Is there any body can tech me how to config this?

**Comment by imsnif** [comment]
Hey, this is not possible unfortunately. Not because of Zellij but because the terminal emulator doesn't send Zellij this key through STDIN.

**Comment by hamza72x** [comment]
@3Xpl0it3r

Let me give you a workaround:

`iTerm` > `Preferences` > `Keys` > `Remap control key to` = `Left Command`

And `Remap Left command key to` = `Control`

Then in you `.zshrc`

```sh
# define function that retrieves and runs last command
function zsh_clear {
    clear;
    zle redisplay;
}

# define run-again widget from function of the same name
zle -N zsh_clear

# bind widget to Ctrl+K in viins mode
bindkey \^K zsh_clear
```
