### ISSUE TITLE
background rendering issue with vim

### ISSUE THREAD

**Issue by jcaplan** [zellij-org/zellij#201]
![image](https://user-images.githubusercontent.com/10764469/108610003-23f2ac00-73a0-11eb-89d9-2182b2308223.png)

exact same vim configuration running side by side in tmux (left) and zellij (right).
the background is rendered a bit funny in the zellij pane

**Comment by jcaplan** [comment]
issue only appears initially and when scrolling line by line. if I ctrl-f down the file it cleans itself up somehow:

in this picture I've scrolled up and down a bit so the center is colored in properly:

![image](https://user-images.githubusercontent.com/10764469/108610107-0d992000-73a1-11eb-9612-02bcbeaaecb3.png)

**Comment by a-kenji** [comment]
Thanks! Which color scheme is that?

**Comment by jcaplan** [comment]
np :)

```
set background=dark
colorscheme=PaperColor
```
https://github.com/vim-scripts/PaperColor.vim

**Comment by kunalmohan** [comment]
This looks similar to https://github.com/zellij-org/zellij/issues/139

**Comment by a-kenji** [comment]
I can't reproduce it with your colorscheme and background setting sadly.
Can you tell me your terminal emulator and its settings please?

**Comment by imsnif** [comment]
Just a quick note: I would not be surprised if this happens only when running Zellij inside a tmux pane. It's still a bug, but might be a very specific one :)

**Comment by jcaplan** [comment]
for me happens outside of tmux also. I have set `TERM=xterm-256color`

**Comment by imsnif** [comment]
Heads up: I managed to reproduce this, thanks! I'll take a look at it sometime this week.

**Comment by imsnif** [comment]
Fixed! Thanks for the report, @jcaplan - please keep them coming :)

**Comment by dpapchenkov** [comment]
This bug probably ressurected, see #4450 
identical problem: scrolling by page (pgup/pgdn works normally, but scrolling one line broken) broken, setting t_ut= in vim fixes this, so background color erase (bce) broken again.
