### ISSUE TITLE
current work directory not taken from shell for `zellij edit`

### ISSUE THREAD

**Issue by aschleifer** [zellij-org/zellij#2016]
`zellij --version`: `zellij 0.34.3`

I'm running alactritty, zsh and vim. So in a new terminal I do these steps:

1. `zellij` to start a new session from my home folder
2. `pwd` to see in which directory I am right now: `/home/aschleifer`
3. `mkdir zellij-test` to create a new test directory
4. `cd zellij-test` to get into this new directory
5. `pwd` to see in which directory I am right now: `/home/aschleifer/zellij-test`
6. `zellij edit test.txt` to open my vim with a new empty file in a new pane to the right
7. within vim I run `:!pwd` to get vim to print the working directory

The result i get is `/home/aschleifer`, which is the directory from which I started the session (see point 2 above). I expected it to be `/home/aschleifer/zellij-test` like in step 5, since the editor was started from that pane/directory.

**Comment by favetelinguis** [comment]
Sound very much related to https://gist.github.com/favetelinguis/6de5b778846f5b8d3755f71223baac4d where i also see the session pwd in the new pane.

**Comment by imsnif** [comment]
Hey @aschleifer - thanks for opening this issue after our discord chat. I now understand what you mean and can reproduce it: while the file itself is opened/created in the right place, the `pwd` of the process itself is unchanged.

This is a more minor issue IMO, but I'll try to get it fixed for the next version anyway.
