### ISSUE TITLE
exit control mode on non-control input or capture and discard inputs

### ISSUE THREAD

**Issue by jcaplan** [zellij-org/zellij#202]
steps to reproduce:

- press ctrl-g
- type a non-control character (e.g. z) and it shows up on the shell prompt
- then press a valid command key (e.g. p) and it takes me to the pane options. I'm still in command mode!

This is pretty confusing. I would expect to either be completely in or completely out after pressing ctrl-g. if Pressing z key (or any non-command character) should either take me out, or else it should not be forwarded to the terminal and should not appear on the shell prompt.

**Comment by categorille** [comment]
Hi! I think there is already an open issue for this #184.

**Comment by imsnif** [comment]
Yes, this is the same as #184 - closing this one.
