### ISSUE TITLE
`focus` option in custom layout not working

### ISSUE THREAD

**Issue by y-mx-b** [zellij-org/zellij#2021]
**Basic information**

`zellij --version`: zellij 0.34.4
`stty size`: 56 234
`uname -av` or `ver`(Windows): Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64

`wezterm --version`: wezterm 20221122-154621-68c754b1

**Further information**
Layout MWE:
```kdl
layout {
    tab focus=true {
        pane size=1 borderless=true {
            plugin location="zellij:tab-bar"
        }
        pane
    }
    tab {
        pane size=1 borderless=true {
            plugin location="zellij:tab-bar"
        }
        pane
    }
}
```

Result: focus is on tab 2 instead of tab 1

![Screenshot 2022-12-13 at 11 57 10 PM](https://user-images.githubusercontent.com/48655352/207367286-4fe8cdc6-340f-483b-983b-66396fde3e2e.png)

**Comment by y-mx-b** [comment]
Also reproducible in iTerm2 (version 3.4.18)

![Screenshot 2022-12-14 at 12 00 33 AM](https://user-images.githubusercontent.com/48655352/207368143-4f98b5e1-2d5c-4e42-a07c-1010e2cb8d7a.png)

**Comment by mabasic** [comment]
Can confirm that focus does not work for me too. Tried with tab focus and pane focus on single line and inside block, but none works.

```bash
zellij 0.34.4
```

**Comment by pennbauman** [comment]
I'm having focus work for `pane`s but not for `tab`s.  I'm using zellij version 0.34.4.

**Comment by alekspickle** [comment]
yep, for tabs definitely don't work
