### ISSUE TITLE
Weird characters on startup

### ISSUE THREAD

**Issue by Mo8it** [zellij-org/zellij#2022]
When I open Zellij with the terminal Wezterm I get characters like `s[4;2494;4085t[6;43;19t` in the shell prompt.

This happens after the update to version `0.34.3`.

**Comment by Mo8it** [comment]
@imsnif I did edit the description now with Wezterm instead of Kitty. With Wezterm, I get the weird characters every time I launch the terminal with Zellij. Maybe you can reproduce this? I think that this is related to the optimization of the startup time.
Ping me if you have any idea how to debug it :D

**Comment by Mo8it** [comment]
Here is a demonstration video:

[Screencast from 2023-02-21 15-59-54 (trimmed).webm](https://user-images.githubusercontent.com/76752051/220382556-f3ef40a6-ce53-4c2c-8fd7-b9d05e9fe2bf.webm)

It is random. Sometimes you get these characters, sometimes not, sometimes the sequence is short, sometimes double the length.

It seems to me that Zellij is trying to parse the terminal information and has some time limit to stop parsing and the rest is thrown to the shell.

**Comment by imsnif** [comment]
Fixed by https://github.com/zellij-org/zellij/pull/2173
