### ISSUE TITLE
Unable to disable Quit on Ctrl+q

### ISSUE THREAD

**Issue by NeveIsa** [zellij-org/zellij#2026]
Zellij is not respecting the config file where I comment out Ctrl+q line.
Zellij will still quit on Ctrl+q

I use micro text editor which uses the same shortcut to quit  and  I wouldn't want Zellij to quit on Ctrl+q.

   shared_except "locked" {
        bind "Ctrl g" { SwitchToMode "Locked"; }
        // bind "Ctrl q" { Quit; }
        bind "Alt n" { NewPane; }
        bind "Alt h" "Alt Left" { MoveFocusOrTab "Left"; }
        bind "Alt l" "Alt Right" { MoveFocusOrTab "Right"; }
        bind "Alt j" "Alt Down" { MoveFocus "Down"; }
        bind "Alt k" "Alt Up" { MoveFocus "Up"; }
        bind "Alt =" "Alt +" { Resize "Increase"; }
        bind "Alt -" { Resize "Decrease"; }
    }

**Comment by imsnif** [comment]
Have you tried clearing the default keybindings? Globally you can do this with `keybinds clear-defaults=true { ... }`

**Comment by NeveIsa** [comment]
That helped a lot and it works now. Thanks for the quick support.
