### ISSUE TITLE
Lines appear when opening the neovim default start page

### ISSUE THREAD

**Issue by ruihildt** [zellij-org/zellij#2037]
**Basic information**

`zellij --version`: 0.34.4
`stty size`: 35 152
`uname -av` or `ver`(Windows): Linux fedora 6.0.12-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Dec 8 16:58:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`nvim --version`: NVIM v0.8.1
`alacritty --version`: konsole 22.08.3

**Further information**
Reproduction steps, noticeable behavior, related issues, etc

I didn't customize either theme from bash, neovim or zellij. Everything is just default config from Fedora + KDE.

To reproduce:, run NVIM in Zellij, the start page displays blue lines disappearing when typing (but not when using space^^, see gif below).

![zellij-nvim-bug](https://user-images.githubusercontent.com/13787166/208465936-7eb33912-efdf-4a7e-a011-fcdc10ee2645.gif)

[zellij-20.log](https://github.com/zellij-org/zellij/files/10260272/zellij-20.log)
[zellij.log](https://github.com/zellij-org/zellij/files/10260273/zellij.log)
[zellij-9.log](https://github.com/zellij-org/zellij/files/10260269/zellij-9.log)
[zellij-16.log](https://github.com/zellij-org/zellij/files/10260270/zellij-16.log)
[zellij-18.log](https://github.com/zellij-org/zellij/files/10260271/zellij-18.log)

**Comment by raphCode** [comment]
I too get that issue sometimes in vim, but I am still running zellij 0.34.0 (session still open, can't upgrade)
![image](https://user-images.githubusercontent.com/15750438/209163313-18a61c39-16a8-480c-b9e5-049e87d05638.png)

**Comment by imsnif** [comment]
Fixed in https://github.com/zellij-org/zellij/pull/2204
