### ISSUE TITLE
per-session layouts

### ISSUE THREAD

**Issue by Pinoinha** [zellij-org/zellij#2043]
hello,

first of all, using zellij has been a bliss. I've now fully migrated from tmux and encourage my colleagues to give it a try.

one thing I'm missing, and it may as well be implemented already, is the ability to specify a layout to be used by specific sessions.

what I mean is to have something in the config file like so:
```kdl
session name="default" {
   layout "default"
}

session name="work" {
   layout "work"
}
```

or something similar, so that when I attach using `zellij attach -c work`, for example, the session uses it's predefined layout without further specification needed.

I tried to achieve this by doing something like below, to no avail.
```bash
zellij attach -c "work" options --default-layout "work"
```

is there something I'm missing in the docs?

thanks in advance

**Comment by imsnif** [comment]
Hey @Pinoinha - glad you're enjoying Zellij!

I'm a little hesitant to implement something like this, as this behaviour can be quite unexpected if you're not the person who wrote the config file. Imagine toubleshooting why sessions with certain names opened on a certain machine behave differently...

That being said, does this do what you want?
```
zellij --layout my-cool-layout attach -c "work"
```

**Comment by Pinoinha** [comment]
> Hey @Pinoinha - glad you're enjoying Zellij!
> 
> I'm a little hesitant to implement something like this, as this behaviour can be quite unexpected if you're not the person who wrote the config file. Imagine toubleshooting why sessions with certain names opened on a certain machine behave differently...
> 
> That being said, does this do what you want?
> 
> ```
> zellij --layout my-cool-layout attach -c "work"
> ```

this is incredibly simple yet I was able to overlook it lol

that's exactly what I was looking for, thank you so much! that solves my need for the config file implementation, and I get your points on debugging

closing this now
