### ISSUE TITLE
Zellij panics with PermissionDenied unless ran as root (WSL2, arch)

### ISSUE THREAD

**Issue by pedrofgodinho** [zellij-org/zellij#2045]
**Basic information**

`zellij --version`: 0.34.4
`stty size`: 30 120
`uname -av` or `ver`(Windows): `Linux PDesktop 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 GNU/Linux`

List of programs you interact with:
`zsh zsh 5.9 (x86_64-pc-linux-gnu)`
Running WSL 2 (arch) on windows terminal

**Further information**
Running `zellij` simply clears my terminal.  `echo $?` shows exit code `101`. Terminal gets kinda messed up depending on its size. Some lucky hacks with other terminal apps let me scroll up and see the panic:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /home/fowlron/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-utils-0.34.4/src/consts.rs:91:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Launches as usual when ran as `sudo zellij`

**Comment by pedrofgodinho** [comment]
Investigated a bit further, it fails when trying to create the `/run/user/...` directory, as the `/run/user/[UID]` directory somewhy doesn't exist (and it can't create it as `/run/user` is owned by root)

**Comment by imsnif** [comment]
Thanks for the report and investigation! I'll close this for now, but if you find it more, please do add the info here.

**Comment by i2** [comment]
Hi @imsnif,

I can report that I am facing the same issue. I thought, to avoid clutter, I'll use the same thread here.
My WSL2 is Ubuntu and I can confirm /run/user/$UID directory doesn't exist. Even after I create it, say /run/user/1000 for my non-root user, Zellij still gives permission denied error!

**Comment by pedrofgodinho** [comment]
the `/run/user/<pid>` directory is usually created on boot by systemd. WSL does not enable systemd by default. If you're running WSL2 [you can enable it](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/). Permission denied after you create it manually is probably due to directory permissions.

**Comment by TiLopes** [comment]
Hey I have systemd enabled and still get the same error. I'm using Windows 10 and [Arch WSL](https://github.com/sileshn/ArchWSL2) if that makes any difference. I have tried both through pacman and cargo and get an error.

**Comment by TiLopes** [comment]
![image](https://github.com/zellij-org/zellij/assets/106965010/74f5584e-4562-443f-bc9b-8e52834ddfd4)
`/run/user` is empty and it seems root is the owner of `/run/user/` is root.

**Comment by TiLopes** [comment]
@pedrofgodinho a simple `chown` to `/run/user/` seems to have solved the problem. Thank you for your help.

**Comment by kevinbader** [comment]
just wanted to add: happened to me as well, on WSL2 with Ubuntu - zellij wipes the screen, then exits. An error message would be nice 🙂
