### ISSUE TITLE
bash_profile not loaded

### ISSUE THREAD

**Issue by rgreinho** [zellij-org/zellij#2050]
**Basic information**

`zellij --version`: git branch --set-upstream-to=origin/
`stty size`:
`uname -av` or `ver`(Windows): Darwin Naboo.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 arm64

When starting zellij on osx, my `bash_profile` is not loaded automatically and I have to source it manually every time I open a new pane. Is there a way change this behavior?

Related discussion (although empty): https://github.com/zellij-org/zellij/discussions/1733

**Comment by naosense** [comment]
Hey@rgreinho , thanks for your report. As far as I know, `bash_profile` only loads when the user logs in, which is the behavior of the operating system. If you want to load every time the shell starts, you might want to try `bashrc`.

**Comment by rgreinho** [comment]
Thanks for your answer! I read a little bit more about it in the [bash manual](https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html#Bash-Startup-Files) After adjusting my content between the 2 files, now zellij works like a charm 👍
