### ISSUE TITLE
alt + any key. It doesn't work.  Alacritty + zellij + macOS 

### ISSUE THREAD

**Issue by keeYuc** [zellij-org/zellij#2051]
I have set a meta key in Alacritty.
I use option as alt in nvim.It works very well

- { key: N,         mods: Alt,       chars: "\x1bn"                       }

But when I enter zellij, it doesn't work. I use alt+n, alt+ any,no response, just output ˜ Like this

**Comment by cakir-enes** [comment]
Same goes for Warp, iTerm and kitty. It worked fine on wezterm tho

**Comment by naosense** [comment]
Thanks for your report. If you use iterm2, #1936 may work for you. I'm not familiar with Alacritty, you can check to see if Alacritty has such a setting

**Comment by alex35mil** [comment]
For Alacritty, https://github.com/alacritty/alacritty/issues/62#issuecomment-347552058

**Comment by alex35mil** [comment]
In Alacritty, the `Home`, `End`, and `Insert` keys also don't work. I didn't remap any of those keys anywhere.

**Comment by benvds** [comment]
I've also got this problem. setting the keybindings from the alacritty issues doesn't seem to work

**Comment by bguo068** [comment]
I had a similar issue with macOS

**Comment by VersBinarii** [comment]
Same here, works fine with iTerm but Alacritty just refuses to work. Also Alacritty + tmux works without issues

**Comment by merikan** [comment]
To make `Option` key act as `Alt` key on Macos was fixed in [v0.12.0-RC1](https://github.com/alacritty/alacritty/releases/tag/v0.12.0-rc1) with the `Window` option `option_as_alt`. Using `Alt`+`[h,j,k,l]` to switch between Panes now works as expected.
```
window:
  option_as_alt: Both
```

**Comment by imsnif** [comment]
We recently added an FAQ for this issue specifically: https://zellij.dev/documentation/faq.html#i-am-a-macos-user-how-can-i-use-the-alt-key

@merikan - if you'd like to make a PR to the zellij website repository and add this information for Alacritty, it would be greatly appreciated!

**Comment by 3bluebird** [comment]
@merikan  @alex35mil According to your configuration, after it is completed, the `Alt + hjkl` keys are effective, but only `Alt+n` does not work. It's so strange. 😣 

Please help me. 🥹

**Comment by merikan** [comment]
@3bluebird tI'm not quite sure I understand what you mean. The `option_as_alt` was added to Alacritty v0.12-RC1, try to download the latest (-RC2) and see if it works. 
Or did you do the keybindings in `alacritty.yaml`? I used to have that but the problem for me was that I am switching between ansi/us and iso/swe keyboards.
Try to start a new Alacrity session with debug enabled `alacritty --print-events | grep -i keyboardinput`
Copied from Alacritty website
```
```

**Comment by merikan** [comment]
@3bluebird 
Strange, it looks like it didn't send the `n` key
Are you using the latest Alacritty rc version?

I'm using Alacritty v0.12.0-rc with the config value `option_as_alt: Both`
When I start Alacritty with `print-event` and press `Option+n` I get the following values:
```
1. [54.333594328s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(140174797402112)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 58, state: Pressed, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: false } }
2. [58.782553420s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(140174797402112)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 45, state: Pressed, virtual_keycode: Some(N), modifiers: ALT }, is_synthetic: false } }
3. [58.902289590s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(140174797402112)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 45, state: Released, virtual_keycode: Some(N), modifiers: ALT }, is_synthetic: false } }
4. [59.625484260s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(140174797402112)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 58, state: Released, virtual_keycode: Some(LAlt), modifiers: (empty) }, is_synthetic: false } }
```
Look at the `Some` element and you will see LAlt (left option) and N
The first two have State: `Pressed` and the other two has `Released`

Have you tried to remove all your keybindings in Alacaritty just to be sure?

**Comment by 3bluebird** [comment]
@merikan  Haha, after switching to Alacritty v0.12.0-rc, the problem was fixed. I extend my sincerest thanks to you, thank you! 🤣

**Comment by cx330zer0** [comment]
input 'alt  <-' becomes D ,Unable to quickly jump words in terminal
<img width="775" alt="image" src="https://github.com/zellij-org/zellij/assets/75836557/d3929703-9d86-468a-8fe3-c1b779ac49ff">
This is my toml

**Comment by NullVoxPopuli** [comment]
I have an issue with alt+n on macos wiht `option_as_alt`,

```
[25.909710958s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(DeviceId), event: KeyEvent { physical_key: Code(AltLeft), logical_key: Named(Alt), text: None, location: Left, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: None, key_without_modifiers: Named(Alt) } }, is_synthetic: false }
[26.120547791s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(DeviceId), event: KeyEvent { physical_key: Code(KeyL), logical_key: Character("n"), text: Some("n"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("n"), key_without_modifiers: Character("n") } }, is_synthetic: false }
[26.200185416s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(DeviceId), event: KeyEvent { physical_key: Code(KeyL), logical_key: Character("n"), text: None, location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("n"), key_without_modifiers: Character("n") } }, is_synthetic: false }
[26.488583958s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(DeviceId), event: KeyEvent { physical_key: Code(AltLeft), logical_key: Named(Alt), text: None, location: Left, state: Released, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: None, key_without_modifiers: Named(Alt) } }, is_synthetic: false }
```

I'm not using qwerty -- could that be a problem?

The issue that I'm seeing is that the key combo seems to be captured by alacritty, and not passed to any of my TUIs (neovim in particular)

**Comment by nietaki** [comment]
For all Polish (and other moonspeak) users, to keep the ability to type all your "żółć" characters in your files, you want this in your Alacritty config:

```toml
[window]
option_as_alt = "OnlyLeft"
```

It's easy to find anyways, but it might save someone a step
