### ISSUE TITLE
Is there a way to close other panel by shortcuts in zellij?

### ISSUE THREAD

**Issue by woshichuanqilz** [zellij-org/zellij#2053]
for example  I have three panel in window, I want to close other two panels when I was in one. 

It is a pretty useful commands for me but I cant find it in the manual, how to do it?

**Comment by raphCode** [comment]
Have a look at `zellij action --help`. I believe you can focus the desired pane with these actions and close it.

What do you want to achieve?
There are more options, which I imagine could be useful for you:
- There is the possibility to specify commands in layouts that are executed in their own panes, and the panes can be configured to close after the command exits.
- Also there are _floating panes_ which can be toggled and they _float_ on top of the other panes.

**Comment by woshichuanqilz** [comment]
> Have a look at `zellij action --help`. I believe you can focus the desired pane with these actions and close it.
> 
> What do you want to achieve? There are more options, which I guess could be useful for you:
> 
> * There is the possibility to specify commands in layouts that are executed in their own panes, and the panes can be configured to close after the command exits.
> * Also there are _floating panes_ which can be toggled and they _float_ on top of the other panes.
> * You can also temporarily maximize a single pane to fullscreen

Thank you so there is not a command same to `close other panel`. 
Base on your options, I think fullscreen is the closet. 

Thank you
