### ISSUE TITLE
How to use the search feature in the zellij?

### ISSUE THREAD

**Issue by woshichuanqilz** [zellij-org/zellij#2054]
when in search mode, nothing happens when I type the key it says. And I havent found related topic in the doc. How to use it? 

![image](https://user-images.githubusercontent.com/11295355/210129094-9377e584-2de6-436a-9420-7f28ffcd9f08.png)

**Comment by raphCode** [comment]
The screenshot shows panes that look like you are running (neo)vim. The search does not work there.

The search feature is intended for terminal scrollback, such as when you are in your shell and a command outputs a lot of text. In a normal terminal emulator you can then scroll up and down to see the earlier text. In zellij, this can be achieved in the scroll mode or with the mouse wheel as well.

---

Nonetheless, we could enhance the UI to indicate scroll mode does not work in vim and similar applications. What is the correct name for that terminal mode again?

**Comment by woshichuanqilz** [comment]
> The screenshot shows panes that look like you are running (neo)vim. The search does not work there.
> 
> The search feature is intended for terminal scrollback, such as when you are in your shell and a command outputs a lot of text. In a normal terminal emulator you can then scroll up and down to see the earlier text. In zellij, this can be achieved in the scroll mode or with the mouse wheel as well.
> 
> Nonetheless, we could enhance the UI to indicate scroll mode does not work in vim and similar applications. What is the correct name for that terminal mode again?

Thank you. 

And what do you mean by terminal mode?

**Comment by raphCode** [comment]
Don't worry about terminal modes, that question was directed to the other zellij devs.
It is about the internal workings of the linux tty.
