### ISSUE TITLE
Support for vim-tmux-navigator

### ISSUE THREAD

**Issue by casonadams** [zellij-org/zellij#2057]
It would be nice to have a `if-shell` similar to `tmux`
So that I can do a similar setup as follows:

```tmux.conf
# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator

is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?)(diff)?$'"

bind 'h' if-shell "$is_vim" 'send-keys C-w h' 'select-pane -L'
bind 'j' if-shell "$is_vim" 'send-keys C-w j' 'select-pane -D'
bind 'k' if-shell "$is_vim" 'send-keys C-w k' 'select-pane -U'
bind 'l' if-shell "$is_vim" 'send-keys C-w l' 'select-pane -R'
```

I wouldn't mind helping to do something like this if I can get some direction on maybe where to start.

**Comment by jaeheonji** [comment]
Hi, @casonadams

There is already discussion related to this feature. #967
And You can check this neovim plugins [Lilja/zellij.nvim](https://github.com/Lilja/zellij.nvim)

**Comment by imsnif** [comment]
Closing as duplicate, please see: https://github.com/zellij-org/zellij/issues/967#issuecomment-2089955089
