### ISSUE TITLE
Change theme failed how to fix

### ISSUE THREAD

**Issue by woshichuanqilz** [zellij-org/zellij#2059]
Here is my config dir. 
├── config.yaml
├── layout
│   └── oriLayout.yaml
└── themes
    └── tokyo-night-dark.kdl

The setting in my config file is `theme: "tokyo-night-dark". But no change on my zellij appearance. How to fix . 

Version

`zellij 0.31.1`

**Comment by naosense** [comment]
thanks for your report. Maybe you can try putting the theme in CONFIG_DIR/themes @woshichuanqilz 

Based on documentation https://zellij.dev/documentation/themes.html
> themes is located in CONFIG_DIR/themes by default. You can check it through zellij setup --check

**Comment by woshichuanqilz** [comment]
> thanks for your report. Maybe you can try putting the theme in CONFIG_DIR/themes @woshichuanqilz
> 
> Based on documentation https://zellij.dev/documentation/themes.html
> 
> > themes is located in CONFIG_DIR/themes by default. You can check it through zellij setup --check

Yes it is in the right directory. 
`zellij setup --check`: 
[THEME DIR]: "/home/lizhe/.config/zellij/themes" 

My setting:
![image](https://user-images.githubusercontent.com/11295355/210296907-f91b2768-f2c6-4fda-9d66-aa67a49c14a4.png)

**Comment by naosense** [comment]
Sorry, didn't solve your problem. I'm not familiar with this piece, see if others know it. However I found your version a bit old, you can upgrade to see if it works

**Comment by woshichuanqilz** [comment]
> Sorry, didn't solve your problem. I'm not familiar with this piece, see if others know it. However I found your version a bit old, you can upgrade to see if it works

Yes it caused by the version it is too old. Thank you
