### ISSUE TITLE
UTF-8 doesn’t show up in title

### ISSUE THREAD

**Issue by AkiroPhi** [zellij-org/zellij#2065]
**Basic information**

`zellij --version`: `zellij 0.34.4`
`stty size`: `51 239`
`uname -av` or `ver`(Windows): `Linux eg0 6.1.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 31 Dec 2022 17:40:35 +0000 x86_64 GNU/Linux`

**Reproducing**

Rename a tab or a pane with an "à, ê, é". I have tried with greek and cyrillic alphabet too.
The letter don’t show up in the title.

(This is my first issue, if i’m missing something, please tell me)

**Comment by naosense** [comment]
Hey @AkiroPhi , thanks for your report! I'll take a look.

**Comment by naosense** [comment]
Hey @imsnif ,  i found code below will filter non-english char, is this intend?
https://github.com/zellij-org/zellij/blob/3da1cbf95c34283091186fd54926673fe2ec10f6/zellij-server/src/screen.rs#L1113-L1115

**Comment by imsnif** [comment]
Hey @naosense - I think this is intended. Looking through git blame, it seems to have been a fix for: https://github.com/zellij-org/zellij/issues/1009

Maybe we can leave it as is but expand it to also include other special characters?

**Comment by AkiroPhi** [comment]
Nice Thank you very much
