### ISSUE TITLE
status-bar broken with size=1

### ISSUE THREAD

**Issue by panki27** [zellij-org/zellij#2077]
I found [this PR](https://github.com/zellij-org/zellij/pull/1875), which is supposed to only display the shortcut bar and no tips with `size=1`.

This seems to be broken in `zellij 0.34.4`. I am using the following layout:

```
layout {
    pane size=1 borderless=true {
        plugin location="zellij:tab-bar"
    }
    pane {
        pane 
    }
    pane size=1 borderless=true {
        plugin location="zellij:status-bar"
    }
}
```

But the status-bar does not appear at all. If I configure it with `size=2`, it works.

Also: If this `size=1` would work, what happens if I hit e.g. CTRL+ T? Usually, further hints (`<n> New`) are displayed on line 2.
Is it possible to still get these, but with `size=1`, basically overwriting the first line of the status bar?

Thanks in advance ❤

**Comment by imsnif** [comment]
Hey - we made some changes to the plugin system that might have broken this. This was a bit of "undefined behavior" to begin with... I am definitely open to implement some conditional rendering here though. I like your suggestion about displaying the tips if we're inside a non-normal mode. Adding a "help wanted" here if anyone's interested in working on this.
