### ISSUE TITLE
zellij sessions sockets may get deleted

### ISSUE THREAD

**Issue by raphCode** [zellij-org/zellij#2080]
zellij places its server sockets in XDG_RUNTIME_DIR.
Per specification*, this directory may be cleaned of old files periodically, and I suspect at least one user on discord lost access to his session this way.
The problem can be solved in two ways, ideally we do both:
- set the sticky bit on the socket file to avoid automatic cleanup *
- provide a method to recreate the socket file, e.g. on SIGUSR1

*Sources:
https://wiki.archlinux.org/title/XDG_Base_Directory#User_directories
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by luciusmagn** [comment]
Oh yeah, I was the user :D

**Comment by tlinford** [comment]
> Oh yeah, I was the user :D

Out of curiosity, could you share some details on your setup? It seems that in most cases (XDG_RUNTIME_DIR managed by systemd), automatic cleanup does not really happen.

**Comment by raphCode** [comment]
He mentioned to use the init system s6: https://www.skarnet.org/software/s6-linux-init/

**Comment by raphCode** [comment]
While #2141 prevents the automatic cleanup, I think it would be nice to recreate accidentally deleted sockets as outlined in the first post.
What do you think Thomas?

**Comment by luciusmagn** [comment]
Yep, I use Artix Linux with s6 init from skarnet!
