### ISSUE TITLE
Alt-h, Alt-l only go in one direction in fullscreen panes

### ISSUE THREAD

**Issue by imsuck** [zellij-org/zellij#2106]
**Basic information**

`zellij --version`: zellij 0.34.4 and [b274fc5](https://github.com/zellij-org/zellij/commit/b274fc5ab19abe8b3ef7f7afe38897f526263414)
`stty size`: 42 168
`uname -av` or `ver`(Windows): Linux endeavouros 6.1.6-arch1-3 #1 SMP PREEMPT_DYNAMIC Mon, 16 Jan 2023 12:51:23 +0000 x86_64 GNU/Linux

**Further information**

Reproduction steps:
1. Open `zellij`.
2. Open 3 or more panes in 1 tab.
3. Enable fullscreen.
4. Press `Alt-h`/`Alt-l`, they will both switch to the next pane but not the previous one.

https://user-images.githubusercontent.com/49095435/213832357-f4a28ebd-4001-40ce-913d-0f21e10798cc.mp4

**Comment by naosense** [comment]
can't see anything in the video

**Comment by imsuck** [comment]
> can't see anything in the video

If you have 3 panes: 1, 2, 3. After fullscreen pane 1, pressing either `Alt-h` or `Alt-l` will only cycle them in 1 direction (1 -> 2 -> 3 -> 1 -> ...).

In the video, I pressed `Alt-l` `Alt-l` `Alt-h` `Alt-h` which means the tabs should cycle like this 1 -> 2 -> 3  -> 2 -> 1.
But zellij cycled 1 -> 2 -> 3  -> 1 -> 2.

**Comment by imsnif** [comment]
I noticed this too the other day! Would love to see a fix for this.
