### ISSUE TITLE
CJK in Tab name

### ISSUE THREAD

**Issue by nikolasbertrand** [zellij-org/zellij#2108]
Using Fedora 37

The issue is not important, but still maybe a bug. 

When using layouts one is able to add CJK (Chinese, Japanese, Korean) Text as Tab/pane title. While the pane title shows this correctly, the Tab title stays blank. 

Example: 

tab name="Hello"      -> shows as  'Hello' correctly 
tab name="Helloば"  -> shows as '' ... blank
tab name="ば”　       -> is also blank 
Same with Kanji and Hangul. 

This shouldn't be a font issue, since pane name="" works flawlessly and the fonts are the same I assume.  
I have not tested using them in the status bar yet, but for users of non alphanumeric scripts this might be Interesting to look at.

**Comment by imsnif** [comment]
@naosense - I think you did a similar fix for pane names, right? Or was that a different issue?

**Comment by naosense** [comment]
@imsnif yep, I think it is
@nikolasbertrand Are you using the latest merged code?

**Comment by nikolasbertrand** [comment]
@naosense I am on the   with cargo packaged version : 0.34.4

**Comment by imsnif** [comment]
> @imsnif yep, I think it is @nikolasbertrand Are you using the latest merged code?

Would you like to see if the fix can work here too? It's probably a very similar issue...
