### ISSUE TITLE
Feature request: Ability to rename a session

### ISSUE THREAD

**Issue by Sharpeee** [zellij-org/zellij#2113]
I am really not a fan of the auto-generated session names! They are weird and difficult to remember!

I would like #1907 to be implemented, but I would also like a way to rename the session after it has been started, as I do not always know what I am going to use the session for.

**Comment by jaeheonji** [comment]
Note: #998, #999

**Comment by Abraxas-Knister** [comment]
To anyone who finds this in search for an answer: 
 - `<c-b>` to unlock 
 - `o` to open the session tab 
 - `w` then gets to the session manager 
 - `<c-r>` will then rename
 
or, from inside the session to be renamed 

    zellij action rename-session <name>
