### ISSUE TITLE
Unfortunate random session name

### ISSUE THREAD

**Issue by greysonp** [zellij-org/zellij#2114]
Very unfortunate session name :sweat_smile: 
I'd probably just remove the word "racial" from the word pool.
![image](https://user-images.githubusercontent.com/1358731/214890865-6aa396b0-72d5-44b4-b051-dce51505c0ea.png)

```
$ zellij --version
zellij 0.34.4
```

**Comment by eblume** [comment]
I just got "itchy-balls". I mean, zellij ... yeah, you get it.

My personal opinion, itchy-balls is hilarious, but I do agree that pulling "racial" out of the list is a good idea, and it looks like Issue #2122 could handle my itchy-balls problem.

**Comment by gingsi** [comment]
The first words that zellij greeted me with was "old-wound". I am now using an alias with a random 3 letter name

`alias jn='zellij --session $(tr -dc a-z0-9 </dev/urandom | head -c 3 ; echo "")'`

Connecting this similar issue https://github.com/zellij-org/zellij/issues/2617
