### ISSUE TITLE
Strider opens each file in two panes

### ISSUE THREAD

**Issue by idevtier** [zellij-org/zellij#2118]
If I start new session with command `zellij --layout strider` or my custom layout with strider, then plugin works correctly. But if I create new tab with layout `zellij action new-tab --layout strider`, then strider opens each file twice (in two panes). 

`stty size`  - 23 129
zellij version - 0.34.4

[logs.tar.gz](https://github.com/zellij-org/zellij/files/10523081/logs.tar.gz)

Thank you for the time, maybe next week I will have time and I will try to send PR.

**Comment by Zykino** [comment]
Same. It also open the file with `vim` instead of my configured `$EDITOR`: `helix`(in fish) or `kak` (in bash).
It also open `bash` as shell instead of `fish` that I configured.

And now that I say that, some issues in that may be linked to #2187
