### ISSUE TITLE
Keybind to change pane layout (horizontal to vertical)

### ISSUE THREAD

**Issue by davxy** [zellij-org/zellij#2121]
If I have my window horizontally splitted in two panes, is there an action that I can associate to a keybind
(or a keybind I'm not aware of) that allows me to change the layout to two vertically splitted panes?

Or something like tmux `ctrl+b  + space` to change how the panes are organized within the window

As an easy solution I was expecting that in "Pane" mode (ctrl+b) I can do that using 'l' or 'r'.

As a hack is possible to do that by:
1. first create a temporary pane on the right of one of the two horizontal panes
2. move the temporary pane down (or up)
3. close the "temporary pane"
4. now I have the original two horizontal panes as two vertical panes

But I don't think this is the proper solution 😃

**Comment by imsnif** [comment]
This will come in the next version, here's a preview (the default layout will come with "vertical", "horizontal" and "stacked" swap layouts for tiled panes and "staggered", "expanded" and "spread" for floating panes).
![img-2023-01-25-095443](https://user-images.githubusercontent.com/795598/215485699-d11eb22b-350c-42ec-a51f-2bb59148617c.png)

**Comment by davxy** [comment]
Is there already an open PR for this feature?

**Comment by imsnif** [comment]
Not yet, still working out the kinks!

**Comment by davxy** [comment]
closed by https://github.com/zellij-org/zellij/pull/2167
