### ISSUE TITLE
U+00303 (combining tilde) disappears in zellij

### ISSUE THREAD

**Issue by rowanxshi** [zellij-org/zellij#2124]
**Basic information**

`zellij --version`: `zellij 0.34.4`
`stty size`: `57 80`
`uname -av` or `ver`(Windows): `Darwin serene.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 arm64`

**Further information**
U+00303 (combining tilde) in e.g. p ̃ doesn't show up in zellij (either on archlinux or macos). Outside of zellij, the tilde displays above the character properly.

To replicate, paste p ̃ (or any other character with the tilde) into zellij.
<img width="639" alt="Screenshot 2023-01-30 at 16 35 38" src="https://user-images.githubusercontent.com/37481598/215600814-b411b13b-58dc-46cd-881a-73e6096ea710.png">

**Comment by dyuri** [comment]
Other unicode combining characters/ranges are affected as well.

W/O zellij:
![image](https://user-images.githubusercontent.com/126637/215704680-93192ef2-409f-45e1-843a-fbced5224a0e.png)

In zellij:
![image](https://user-images.githubusercontent.com/126637/215704971-17faa1d7-4948-4569-9685-200b073a0d32.png)

Steps to reproduce:
```
$ python -c "print('a\u0363\u1ab8\ufe2d')"
a᪸︭ͣ
```
