### ISSUE TITLE
Feature: no frames for single pane tabs

### ISSUE THREAD

**Issue by Pheon-Dev** [zellij-org/zellij#2129]
This is more of a feature request than an issue:
- Could you have an option to have frames set to true but only show on tabs with more than one pane?

**Comment by imsnif** [comment]
This is a good solution! But to be fair it won't do what you want if you open another pane in "tab one".

Next version we're introducing `swap_layouts` which will allow you (among other things) to configure how the panes behave progressively as you open panes. Which I think would be a nicer experience for you.

**Comment by Pheon-Dev** [comment]
> This is a good solution! But to be fair it won't do what you want if you open another pane in "tab one".
> 
> Next version we're introducing `swap_layouts` which will allow you (among other things) to configure how the panes behave progressively as you open panes. Which I think would be a nicer experience for you.

Works alright for me at the moment @imsnif, can't wait for the next version. I've always wanted a way to swap active layouts
![Picture](https://user-images.githubusercontent.com/93865776/216094809-5d246811-817a-4e5a-8354-7f947f4c893a.png)
![Picture_1](https://user-images.githubusercontent.com/93865776/216094847-24c96a55-592d-4a73-b447-c3ea05d0b76f.png)

**Comment by imsnif** [comment]
Looks great! But didn't you want the frame back on the original pane once there are more of them? Or did I misunderstand?

**Comment by Pheon-Dev** [comment]
> Looks great! But didn't you want the frame back on the original pane once there are more of them? Or did I misunderstand?

You did understand, but I think the bug I thought is a better feature and works far much better than I wanted. You can see my lualine is right at the bottom where the frame would have been, more real estate for the editor the better. Good work.
