### ISSUE TITLE
Persistent session keybinding even after updating it.

### ISSUE THREAD

**Issue by Kahss** [zellij-org/zellij#2135]
**Basic information**

`zellij --version`: 0.34.4
`stty size`: 57 201
`uname -av` or `ver`(Windows): Linux LGOP5550 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

`nvim --version`: NVIM v0.9.0-dev

**Further information**
Reproduction steps:
- Modify `$HOME/.config/zellij/config.kdl`
- Update keybindings for session :
```
    // Change Ctrl o by Ctrl w to switch to session mode
    session {
        bind "Ctrl w" { SwitchToMode "Normal"; }
        bind "Ctrl s" { SwitchToMode "Scroll"; }
        bind "d" { Detach; }
    }
   ...
    shared_except "session" "locked" {
        bind "Ctrl w" { SwitchToMode "Session"; }
    }
```
- Exit zellij
- Open a new zellij session, the displayed keybinding for session is actually `Ctrl w`
- Press `Ctrl o`, it switches to session mode
- Press `esc` to exit session mode
- Press `Ctrl w`, it switches to session mode

This bug prevents me to use the neovim `Ctrl o` shortcut to jump back one level.

**Comment by imsnif** [comment]
I think you need to modify the `keybinds` node to have `clear-defaults=true`. There's a commented out line at the beginning of the config with this. Could you give it a try?

**Comment by Kahss** [comment]
It definitively worked. I should have read more carefully. Thank you very much !
