### ISSUE TITLE
installation w/ nix fails on arm64  

### ISSUE THREAD

**Issue by simondegheselle** [zellij-org/zellij#2149]
![image](https://user-images.githubusercontent.com/10697278/217788766-971a29aa-2de3-46c4-9fe7-f3e2c8fbab3c.png)

**Comment by imsnif** [comment]
Hey - we do not support nix directly through this repository and quite honestly I don't know a lot about it myself. Does it work with `cargo install --locked zellij`?

**Comment by simondegheselle** [comment]
Hi @imsnif, thx a lot for the reply, really enjoy using Zellij! it does seem to work properly with `cargo install --locked zellij` 👍. I was not aware that it was not officially supported on nix (therefore I'll close the issue)

It does seem like there is a package registered on nix for zellij, and it works flawless on my laptop (mac M1), however it seems to fail with the error above on aarch64 machines... 
https://search.nixos.org/packages?channel=22.11&show=zellij&from=0&size=50&sort=relevance&type=packages&query=zellij

**Comment by imsnif** [comment]
All good, glad you're enjoying Zellij!

We used to support Nix internally on this repository when it was the development environment of one of the maintainers, but this is no longer relevant - so we removed the support.

There seems to be a list of maintainers for this package in the link, might be a good idea to contact them.
