### ISSUE TITLE
Blank pane templates with `cwd` use wrong shell

### ISSUE THREAD

**Issue by har7an** [zellij-org/zellij#2150]
Thank you for taking the time to file this issue! Please follow the instructions and fill in the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

**Basic information**

`zellij --version`: latest main (5eb2d055ffa23f6775c12d7cc7e900e0d66a3def)
`stty size`: 55 118
`uname -av` or `ver`(Windows): Linux 6.1.9-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Feb  2 00:21:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Further information**

Start zellij with the following layout:

```
layout {
    pane_template name="shell" {
        name "SHELL"
        cwd "/home/hartan"
    }

    shell
}
```

- **Expected result**: Zellij uses the shell I have configured, `/bin/zsh`
- **Actual result**: Zellij uses the shell from `$SHELL`, `/bin/bash`

Regular panes use `/bin/zsh` as configured.

**Comment by imsnif** [comment]
Thanks for filing this @har7an - could you please separate these into 2 issues though? It would be easier to keep track of, as they are different bugs.

**Comment by har7an** [comment]
@imsnif Sure thing, sorry for that. The other one is #2165 now. :)

**Comment by imsnif** [comment]
Fixed by https://github.com/zellij-org/zellij/pull/2203
