### ISSUE TITLE
Layout file not found when used with new-tab action

### ISSUE THREAD

**Issue by darthmall** [zellij-org/zellij#2155]
**Basic information**

`zellij --version`: 0.34.4
`stty size`: 36 175
`uname -av`: Linux spiraling-shape 6.0.12-76060006-generic #202212290932~1674139725~22.04~ca93ccf SMP PREEMPT_DYNAMIC Thu J x86_64 x86_64 x86_64 GNU/Linux

**Further information**

I have a layout in `~/.config/zellij/layouts/dev.kdl`.

1. Start `zellij` (my default layout is set to `compact`)
2. Open a new tab with the dev layout: `zellij action new-tab -l dev`
3. Zellij responds `Failed to load layout: IoError: The layout was not found, File: dev`

According to `zellij setup --check`, my layout directory at the time is correct: `/home/evan/.config/zellij/layouts`.

If I start zellij with the dev layout — `zellij -l dev` — it finds the layout no problem.

**Logs**

[zellij.log](https://github.com/zellij-org/zellij/files/10714876/zellij.log)
[zellij-11.log](https://github.com/zellij-org/zellij/files/10714877/zellij-11.log)

**Comment by darthmall** [comment]
It may also be worth mentioning that creating a new tab with a built-in layout after starting Zellij with my custom layout works.

```
zellij -l dev
zellij action new-tab -l compact
```

It’s only trying to create a new tab from a compact layout with my custom layout that fails.

**Comment by zolrath** [comment]
This definitely should be fixed, but as a workaround you can provide the full path to layout to the `new-tab` action, as it doesn't seem to understand where the layout folder is.

**Comment by imsnif** [comment]
Fixed in https://github.com/zellij-org/zellij/pull/2198

Should be published in the next version (hopefully next week!)
