### ISSUE TITLE
Zellij window cannot display pictures.

### ISSUE THREAD

**Issue by wangmings** [zellij-org/zellij#2158]
terminal： iterm2

Open zellij enters the imgcat command supported by iterm2 to display the picture! You can't display pictures in zellij. Quit zellij and you can display pictures.

**Comment by imsnif** [comment]
Hey, Zellij only supports images using the widely supported Sixel protocol. imgcat uses (as far as I could figure out) a specialized protocol developed by iTerm2 which Zellij does not support.

You can check out `img2sixel` (from the libsixel) utility if you'd like to see supported images.

**Comment by jiiiijiij** [comment]
img2sixel don't work when I openup zellij :(((
