### ISSUE TITLE
Explicit names in command pane templates are ignored

### ISSUE THREAD

**Issue by har7an** [zellij-org/zellij#2165]
Thank you for taking the time to file this issue! Please follow the instructions and fill in the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

**Basic information**

`zellij --version`: latest main (5eb2d055ffa23f6775c12d7cc7e900e0d66a3def)
`stty size`: 55 118
`uname -av` or `ver`(Windows): Linux 6.1.9-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Feb  2 00:21:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Steps to reproduce**

Start zellij with the following layout:

```
layout {
    pane_template name="shell" {
        name "SHELL"
        cwd "/home/hartan"
        command "/bin/zsh"
    }

    shell
}
```

- **Expected result**: Zellij starts with a single pane, which has "SHELL" as title
- **Actual result**: Zellij starts with a single pane, which has "/bin/zsh" as title

**Comment by imsnif** [comment]
Hey, so - I think this is not a bug. The "name" field is used to name the `pane_template` (`shell`). If you want the pane to have a name of its own, you could do

```kdl
layout {
    pane_template name="shell" {
        name "SHELL"
        cwd "/home/hartan"
        command "/bin/zsh"
    }

    shell name="SHELL"
}
```

I get what you're trying to do though - and we could probably have an option to make this explicit by aliasing it to `title`.
