### ISSUE TITLE
feature / ability to remove "Zellij (session-name)" from top bar

### ISSUE THREAD

**Issue by pergamomo** [zellij-org/zellij#2172]
When using work path as session name (see: https://github.com/zellij-org/zellij/issues/2171 ) the top bar becomes cluttered.

![image](https://user-images.githubusercontent.com/82210878/219704400-68b1d5f4-261a-486a-99b8-f2f32664a333.png)

I would prefer to not have it at all and only show the tabs.

Like this:
![image](https://user-images.githubusercontent.com/82210878/219705861-f687873a-5175-4932-a620-7b340a842faa.png)

Thanks!

**Comment by mirql** [comment]
here is the plugin from zellij docs also without branding:

https://github.com/dj95/zjstatus

**Comment by survirtual** [comment]
> I'm pasting my response to the relevant PR here to make this information easier to find:
> 
> Zellij is an open-source project without any significant funding. This means that in addition to developing and maintaining the software, us maintainers also need to take care of outreach. Help others find out about Zellij in various ways. This is not an easy task when you do not have money to put into it like some other VC-funded tools in this space.
> 
> One of the major ways people find out about Zellij is from screenshots, streams or even just by looking over a friend's shoulder. If we include a config parameter that will allow people to remove our name from the UI - we would be making it more difficult for new users to find out about us, and in turn more difficult for us maintainers to perform outreach (I can testify that doing so as is takes away a significant amount of my time from development).
> 
> If anyone feels strongly about this, they are always welcome to create a version of the UI without our tool's name and maintain it on their own. This is something that will become easier in the coming months as we improve our plugin system.
> 
> So for the time being, until our funding and/or outreach situation changes - I'm going to have to leave this as part of our UI to help more users find out about us. Apologies if this inconveniences anyone - I hope you can see this as a small price to pay for a tool you love.

This is not the way to do it and is very off-putting.  You're making users install a third-party plugin just so they can have a clean experience on a terminal multiplexer?

I'm going to go do some breathing exercises now because I shouldn't be getting this upset over such nonsense.  When you make a useful utility, keep your ego out of it please.  I got my hopes up and invested time to using this tool and have wasted hours chasing for a non-invasive way to remove this branding, as it is a non-starter for me and totally disrupts my mental flow.  This is something that should easily be configurable using a single-line configuration.

When I work, I don't want to see this name, and I don't want to see a hard-coded goodbye message.  The fact this isn't easily configurable speaks to the quality of this project, as I no longer trust it for something as essential as terminal multiplexing.  Additionally, if there was a funding option, I would no longer be inclined to donate anything.

I really liked what I saw, too.  It's a shame.

**Comment by imsnif** [comment]
I'm sorry you don't like the way this free, open-source, not-for-profit software behaves. I encourage you to use software that makes you happy. If Zellij is not that for you, I'm sure you'll find something else that suits your needs.

**Comment by survirtual** [comment]
> I'm sorry you don't like the way this free, open-source, not-for-profit software behaves. I encourage you to use software that makes you happy. If Zellij is not that for you, I'm sure you'll find something else that suits your needs.

I encourage you to write software that is purely in service of users as opposed to ego.  I hope that you understand what I mean by that someday.  Projects tend to get more support and funding that way, especially when they lack smug passive-hostility towards users who would otherwise provide technical and financial support.

**Comment by survirtual** [comment]
For anyone else who is annoyed by this, you can fix it by rebuilding this project and performing these changes:
```bash
sed -i 's/ Zellij / /g' default-plugins/tab-bar/src/line.rs
sed -i 's/ Zellij / /g' default-plugins/compact-bar/src/line.rs
sed -i 's/Bye from Zellij!/Session Exited/g' zellij-client/src/lib.rs
sed -i 's/Bye from Zellij!/Session Exited/g' zellij-utils/src/ipc.rs
```

That should also provide the locations to modify if you'd like to inspect it yourself.

You need to rebuild the wasm modules as they are embedded via includebytes, then build the main project.

Here is a hacked together nix flake you can use that performs this change.  Use at your own risk.  It accomplished the task for me.

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    naersk.url = "github:nix-community/naersk";
    fenix.url = "github:nix-community/fenix";

    zellij = {
      url = "github:zellij-org/zellij";
      flake = false;
    };
  };

  outputs =
    {
      self,
      nixpkgs,
      flake-utils,
      fenix,
      naersk,
      zellij,
    }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs { inherit system; };

        fenixPkgs = fenix.packages.${system};

        # Toolchain with wasm stdlib (wasm32-wasip1)
        toolchain = fenixPkgs.combine [
          fenixPkgs.stable.rustc
          fenixPkgs.stable.cargo
          fenixPkgs.stable.rustfmt
          fenixPkgs.stable.clippy
          fenixPkgs.targets.wasm32-wasip1.stable.rust-std
        ];

        naerskLib = naersk.lib.${system}.override {
          cargo = toolchain;
          rustc = toolchain;
        };

        # Patch source
        zellijPatched = pkgs.stdenvNoCC.mkDerivation {
          pname = "zellij-src";
          version = "patched";
          src = zellij;

          nativeBuildInputs = with pkgs; [ ripgrep ];

          phases = [
            "unpackPhase"
            "patchPhase"
            "installPhase"
          ];

          patchPhase = ''
            set -euxo pipefail

            echo "== check files exist =="
            ls -la default-plugins/tab-bar/src/line.rs
            ls -la zellij-client/src/lib.rs
            ls -la zellij-utils/src/ipc.rs

            echo "== pre-check patterns =="
            rg -n "Zellij " default-plugins/tab-bar/src/line.rs || true
            rg -n "Bye from Zellij!" zellij-client/src/lib.rs zellij-utils/src/ipc.rs || true

            echo "== apply substitutions =="
            substituteInPlace default-plugins/tab-bar/src/line.rs \
              --replace-fail ' Zellij ' ' '

            substituteInPlace default-plugins/compact-bar/src/line.rs \
              --replace-fail ' Zellij ' ' '

            substituteInPlace zellij-client/src/lib.rs \
              --replace-fail 'Bye from Zellij!' 'Session Exited'

            substituteInPlace zellij-utils/src/ipc.rs \
              --replace-fail 'Bye from Zellij!' 'Session Exited'

            echo "== post-check =="
            ! rg -n "Zellij " default-plugins/tab-bar/src/line.rs
            rg -n "Session Exited" zellij-client/src/lib.rs zellij-utils/src/ipc.rs
            ! rg -n "Bye from Zellij!" zellij-client/src/lib.rs zellij-utils/src/ipc.rs
          '';

          installPhase = ''
            mkdir -p $out
            cp -R . $out/
          '';
        };
      in
      {
        packages.default = naerskLib.buildPackage {
          src = zellijPatched;

          pname = "zellij";
          version = "git-faeb91a3";

          cargoHash = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";

          nativeBuildInputs = with pkgs; [
            pkg-config
            perl
            protobuf # provides protoc for xtask build pipeline
          ];

          buildInputs = with pkgs; [
            zlib
            openssl
            curl
            ripgrep
          ];

          dontStrip = true;

          # Rebuild default plugins to wasm and refresh assets/plugins/*.wasm
          preBuild = ''
            set -euxo pipefail

            # naersk deps build uses dummy-src.
            # Only run xtask in the real workspace, not naersk deps dummy-src:
            # xtask must be present as an actual binary crate.
            if [ -f xtask/Cargo.toml ] && [ -f xtask/src/main.rs ]; then
              # Rebuild plugins (from patched sources in this build dir)
              ${toolchain}/bin/cargo xtask build --release --plugins-only

              # Ensure the bytes embedded by zellij-utils are the rebuilt ones.
              # zellij-utils embeds from: zellij-utils/assets/plugins/*.wasm
              embed_dir="zellij-utils/assets/plugins"
              target_dir="target/wasm32-wasip1/release"

              test -d "$embed_dir"
              test -d "$target_dir"

              # Fail hard if xtask didn't produce expected outputs
              for f in \
                compact-bar.wasm status-bar.wasm tab-bar.wasm strider.wasm session-manager.wasm \
                configuration.wasm plugin-manager.wasm about.wasm share.wasm multiple-select.wasm \
                sequence.wasm layout-manager.wasm
              do
                test -f "$target_dir/$f"
              done

              # Overwrite embed directory with rebuilt artifacts
              rm -f "$embed_dir"/*.wasm
              cp -f "$target_dir"/*.wasm "$embed_dir"/

              # Sanity: ensure embed dir now has all expected wasm
              for f in \
                compact-bar.wasm status-bar.wasm tab-bar.wasm strider.wasm session-manager.wasm \
                configuration.wasm plugin-manager.wasm about.wasm share.wasm multiple-select.wasm \
                sequence.wasm layout-manager.wasm
              do
                test -f "$embed_dir/$f"
              done
            else
              echo "Skipping plugin rebuild (deps-only dummy-src)."
            fi
          '';

          ZLIB_NO_VENDOR = "1";
          OPENSSL_NO_VENDOR = "1";
        };

        devShells.default = pkgs.mkShell {
          packages = with pkgs; [
            toolchain
            fenixPkgs.rust-analyzer
            protobuf
          ];
        };
      }
    );
}
```
