### ISSUE TITLE
Bug: when renaming tabs to a long name that exceeds the screen width, the app crashes

### ISSUE THREAD

**Issue by imsnif** [zellij-org/zellij#218]
To reproduce:
1. Open a new tab
2. Rename it to a name that exceeds the screen width
3. The app crashes

This can be fixed by truncating the name itself (eg. `I am a very long name` ==> `I am a[...]g name`).

**Comment by dragfire** [comment]
Is this still open?

**Comment by imsnif** [comment]
Already fixed
