### ISSUE TITLE
Feature request: key bindings in scrollback editor

### ISSUE THREAD

**Issue by elkarouh** [zellij-org/zellij#2183]
Hi,

I use emacs as my scrollback editor.
It is however very annoying to lose the 'ctrl-s' binding when searching with emacs.
I think it would be nice to have a config option that allows temporarily disabling the zellij key bindings, when within emacs.

**Comment by naosense** [comment]
@elkarouh Hey have you try the lock mode, does it meet your requirements?

**Comment by elkarouh** [comment]
It works !
The documentation wasn't clear to me about the lock mode.
Many thanks!
