### ISSUE TITLE
Attaching to session after lost VPN connection gives freezing window

### ISSUE THREAD

**Issue by pkosel** [zellij-org/zellij#2189]
**Basic information**
Reattaching to a session after I lost my VPN connection, zellij gives me a freezing window, although the cursor is blinking. I don't know if this is normal or the expected behavior or how it is handled in tmux.

`zellij --version`: zellij 0.33.0
`stty size`: 26 106
`uname -av` or `ver`(Windows): Linux xxxxxxx 5.15.93 #1-NixOS SMP Thu Feb 9 10:26:48 UTC 2023 x86_64 GNU/Linux

List of programs you interact with as, `PROGRAM --version`:
`kitty --version`: kitty 0.27.1 created by Kovid Goyal

**Further information**

Steps to reproduce:
- Connect to VPN
- Run zellij
- ssh into server
- Disconnect from VPN
- Reconnect to VPN
- Attach to existing session

Thanks!

**Comment by imsnif** [comment]
@raphCode - any ideas?

**Comment by pkosel** [comment]
Zellij is running locally. The local zellij UI is still responsive/not frozen. I guess since the problem seems to be on the ssh side, I might close this issue then.

**Comment by raphCode** [comment]
Probably [mosh](https://mosh.org/) is useful for you?
Alternatively, use the ssh options `ServerAliveInterval` and `ServerAliveCountMax` to automatically kill off stale ssh sessions.
