### ISSUE TITLE
Support cwd as a zellij option

### ISSUE THREAD

**Issue by elijahmanor** [zellij-org/zellij#2205]
I make a [zellij session creator/switcher](https://gist.github.com/elijahmanor/a8af9a19e7b12b4bde7fa9b9d4b7037d) and a zellij feature that would be nice is having a way to tell zellij which directory to use when a session is created.

Something like the following would be helpful. Thank you for the great project!

`zellij options --cwd <path>`

**Comment by pitoniak32** [comment]
I really like this idea, being able to say what dir to start in for a new session would be very helpful. In particular 
```
zellij -s <session-name> --create --layout <layout> --cwd <dir>
```

**Comment by imsnif** [comment]
This has been implemented (thanks [@Kangaxx-0](https://github.com/Kangaxx-0)!) and is in `main`. Will be released when we next release in the near future.

**Comment by elijahmanor** [comment]
YAY thanks @Kangaxx-0 and @imsnif I look forward to the release!

**Comment by cblessing24** [comment]
Hey I noticed that `~` is not expanded when using it with `--default-cwd`. Is that intentional?

**Comment by Kangaxx-0** [comment]
> Hey I noticed that `~` is not expanded when using it with `--default-cwd`. Is that intentional?

Can you provide more context, please?

**Comment by cblessing24** [comment]
Running `zellij options --default-cwd=~/some/path` seems to ignore the option. I always end up in the home directory. Using `--default-cwd=/home/user/some/path` works as expected.
