### ISSUE TITLE
Crash - No Longer Working

### ISSUE THREAD

**Issue by aponplugins** [zellij-org/zellij#2208]
In an instance of zellij, running nushell, in iTerm2 on MacOS Ventura on an M1 MacBook Pro, I ran an `ls` command and scrolled up to view a long list of outputs. Upon scrolling down things started to get slow and then zellij quit, returning me to the shell (nushell) with which I started zellij. There was an error output that read something like, `Buffer full`. Unfortunately, I cannot reproduce as I cannot start zellij anymore, the command just hangs. I uninstalled and reinstalled zellij with homebrew but my shell still hangs. I also uninstalled  and reinstalled with cargo but same issue.

```
> zellij --version
zellij 0.34.4

> stty size
89 478

> zellij --debug
<hangs>

> zellij
<hangs>
```

**Comment by imsnif** [comment]
Hey, sorry for the experience!

This is already fixed in main. You can solve this by killing the zellij session (something like `killall -9 zellij`?)

**Comment by aponplugins** [comment]
Thanks! Working again now.

**Comment by robinmoussu** [comment]
Perfect. I had the same issue (except that I did not had any error message), and `killall -9 zellij` unstuck me. It’s nice to know that it’s already fixed.
