### ISSUE TITLE
Simple layout with tabs not working.

### ISSUE THREAD

**Issue by Leblake** [zellij-org/zellij#2217]
**Basic information**

`zellij --version`: **0.34.4**
`stty size`: **45 238**
`uname -av` or `ver`(Windows): **Linux 6.1.12-1-MANJARO #1 SMP PREEMPT_DYNAMIC Tue Feb 14 21:59:10 UTC 2023 x86_64 GNU/Linux**

List of programs you interact with as, `PROGRAM --version`:
`alacritty --version`: **alacritty 0.11.0 (8dbaa0bb)**
`terminator --verion`: **terminator 2.1.2**

**Further information**
Tried to create a layout with two tabs to open `btop` and `bandwhich`, following the instructions [here](https://zellij.dev/documentation/creating-a-layout.html). When it failed, I reverted to the most simple layout with two tabs, and it still failed. The result is that two Zellij instances open, each with one tab and both in the same terminal. I have to `exit` twice to go back to the terminal instance from where I invoked `zellij --layout ~/.config/zellij/layouts/tab-layout.kdl`. Also tried with `terminator`. Following is the `kdl` file:

```kdl
layout {
     tab
     tab
}
```

**Comment by pitoniak32** [comment]
I am getting this same behavior when trying to create a new tab with
```bash
zellij action new-tab -l $HOME/.config/zellij/layouts/project_layout.kdl
```

project_layout.kdl
```kdl
layout {
  tab name="my third tab" split_direction="vertical" {
        // a tab with a name and two vertical panes
        pane
        pane
    }
}
```
before command:
<img width="1512" alt="Screen Shot 2023-03-03 at 4 13 24 PM" src="https://user-images.githubusercontent.com/84917393/222830482-f85274c2-e005-4645-a340-fee95e958bbd.png">

after command:
<img width="1512" alt="Screen Shot 2023-03-03 at 4 13 34 PM" src="https://user-images.githubusercontent.com/84917393/222830532-1d87719d-1300-4017-abcb-e4bb51c32d59.png">

**Comment by pitoniak32** [comment]
After some testing I found that the default example generated with the following command works.
```bash
zellij setup --dump-layout default > /tmp/my-quickstart-layout-file.kdl
```
So it seems that when generating a new tab it is excluding the tab-bar and status-bar plugins because they are not there by default.

but in your case @Leblake I don't think that using more than one `tab` in a new-tab action is valid. I was reading the code and there is a check when performing this action to ensure there are no more than one tabs present in the layout [here](https://github.com/zellij-org/zellij/blob/c6c9bb5c370e8ea9c38cf66efc445d2caafd1baa/zellij-utils/src/input/actions.rs#L413)

But anyways the fix is to wrap the tab layout in the plugins to get expected behavior. This is not a bug but seems to be expected behavior. After reading through [this](https://zellij.dev/tutorials/layouts/) tutorial I see that there is a step to add the plugins back.
```kdl
layout {
    pane size=1 borderless=true {
        plugin location="zellij:tab-bar"
    }
    pane {
      command "echo"
      args "Hello, World!"
    }
    pane size=2 borderless=true {
        plugin location="zellij:status-bar"
    }
}
```

**Comment by Leblake** [comment]
Thank you for the interest and the info! However, all that is oriented towards panes, and my problem is with tabs! Can't open two tabs and have them share the same instance (can't explain it better, they open one on top of the other and I have to close the first one to access the second).

**Comment by pitoniak32** [comment]
> 

Ahhh gottcha, this still applys to what you are looking to do. Use the example layout below to create a new session with two tabs. (you can use templates to get rid of the repetition)

`zellij -s testing -l ./test_tab.kdl`

example:
```kdl
 layout {
    tab {
      pane size=1 borderless=true {
          plugin location="zellij:tab-bar"
      }
      pane
      pane size=2 borderless=true {
          plugin location="zellij:status-bar"
      }
    }
    tab {
      pane size=1 borderless=true {
          plugin location="zellij:tab-bar"
      }
      pane
      pane size=2 borderless=true {
          plugin location="zellij:status-bar"
      }
    }
}
```

**Comment by Leblake** [comment]
Thank you for this!!!!

I finally understood how it works: the `tab-bar` and the `status-bar` are also panes on their own. Now everything makes sense. I guess it was only me not understanding the documentation.

**Comment by pitoniak32** [comment]
> Thank you for this!!!!
> 
> I finally understood how it works: the `tab-bar` and the `status-bar` are also panes on their own. Now everything makes sense. I guess it was only me not understanding the documentation.

Hahaha, I was in the same boat here! Glad I was able to help!
