### ISSUE TITLE
Feature Request: action to list tabs in current session

### ISSUE THREAD

**Issue by pitoniak32** [zellij-org/zellij#2221]
## Prelude
This is my first feature request for this project, I have been using tmux for a while and just stumbled across `zellij` on YouTube when watching rust videos. This project has so many things I was hoping for in tmux and I am converting all my tooling over!

I would love to contribute this feature to the project if its found to be valuable :)

## Intention / Use Case
I am implementing a script that uses fzf to search projects in a given directory. When you select a project it will create a new tab with the following command. 

```bash
zellij action new-tab \
  --layout $HOME/.config/zellij/layouts/project_layout.kdl \
  --cwd $path_name \
  --name $session_name
```

It works as is, but It will also create duplicate tabs if one already exists for the project, I want to be able to check if a tab with a given name exists and if it does change to that tab. I am not sure of a way to do this with the current features available.

## Goal Behavior
```bash
$ zellij action list-tabs -s <session-name(or current if omitted)>
tab-name1
tab-name2
# etc...
```

### Extra:
~~It might require another issue but I would also like to be able to select a tab by name.~~
this was added in the most recent update :)

**Comment by gauthierc** [comment]
Another solution would be to extend the "zellij ls" functionality to output the full zellij session in a json format.
The kitty software has a similar command "kitty @ ls" which displays as json output all instances, tabs and panes.
So it is easy with a json parser like jq to extract the information we need.

We have here all the information, the list of tabs or panes, who has the focus, the processes that are running...
Like this :
```
❯ kitty @ ls
[
  {
    "id": 1,
    "is_active": true,
    "is_focused": true,
    "last_focused": true,
    "platform_window_id": 4194318,
    "tabs": [
      {
        "active_window_history": [
          1
        ],
        "enabled_layouts": [
          "tall",
          "grid",
          "splits",
          "fat",
          "vertical",
          "stack"
        ],
        "id": 1,
        "is_active": true,
        "is_focused": true,
        "layout": "tall",
        "layout_opts": {
          "bias": 50,
          "full_size": 1,
          "mirrored": false
        },
        "layout_state": {
          "biased_map": {},
          "main_bias": [
            0.5,
            0.5
          ],
          "num_full_size_windows": 1
        },
        "title": "kitty @ ls",
        "windows": [
          {
            "cmdline": [
              "/usr/bin/zsh"
            ],
            "columns": 189,
            "cwd": "/home/user",
            "env": {
              "COLORTERM": "truecolor",
            },
            "foreground_processes": [
              {
                "cmdline": [
                  "kitty",
                  "@",
                  "ls"
                ],
                "cwd": "/home/user",
                "pid": 47308
              }
            ],
            "id": 1,
            "is_active": true,
            "is_focused": true,
            "is_self": true,
            "lines": 50,
            "pid": 39084,
            "title": "kitty @ ls"
          }
        ]
      }
    ],
    "wm_class": "kitty",
    "wm_name": "kitty"
  }
]
```

What do you think about this ?

**Comment by pitoniak32** [comment]
> Another solution would be to extend the "zellij ls" functionality to output the full zellij session in a json format.
> The kitty software has a similar command "kitty @ ls" which displays as json output all instances, tabs and panes.
> So it is easy with a json parser like jq to extract the information we need.

I like this idea, fortunately for me the latest release of `zellij` contains `action go-to-tab-name` which will allow me to easily update my scripts. But I certainly see how listing json structure of zellij status would be greatly useful.

**Comment by pitoniak32** [comment]
closing this issue to cause less noise because I am happy with the current options :)
