### ISSUE TITLE
Flag -c in 'zellij attach' no longer working as expected

### ISSUE THREAD

**Issue by brneor** [zellij-org/zellij#2232]
Since I upgraded to v0.35.1 this morning, using `-c` to attach to a session or create it doesn't exist no longer working as in previous version.

Steps to reproduce:
1. With no zellij instances running, run `zellij attach -c Development`
2. Detach session
3. Run `zellij attach -c Development` again.

Expected: zellij attached to existing session named "Development"
Current: `Session with name "Development" already exists. Use attach commando to connect to it or specify a different name`.

**Comment by Giom-fm** [comment]
Same issue over here

**Comment by imsnif** [comment]
Hey, apologies for this regression! I issued a fix for it and will release a patch version in the next few days (I want to wait and see if there are other regressions to fix quickly).

**Comment by JannesMeyer** [comment]
Same issue here. On top of that homebrew makes it almost impossible to downgrade to an older version, so I'm stuck with 0.35.1 for now 😞

**Comment by paletochen** [comment]
The fix is submitted so you can download the code from this repo and build from source.
I did that and now I can use -c again
