### ISSUE TITLE
Toggle pane layout Alt+[] on custom layouts

### ISSUE THREAD

**Issue by Pheon-Dev** [zellij-org/zellij#2238]
How can I use Alt+[] on custom layouts?

Good job on the latest version. Couldn't to try it out :-)

**Comment by naosense** [comment]
add this to your config file
```kdl
bind "Alt [" { PreviousSwapLayout; }
bind "Alt ]" { NextSwapLayout; }
```
<img width="488" alt="image" src="https://user-images.githubusercontent.com/2225426/223645762-25d1192f-47a0-44e0-aa08-8afc405cf8bd.png">

**Comment by rod-stuchi** [comment]
My problem is similar on `zellij 0.35.1`, I've tried on Alacritty and Konsole.

With any custom layout the binding `Alt + []` doesn't work. It works only in the default layout.

```kdl
layout {
    pane size=1 borderless=true {
        plugin location="zellij:tab-bar"
    }
    pane split_direction="vertical" {
        pane
        pane split_direction="horizontal" {
            pane
            pane
            pane
        }
    }
    pane size=1 borderless=true {
        plugin location="zellij:status-bar"
    }
}

```

Even with the simplest layout, and adding panes manually the SwapLayout function doesn't work.
```kdl
layout
```

Also tried changing to tmux bindings and hit `space`, doesn't work.

**Comment by rod-stuchi** [comment]
> I did settle for:
> 
> ```
> pane {
>   bind "Space" { NextSwapLayout; }
> }
> ```
> 
> As a workaround tho.

For me, works only on the **default** layout, any custom layout it doesn't work.

**Comment by Pheon-Dev** [comment]
Just got back and tried it out but to no avail.

**Comment by rod-stuchi** [comment]
Hey @imsnif thank you for clarifying it. It's working perfectly now.

**Comment by talios** [comment]
@imsnif `option_as_alt: Both` works a treat for my case too.  Nice.

**Comment by imsnif** [comment]
Hey, so I'm closing this issue for now. But if someone on this thread still has a problem not addressed by my comment, please tag me here and I'll reopen so we can look into it.
