### ISSUE TITLE
tmux like key bindings option

### ISSUE THREAD

**Issue by jcaplan** [zellij-org/zellij#225]
Related to #25 and #220.

I think the getting started mode and status toolbar are great. but I can't work without tmux and I am very attached to my key bindings. I don't think I could ever make the switch without being able to configure zellij with my key bindings.

Why not just continue to use tmux then? Maybe one day there's some cool plugins to make a user curious about zellij, but someone who's a tmux power user would never bail if they can't take their key bindings with them.

- short circuit single key bindings to actions. ctrl+<configurable key> -> <second key>. Even if you let people customize some of the mappings, what happens if I want to have all my input modes flattened into one big category?
- I navigate in tmux with `alt+<h/j/k/l>`. That's definitely one I can't live without.

**Comment by a-kenji** [comment]
Hey! I have similar issues as you.

I updated the example config file for now. 
Does that do what you want?

**Comment by a-kenji** [comment]
We want to provide sane defaults for people,
so having a configuration file that emulates the tmux config makes sense.
Inspiration in /example/config.yaml and example/default.yaml,
as well as the keybindings documentation.
/example/tmux.yaml could be a suitable location.

**Comment by SaintFenix** [comment]
I'd like to be assigned this, I think I can get close, and get a list of functions that are Tmux specific that are not implemented in Zellij, but may wish to be in the future.

**Comment by a-kenji** [comment]
Awesome! This would be very helpful.

**Comment by a-kenji** [comment]
@SaintFenix 
If you are interested, it is possible to start now in an arbitrary mode.
So the example configuration files could be updated to reflect that.

**Comment by imsnif** [comment]
Tmux keybindings work out of the box, just try 'em.

**Comment by danielb2** [comment]
> Tmux keybindings work out of the box, just try 'em.

thanks. I worded it poorly. I wanted as a complete emulation of tmux as possible since keybindings were also clashing with keybindings in other terminal apps. I've added lots of keybindings and cleared the one that comes by default. Would be cool to have an example config where it's already all done
