### ISSUE TITLE
is it possible to configure floating pane position?

### ISSUE THREAD

**Issue by sangshuduo** [zellij-org/zellij#2253]
sorry if my question is duplicated as I did not find any document mentioning how to configure a floating pane at a preconfigured position instead of central of screen.

Thanks!

**Comment by imsnif** [comment]
Definitely possible! As part of a layout. Check out: https://zellij.dev/documentation/creating-a-layout.html#floating-panes
For more information about layouts in a screencast/tutorial form, check out: https://zellij.dev/tutorials/layouts/

Or you could do this as part of Swap Layouts, changing the way the floating panes are opened by default (with the default swap layouts it should be a matter of switching the location between the "staggered" and "spread" layouts - or rolling your own): https://zellij.dev/documentation/swap-layouts.html
