### ISSUE TITLE
[attach -c] When using attach -c for an existing session I get an error message saying the session already exists

### ISSUE THREAD

**Issue by pitoniak32** [zellij-org/zellij#2260]
**Basic information**

`zellij --version`: `zellij 0.35.1`
`stty size`: `64 270`
`uname -av`: `Darwin US-YFCRWDX2QT.local 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000 arm64`

**Further information**
When trying to attach to an existing session, or create if the session does not exist I am getting the following error.

`zellij attach session_name -c`

```
Session with name "session_name" already exists. Use attach command to connect to it or specify a different name.
```

## Steps to reproduce
1. open zellij session with expected name `zellij -s testing`
2. detatch from zellij session
3. try and attach to existing session, with `-c` flag `zellij a testing -c`
4. See error `Session with name "testing" already exists. Use attach command to connect to it or specify a different name.`

## Expected Behavior
When the session already exists I expected that it would be attached to rather than an error.

(Once I am out of work I am going to look into the code and maybe take a shot at a fix)

**Comment by yves-biener** [comment]
I have the same issue, but I can provide further information:
- This issue is also present in version 0.34.5 (my previous install, which I overwrote with the newest release)
- This issue is not present in version 0.34.4 (different machine, which I have not yet updated)

Maybe this can help to find the source of the bug.

**Comment by JannesMeyer** [comment]
I think it's already fixed in https://github.com/zellij-org/zellij/pull/2247, but not released yet

**Comment by pitoniak32** [comment]
Duplicate: https://github.com/zellij-org/zellij/pull/2247
