### ISSUE TITLE
Slow starting time with message

### ISSUE THREAD

**Issue by sucrecacao** [zellij-org/zellij#2261]
Hello,

Zellij looks super exiting!

However, I experienced a slow starting time ( compared to tmux ) 
Before Zellij start, I can see a message that freeze before launch the TUI.
The message freeze long enough for me to be able to read it. 

The message says:
`Querying terminal emulator for default colors or pixel/cell ratio ...`

Can I get rid of this message ? Is this "query" slowing my startup time?

Otherwise, how can I boost startup time ?

**Comment by imsnif** [comment]
Starting from version 0.35.1, this query is cached. Meaning it only happens the first time and (assuming it was not interrupted) afterwards should not happen. Does it happen for you after the first run?

**Comment by sucrecacao** [comment]
it is way better ! 

A tiny tiny blink doesn't make it look instantaneous, but if it is the price to pay to avoid tmux API I'm alright with that :)

Great job @imsnif :+1:

**Comment by MossabDiae** [comment]
> Starting from version 0.35.1, this query is cached. Meaning it only happens the first time and (assuming it was not interrupted) afterwards should not happen. Does it happen for you after the first run?

I'm running `zellij 0.35.2` and it does happen every single time
