### ISSUE TITLE
oh-my-zsh + windows terminal + zellij colors

### ISSUE THREAD

**Issue by jcaplan** [zellij-org/zellij#227]
a lot of my font rendering issues were fixed by switching to running wsl2 ubuntu in windows terminal with jetbrains mono font.

zsh auto complete should look like this:
![image](https://user-images.githubusercontent.com/10764469/111016105-00f16180-837a-11eb-837c-03c7aa6c1bed.png)

but when I open zellij it looks like this:
![image](https://user-images.githubusercontent.com/10764469/111016151-4150df80-837a-11eb-9260-dfc561798880.png)

**Comment by imsnif** [comment]
Fixed.
