### ISSUE TITLE
Floating pane doesn't expand to Fullscreen 

### ISSUE THREAD

**Issue by CodeToLearnScience** [zellij-org/zellij#2270]
When I try to expand, the floating pane to full screen, it doesn't work

**Basic information**

`zellij --version`: 0.35.1
`stty size`: 24 1024
`uname -av` or `ver`(Windows): Microsoft-standard-WSL2

**Comment by giyany** [comment]
Hi, 
AFAIK this is a UI decision and works as intended.

**Comment by imsnif** [comment]
Yeah, a full screen floating pane might make things confusing (am I focused on floating panes? am I focused on tiled panes?) and also make it a little hard to move focus to other floating panes (should it be possible?)

You could work around this by using the `ENLARGED` floating panes layout. By default move to it with `Alt` + `[]` until you get there.

**Comment by maruthinh** [comment]
Thanks @imsnif
