### ISSUE TITLE
Layout with focused stack pane does not expand focused pane

### ISSUE THREAD

**Issue by zolrath** [zellij-org/zellij#2271]
Hey hey! Excited to experiment with the new release. I've found an issue with stacked panes when used in a layout.

## Issue
When creating a layout with stacked panes the final pane listed is always the expanded pane, even if another pane is set to focused.

```
  tab name="Test" split_direction="vertical" {
    pane size="65%"
    pane split_direction="horizontal" stacked=true {
      pane command="ls"
      pane { 
        command "ls"
        focus true
      }
      pane command="ls"
    }
```

![image](https://user-images.githubusercontent.com/454563/224452941-f12706ef-f2d6-485b-aaba-6274ce59a24f.png)

## Expectation
Baseline expectation here is that the focused pane would be expanded, not the last pane on the list.

My actual desire here is *not* to focus the middle pane though. In reality I'd prefer to be able to set an `expanded true` option, that way the middle pane can be expanded but I can have another interactive pane focused elsewhere (in this example, the `size="65%"` pane).

`zellij --version`: zellij 0.35.2

**Comment by imsnif** [comment]
Hey @zolrath - is there perhaps more to this layout? I tried reproducing this with it and couldn't.

**Comment by zolrath** [comment]
Here's the full config @imsnif , sorry for not including it verbatim the first time.
Just tested it and still see the same result!

```kdl
layout {
  default_tab_template {
    pane size=1 borderless=true {
      plugin location="zellij:tab-bar"
    }
    children
    pane size=2 borderless=true {
      plugin location="zellij:status-bar"
    }
  }

  tab name="Test" split_direction="vertical" {
    pane size="65%"
    pane split_direction="horizontal" stacked=true {
      pane command="ls"
      pane { 
        command "ls"
        focus true
      }
      pane command="ls"
    }
  }
}
```

**Comment by imsnif** [comment]
Actually - this was not entirely fixed, my mistake. I'm on it...

**Comment by imsnif** [comment]
*Now* it's fixed!
