### ISSUE TITLE
Allow specifying which pane is expanded in a stacked pane layout

### ISSUE THREAD

**Issue by zolrath** [zellij-org/zellij#2272]
Hi!
I've got a number of commands I'd like to place in a stacked layout.
Currently when creating a stacked layout, the final pane in the stack is automatically expanded when the layout is launched.

I'd like to be able to include `expanded true` on a single pane in the layout stack and have that pane be expanded on launch.

Originally I was going to work around this by placing the command I care about at the end of the list but my commands are order dependent and the pane I'd like expanded cannot be moved to the end.

## Usage
```
  tab name="Test" split_direction="vertical" {
    pane size="65%" focus=true
    pane split_direction="horizontal" stacked=true {
      pane command="ls"
      pane { 
        command "ls"
        expanded true
      }
      pane command="ls"
    }
```

Would result in

![image](https://user-images.githubusercontent.com/454563/224518387-1fadb8fe-9b89-42fc-bf80-2b4df1bb1c1e.png)

**Comment by imsnif** [comment]
Implemented
