### ISSUE TITLE
Add status display to the right of tab-bar[New Feature]

### ISSUE THREAD

**Issue by liaohui5** [zellij-org/zellij#2276]
In some tab I don't want to show status-bar, but I can't know the current mode without showing status-bar,
so, I want to be able to display status text to these locations., like this
![image](https://user-images.githubusercontent.com/29266093/224488181-27488dc3-9e6f-4c6c-9593-13a6bdae8362.png)

**Comment by imsnif** [comment]
Have you considered using the `compact-bar`? It shows the status too...

**Comment by liaohui5** [comment]
> Have you considered using the `compact-bar`? It shows the status too...

thank you very much! problem solved
