### ISSUE TITLE
Wrong alignment of layout which loaded with `new-tab` action 

### ISSUE THREAD

**Issue by jaeheonji** [zellij-org/zellij#2280]
**Basic information**

`zellij --version`: `0.35.2`
`stty size`: `55 186`
`uname -av` or `ver`(Windows): `Linux Meow 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 GNU/Linux`

**Further information**

> This issue was reported by melMass#3336 in the Discord. Thanky you!
> https://discord.com/channels/771367133715628073/771367133715628076/1084167384790741112

After running zelli without any layout, if I open a new tab with `zellij action new-tab`, In that tab, when creating a new Pane, the alignment is not normal.

current:
[![asciicast](https://asciinema.org/a/2JLxQEBexARq70bfqG7KDysrR.svg)](https://asciinema.org/a/2JLxQEBexARq70bfqG7KDysrR)

expected:
[![asciicast](https://asciinema.org/a/w0K3qv9Ky4j637KFkkty56wYN.svg)](https://asciinema.org/a/w0K3qv9Ky4j637KFkkty56wYN)

I don't know the exact reason yet, but it seems to be an issue with the recently added SwapLayout.

**Comment by jaeheonji** [comment]
I found the problem with this.

When creating a tab by with specific layout as `zellij action`, the settings for SwapLayout are not applied. (Only default SwapLayout settings apply)

**Comment by imsnif** [comment]
Hey @jaeheonji - when I tested this, if you define Swap Layouts for your custom layouts they should be loaded. Could it be that what's happening here is that there are no swap layouts defined for this custom layout and Zellij is taking the default swap layouts instead?

**Comment by jaeheonji** [comment]
@imsnif Yes right! only when loading a layout with the new-tab action

**Comment by jaeheonji** [comment]
@imsnif Actually, when I first saw this issue, I thought it was a different problem, but after checking today,

>So @jaeheonji - I think a good fix for this would be to only add the existing swap layouts to new tabs opened without an explicit >layout, right? and for these we add swap layouts if they are included in the layout (or in a .swap.kdl file). What do you think?

Yes, I think that is good fix way.
