### ISSUE TITLE
`borderless=true` in layout is ignored on re-attach

### ISSUE THREAD

**Issue by alex35mil** [zellij-org/zellij#2292]
When I create a new session, `borderless` option works. However, when I re-attach to the session, the border appears.

**Basic information**

`zellij --version`: zellij 0.35.2
`stty size`: 42 185
`uname -av`: Darwin alex-macbook-pro-m1.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64

List of programs you interact with:
`nvim --version`: NVIM v0.8.3 Build type: Release LuaJIT 2.1.0-beta3 Compiled by _nixbld0 Features: +acl +iconv +tui
`alacritty --version`: Version 0.11.0 (1)

**Comment by raphCode** [comment]
Not sure if this is considered a bug because the borderless-ness is coupled to the session I think.
You can toggle the borders at runtime with `Ctrl-P` `Z` in the default keybindings, or with the command `zellij action toggle-pane-frames`.
Does this help?

**Comment by raphCode** [comment]
Sorry, I thought you were referring to starting zellij with `zellij options --no-pane-frames`.

**Comment by thricedotted** [comment]
I believe this affects not just sessions that are detached and reattached via the command line, but window resizes as well. When I move the terminal emulator hosting zellij between displays, borders appear around all panes, even those that are designated borderless in the layout.

**Comment by alex35mil** [comment]
Yup. FIWI it got broken in the latest release. Prior to the current version, layouts worked smoothly.

**Comment by raphCode** [comment]
Pinging @imsnif because he might be interested in regressions

**Comment by alex35mil** [comment]
Actually, the param that is [defined in the `default_tab_template`](https://github.com/alex35mil/dotfiles/blob/a699f5355ee5c9df0c24d30457c8ba27c87cf07c/user/cfg/zellij/layouts/editor.kdl#L4) works. But the one that is [defined in the `tab`](https://github.com/alex35mil/dotfiles/blob/a699f5355ee5c9df0c24d30457c8ba27c87cf07c/user/cfg/zellij/layouts/editor.kdl#L11) doesn't.

**Comment by imsnif** [comment]
Thanks for the help @alex35mil - this is now fixed in main.
