### ISSUE TITLE
pane should go to previously active when possible

### ISSUE THREAD

**Issue by jcaplan** [zellij-org/zellij#230]
consider this layout:
![image](https://user-images.githubusercontent.com/10764469/111021643-e3cd8a80-839b-11eb-8580-a4c8de336028.png)

If I am in the top right pane and then move to the left pane and then back to the right again, zellij chooses the bottom right pane.
I think it is reasonable to expect the top right pane (i.e. the last active pane to the right) to become active when moving back to the right.

The algorithm that determines which pane to move to when multiple panes are on the border of the active pane should give precedence to the last active pane.

**Comment by dantepippi** [comment]
I could take a look at it.
