### ISSUE TITLE
[Feature Request] OAuth , Sign in, Autosave User states across machines

### ISSUE THREAD

**Issue by fire17** [zellij-org/zellij#2306]
Hi there! Just found out about Zellij; looks really awesome :)

One of the things I want the most is to be able to sync my workspace across machines. For example now I'm changing over to a new computer, and will AGAIN go through installing oh-my-zsh and fish-like-autocomplete and so on... I really wish that my terminal let me login with my github , and just get my environment. Very similar to how chrome behaves, it will auto install and configure all the extensions I am using.

` bash <(curl -L zellij.dev/launch) fire17 `

This should run my personal setup configurations and present me with the environment I'm familiar with. 
Either through OAuth or tokens.
My first thought is that you'd need to host a server for users, but I guess you could just have each user have his own repo for that, so, after signin in, it will first clone fire17/zellij_config (or create it if doesn't exist for first time synced users)

What do you think? Hope that the value is clear and also that it can be straightforward enough to make soon..
Thanks a lot and all the best!
Have a good one 👍

**Comment by raphCode** [comment]
Probably I am understanding your use case wrong, but my approach would have been to put all relevant configuration files into a git repo and sync it to your machines. More or less what the plethora of dotfile managers out there do.

Can you outline why you think a zellij feature would be better in your case?

**Comment by fire17** [comment]
> Can you outline why you think a zellij feature would be better in your case?

Well, as it says in the Readme, Zellij comes with batteries included

Think about it this way, do you want to have to install an extension to manage and sync your Chrome extensions, or would you like Chrome itself to do that?

By all means, use a good foss implementation under the hood, but I think we as users should be able get our Perfect Workspace using Zellij alone. That obviously includes a seemless sync opt-in 

Let me know that you think,
Thanks and have a good one!
All the best and Happy Spring

**Comment by scabala** [comment]
I think that is waaay out of Zellij's scope and should be handled by some other tool. Zellij is _terminal multiplexer_ first and foremost

**Comment by raphCode** [comment]
I too think that is way out of scope.
