### ISSUE TITLE
zsh autocompletion 

### ISSUE THREAD

**Issue by ixzh** [zellij-org/zellij#2316]
hi I did the following :

zellij setup --generate-completion zsh >> ~/.zshrc

when I source .zshrc the following warning were thrown: 
```
_arguments:comparguments:327: can only be called from completion function

```

I check all _arguments were wrapped in _zellij_commands function. So how can I suppress this warning? Thanks!

**Comment by ixzh** [comment]
Yeah commenting out the said line did the trick. Thank you!  A side question is I don't want to lengthen my already-very-long .zshrc.   Would it be possible to have the defs in a separate file under $fpath and get source when zsh starts.

I tried `zellij setup --generate-completion zsh > ~/.zsh/misc/_zellij`, but it seems never get sourced, although ~/.zsh/misc folder is included in $fpath.

I tried this because I don't want to pollute the .zshrc.

**Comment by IcarusSosie** [comment]
The way I have it set up is as a custom zsh plugin in `~/.zsh/plugins/zellig_completion/zellig_completion.plugin.zsh`.
Then I add that path to fpath in my .zshrc and run compinit again.

Although l’m on NixOS so l’m not too worried about the cleanliness of my config files as long as my .nix files are clean ^^

**Comment by 0rphee** [comment]
Maybe this could be mentioned in the docs? this also happened to me...

**Comment by IcarusSosie** [comment]
@imsnif I'm not certain if there is a reason to call `_zellij "$@"` at the end of the generated file, or if it's just meant as an example for custom zsh configurations. In any case, it might be nice to comment it in the generated file or mention it in the docs.

I'm not familiar with zellij internals (and I've been env-hopping so I don't really use zellij all that much recently) but if you point me in the right direction I could take care of submitting the PR :smile:

**Comment by matmilbury** [comment]
this issue should be reopened as this is a bug in completions generated by zellij @ixzh

**Comment by matmilbury** [comment]
using `_zellij` file name fixed this for me, turns out it's not a problem with zellij.

```bash
zellij setup --generate-completion zsh >> ~/.oh-my-zsh/custom/plugins/zellij/_zellij
```

**Comment by ohare93** [comment]
Still an issue. I tried all the above, yet nothing worked. In the end I agree with @IcarusSosie, what's the point in calling `_zellij "$@"` (and thus the whole code before that)?

All I want is the autocomplete of the neat functions. So I just got rid of this setup and copied the following into my .zshrc 👍 

```bash
function zr () { zellij run --name "$*" -- zsh -ic "$*";}
function zrf () { zellij run --name "$*" --floating -- zsh -ic "$*";}
function zri () { zellij run --name "$*" --in-place -- zsh -ic "$*";}
function ze () { zellij edit "$*";}
function zef () { zellij edit --floating "$*";}
function zei () { zellij edit --in-place "$*";}
function zpipe () { 
  if [ -z "$1" ]; then
    zellij pipe;
  else 
    zellij pipe -p $1;
  fi
}
```

**Comment by franckrasolo** [comment]
Alternatively, the following also works:

```bash
source <(zellij setup --generate-completion zsh | sed '/_zellij "$@"/d')
```

**Comment by XavierFigari** [comment]
> The way I have it set up is as a custom zsh plugin in `~/.zsh/plugins/zellij_completion/zellij_completion.plugin.zsh`. Then I add that path to fpath in my .zshrc and run compinit again.
> 
> Although l’m on NixOS so l’m not too worried about the cleanliness of my config files as long as my .nix files are clean ^^

Hello, could you please elaborate a little bit ? What is the content of your zellij_completion.plugin.zsh file ? Where and when do you run compinit ? Thanks !

**Comment by Sharparam** [comment]
> Alternatively, the following also works:
> 
> source <(zellij setup --generate-completion zsh | sed '/_zellij "$@"/d')

@franckrasolo I don't think that actually fixes it, it just causes the completion stuff to not run while still defining the helper functions.

In my commit (seen above) I just manually define those functions instead while skipping the auto-generated completion script, and I still get some basic completion for Zellij (not sure where that is coming from).

Compared to bash: Where the automated completion generation does work and I get more extensive completion help (including flags, which are missing in Zsh without proper completion definitions).

I don't really know enough/anything about Zsh completion to make a proper fix/workaround.

Anyway, this is still an issue and needs to be re-opened.
