### ISSUE TITLE
Latest `zellij` overly favors vertical split

### ISSUE THREAD

**Issue by max-sixty** [zellij-org/zellij#2319]
Firstly — thanks a lot for Zellij — it's a core part of my workflow.

**Basic information**

`zellij --version`: zellij 0.35.2
`stty size`: `135 178`
`uname -av` or `ver`(Windows): `Darwin [] 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64`

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`alacritty --version`: alacritty 0.13.0-dev (2377c0a7)

**Further information**

I have my monitors in portrait more, so the default first split should generally be horizontal. That used to be the default on previous versions of Zellij.

More recently, the default split is vertical. Unless I have different preferences from others, I wouldn't expect this to be a good split.

<img width="717" alt="image" src="https://user-images.githubusercontent.com/5635139/227095211-28abe02b-36e9-4961-8cd1-22b2cde8dd7c.png">

Let me know if any other info is helpful (or feel free to close if this is a deliberate choice...)

**Comment by imsnif** [comment]
Hey @max-sixty - glad you like Zellij and that it's helping you out in your workflow. At runtime, you can change this behavior by pressing `Alt` + `[` until you reach the desired layout.

Permanently, you can change this in in two ways:
1. The best way would be by adjusting the default [Swap Layouts](https://zellij.dev/documentation/swap-layouts.html). You'll need to switch between the `horizontal` and `vertical` swap layouts.
2. Second best would be to add `auto_layout false` to your config. This would bring the behavior back to the way it was in previous versions, but I think the experience you get will not be as good.
