### ISSUE TITLE
docs: please list default keybindings

### ISSUE THREAD

**Issue by colemickens** [zellij-org/zellij#2324]
Every once in a while, I do indeed forget a keybinding. Instead of changing my entire config just to have the full UI, it would be great if the keybindings were just documented.

As is, this leaves me sad:

>Zellij comes with a default set of keybindings that try to fit as many different users and use cases while trying to maximize comfort for everyone.

and then doesn't list them.

**Comment by TheButlah** [comment]
aren't the keybindings listed directly in the UI? 
<img width="1287" alt="Screenshot 2023-03-26 at 12 46 26 AM" src="https://user-images.githubusercontent.com/6969415/227755833-b4773460-d411-4cca-90f7-bf15a40b9469.png">

**Comment by colemickens** [comment]
They are, but only when the full UI is enabled. It feels weird to say "enable the full UI to know the shortcuts/default shortcuts".

Maybe a better option would be a feature that allows you to see a pop-up window listing current keybinds?

**Comment by colemickens** [comment]
see https://github.com/zellij-org/zellij-org.github.io/pull/212
