### ISSUE TITLE
Error opening terminal: alacritty

### ISSUE THREAD

**Issue by sangshuduo** [zellij-org/zellij#2326]
Running Ubuntu 1804 inside vagrant box. Set alacritty as the default terminal. Launch zellij (0.35.2) with a few panes. The primary pane works but other panes show "Error opening terminal: alacritty".

Any idea?

**Comment by sangshuduo** [comment]
htop issue, not zellij. sorry

**Comment by nrobinaubertin** [comment]
I had the same issue just with `watch <cmd>` using kitty as a terminal. I solved it using `TERM="xterm" watch <cmd>`.
