### ISSUE TITLE
killing ssh connection may crash remote zellij server with "failed to enable mouse mode"

### ISSUE THREAD

**Issue by matu3ba** [zellij-org/zellij#2329]
**Basic information**

`zellij --version`: zellij 0.35.2
`stty size`: 52 209
`uname -av` or `ver`(Windows): Linux ASG141 4.4.0-19041-Microsoft #2311-Microsoft Tue Nov 08 17:09:00 PST 2022 x86_64 x86_64 x86_64 GNU/Linux
within Windows Terminal (https://github.com/microsoft/terminal) 1.16.10261.0

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example: many. Host was likely affected by OOM from antivirus or Windows doing weird things on OOM (with WSL 1).

**Further information**
Reproduction steps, noticeable behavior, related issues, etc: Run zellij on remote Linux and have sshd installed and reachable from host. ssh into remote Linux via WSL1 within Windows Terminal. Run into OOM on Windows host (ie via having memory limit on virtual machine. I bootstrapped Zig from source, but there are likely many ways).

<details>

```
INFO   |zellij_server::plugins   | 2023-03-27 23:15:26.600 [wasm      ] [/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.35.2/src/plugins/mod.rs:132]: wasm main thread exits‗      1 ERROR  |???                      | 2023-03-27 23:15:26.602 [main      ] [/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-client-0.35.2/src/lib.rs:433]: a non-fatal error occured            2
     3 Caused by:
     4     0: failed to enable mouse mode
     5     1: Input/output error (os error 5)‗
     6 INFO   |zellij_client            | 2023-03-27 23:15:26.602 [main      ] [/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-client-0.35.2/src/lib.rs:434]: Bye from Zellij!‗
     7 ERROR  |zellij_utils::errors::not| 2023-03-27 23:15:26.609 [async-std/runti] [/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-utils-0.35.2/src/errors.rs:576]: Panic occured:
     8              thread: async-std/runtime
     9              location: At /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.35.2/src/pty.rs:583:22
    10              message: Program terminates: a fatal error occured
    11
    12 Caused by:
    13     0: failed to run async task for terminal 103
    14     1: failed to listen for bytes from PTY
    15     2: failed to async-send to screen
    16     3: failed to send message to screen
    17     4: Originating Thread(s)
    18 ‗‗‗‗‗‗‗
    19     5: failed to send message to channel‗
    20 ERROR  |zellij_utils::errors::not| 2023-03-27 23:15:26.619 [async-std/runti] [/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-utils-0.35.2/src/errors.rs:576]: Panic occured:
    21              thread: async-std/runtime
    22              location: At /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.35.2/src/pty.rs:694:30
    23              message: Program terminates: a fatal error occured
    24
    25 Caused by:
    26     0: failed to spawn terminals for layout
    27     1: failed to listen for bytes from PTY
    28     2: failed to async-send to screen
    29     3: failed to send message to screen
    30     4: Originating Thread(s)
    31 ‗‗‗‗‗‗‗
    32     5: failed to send message to channel‗
    33 ERROR  |zellij_utils::errors::not| 2023-03-27 23:15:26.625 [async-std/runti] [/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-utils-0.35.2/src/errors.rs:576]: Panic occured:
    34              thread: async-std/runtime
    35              location: At /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.35.2/src/pty.rs:694:30
    36              message: Program terminates: a fatal error occured
    37
    38 Caused by:
    39     0: failed to spawn terminals for layout
    40     1: failed to listen for bytes from PTY
    41     2: failed to async-send to screen
    42     3: failed to send message to screen
    43     4: Originating Thread(s)
    44 ‗‗‗‗‗‗‗
    45     5: failed to send message to channel‗
```

</details>

Possible a similar or identical cause as  #1985 (unable to write to broken tty).

**Comment by raphCode** [comment]
Today, I experienced the same crash.
Differences to OPs crash:
- I am using Arch locally and remote
- I used `mosh` to connect to the remote machine
- No OOM situation

Steps I performed:
- logged in with `mosh`
- `killall mosh` to get rid of orphaned sessions (at least one session contained a zellij client)
- log in with `mosh` again because the previous command kicked me out, obviously
- `zellij a`
- `No active zellij sessions found.` :(

Log message:
```
ERROR  |???                      | 2023-07-11 08:38:20.164 [main      ] [zellij-client/src/lib.rs:434]: a non-fatal error occured

Caused by:
    0: failed to enable mouse mode
    1: Input/output error (os error 5)
INFO   |zellij_client            | 2023-07-11 08:38:20.164 [main      ] [zellij-client/src/lib.rs:435]: Bye from Zellij!
```

**Comment by raphCode** [comment]
The error message seems to be from here:
https://github.com/zellij-org/zellij/blob/61f3789c88ca5c948cacaa2d1228e51389cc24f5/zellij-client/src/os_input_output.rs#L227-L235
Since you are the 'mouse guy':
@tlinford Any idea what is going on?
It says non-fatal error in the log, but then crashes :(

**Comment by tlinford** [comment]
> The error message seems to be from here:
> 
> https://github.com/zellij-org/zellij/blob/61f3789c88ca5c948cacaa2d1228e51389cc24f5/zellij-client/src/os_input_output.rs#L227-L235
> 
> Since you are the 'mouse guy':
> @tlinford Any idea what is going on?
> It says non-fatal error in the log, but then crashes :(
I don't think that's what causing the crash, that code is in `zellij-client` and should not be able to crash the server process and bring down the session.

**Comment by tlinford** [comment]
> Yes, I got confused. Sorry. I already edited my messages above.
> 
> In fact, since I experienced the same error message without a crash, I believe we might handle the error better now, compared to when this issue was opened?

No worries! I'm sure there have been improvements in that area lately, so that's a possibility :)

**Comment by matu3ba** [comment]
> If not, I would lean towards closing this.

LGTM. Closing for now with hint to reopen, if issue reoccurs.
