### ISSUE TITLE
Action hangs when using `nvim -u {config}` as a `scrollback_editor`

### ISSUE THREAD

**Issue by cbochs** [zellij-org/zellij#2335]
When setting the `scrollback_editor` to use a custom nvim config (`-u`), trying to open the scrollback in the editor hangs.

I've tried both:
* `scrollback_editor "nvim -u ~/.config/zellij/scrollback.vim"`
* `scrollback_editor "nvim -u ~/.config/zellij/scrollback.vim --"`

**Additional Information**

The following also doesn't work:

```
scrollback_editor = "nvim -c 'set number'"
```

But instead of hanging it opens two buffers: the scrollback buffer and an empty buffer called `number'`. This also feels like a bug to me.

**Reproduction**

1. Create config `echo "set number" > scrollback.vim`
1. Set `scrollback_editor` to `"nvim -u scrollback.vim"`
2. Open `zellij`
3. Run `zellij action edit-scrollback`
4. Action hangs

**Expected result**

Scrollback buffer should open in preferred `scrollback_editor`.

**Basic information**

`zellij --version`: zellij 0.35.2
`stty size`: 64 215
`uname -av` or `ver`(Windows): Darwin cbochs 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64

List of programs you interact with:

`nvim --version`: NVIM v0.9.0-dev-1291+gbad218cd6

**Comment by cbochs** [comment]
**EDIT**: I just tried the following and it worked:

```
scrollback_editor = "nvim -u scrollback.vim"
```

This appears to be some issue with path resolution? Running `nvim -u ~/.config/zellij/scrollback.vim` on its own works just fine.

**Comment by cbochs** [comment]
@imsnif Based on #2339 am I understanding it correctly that substrings in the `scrollback_editor` field (i.e. `nvim -c "set number"`) are disallowed, but the above `nvim -u {config}` should work correctly?

Also, thanks for the quick fix 🙂

**Comment by imsnif** [comment]
Yes, exactly. And happily :)
