### ISSUE TITLE
layout pane command can't seem to execute an alias

### ISSUE THREAD

**Issue by Zolmok** [zellij-org/zellij#2349]
**Basic information**

`zellij --version`: zellij 0.35.2
`stty size`: 64 252
`uname -av` or `ver`(Windows): Linux zolmok 6.2.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 22 Mar 2023 22:52:35 +0000 x86_64 GNU/Linux

**Further information**
Reproduction steps, noticeable behavior, related issues, etc

1) create an alias
```
❯ alias rw='source .dev.env; yarn redwood'
```
2) create a layout that uses that alias as a command
```
layout {
  tab focus=true name="1:Server" {
    pane size=1 borderless=true {
        plugin location="zellij:tab-bar"
    }
    pane command="rw" {
      args "dev" "--forward=\"--allowed-hosts all\""
    }
    pane size=2 borderless=true {
        plugin location="zellij:status-bar"
    }
  }
}
```

Expect zellij to run the command
Actual:
> Command not found: rw
> If you were including arguments as part of the command, try including them as 'args' instead.

**Comment by scabala** [comment]
That is intended behavior. Zellij runs system executables as commands, not wrapped by system shell. You can try running you shell and your alias, i.e. `bash -i rw`, maybe it helps

**Comment by Zolmok** [comment]
`bash -i` doesn't work, but I was able to get around it by creating a script with what I needed and then calling the script.
