### ISSUE TITLE
Add support for maximize pane

### ISSUE THREAD

**Issue by turboninh** [zellij-org/zellij#2351]
Most of the time in dev, I open multiple panes to run different (long-lived) commands. Sometimes, when I need to read the log, I want to expand the pane to maximize the screen size. In Tmux, I can set up this key binding to toggle the pain maximize size and it is extremely useful.
```
bind-key "z" resize-pane -Z \; display-message "Pane zoomed to maximum"
```
Is there any way we can do the same thing with Zellij?

**Comment by scabala** [comment]
I'm not sure if I understand correctly but isn't `Ctrl+p,f` what four looking for?

**Comment by turboninh** [comment]
@scabala Omg, it is exactly what I am looking for. Thank you so much <3
