### ISSUE TITLE
Switch tab by index

### ISSUE THREAD

**Issue by turboninh** [zellij-org/zellij#2352]
I think the ability to switch between tab by index would increase productivity a lot.

**Comment by imsnif** [comment]
You can do this by default with `Ctrl t` + `<index>` (they stat with 1, just like the tab names).

**Comment by turboninh** [comment]
@imsnif Perfect! Thank you very much <3

**Comment by tesar-tech** [comment]
BTW - if you want the `Ctrl + 9` to go to the last tab (as is done in web browsers usually), you can do:

```kdl
         bind "Ctrl 9" {GoToTab 1; GoToPreviousTab; }
```
