### ISSUE TITLE
Names crate produces unappropiate name combination

### ISSUE THREAD

**Issue by azzamsa** [zellij-org/zellij#2353]
Hi.

I have opened an issue regarding this upstream https://github.com/fnichol/names/issues/26. 
But, another alternative are:

1) We can roll our own name generator similar to [moby/pkg/namesgenerator
/names-generator.go](https://github.com/moby/moby/blob/dd3b71d17c614f837c4bba18baed9fa2cb31f1a4/pkg/namesgenerator/names-generator.go#L20) spirit. But, instead of character names, we have to use animal and fruits name. Learn from previous mistakes. The moby names generator creates a heated political discussion about what to remove/include https://github.com/moby/moby/pull/43210#issuecomment-1029934277

2) Using custom dictionary https://github.com/fnichol/names#example-with-custom-dictionaries

![image](https://user-images.githubusercontent.com/17734314/230754166-3d6f151d-d889-4ad3-a8f2-38927450f980.png)

**Comment by tlinford** [comment]
Related: #1907, #1911, #2122
