### ISSUE TITLE
Zellij disabling true color on Helix text editor

### ISSUE THREAD

**Issue by andradei** [zellij-org/zellij#2359]
I just installed Zellij on my environment:

## Steps to reproduce
1. Open a terminal (wezterm or windows terminal)
2. Start `wsl`
3. Open `helix`: theme is picked up and works
4. Close helix
5. Start a Zellij session
6. Open `helix`: theme is borked, trying to set a new theme throws the following message

![image](https://user-images.githubusercontent.com/2653546/231573997-fed1b31a-9930-4b4b-90a7-7d4242c31d72.png)

## Note

NeoVim more or less gets it's theme applied.

## Versions

- zellij 0.35.2
- `uname -av`: Linux AE-22-01 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Windows 11
- wezterm: 20230408-112425-69ae8472
- helix: 23.03 (3cf03723)

**Comment by imsnif** [comment]
Hey, this very likely has to do with the method Helix uses to detect true color support - since this is transparent to Zellij (if your terminal supports it, Zellij should do the right thing). I'd be happy to look into it, but I'll need more information.

**Comment by andradei** [comment]
Thank you for the disposition. I'll open an issue on helix and update here (or close the issue) as needed.
P.S.: Great software, 30min in and I'm already flying with Zellij.

**Comment by andradei** [comment]
Confirmed this is a non-issue on zellij
