### ISSUE TITLE
cat large file consumes and doesn't release huge amounts of memory

### ISSUE THREAD

**Issue by jcaplan** [zellij-org/zellij#236]
# steps to reproduce
generate a text file
```python
#!/usr/bin/env python
import lorem

for i, s in enumerate(lorem.sentence(20)):
    if i > 100000:
        break
    print(s)
```

cat test file repeatedly

# actual results

Significant memory utilization and **does not** decrease. this is not a spike, it's a big memory leak.

before zellij is running:
![image](https://user-images.githubusercontent.com/10764469/111858551-53012c80-8910-11eb-9011-14ecd2d07539.png)

after starting zellij:
![image](https://user-images.githubusercontent.com/10764469/111858563-6613fc80-8910-11eb-93b0-7b9b5ef86608.png)

after cat the large file:
![image](https://user-images.githubusercontent.com/10764469/111858575-7b892680-8910-11eb-947c-48a1b8e7e17f.png)

after cat again:
![image](https://user-images.githubusercontent.com/10764469/111858590-9491d780-8910-11eb-971a-79ba433d191e.png)

# expected results

Memory utilization should not increase due to terminal output

# Environment

Tested on WSL2 running on Windows Terminal

**Comment by a-kenji** [comment]
The scroll back huffer is currently unlimited. Could that be the culprit here?

**Comment by imsnif** [comment]
> The scroll back buffer is currently unlimited. Could that be the culprit here?

I'm almost 100% sure that's the issue. I think this is what @TheLostLambda encountered as well.
To fix this, we should (for now) have a hard limit here: https://github.com/zellij-org/zellij/blob/main/src/client/panes/grid.rs#L147
And later on have it configurable.

**Comment by jcaplan** [comment]
that may be *part* of the issue. except the file is 5MB. When I do it in tmux, which also has a really big (but not infinite scroll buffer), the memory utilization changes by about 5MB. zellij consumes almost 1GB when doing 5MB worth of scrolling. The same inefficiencies that are hurting performance are also not cleaning up memory properly. a lot of this goes away if you never use that memory in the first place. performance degradation and memory utilization are symptoms of a structural problem.

I've been catching up on `tab`, `terminal_pane`, and `grid`. I see that grid owns the screen buffers, and knows exactly when any spot in the terminal is changing. instead of passing that information through many for loops and copies on its way to eventually get written to stdout by tab, grid should be writing to stdout. when things are stored in its buffer it should be in the final format to directly write to stdout, since writing out the same information multiple times is unavoidable. you should transform on the way in, so you don't have to constantly transform on the way out (like when scrolling, should just be a straight up write of the updated grid buffer). For example, `as_character_lines` should be a one time transform on a line, not something constantly happening on the same data over and over, let alone every key stroke.

That would also make it less convoluted write out a single character and reduce the amount that needs to be written because grid has the most detailed information about what is changing and how, since it needs it to update the buffer. if you're writing a single character, then grid should write out that character to its position, not pass up a line or the whole terminal contents to pane, iterating through every character in the pane along the way.

If the grid buffer is an array of line buffers, then the scroll buffer just takes ownership over lines when they move off screen, those lines should be strings, that can be re-written to stdout without any processing. The scroll buffer should have 0 memory overhead beyond the size of the string.

**Comment by imsnif** [comment]
@jcaplan - it's a little hard for me to relate to what you're writing because I'm not sure I understand the context. Are you offering to do this and proposing a design? Or are you giving advice?

**Comment by 5c077m4n** [comment]
@imsnif just FYI:
The command `head -c 32MB </dev/urandom >/tmp/large_file.txt`'s output completely freezes up the zellij instance, while `head -c 32MB </dev/urandom | base64 >/tmp/large_file.txt`'s output works...

**Comment by a-kenji** [comment]
> @imsnif just FYI:
> The command `head -c 32MB </dev/urandom >/tmp/large_file.txt`'s output completely freezes up the zellij instance, while `head -c 32MB </dev/urandom | base64 >/tmp/large_file.txt`'s output works...

I have a similar experience with these test files.

**Comment by imsnif** [comment]
This has been fixed
