### ISSUE TITLE
pane borders persist when switching between tabs

### ISSUE THREAD

**Issue by denismaxim0v** [zellij-org/zellij#237]
If on the `fist tab` we open a few panes, then open a `new tab` 
and switch between them the pane borders will persist
![Screenshot from 2021-03-20 16-56-58](https://user-images.githubusercontent.com/11789381/111875766-21d23c00-89a4-11eb-974a-03e70e9eb59e.png)
![Screenshot from 2021-03-20 16-57-13](https://user-images.githubusercontent.com/11789381/111875768-226ad280-89a4-11eb-824e-cb63ff6cb9b4.png)
![Screenshot from 2021-03-20 16-57-23](https://user-images.githubusercontent.com/11789381/111875769-23036900-89a4-11eb-9d28-a19303396552.png)

**Comment by imsnif** [comment]
This has been fixed
