### ISSUE TITLE
Status bar intermittently displays wrong keybindings.

### ISSUE THREAD

**Issue by sebastiancarlos** [zellij-org/zellij#2391]
I made this change from default on `config.kdl`:

```
    shared_except "locked" {
        bind "Ctrl g" { SwitchToMode "Locked"; }
        bind "Alt q" { Quit; } // <--- only this line changed, from "Ctrl q"
```

After running `zellij`, the status bar will sometimes show the old keybinding. This is just a visual issue - the new keybinding always works.

<img width="158" alt="Screenshot 2023-04-22 at 10 07 44" src="https://user-images.githubusercontent.com/88276600/233772273-e2467501-04eb-4bf1-95f3-e77e9ad5a5c1.png">
<img width="163" alt="Screenshot 2023-04-22 at 10 07 21" src="https://user-images.githubusercontent.com/88276600/233772275-840ef7c0-06fa-4ece-a7eb-a83c9af0352d.png">

**Basic information**

`zellij --version`: zellij 0.36.0
`stty size`: 45 178
`uname -av` or `ver`(Windows): Darwin XXXX 21.6.0 Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64 x86_64

**Comment by npupko** [comment]
@sebastiancarlos Looks like you did not disabled default bindings. You either need to disable all default bindings for the specific section like

```kdl
keybinds clear-defaults=true { // will clear all default keybinds
    normal {
        // ...
    }
}
```

or just unbind specific action

```kdl
shared_except "locked" {
    unbind "Ctrl g"
    bind "Alt g" { SwitchToMode "Locked"; }
}
```

**Comment by sebastiancarlos** [comment]
Thanks!
