### ISSUE TITLE
custom layout

### ISSUE THREAD

**Issue by ixzh** [zellij-org/zellij#2404]
hi, 

I find custom layout useful but not flexible: 
1. once a cumtom layout is set, I can't seem to change layout using `alt [`.
2. the custom layout don't have the status bar at bottom. 

I'd like to have the compact layout status bar at the bottom of the tab. Is it possible?

**Comment by ElSargo** [comment]
To get compact bar at the bottom you can use
```kdl
layout
    default_tab_template {
        children
        pane size=1 borderless=true {
            plugin location="zellij:compact-bar"
        }
    }
}

```

**Comment by ixzh** [comment]
thanks! that works!
