### ISSUE TITLE
FR: hide Zellij branding/title in tab bar

### ISSUE THREAD

**Issue by Drugoy** [zellij-org/zellij#2427]
There's already an option to hide session name.
I'd like to also hide Zellij branding/title from tab bar, so that tab-bar would only consist of tabs.

**Comment by imsnif** [comment]
Hey, this is not an option I'd like to provide by default at this time.

Zellij is an OSS project without corporate funding, meaning we do not have a marketing/advertizing/outreach budget. This branding is one of the main ways people find out about us (from screenshots, streams or just looking over a colleague's shoulder).

You can technically remove it by rolling your own plugin, but right now this is not a very pleasant experience. These days I'm working on remedying that - stay tuned!

**Comment by Drugoy** [comment]
That's fair.
As a compromise I'd suggest moving the branding (instead of completely hiding it) to the status bar, but I'll leave it to you to decide whether to reopen this ticket.

**Comment by milanglacier** [comment]
> That's fair.
> As a compromise I'd suggest moving the branding (instead of completely hiding it) to the status bar, but I'll leave it to you to decide whether to reopen this ticket.
> Edit: just noticed I can't reopen anyways, hehe :)

I think that status bar is overcrowded since it also takes the responsibility to show keybindings hint. Tab bar has more free space and is ideal to show the branding.
