### ISSUE TITLE
[Feature Request] Support use of Zellij with Neovim smart splits plugin

### ISSUE THREAD

**Issue by linux-cultist** [zellij-org/zellij#2434]
This neovim plugin supports tmux and I was wondering if it could support zellij as well: https://github.com/mrjones2014/smart-splits.nvim

I asked on the plugin github page and the author says he would need command line support for a few things: https://github.com/mrjones2014/smart-splits.nvim/issues/111

Have a look and see if this is something you would consider implementing, to increase adoption of zellij in the neovim community. Thank you!

**Comment by mrjones2014** [comment]
Adding extra context here. I reached out in the matrix channel and there is a caveat:

> tl;dr: the only hard blocker to my plugin supporting ZelliJ is a way to get the currently focused pane ID via the CLI, is that possible? 
>
> hey, so this is a bit of a hard thing to do in the context of Zellij... Zellij supports true multiplayer sessions, meaning each connected user gets their own cursor. If they are focused on different panes, which ID would you expect to receive?
> We can't know who issued the command from the CLI, because the shell doesn't know about the multiple users. It could very well be that one user started typing the CLI command, another user finished typing it and a third user pressed ENTER.
> We could give you a list, but then we're just offloading the problem to you :)

Maybe it would be possible for `smart-splits.nvim` to just not support multiple sessions and disable the mux integration if Zellij returns more than one focused pane ID.

I'll also copy my table here for convenience. I have a Lua API wrapper around multiplexer backends, here's the support table I made for Zellij:


| Lua method                        | Zellij CLI support                                                                                                                                                    |
| --------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `is_in_session()`                 | Maybe possible with `zellij list-sessions`?                                                                                                                           |
| `current_pane_id()`               | No CLI command I could find. Is there an environment variable, maybe?                                                                                                                                                       |
| `current_pane_at_edge(direction)` | No CLI command I could find. Can possibly be worked around with `zellij cli move-focus` back and forth.                                                                            |
| `current_pane_is_zoomed()`        | `zellij cli toggle-fullscreen` exists, but no way to _check_ if it is fullscreen. Not a critical component for the plugin, options may not work completely correctly. |
| `next_pane(direction)`            | `zellij action move-focus [direction]`                                                                                                                                |
| `resize_pane(direction)`          | `zellij action resize [direction]`                                                                                                                                    |
| `split_pane(direction)`           | `zellij action new-pane --direction [direction]`                                                                                                                      |

**Comment by linux-cultist** [comment]
Yes I think not supporting multiple sessions would be fine, and plugin integration would still be super useful for most users.

**Comment by jaeheonji** [comment]
Maybe this issue will help. #967

**Comment by tlinford** [comment]
Adding this action to get the current pane id should not be a problem really, just needs someone to pick it up.

**Comment by Kangaxx-0** [comment]
I am not familiar with `smart-splits.nvim`  plugin, but if the requirement is only to add a new `action` that returns the current active pane id, I can spend some time on that

**Comment by mrjones2014** [comment]
For full/better support, we'd also need a way to check if that pane is at an edge of the screen, and a way to tell if the pane is zoomed/maximized, but we can do rudimentary support with just a way to get the current pane ID.

To check if we're at the edge, we can try moving to a new pane, and if the same pane ID is returned, then we're at an edge. It's a bit of a hack and looks a little weird since the cursor will flash, but it works.

See the table I support posted above.

**Comment by Kangaxx-0** [comment]
I've got an active pr to implement swap tab - https://github.com/zellij-org/zellij/pull/2242, it already does a check if pane is at an edge, I can include that in my pr as rudimentary support :)

**Comment by Kangaxx-0** [comment]
I've published a pr for this, want to have some feedbacks before I continue

**Comment by Kangaxx-0** [comment]
QQs:
-  what does `is-in-session` API do?, what is expected to return ?
-  `current_pane_at_edge(direction)` -> if I call this with `right`, then the expected result is either `true` or `false`, a simply boolean value?

**Comment by mrjones2014** [comment]
`is_in_session` just returns a Boolean indicating if you’re in a session for the mux.

`current_pane_at_edge('right')` should return true if the current page is at the right edge, correct.

**Comment by Kangaxx-0** [comment]
> `is_in_session` just returns a Boolean indicating if you’re in a session for the mux.
> 
> `current_pane_at_edge('right')` should return true if the current page is at the right edge, correct.

Thanks, :) FYI - I am having an active pr to handle wrap around panes: Say you have one tab with 3 panes in zellij - A|B|C, and the C is current one, then when you move to the right, zellij will automatically focus the leftmost one which is A.

For this feature request -  having 3 separated APIs(paneId, at the edge and is_in_session) makes more sense, I will continue the rest of code changes

**Comment by Kangaxx-0** [comment]
I've added the support to know if a pane is on the edge by giving direction.  For `is_in_session`, I don't think it is really necessary since it is always the case

**Comment by mrjones2014** [comment]
> For is_in_session, I don't think it is really necessary since it is always the case

yeah this is more for my side, it can be implemented by checking if the current pane ID returns a value or not.

**Comment by lukebarton** [comment]
I’d really like to see this supported because having 3 separate sets of keybinds for switching windows, zellij panes and nvim splits is quite inconvenient.

**Comment by imsnif** [comment]
Hey @mrjones2014 - just released a patch version that among other things includes:
1. `zellij action list-clients` (https://github.com/zellij-org/zellij/pull/3314)
2. Support for binding `Ctrl j`

I think these two should allow you to perform the integration?

Also just note: you can always look at the `ZELLIJ_PANE_ID` environment variable to get the terminal pane id of a pane (in `zellij action list-clients` this will be translated to `terminal_<ZELLIJ_PANE_ID>`.

**Comment by mrjones2014** [comment]
> you can always look at the ZELLIJ_PANE_ID environment variable to get the terminal pane id of a pane

This is the pane ID of the current pane, right? I still need to use `zellij action list-clients` if I want to be able to get the ID of the active pane, from any other pane?

If that's possible now, then yeah I think we should be able to integrate with Zellij!

**Comment by imsnif** [comment]
To your questions, in order: yes and yes :)

Happy hacking!
