### ISSUE TITLE
Ability to quickly switch between sessions

### ISSUE THREAD

**Issue by VinukaThejana** [zellij-org/zellij#2454]
I love working with Zellij

When working with multiple codebases I would love the ability to switch between sessions using a keybinding quickly. Is this possible to be achieved?

**Comment by scabala** [comment]
This is currently not possible. I personally just detach from session, have simple script with `fzf` to attach to chosen one and call it a day. From what I know, it is however planned to do.

You might want try https://docs.rs/crate/zellij-runner/latest - I did not use it personally

**Comment by VinukaThejana** [comment]
Thanks
