### ISSUE TITLE
Presence in the Debian package repository [feature request]

### ISSUE THREAD

**Issue by R-Rothrock** [zellij-org/zellij#2458]
Make installation as easy as `sudo apt install zellij`. I realize this is a bit of a pain, as it's not quite the same infrastructure as the AUR.

**Comment by imsnif** [comment]
Hey, I'd be totally happy to welcome this - but we do not maintain outside packages (aside from crates.io and one of the maintainers who maintains the AUR-git repo). If someone wants to go ahead and do this, I'd offer whatever help I can.

**Comment by R-Rothrock** [comment]
I’ll do some research, but I might (_might_) be able get a sponsor to help me upload it. Wish me luck.
