### ISSUE TITLE
Support for relative path or env var in layout CWD

### ISSUE THREAD

**Issue by t18n** [zellij-org/zellij#2468]
I have multiple computers and I wish that I can sync all the layouts. However, the one thing that prevent me from doing that is that `cwd` only supports absolute path. 

```sh
# Computer A
layout {
    tab name="Dotfiles" cwd="/Users/User-A/dotfiles" {
             # pane config
        }
    }
}

# Computer B
layout {
    tab name="Dotfiles" cwd="/Users/User-B/dotfiles" {
             # pane config
    }
}
```

I would like to request support for relative path or env to make it easier to sync with dotfiles.

**Comment by scabala** [comment]
I think this is duplicate of #2035

**Comment by Nicoretti** [comment]
@scabala think so too. .
 @t18n, could you please review and close/update the ticket?

**Comment by t18n** [comment]
Duplicates https://github.com/zellij-org/zellij/issues/2035
