### ISSUE TITLE
How to change the default size of floating panes?

### ISSUE THREAD

**Issue by randomizethistoopls** [zellij-org/zellij#2489]
I'm only seeing an option to set the size of the floating panes created within a layout. How can I make any floating pane created at any time bigger for any layout?

**Comment by scabala** [comment]
This is currently not possible, unfortunately. However, this functionality would be similar to #1906?

**Comment by randomizethistoopls** [comment]
Sort of. I'd still prefer to have larger floating panes rather than being able to switch between full screen and the default.

**Comment by scabala** [comment]
Huh, new day, new things to learn.

Sorry for the confusion but happy this actually got resolved!
