### ISSUE TITLE
zellij with neovim copy/paste

### ISSUE THREAD

**Issue by Sam-su2060** [zellij-org/zellij#2491]
Hello,

Any kind of zellij/neovim integration to make copy to system clipboard working the same way like tmux?

**Comment by jaeheonji** [comment]
Hi, @Sam-su2060! unfortunately zellij doesn't officially provide such feature.

I'm not sure exactly how the tmux/neovim integration works, but If you are interested in it you can find and request what you need on zellij.

Thank you :)
