### ISSUE TITLE
Zellij crashes at start, load in the sky

### ISSUE THREAD

**Issue by matthiasbeyer** [zellij-org/zellij#2495]
Zellij 0.36.0 crashes at startup with

```
Received empty message from server
```

and load on my device goes up to over 20. This happened after a fresh boot.

**In Case of Graphical or Performance Issues**

`/tmp/zellij-1000/zellij-log/`:

```
INFO   |zellij_client            | 2023-05-30 18:13:53.281 [main      ] [zellij-client/src/lib.rs:143]: Starting Zellij client! 
INFO   |zellij_server            | 2023-05-30 18:13:53.290 [main      ] [zellij-server/src/lib.rs:237]: Starting Zellij server! 
INFO   |zellij_server            | 2023-05-30 18:13:53.345 [main      ] [zellij-server/src/lib.rs:843]: Compiling plugins using Cranelift 
INFO   |zellij_server::plugins   | 2023-05-30 18:13:53.346 [wasm      ] [zellij-server/src/plugins/mod.rs:72]: Wasm main thread starts 
INFO   |zellij_utils::input::plug| 2023-05-30 18:13:53.355 [async-std/runti] [zellij-utils/src/input/plugins.rs:139]: Plugin 'compact-bar.wasm' exists in the 'PLUGIN DIR' at '/home/m/.local/share/zellij/plugins/' but is being ignored 
WARN   |zellij_utils::ipc        | 2023-05-30 18:14:45.050 [router    ] [zellij-utils/src/ipc.rs:230]: Error in IpcReceiver.recv(): InvalidMarkerRead(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) 
ERROR  |zellij_client            | 2023-05-30 18:14:45.050 [router    ] [zellij-client/src/lib.rs:309]: Received empty message from server 
```

**Basic information**

`zellij --version`: 0.36.0 
`stty size`: `58 118`
`uname -av` or `ver`(Windows): `Linux hoshi 5.4.243 #1-NixOS SMP Wed May 17 09:36:05 UTC 2023 x86_64 GNU/Linux`

List of programs you interact with as, `PROGRAM --version`: None

**Further information**

This is new with 0.36.0, has not ever happened before.

**Comment by matthiasbeyer** [comment]
Hm it is indeed interesting! I just noticed that my other device also has 0.36.0 installed and I have no issue there... :thinking:

**Comment by non-descriptive** [comment]
There's some number of issues related to panicking of wasm plugins like #2078. Something definitely gone wrong with them in 0.36 version. In 0.37.0 everything looks fine.

**Comment by imsnif** [comment]
@non-descriptive - these sorts of issues usually have to do with the wrong version of the plugins being loaded. I'm happy to look further into these issues, but just to stress that they almost 100% have to do with the environment: eg. duplicate entries in cache (stemming from having previously compiled git version of the same number), compiling the plugins by hand (my guess about the nix CI in this case) etc.

If this were a sweeping issue there would have been considerably more people reporting it by now (as well as CI failures etc.)

Again, happy to help - but let's look at the environment before we look at changes in the version. I could be wrong but this almost certainly comes from there.

This goes for @matthiasbeyer as well.

**Comment by non-descriptive** [comment]
used to install via `cargo install --git https://github.com/zellij-org/zellij [--force]`. Used everything with default setup without installing any extras or setting up config or layout files. No idea what should affect environment so much it break between versions on defaults.

Also there's a bunch of opened issues related to [startup crashes](https://github.com/search?q=repo%3Azellij-org%2Fzellij+panicked&type=issues), so people were reporting this kind of issues. Definitely this requires some cleanup and I guess you are short on manpower to deal with all of them. Parts of them probably should be closed as dupes. 

> Again, happy to help - but let's look at the environment before we look at changes in the version.

This require specifics what exact environment people should provide to help to help? Something like `echo "$ZELLIJ|$SHELL|$EDITOR|$TERM|$(uname -osr)"`? Specify terminal? Logs?
