### ISSUE TITLE
How to remove zellij session name from compact bar

### ISSUE THREAD

**Issue by veranorooz** [zellij-org/zellij#2506]
How does one remove the left and right most elements from the compact bar? What does the right one represent?

![image](https://github.com/zellij-org/zellij/assets/60433637/be465ceb-17e3-4155-b150-28e0a8245a28)

**Comment by J-Kappes** [comment]
Yeah, the `hide_session_name` option doesn't seem to work for the compact layout :(

**Comment by Kangaxx-0** [comment]
This bug should be fixed in next release. There is one thing I'd like to ask - How you guys turn on `hide_session_name` as it is not part of config settings now.

**Comment by J-Kappes** [comment]
> How you guys turn on `hide_session_name` as it is not part of config settings now.

I followed the instructions from the [zellij docs](https://zellij.dev/documentation/options.html). Second entry from the bottom. I added that snippet to the bottom of my config.kdl

**Comment by Kangaxx-0** [comment]
> > How you guys turn on `hide_session_name` as it is not part of config settings now.
> 
> I followed the instructions from the [zellij docs](https://zellij.dev/documentation/options.html). Second entry from the bottom. I added that snippet to the bottom of my config.kdl

Thanks :)

**Comment by veranorooz** [comment]
> > How you guys turn on `hide_session_name` as it is not part of config settings now.
> 
> I followed the instructions from the [zellij docs](https://zellij.dev/documentation/options.html). Second entry from the bottom. I added that snippet to the bottom of my config.kdl

I tried this just in case too but it does say pane frames so I'm not sure if it applies here

**Comment by Kangaxx-0** [comment]
Can you guys try the latest version, does it solve the problem ?

**Comment by J-Kappes** [comment]
It does for me.

**Comment by Kangaxx-0** [comment]
@imsnif @jaeheonji I believe this one is ready to close :)

**Comment by mahume** [comment]
Is there a way to remove "Zellij" from the UI? Seems to be unnecessary information for those of us looking for a compact UI.
