### ISSUE TITLE
exit a pane doesn't resize the window (no SIGWINCH?)

### ISSUE THREAD

**Issue by qballer** [zellij-org/zellij#251]
I have this weird situation that the upper part isn't a zellij pane but the bottom is. In the picture you can see I can't go up. 

![Screen Shot 2021-04-04 at 20 35 34](https://user-images.githubusercontent.com/1002622/113516880-6acde700-9585-11eb-9d55-57c61703534f.png)

**Comment by a-kenji** [comment]
Thanks! I think it has to do with the plugin accidentally getting larger than it should be.
Could be related to  #217 .
You could try to send a SIGWINCH manually to the window to confirm:
```
pkill -WINCH zellij
```
