### ISSUE TITLE
Feature(Config): Dump default config

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#253]
Make it possible to dump a default config to
either stdout or a file.
Possibly with comments explaining the Actions,
related to #247 . 

More discussion in #244 , 
especially https://github.com/zellij-org/zellij/pull/224#issuecomment-799265605 .

**Comment by a-kenji** [comment]
Should be easy to implement once  #283 is there.

**Comment by matthiasbeyer** [comment]
I think this is a good idea, opposing to writing a default configuration automatically on the first run, which I think is a _bad_ idea (since implicit is always worse than explicit).

Having a warning about a missing configuration file and a note on how to create a default config file is IMO a way better user experience than just silently writing a default file to disk and using that.

**Comment by a-kenji** [comment]
>I think this is a good idea, opposing to writing a default configuration automatically on the first run, which I think is a bad idea (since implicit is always worse than explicit).

I agree, this seems like a more sane default. 

>Having a warning about a missing configuration file and a note on how to create a default config file is IMO a way better user experience than just silently writing a default file to disk and using that.

Maybe have a command that will bootstrap everything for the user? And a different to dump it to stdout?

**Comment by matthiasbeyer** [comment]
> Maybe have a command that will bootstrap everything for the user? 

Yep, a nice interactive one probably. Maybe there's even a framework for things like that somewhere, otherwise we could implement a small one (would love to contribute on such a thing)!

> And a different to dump it to stdout?

Yep, sounds good.

**Comment by a-kenji** [comment]
Awesome! I will try to get a different issue to kind of pull all that stuff together soonish.

**Comment by imsnif** [comment]
@a-kenji - I think this is released already, right?

**Comment by a-kenji** [comment]
@imsnif - Yes!
