### ISSUE TITLE
Feature Request: `--layout` optionally takes a path to a file

### ISSUE THREAD

**Issue by Industrial** [zellij-org/zellij#2549]
As a user of Zellij, I enjoy the automation of the setup of my terminals and editors, compile processes, unit tests, git clients etc for software projects. The way I set it up and the commands to be run differ between projects and toolchains.

What I would like to have is the option to put a zellij layout inside my software project instead of in the layout directory. This way I can keep the configuration local and I can check it into git.

`cd ~/Code/myproject && zellij --layout ./myproject.kdl`

That would be so awesome!

**Comment by LeSnake04** [comment]
![image](https://github.com/zellij-org/zellij/assets/47243761/3ecf539b-4d62-4301-849e-59a1190cc272)
Are you sure you cant do this already?

**Comment by Industrial** [comment]
Um, yes. You are correct. Sorry for not reading the `--help` correctly :-1:
