### ISSUE TITLE
0.37.1 requires the .config/zellij/themes dir to exist or it crashes on startup

### ISSUE THREAD

**Issue by lespea** [zellij-org/zellij#2565]
Thank you for taking the time to file this issue! Please follow the instructions and fill in the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

**In Case of Graphical or Performance Issues**

1. Delete the contents of `/tmp/zellij-1000/zellij-log`, ie with `cd /tmp/zellij-1000/` and `rm -fr zellij-log/` (`/tmp/` is `$TMPDIR/` on OSX)
2. Run `zellij --debug`
3. Run `stty size`, copy the result and attach it in the bug report
4. Recreate your issue.
5. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.

> The log file is completely empty and running with debug produces no extra output

**Basic information**

`zellij --version`: 0.37.1
`stty size`: 81 288
`uname -av` or `ver`(Windows): 6.3.8-zen1-1-zen

List of programs you interact with as, `PROGRAM --version`: `N/A`

**Further information**

The entire contents of my `config.kbl` file is this:
```
theme "tokyo-night"
```

In 0.37.0 this worked fine and zellij loaded with the correct built-in theme, in 0.37.1 it crashes with
```
IoError: No such file or directory (os error 2), File: /home/adam/.config/zellij/themes
```

If I manually create the directory `themes` in that folder it runs without crashing and loads the appropriate theme.

**Comment by dominz88** [comment]
I've encountered the same bug. 
OS: Ubuntu 22.04
Zellij: 0.37.1 installed with cargo

It seems it has something to do with [these revert ](https://github.com/zellij-org/zellij/commit/a35bdb71e61015cac4922556cb5246e0c775ffcd)

**Comment by imsnif** [comment]
Ping @jaeheonji - when you have the chance

**Comment by jaeheonji** [comment]
Sorry guys! I'm fixing now :) Thank you for letting me know!

**Comment by dominz88** [comment]
Hello does the hotfix really "Include theme files into the zellij binary"? I ask because when i strace zellij 0.37.1 I get `openat(AT_FDCWD, "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-utils-0.37.1/assets/themes", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 5
`

**Comment by jaeheonji** [comment]
@dominz88 No, 0.37.1 does not include themes. So I fixed both (include this issue)
