### ISSUE TITLE
Symbol "¯\_( ͡° ͜ʖ ͡°)_/¯" not render correctly under zellij

### ISSUE THREAD

**Issue by dragove** [zellij-org/zellij#2580]
symbol ¯\_( ͡° ͜ʖ ͡°)_/¯ renders only  ¯\_( ° ʖ °)_/¯ in zellij

`zellij --version`: 0.37.2
`stty size`:
`uname -av` or `ver`(Windows): Linux arch 6.3.9-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 21 Jun 2023 20:46:07 +0000 x86_64 GNU/Linux

konsole-version: 23.04.2

**Further information**
Reproduction steps: just paste " ¯\_( ͡° ͜ʖ ͡°)_/¯ " in zellij, this works well in  konsole without zellij or with tmux.

**Comment by timmclean** [comment]
I see this problem too. Here's a smaller test case:

```
$ echo -n ' ͡' > test.txt
$ hd test.txt
00000000  20 cd a1                                          | ..|                                                                                                                                                  
00000003                                                                                                                                                                                                           
$ cat test.txt
```

Outside of zellij, `cat` will show a space with a diacritic over top. Inside zellij, `cat` shows only a space.

The test case is a space character (`20`) followed by U+0361 "Combining Double Inverted Breve" (utf-8 encoded as `cd a1`).

**Comment by timmclean** [comment]
Related: https://github.com/zellij-org/zellij/issues/1538

**Comment by dragove** [comment]
Thanks for info me that, I close this issue as duplicated.
