### ISSUE TITLE
sha256 checksums do not match

### ISSUE THREAD

**Issue by kaushalyap** [zellij-org/zellij#2594]
```
~/DOWNLOADS 
❯ sha256sum zellij-x86_64-unknown-linux-musl.tar.gz
199da1af301c9808d517d58c686d2fc32f78be412f4a189f8e7195e88653c1c9  zellij-x86_64-unknown-linux-musl.tar.gz

~/DOWNLOADS 
❯ cat zellij-x86_64-unknown-linux-musl.sha256sum
───────┬────────────────────────────────────────────────────────────────────────
       │ File: zellij-x86_64-unknown-linux-musl.sha256sum
───────┼────────────────────────────────────────────────────────────────────────
   1   │ 0d3bc9e261d093ebde1876c3fd38ec392561487c9b5fc820e38e2fde4d28a62f  zelli
       │ j
───────┴─
```

**Comment by gauthierc** [comment]
Hello,
The file contains the sha256sum footprint of the zellij binary, not the tar.gz file.
```
❯ sha256sum zellij
0d3bc9e261d093ebde1876c3fd38ec392561487c9b5fc820e38e2fde4d28a62f  zellij
```

**Comment by Zykino** [comment]
Don’t forget, to check a file full of hash use `sha256sum -c zellij-x86_64-unknown-linux-musl.sha256sum`. That way it would have told you the file `zellij` does not exist (not the same name).

**Comment by kaushalyap** [comment]
> Hello, The file contains the sha256sum footprint of the zellij binary, not the tar.gz file.
> 
> ```
> ❯ sha256sum zellij
> 0d3bc9e261d093ebde1876c3fd38ec392561487c9b5fc820e38e2fde4d28a62f  zellij
> ```

Sorry I did not knew that, thanks!
