### ISSUE TITLE
Mixing of Zellij default theme and light terminal themes is unreadable

### ISSUE THREAD

**Issue by Naeddyr** [zellij-org/zellij#2596]
Hi, first time user.

Ubuntu 22.04.2 LTS, Gnome Terminal Version 3.44.0 for GNOME 42
Installed through cargo zellij 0.37.2

When I open up zellij (without configuration), I am greeted with:
![Screenshot from 2023-07-01 18-45-45](https://github.com/zellij-org/zellij/assets/32275753/cb592626-4b47-4876-82e4-95138f04290e)

Some of Zellij's bg colors (the margins around a pane and the bottom status bar at least at first glance) seem to default to the user's terminal's background color, but this causes problems when the theme is incompatible with the fg colors of Zellij's default theme.

How tmux handles this issue: margins change color based the terminal theme, the bottom bar doesn't use the terminal's colors (though there's a tiny outline around the whole screen).

**Comment by Naeddyr** [comment]
![Screenshot from 2023-07-02 16-16-15](https://github.com/zellij-org/zellij/assets/32275753/802c4b8f-b35d-4fd3-8ea2-9fbeade4889f)

I decided to try out a theme from zellij-utils, in this screenshot it's [solarized-light](https://github.com/zellij-org/zellij/blob/main/zellij-utils/assets/themes/solarized-light.kdl), but all of the example themes are also "semantically" broken.

As a test I created this theme based on solarized-light:
```
    super-light {
        fg 000 000 000
        bg 255 255 255
        black 64 000 000
        red 220 50 47
        green 133 153 0
        yellow 181 137 0
        blue 38 139 210
        magenta 211 54 130
        cyan 42 161 152
        white 238 232 213
        orange 203 75 22
    }
```
which resulted in this monstrosity:
![Screenshot from 2023-07-02 16-21-36](https://github.com/zellij-org/zellij/assets/32275753/4aa87fd5-c57a-4503-b1c6-052aa6d34285)

So, what I believe is happening is that Zellij assumes everyone is using a dark theme. fg and bg are used only when they're swapped in their meaning (fg is used as a background color and bg is used as a foreground color), but elsewhere only color names are used and where they are used the assumption is a dark background: "white" is always a text color, even when the terminal has a light background.

Of course there's a workaround by creating a theme that makes sense, but the real solution would be to have agnostic palette names ("bg1, fg4, bgred, fgmagenta") instead of hard-coded color names that don't make sense when put into the context of actually using Zellij with a light background.

**Comment by tlinford** [comment]
there's been talk of improving the way themes are defined here: https://github.com/zellij-org/zellij/issues/2297

**Comment by Naeddyr** [comment]
Good to hear!

**Comment by imsnif** [comment]
I'm closing this in favor of: #2297
