### ISSUE TITLE
Zellij SVG icon / Devicon

### ISSUE THREAD

**Issue by Lilja** [zellij-org/zellij#2597]
I was looking around the [devicons website ](https://devicon.dev/) to see if I can use the zellij icon for a not-yet-released-plugin that I'm creating.

Perhaps it could be worth investing some time into submitting a patch that adds the icon to their repository. Zellij is a developer tool after all(something that they require).

One of the requirements of the icons is that they are SVG. It would appear that the logo in the asset directory in a png. Is there a SVG icon available?

**Comment by imsnif** [comment]
Cool, there you go

![zellij-logo](https://github.com/zellij-org/zellij/assets/795598/448aee32-2f58-4d0a-ae30-0b2c546031f8)
