### ISSUE TITLE
Failed Install on Debian: error[E0425]: cannot find value `fake_curso2` in this scope

### ISSUE THREAD

**Issue by badjr13** [zellij-org/zellij#2600]
I'm attempting to install Zellij on a fresh install of Debian using:
`cargo install --locked zellij`

and I'm erroring out when it goes to compile `zellij-server v0.37.2`

```
   Compiling zellij-server v0.37.2
error[E0425]: cannot find value `fake_curso2` in this scope
   --> /home/badjr13/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zellij-server-0.37.2/src/panes/terminal_pane.rs:429:31
    |
429 |             vte_output = Some(fake_curso2);
    |                               ^^^^^^^^^^^ help: a local variable with a similar name exists: `fake_cursor`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `zellij-server` (lib) due to previous error
```

System Info:
```
❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```
```
❯ rustup --version
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.70.0 (90c541806 2023-05-31)`
```

**Comment by imsnif** [comment]
This is not part of our code base, where the variable name appears properly: https://github.com/zellij-org/zellij/blob/main/zellij-server/src/panes/terminal_pane.rs#L429

Not sure how this happened (maybe something manipulated the cache directly somehow?) in any case, deleting the cached file (`/home/badjr13/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zellij-server-0.37.2/src/panes/terminal_pane.rs`) might help?

**Comment by badjr13** [comment]
This worked. Thank you!
