### ISSUE TITLE
Add tmux-fingers functionality

### ISSUE THREAD

**Issue by shahamran** [zellij-org/zellij#2601]
It'd be great if we could have something like [`tmux-fingers`] mode in zellij.
Namely, pressing some key combination to switch to "fingers-mode", which highlights relevant items from the scrollback, and pressing 1-2 letters to copy / "select" one item.

We can emulate this behavior with scrollback editing and vim EasyMotion, but it's much less convenient than `fingers`, since it requires many more key-strokes.

Another tmux plugin with the same functionality: [`tmux-thumbs`].

[`tmux-fingers`]: <https://github.com/Morantron/tmux-fingers>
[`tmux-thumbs`]: <https://github.com/fcsonline/tmux-thumbs>

**Comment by imsnif** [comment]
Sounds like great ideas for plugins once we add an API to read scrollback and to draw on the output buffer (coming soon!)
