### ISSUE TITLE
Can't bind Ctrl + [ i, j, m]

### ISSUE THREAD

**Issue by J-Kappes** [zellij-org/zellij#2609]
**Basic information**

`zellij --version`:  0.37.2
`stty size`: 41 184
`uname -av` or `ver`(Windows): Linux FedoraMain 6.3.11-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Jul  2 13:17:31 UTC 2023 x86_64 GNU/Linux

`alacritty --version`: alacritty 0.12.2 (no config file, ergo no keybinds AFAIK)

**Further information**
For me binding `search { PageScrollUp; } ` or `shared_except "move" "locked" { SwitchToMode "Move"}` to `Ctrl` plus any of `i`, `j` or `m` didn't work. Zellij ignored the signals and passed them on to the Shell within.

**Comment by tlinford** [comment]
This is because normally these keys are interpreted as follows by an application running in a terminal:
ctrl + i = TAB
ctrl + j = Enter
ctrl + m = Enter

**Comment by J-Kappes** [comment]
Oh, so this is unavoidable :(
