### ISSUE TITLE
Bug: Weird scrolling behavior in nvim inside xterm

### ISSUE THREAD

**Issue by denismaxim0v** [zellij-org/zellij#263]
Steps to reproduce:
- Start zellij in xterm
- Open neovim
- Split vertically and open two files
- Scroll
![Screenshot from 2021-04-10 15-30-22](https://user-images.githubusercontent.com/11789381/114269863-dbf01d00-9a11-11eb-8589-aa051432b77d.png)
![Screenshot from 2021-04-10 15-32-31](https://user-images.githubusercontent.com/11789381/114269891-05a94400-9a12-11eb-9bc7-bd01ee078a4a.png)

**Comment by imsnif** [comment]
Hey @denismaxim0v, I think I'm familiar with this issue. Is it fixed once you resize the pane?

**Comment by imsnif** [comment]
@denismaxim0v - does this still happen in `0.10.0`?

**Comment by denismaxim0v** [comment]
> @denismaxim0v - does this still happen in `0.10.0`?

Yeah, still same behaviour

**Comment by denismaxim0v** [comment]
https://user-images.githubusercontent.com/11789381/118349704-ea72ac80-b55a-11eb-9d00-c170c8f356f7.mp4

**Comment by imsnif** [comment]
I somehow missed the fact that this is a neovim split and not a Zellij split :D I'll try to reproduce it next week and if I can't I'll ask for your help with log files.

**Comment by RobWalt** [comment]
@denismaxim0v Hey, I'm currently trying to work on some bugs and I want to help you here.

I also use nvim and it isn't happening in my instance :/

Is this issue still happening and if so, do you use any special plugins?

**Comment by denismaxim0v** [comment]
Hmm, seems like it's not happening anymore :D
