### ISSUE TITLE
`Ctrl s` is not cleared by `keybinds clear-defaults=true`

### ISSUE THREAD

**Issue by rikhuijzer** [zellij-org/zellij#2635]
After creating the following config

```kdl
keybinds clear-defaults=true {
    normal {
        // uncomment this and adjust key if using copy_on_select=false
        // bind "Alt c" { Copy; }
        bind "Ctrl g" { SwitchToMode "Locked"; }
        bind "Ctrl p" { SwitchToMode "Pane"; }
        bind "Ctrl h" { SwitchToMode "Move"; }
        bind "Ctrl b" { SwitchToMode "Tab"; }
        bind "Ctrl l" { SwitchToMode "Search"; }
        bind "Ctrl o" { SwitchToMode "Session"; }
    }
    <default `zellij setup --dump-config`>
}
```
Here, I've set tab mode to `Ctrl b`. And indeed after starting Zellij, `Ctrl b` goes into `Tab` mode instead of the usual `Ctrl t`. When pressing `Ctrl t`, nothing happens as it should when loading above config.

I've also set search mode to `Ctrl l`. However, after starting Zellij, `Ctrl s` is still linked to `Search` mode. So when pressing `Ctrl s`, the `Search` mode opens up. `Ctrl l` also opens the search mode at the same time.

Therefore, I suspect that `Ctrl s` is not cleared when setting `keybinds clear-defaults=true`.

**Basic information**

```sh
$ zellij --version
zellij 0.37.2
````

```sh
$ uname -av
Darwin [...] Darwin Kernel Version 22.5.0 [...] arm64
```

```sh
$ alacritty --version
alacritty 0.12.2
```

**Comment by imsnif** [comment]
Hey @rikhuijzer - just commenting quickly to give you a direction for tihs and https://github.com/zellij-org/zellij/issues/2634 - could it be that the various `shared` keybindings sections are interfering with your config? I know it can be a little confusing...

**Comment by rikhuijzer** [comment]
Hey Aram. Thanks. You're right. I've now blindly replaced all `Ctrl s` in the config and now it's indeed gone. I'll close this issue 😄
