### ISSUE TITLE
Get current mode?

### ISSUE THREAD

**Issue by nalply** [zellij-org/zellij#2636]
How can I get the current mode of ZelliJ?

I am thinking about writing a small script for a mini floating pane to always show the current mode. I have removed the status bar, so I don't know in which mode I am trying to recreate the status bar as a small floating pane. Perhaps too complicated?

I imagine something like `zellij action get-mode` which prints the mode Zellij is currently in.

**Comment by imsnif** [comment]
This is a bit hard to do on the CLI since there can be different clients connected to the same session and it's impossible for Zellij to identify them.

Our intention is for users to develop plugins to do these things: https://zellij.dev/documentation/plugin-api-events.html#modeupdate

**Comment by nalply** [comment]
Thanks, I understand. Closing.
