### ISSUE TITLE
[Feature Request] Allow keybindings to change configuration options

### ISSUE THREAD

**Issue by gondolyr** [zellij-org/zellij#2645]
# What?

I would like the ability to set keybindings in the configuration that modify the active session's configuration (or tab/pane). There should at least be a way to flip between Boolean values, though I'm not sure what the value of setting arbitrary string values (outside of enums) for options such as [`default_layout`](https://zellij.dev/documentation/options.html#default_layout) would be here. I think as an MVP for this feature, only Boolean options should be supported.

The `Ctrl z p` keybinding activates the [`TogglePaneFrames`](https://zellij.dev/documentation/keybindings-possible-actions.html#togglepaneframes) action, which is like toggling the [`pane_frames`](https://zellij.dev/documentation/options.html#pane_frames) option, though is built-in.

# Why?

I would like to toggle [`copy_on_select`](https://zellij.dev/documentation/options.html#copy_on_select) so that I can highlight text I've dumped with `cat`.

# Challenges

We probably wouldn't want to end up in a situation where a keybinding causes a recursive reconfiguration so maybe this feature should be limited in scope. Maybe it would be fine if it does happen?

# Related Issues

These are issues I've read that seem similar to my request.

- https://github.com/zellij-org/zellij/issues/1405
- https://github.com/zellij-org/zellij/issues/1646

**Comment by jaeheonji** [comment]
I think this can be resolved and closed.
* #3422
* #3556 
* #3558
