### ISSUE TITLE
Make `brown-slave` not one of the valid randomly generated names for a session

### ISSUE THREAD

**Issue by gamma-delta** [zellij-org/zellij#2676]
![image](https://github.com/zellij-org/zellij/assets/29877714/aa6da6df-775f-4a2b-b81e-09848390670a)

Yeouch!

**Comment by gamma-delta** [comment]
Huh, looking at the list of nouns it looks like `slave` isn't in there (thank god)

https://github.com/zellij-org/zellij/blob/main/src/sessions.rs#L303

Which is weird, because I'm on v0.37.2.

**Comment by gamma-delta** [comment]
... *huh*, it is one of the default words in the `names` crate but Zellij should be providing its own list.

https://github.com/fnichol/names/blob/main/data/nouns.txt#L770

Maybe I should go file a report on *their* repo but it is odd that it is using their list instead of the list you pass.

**Comment by gamma-delta** [comment]
The latest version of `names` is 0.14.1 and zellij is using 0.14.0 but it looks like it just bumps dependencies.

**Comment by tlinford** [comment]
This has been addressed in #2122. It's in main and will be included in the next release :)
