### ISSUE TITLE
[Question] linking windows from one session to the other?

### ISSUE THREAD

**Issue by ahmedelgabri** [zellij-org/zellij#2681]
My workflow in tmux relies heavily on linking windows between sessions, one shared session with common windows like mail, notes, etc… being linked to from the main sessions. This is done through scripting, the flow is roughly the following:

```shell
#!/usr/bin/env sh

if ! (tmux list-sessions | cut -d ':' -f 1 | grep -q ^"_shared"\$); then
  # Creating the detached shared session
  tmux new-session -d -s "_shared"

  # Creating a "mail" window inside the shared session & running the mail app
  tmux new-window -n 'mail'
  tmux send-keys "neomutt" C-m
fi

if ! (tmux list-sessions | cut -d ':' -f 1 | grep -q ^"$1"\$); then
  # Creating the main session
  tmux new-session -d -t "$1"

  # Linking the mail window from the shared session into a window inside the current session
  if tmux has-session -t _shared:mail 2>/dev/null; then
    tmux link-window -s _shared:mail -t 2
  fi

  tmux attach -t "$1"
fi
```

Then I can call this script, for example, like so `t my-session`, this will create the shared session if not already there & create a "my-session" session and link the mail window from the shared session inside "my-session"

If I run this again for a new session `t my-new-session`, it should do exactly the same thing as above, and now all three sessions will have the same "mail" window shared between them. Killing "my-session" or "my-new-session" **doesn't** kill the mail window, but killing the shared session does.

So I was wondering if Zellij can do this currently (looks like no, from my search) and if something like this might be on the roadmap?

**Comment by giyany** [comment]
I'm not a maintainer, but this sounds:
1. like a very cool feature...
2. which will make a beautiful plug-in.

Ultimately @imsnif will tell us which is which, but in the meantime I wanted to mention the Zellij plug-in system in case that's something you're interested in.

**Comment by imsnif** [comment]
Yes! We still need to add this capability to core (sharing panes between sessions) so that plugins will have them as wel, but this is definitely something I want to do.

**Comment by ahmedelgabri** [comment]
@giyany I'm aware of the plugin system but I dunno if this is still possible with a custom plugin or not, yet.

@imsnif that's great to hear! I will close the issue then since everything is clear now.
