### ISSUE TITLE
keyboard input is broadcasted to all panes.

### ISSUE THREAD

**Issue by ocehugo** [zellij-org/zellij#2684]
**Basic information**

`zellij --version`: 0.36.0
`rustc/cargo --version`: 1.67.1
`nvim --version`: v0.9.0

**Further information**

I usually have a pane for long neovim sessions with their built-in terminal. Sometimes I want to escape that pane by opening a new zellij pane in the same tab. Suddenly, after typing in the new pane, the input is sent to both the current active pane and the inactive/previous neovim pane. Surprisingly, closing the newly opened pane and triggering a new one does not fix the issue.  Opening a new pane (3rd) also produces the same problem - the input is now sent to three different panes. Exiting the neovim in the old pane while the second pane is open also does not fix the issue - any input is bound to all panes in this tab forever.

Hence, the problem is that the input ownership/handling to the correct pane is broken - probably when spawning a new pane. 
However, new panes on a newly created tab in the same session, are not affected. Also, moving between the defunc tab and a new vanilla tab does not solve the issue. Only one time I had two tabs with the same problem.

So far, I can detect this problem after spawning a new pane in some old tab. I didn't notice, yet, if it would happen after reattaching to a session/pane with more than one pane, and , after spawning or typing, the input would suddenly be broadcasted to all panes. I couldn't pinpoint the problem in the logs, but I noticed it usually happens in long-running zellij sessions/tabs. I usually got other zellij sessions running.

The symptoms do not look like a terminal input problem, but I tested it anyway by attaching to the session/tab in gnome-terminal(local), wezterm (via ssh/local), alacritty (local), and even windows terminal (via ssh).

Lastly, the only thing in the log is some warnings related to mouse events. They were emitted before or after I could detect the issue - not sure if they related, but I got some of those (as expected in normal usage, I guess):

```log
Caused by:
    0: failed to enable mouse mode
    1: Input/output error (os error 5)
INFO   |zellij_client            | 2023-08-07 20:49:40.652 [main      ] [/home/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-client-0.36.0/src/lib.rs:435]: Bye from Zellij!
INFO   |zellij_client            | 2023-08-08 09:20:40.804 [main      ] [/home/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-client-0.36.0/src/lib.rs:143]: Starting Zellij client!
WARN   |zellij_server::panes::gri| 2023-08-08 13:55:39.834 [screen    ] [/home/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.36.0/src/panes/grid.rs:2997]: Unhandled esc_dispatch: 61->[]
WARN   |zellij_server::panes::gri| 2023-08-08 13:56:19.704 [screen    ] [/home/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.36.0/src/panes/grid.rs:2997]: Unhandled esc_dispatch: 62->[]
WARN   |zellij_server::panes::gri| 2023-08-08 14:17:37.760 [screen    ] [/home/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.36.0/src/panes/grid.rs:2997]: Unhandled esc_dispatch: 61->[]
INFO   |zellij_server::plugins::w| 2023-08-08 14:17:44.832 [wasm      ] [/home/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.36.0/src/plugins/wasm_bridge.rs:259]: Bye from plugin 8
INFO   |zellij_server::plugins::w| 2023-08-08 14:17:44.832 [wasm      ] [/home/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.36.0/src/plugins/wasm_bridge.rs:259]: Bye from plugin 10
WARN   |zellij_server::panes::gri| 2023-08-08 14:36:47.260 [screen    ] [/home/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.36.0/src/panes/grid.rs:2997]: Unhandled esc_dispatch: 62->[]
WARN   |zellij_server::panes::gri| 2023-08-08 14:36:49.402 [screen    ] [/home/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.36.0/src/panes/grid.rs:2997]: Unhandled esc_dispatch: 61->[]
WARN   |zellij_server::panes::gri| 2023-08-08 14:45:48.715 [screen    ] [/home/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.36.0/src/panes/grid.rs:2997]: Unhandled esc_dispatch: 62->[]
WARN   |zellij_server::panes::gri| 2023-08-08 14:45:49.461 [screen    ] [/home/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.36.0/src/panes/grid.rs:2997]: Unhandled esc_dispatch: 61->[]
WARN   |zellij_server::panes::gri| 2023-08-08 14:45:51.179 [screen    ] [/home/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.36.0/src/panes/grid.rs:2997]: Unhandled esc_dispatch: 62->[]
WARN   |zellij_server::panes::gri| 2023-08-08 14:45:51.722 [screen    ] [/home/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.36.0/src/panes/grid.rs:2997]: Unhandled esc_dispatch: 61->[]
WARN   |zellij_server::panes::gri| 2023-08-08 16:04:09.553 [screen    ] [/home/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.36.0/src/panes/grid.rs:2997]: Unhandled esc_dispatch: 62->[]
ERROR  |???                      | 2023-08-08 18:37:07.245 [main      ] [/home/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-client-0.36.0/src/lib.rs:434]: a non-fatal error occured
``` 

Let me know the best way to track this - including flags or env vars that may be handy.

**Comment by imsnif** [comment]
Sounds to me like maybe you have tab sync mode on?

**Comment by ocehugo** [comment]
Nothing like being embarrassed by lack of knowledge of a feature available and visible in the tab options.  I need new glasses.

Thanks

**Comment by imsnif** [comment]
Please do not be embarrassed @ocehugo ! If you did not notice it, it's on us as UI designers and not on you. I believe tools are supposed to serve users, not the other way around.

So apologies for the confusion and I'm glad all is well for you in the end!

**Comment by ocehugo** [comment]
You are too kind but i should have read the docs! " It's a feature" is ringing in my head still hehe. I guess the defaults are so good that I didn't even touch it and since i never used thar feature in tmux here iam! Thanks for this awesome software.

**Comment by NorfeldtKnowit** [comment]
When I pressed `CTRL` + `t` it does seem to enter a sync mode (without showing that it's on). 
It took me some time to figure out how disable it (pressing the shortcut again) - so just sharing it here for others.
