### ISSUE TITLE
Zellij is not killed after the terminal quits

### ISSUE THREAD

**Issue by bq-wrongway** [zellij-org/zellij#2687]
When starting zellij in my foot terminal, i can see that two zellij instances spawn :

One is about 50MB and another one is <10MB, then i kill terminal window, ie, alt + q in my case.

What happens is that smaller process exits right away, but the 50 mb one stays alive, so i start new terminal, launch zellij, kill terminal, and zellij process that has 50MB stays alive, (and now are two of them, so over 100MB)

And this can go ad-nauseum, the only way is to

Im using popOS , and zellij 0.37.2

![Screenshot from 2023-08-09 21-07-03](https://github.com/zellij-org/zellij/assets/97843623/39998e31-b591-40a5-b3c5-b9c82bab5cb8)
![Screenshot from 2023-08-09 21-07-23](https://github.com/zellij-org/zellij/assets/97843623/9d8c0ee8-adda-49dd-bfac-cf8fdc574467)
![Screenshot from 2023-08-09 21-08-01](https://github.com/zellij-org/zellij/assets/97843623/f530d7fb-3cc8-4615-915f-cf690e73249d)
![Screenshot from 2023-08-09 21-08-07](https://github.com/zellij-org/zellij/assets/97843623/93447049-8209-49ff-b788-33dbea34f1fe)
 kill the process manually , either through system monitor, or with terminal command.

**Comment by Zykino** [comment]
I suppose (and I may be wrong here) that the one that stay is the server/session one. Once a terminal is killed and a 50MB offender stay, please try `zellij ls`. If there are 2 session, one of which having the old name, then my assumption is correct: the other session is not quit. Otherwise it may be a real bug :sweat_smile:

**Comment by bq-wrongway** [comment]
So i did try, i ran :
zellij (session was called guttural-trains) i quit the terminal, open new terminal, ran zellij ls, and in list there was session "guttural trains" . So session was not killed, is this bug, or is it some behaviour that i can correct ? 
Like, kill session on terminal exit, kind of thing

**Comment by Zykino** [comment]
It is a feature I’m afraid :sweat_smile:.

The background task is a session you can read a bit more [here](https://zellij.dev/documentation/overview), and by searching for "session" in the documentation website. This make it possible to connect multiple terminal to the same session (one from SSH for example), detach from a session, let the background tasks run and then re-attach to it later (some peoples use it to have their mail and/or IRC clients open in the background).

You can quit a session from within with `Ctrl+q` by default (its written in the bottom bar but the theme clash a bit so its strangely white). Or by exiting all the tabs & panes.

**Comment by bq-wrongway** [comment]
I found this in docs:

Choose what to do when zellij receives SIGTERM, SIGINT, SIGQUIT or SIGHUP eg. when terminal window with an active zellij session is closed

Options:

    detach (Default)
    quit

on_force_close "quit"

So il try to change default setting to quit
