### ISSUE TITLE
Shift + hover on link in panel combines selection with text in other panel

### ISSUE THREAD

**Issue by Bobby-Wan** [zellij-org/zellij#2718]
**Following the debug procedure, no zellij debug file/folder is created in the tmp directory (MacOS).**

 
**Basic information**

`zellij --version`: 0.37.2
`stty size`: 56 70
`uname -av` : Darwin bozhidara3MD6R.vmware.com 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 x86_64

`alacritty --version`: alacritty 0.12.2 (9d9982d)

**Further information**
Reproduction steps:
Create a layout with two panels split vertically.
Paste a long (multiline) url in the left panel.
If it overlaps with text in the right panel in just the right way, shift + hover over the left url selects text from the right panel as well.
Anything after the first line of the original url is not selected, only the first line in both panels.
 
 [Example here](https://imgur.com/2qSxZXx)

**Comment by imsnif** [comment]
Hey, thanks for opening this issue and going through the trouble of attaching a screenshot!

This issue however is not something Zellij can do anything about. As soon as you press shift, the mouse hover/click bypasses Zellij and goes to your terminal emulator (who in this case is in charge of marking the link with an underline, and does not know anything about Zellij).

In the future Zellij might add better hyperlink support in itself and then this will work out of the box without the need to press shift.

**Comment by Bobby-Wan** [comment]
I see what you mean. Thanks for the quick feedback!
