### ISSUE TITLE
Display glitched when switching sessions with session manager on windows with WSL

### ISSUE THREAD

**Issue by tranzystorek-io** [zellij-org/zellij#2736]
When creating a new session or switching to another existing one with the session manager, the display ends up in a broken state:

![obraz](https://github.com/zellij-org/zellij/assets/5671049/b725ba52-abfd-43f7-adc4-2176b993101d)

**In Case of Graphical or Performance Issues**

1. Delete the contents of `/tmp/zellij-1000/zellij-log`, ie with `cd /tmp/zellij-1000/` and `rm -fr zellij-log/` (`/tmp/` is `$TMPDIR/` on OSX)
2. Run `zellij --debug`
3. Run `stty size`, copy the result and attach it in the bug report
4. Recreate your issue.
5. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.

**Basic information**

`zellij --version`: `0.38.0`
`stty size`: `39 171`
`uname -av` or `ver`(Windows): `Linux DESKTOP-0QOMDS0 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 GNU/Linux`

List of programs you interact with as, `PROGRAM --version`:
`Windows Terminal Version: 1.17.11461.0`

**Further information**
Reproduction steps, noticeable behavior, related issues, etc

[zellij.log](https://github.com/zellij-org/zellij/files/12453193/zellij.log)

**Comment by tranzystorek-io** [comment]
THe issue does not reproduce on the `glitch-debug` branch, something in that specific commit (2929decac291ec0417e198ee3c15ad5732996215) prevents repro. Checked that the issue still reproduces on the previous commit (24ce348bb22730abd018ce9fa2fac2cb20f7c026)

**Comment by imsnif** [comment]
Thanks for testing it out @tranzystorek-io ! I tidied up that branch and added some stuff. Could you do me a favor and give it one more test to make sure it's still working?

Basically, I'm pretty sure the issue here is Windows Terminal not behaving properly when receiving a CSI ? 1049h (as I suspected in point 1 above). This issue works around it by not sending it on a reconnect (we don't need to anyway, it was just there to save some code).

**Comment by imsnif** [comment]
Once you confirm I'll merge the branch and release a patch version (along with some more minor fixes).

**Comment by tranzystorek-io** [comment]
I can confirm the new commit on the glitch-debug branch still works (does not reproduce) 😊

**Comment by imsnif** [comment]
Thanks for the super quick confirmation!
