### ISSUE TITLE
How to use with micro?

### ISSUE THREAD

**Issue by Akiyamka** [zellij-org/zellij#2737]
Unfortunately some console editors (like [Micro](https://github.com/zyedidia/micro)) use same bindings like `Ctrl + q`, `Ctrl + s` etc.
Possible solution:
Probably it would be better to add an additional keybind for switching to zellij. Like Alt+z - switch to mod when all zellij keybind works as usual, and alt+z again - disable all zellij binds except alt+z

**Comment by giyany** [comment]
Hi,

Thanks for opening the issue. Do you know about the locked mode with Ctrl+g? Is that perhaps helpful?

**Comment by Akiyamka** [comment]
@giyany thanks, that exactly what I looking for
