### ISSUE TITLE
Resized floating pane does not remember the size when embedded and then un-embedded again

### ISSUE THREAD

**Issue by marc-thieme** [zellij-org/zellij#2739]
For instance, I like to have a large floating pane for managing gh issues or something like that. I resize that to be very large. Sometimes, I need to do some more work in that pane and for that, I embed it as a large pane into the grid.

Now when this heavier work is finished, I un-embed the pane again and go back to my usual workflow. However, when I make it float again, it has the default size for a floating pane again instead of the larger size which I need for it.

Could we make a pane remember its floating size, even after being embedded? Can I do this using the config?

**Comment by imsnif** [comment]
Hey, thanks for reporting. I think you can achieve this using a "swap layout". Have you maybe tried using the built-in "enlarged" layout for floating panes? You can get to it (by default) with `Alt` + `]` until you're there when the floating panes are visible. Wdyt?

**Comment by marc-thieme** [comment]
Wow great feature, thank you I didn't know about that!

I'd still be curious about what you think about the size memory feature, but it's not important anymore. Issue resolved for me, thank you!
