### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by peteringram0** [zellij-org/zellij#2751]
Hi all, 

For some reason icons appear as question makers. Running OSX and version 0.37.2.

![Screenshot 2023-08-30 at 11 13 24](https://github.com/zellij-org/zellij/assets/6588942/ef9f9d97-2073-4af6-8008-2b9440087ec3)

This is most likely a local issue but what font do i need please?

**Comment by imsnif** [comment]
Hey, sorry this is not in a clearer place! This is addressed in our FAQ: https://zellij.dev/documentation/faq#i-see-broken-characters-in-the-default-ui-how-can-i-fix-this

**Comment by Darkcast** [comment]
which nerd font do one needs to install ? all of them ?
