### ISSUE TITLE
Support for connecitng to a TTY/COM (eg. /dev/ttyusb0)

### ISSUE THREAD

**Issue by k12ish** [zellij-org/zellij#2813]
Very new to Zellij, I'd like some way to connect to a serial port, but this doesn't seem to be a feature yet? This is implemented by `screen`:

```bash
screen /dev/ttyUSB0
```

Thank you for your work!!

**Comment by Zykino** [comment]
I think this is a duplicate of #2833. (I know this was first but some discussion already appeared there first.)

**Comment by k12ish** [comment]
Oh well, I'll close the issue then
