### ISSUE TITLE
session manager does not show all the sessions (list-sessions shows more)

### ISSUE THREAD

**Issue by tcoopman** [zellij-org/zellij#2816]
That's the bug:

![Screenshot_20230926_090820](https://github.com/zellij-org/zellij/assets/45546/1d69d436-b3d7-4abc-ab93-6ea1ebbbb891)

version: 0.38.2

**Comment by imsnif** [comment]
Any way to reproduce this?

**Comment by tcoopman** [comment]
I'll try to reproduce it and come back here

**Comment by tcoopman** [comment]
So I don't know exactly how to reproduce it yet, but I have it again:

![image](https://github.com/zellij-org/zellij/assets/45546/f0852e23-2ddd-4611-960e-11dc69644bde)

More information:
terminals: wezterm, konsole

The weird thing is that the when I try to attach to the session that's not in the session manager I get: 
```bash
➜ zellij attach vitreous-lemur

Received empty message from server
```

after that, this session is not listed anymore

**Comment by imsnif** [comment]
So, this sounds like a bit of a different issue to me. The session-manager has better checking of sessions, which is why it doesn't show "dead" sessions like these ones seem to be. Did they crash somehow? Can you tell me more about them?

**Comment by tcoopman** [comment]
I haven't seen this anymore, so I'm going to close this.
