### ISSUE TITLE
Garbled Output from from bpytop:

### ISSUE THREAD

**Issue by saintphaenixos** [zellij-org/zellij#282]
Hello,

I typically use a very graphical system monitor called [bpytop](https://github.com/aristocratos/bpytop).

When used in conjunction with Zellij, Zellij doesn't seem to be able to format the output appropriately and instead the output comes out garbled as bpytop attempts to refresh, so it can't display properly.

I've tested this in these terminals: [Gnome Terminal](https://help.gnome.org/users/gnome-terminal/stable/), [Terminology Terminal](https://www.enlightenment.org/about-terminology.md), and [st terminal](https://st.suckless.org/).

The result is the same in each.

-------------------------------

Steps to reproduce:

1. Install bpytop via `sudo pip3 install bpytop`
2. start `zellij`
3. run `bpytop`

------------------------------

Thank you for this program, I discovered it today, and I'm going to be making this a mainstay, I love how easy it is to use, and it looks great!

**Comment by TheLostLambda** [comment]
Yikes! Quite garbled indeed! Looks like some unhanded CSI codes on our part :slightly_smiling_face: 

I've attached a log of all of the missing codes for @imsnif or someone else to look at when they have the time! Thanks for reporting this!

[unhandled-csi-codes.txt](https://github.com/zellij-org/zellij/files/6344737/log.txt)

**Comment by saintphaenixos** [comment]
@TheLostLambda 

This has been dealt with with Version 0.6 Thank you! I'm a Zellij Loyalist now.

Closing issue.
