### ISSUE TITLE
Feature(Config): Create a Default Config File and Load from there

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#283]
Rework the way the default configuration is loaded:

Create a configuration file at the default location, if not already present.

**Comment by TheLostLambda** [comment]
I think this could both take some inspiration from the current system with layouts and also move those layouts to the config folder. Currently, YAML layouts are in the data directory with plugins (wasm), but the YAML layouts probably belong with the YAML config file :slightly_smiling_face:

**Comment by a-kenji** [comment]
Would it make sense to have both?

Make the layout callable by name, if it is in the config file.
And if it is a path, load it from the path?
And allow some form of compartmentalization by default?

Eg:
An optional /layouts subdirectory in the config directory, that way people can easily find and share certain layouts and still have some layouts in their config.

**Comment by TheLostLambda** [comment]
We could do that, but I might even lean towards @qballer 's suggestion from a while back, just to move everything into the XDG_CONFIG directory. That would make it easier to find for people who want to load their own plugins as well. Could just have one folder with the config, then `layouts/` and `plugins/`

What do you think? That's probably the easiest and clearest for users, but maybe not the most "correct" when it comes to following directory standards.

**Comment by qballer** [comment]
this structure under `~/.config`

zellij/
├── config.yaml
├── layout
└── plugins

**Comment by a-kenji** [comment]
Would this be still desirable then  #253 ? 
Or could it be closed?

**Comment by a-kenji** [comment]
From #290 :

- [ ] add an `env` variable
- [ ] change `config` subcommand to `--config` flag
- [ ] if multiple config flags are present, use the latter

**Comment by imsnif** [comment]
Has this been released?

**Comment by a-kenji** [comment]
Yes, I was using it to track a different issue.
I created it now so it is more explicit.

**Comment by Act0r1** [comment]
sorry guys, but I tried to unbind Ctrl p, but in doesn't work, I also add  ` delete_default_keybindings: true` in pane also in normal mode, nothing happen

**Comment by imsnif** [comment]
Hey @Act0r1 - we moved to a new configuration format. For unbinding keys, you can check out: https://zellij.dev/documentation/keybindings-binding.html#overriding-keys
