### ISSUE TITLE
Feature: cli actions: query panes; go-to pane by name or id; query

### ISSUE THREAD

**Issue by fedoranvar** [zellij-org/zellij#2835]
Good day to you!

suggesting features for zellij action:

* query tabs: 
input: `zellij action query-tabs`
output:  `
{
'id': tabid,
'name':  'tabname',
'active': active_or_not
}
`
* query  panes: 
input: `zellij action query-panes`
output:  `
{
'id': paneid,
'name':  panename,
'active': active_or_not,
'tabid': tabid,
'command': currentcommand
}
`
* go-to pane: 
input: `zellij action go-to pane --name pane_in_currentab`
output:  focus named pane in current tab

usecase: make IDE by bonding zellij and Helix editor

**Comment by azarmadr** [comment]
It would be great such api to query current pane and allow other apps/scripts to use that knowledge to perform actions like, on active pane do not do X

**Comment by davxy** [comment]
Related: https://github.com/zellij-org/zellij/issues/2779 https://github.com/zellij-org/zellij/issues/2845

**Comment by mrdgo** [comment]
Another use case: I integrate zjstatus with neovim. For that, the zjstatus module needs to identify the active pane to render the appropriate status line.

**Comment by imsnif** [comment]
All of these can be done with plugins. This is the Zellij way.

I realize a lot of people are used to doing these things through the CLI - I get it and I totally empathize: this is not the Zellij way. We concentrate on plugins so that distinct pieces of logic will be cross-platform, require no installation, be aware of multiple users, be able to in the future render themselves in a text/ui agnostic way and be sandboxed to user permissions.

The CLI interface is a stop gap solution and I don't want to spend a lot of time expanding it. Please write plugins - I will do (and am doing) everything in my power to make this as easy as possible.

Thanks.

**Comment by WizardUli** [comment]
> All of these can be done with plugins. This is the Zellij way.
> 
> I realize a lot of people are used to doing these things through the CLI - I get it and I totally empathize: this is not the Zellij way. We concentrate on plugins so that distinct pieces of logic will be cross-platform, require no installation, be aware of multiple users, be able to in the future render themselves in a text/ui agnostic way and be sandboxed to user permissions.
> 
> The CLI interface is a stop gap solution and I don't want to spend a lot of time expanding it. Please write plugins - I will do (and am doing) everything in my power to make this as easy as possible.
> 
> Thanks.

The last one absolutely cannot be done via plugins!
Plugin API is completely missing `go_to_pane_name` or any alternative whatsoever. (Yes I read https://zellij.dev/documentation/plugin-api-commands)

**Comment by imsnif** [comment]
> The last one absolutely cannot be done via plugins! Plugin API is completely missing `go_to_pane_name` or any alternative whatsoever. (Yes I read https://zellij.dev/documentation/plugin-api-commands)

Check out https://zellij.dev/documentation/plugin-api-commands#focus_terminal_pane and https://zellij.dev/documentation/plugin-api-commands#focus_plugin_pane

**Comment by imsnif** [comment]
You are more than welcome to ask help on our Discord or Matrix if you're not sure how to do something (better Discord tbh because more plugin authors hang out there).
