### ISSUE TITLE
How do I programmatically open couple of panes and run command on them

### ISSUE THREAD

**Issue by honzajde** [zellij-org/zellij#284]
How do I programmatically open couple of panes and run commands on them

**Comment by TheLostLambda** [comment]
If you mean loading a layout that runs certain commands in certain panes, that's not quite implemented yet, but is something I've been meaning to add for a while!

Is that the sort of thing you were thinking of?

**Comment by honzajde** [comment]
@TheLostLambda that is exactly what I meant :)
