### ISSUE TITLE
Copy mode like Tmux

### ISSUE THREAD

**Issue by BillyLiou** [zellij-org/zellij#2840]
Can I use copy mode like tmux?

I checked the configuration file but did not see any relevant settings.
This feature is very useful, thank you.

**Comment by imsnif** [comment]
Hey, the Zellij way of doing this is using your own `$EDITOR` (eg. vim). You can edit your scrollback with `Ctrl s` + `e` and then copy/paste anything you like with it like you would any other text file. We feel this is a better solution than re-implementing all of vim/emacs/helix/etc.

**Comment by BillyLiou** [comment]
It works, thanks.
