### ISSUE TITLE
Will zellij come to windows?

### ISSUE THREAD

**Issue by leet0rz** [zellij-org/zellij#2843]
PLEASE!

**Comment by imsnif** [comment]
Duplicate of https://github.com/zellij-org/zellij/issues/316... I also see you already commented there, so not entirely sure why you opened a new issue.

**Comment by leet0rz** [comment]
> Duplicate of #316... I also see you already commented there, so not entirely sure why you opened a new issue.

In hopes that you'll pull through with support for windows, many of us need it.
