### ISSUE TITLE
Compatibility: Shellcaster(Pancurses)

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#285]
I get following output in zellij:
![image](https://user-images.githubusercontent.com/65275785/115435171-d9f43e00-a209-11eb-83ba-2237a10330e6.png)
instead of:
![image](https://user-images.githubusercontent.com/65275785/115435250-f001fe80-a209-11eb-9213-280544d84cf1.png)

I suspect it might also be some unhandled sequence, here are the logfiles:
[log.txt](https://github.com/zellij-org/zellij/files/6345317/log.txt)
[zellij-3.log](https://github.com/zellij-org/zellij/files/6345321/zellij-3.log)

**Comment by a-kenji** [comment]
Fixed as of `0.6.0`

**Comment by a-kenji** [comment]
Sadly false alarm, but somehow running 
zellij inside tmux fixes that, maybe that helps with debugging.

**Comment by a-kenji** [comment]
The gui thing is fixed as of `0.7.0`, which is awesome!
But sadly the colors are still different.
![image](https://user-images.githubusercontent.com/65275785/116915229-0c5f5b80-ac4c-11eb-93ba-767eee5a1d3d.png)
vs
![image](https://user-images.githubusercontent.com/65275785/116915304-20a35880-ac4c-11eb-9f16-21d84cec5d3f.png)

**Comment by a-kenji** [comment]
The colors are still equal to the 2nd image on the current main: `0.9.0`.

**Comment by imsnif** [comment]
@a-kenji - I think I found (at least part of) the issue. I merged a fix to main, could you give it a try when you have the chance?

**Comment by a-kenji** [comment]
Thank you! This fixed the issue with Shellcaster.
