### ISSUE TITLE
Feature(Config): Emulate Screen Default Keybindings.

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#286]
We want to provide sane defaults for people, 
so having a configuration file that emulates the screen config makes sense.
Inspiration in `/example/config.yaml` and `example/default.yaml`,
as well as the keybindings [documentation]( https://zellij.dev/documentation/keybindings.html).
`/example/screen.yaml` could be a suitable location.

**Comment by SaintFenix** [comment]
I'll go ahead and take this on as an assignment. @a-kenji

**Comment by a-kenji** [comment]
Awesome!
