### ISSUE TITLE
Zellij crash:  message: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by vezult** [zellij-org/zellij#2860]
**Basic information**

**zellij --version**: zellij 0.38.2
**stty size**: 62 239
**uname -av**: Linux zapazoid 6.1.0-12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.52-1 (2023-09-07) x86_64 GNU/Linux

**Further information**

As best I can remember, I had multiple split panes on my current tab, some
vertical, some horizontal.  I was working in a terminal...I think using "less"?

A crash of this sort (details unknown) happens to me with some
frequency...maybe once or twice a week. I run 3 zellij instances 24/7 and use
it actively at least 8h/day 5 days out of 7. So, it's not super frequent, but
since it always loses state and sometimes interrupts long running
processes...it's enough to be quite noticeable. It seems as if it's been a
"recent" phenomenon, perhaps since 0.35? (I'm guessing). I don't remember
encountering this, at least with enough frequency to think much of it, until
maybe the last month or three. This is the first time I tracked down the log and
looked up the traceback.

[bug.log](https://github.com/zellij-org/zellij/files/12910361/bug.log)

**Comment by imsnif** [comment]
Fixed in https://github.com/zellij-org/zellij/pull/2972 - sorry for the experience and thanks for the report!

**Comment by vezult** [comment]
Exellent. Thanks for fixing this so quickly!
