### ISSUE TITLE
Feature: minimal layout option (tmux-like)

### ISSUE THREAD

**Issue by Solarunit** [zellij-org/zellij#2864]
There is a `simplified_ui` option but UI still looks very busy: we have 2 panels with shortcut tips at the bottom.

I suggest to add another option, let's call it "minimal layout". It would look similar to tmux with a single panel with tabs and other useful info (no tips)

**Comment by imsnif** [comment]
How about the `compact` layout?

More info here: https://zellij.dev/documentation/faq#the-ui-takes-up-too-much-space-what-can-i-do-about-it

**Comment by Solarunit** [comment]
> How about the `compact` layout?

Yea, this is close, I missed it.

![zellij](https://github.com/zellij-org/zellij/assets/20891064/efc39a98-cf0a-4b6d-9500-1642c92edb34)

 - I like `NORMAL` mode indicator :+1: Maybe move to to the right side.
 - for me `VERTICAL` indicator is not that usefull
 - I would like to hide Zelij text, to allocate more space for other stuff
 - auto-generated session name is too long, I would prefer to have just number by default
 - tabs names could be generated like in tmux:

![tmux-tabs](https://github.com/zellij-org/zellij/assets/20891064/b80fdfa6-f93f-48c1-9fc7-9a30e654b891)

**Comment by imsnif** [comment]
Hey, sure. Those are some nice suggestions.

I would suggest you look into our [plugin system](https://zellij.dev/documentation/plugins) which will allow you to implement this in whichever way you like and even share this with others.

Another option which might interest you is to look into [zjstatus](https://github.com/dj95/zjstatus) which is a configurable status-bar for Zellij.

I'm sorry to be so dismissive, but if this project implements the UI (even in a configurable fashion) to everyone's liking, this is what we'd spend our time doing. And, well - tmux already exists. I don't want to re-create it.
