### ISSUE TITLE
Compatibility: Bash in Zellij Ctrl-L / Arrows not working

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#287]
This could also have to do with the nix bash shell.
Possibly related to #281.

I tried different shells with zellij to try to reproduce 281 on linux.
In Bash I get the following problem:
I tried Ctrl+L for a bit.
And Arrows for a bit.
They seem to not be handled. Does the PS1 interferere here possibly?
$`echo $PS1` 
> \n\[\033[1;32m\][\[\e]0;\u@\h: \w\a\]\u@\h:\w]\$\[\033[0m\]

[zellij-3.log](https://github.com/zellij-org/zellij/files/6346357/zellij-3.log)

GNU bash, version 4.4.23(1)-release

**Comment by dejj** [comment]
ZelliJ doesn't passthru Ctrl+ArrowKeys. Using zsh.

Steps:
1. Lock zellij with Ctrl+G
2. Enter some text with spaces
3. Try to move cursor by word with Ctrl+LeftArrow, Ctrl+RightArrow

Expected: Cursor moves between words

Actual: No cursor movement

**Comment by a-kenji** [comment]
* `0.6.0` 
Fixes the Crl+L for me

**Comment by SaintFenix** [comment]
I can confirm @dejj's issue with zsh. it is the same for me in `0.6.0`

**Comment by imsnif** [comment]
This is fixed in `0.10.0`. Closing this issue, but if I'm wrong and this doesn't fix it for you, please tag me and I'll reopen.

**Comment by dejj** [comment]
I confirm fixed. Thank you.
Was this the change: https://github.com/zellij-org/zellij/compare/forward_unknown_keys ?

**Comment by imsnif** [comment]
It was, yes :)
