### ISSUE TITLE
Feat?: create and toggle a floating pane with a specific name

### ISSUE THREAD

**Issue by mostafaqanbaryan** [zellij-org/zellij#2874]
I know that I can open a new floating pane. But I think I can't focus on a floating pane with name.
I want to open `lazygit` on a floating pane and after that in that tab, I would toggle the floating pane with a key bind, without closing `lazygit`.

Summary: a way to create a floating pane with a specific name and focus on it, all with a single key combination.

(I don't know much rust, but I think I can tackle this one if not already implemented)

**Comment by mostafaqanbaryan** [comment]
@imsnif If it's Ok, I like to work on this (FocusOrCreatePane)

**Comment by mostafaqanbaryan** [comment]
> Hey, I think you can do this with a [plugin](https://zellij.dev/documentation/plugins)

Yes, that's possible.
But I thought it could be implemented inside zellij, as it's (imho) a main feature.
I'm gonna work on that plugin for now.
Thank you.

**Comment by imsnif** [comment]
I totally get you, but "inside zellij" means "I will have to maintain it" and there's quite a bit of those already. Trying to minimize them and still give people the functionality they wants. Good luck!

**Comment by mostafaqanbaryan** [comment]
> I totally get you, but "inside zellij" means "I will have to maintain it" and there's quite a bit of those already. Trying to minimize them and still give people the functionality they wants. Good luck!

I totally get that.
Didn't mean it as an insult or something.
Thank you for all the great works you're doing!

**Comment by jorgerojas26** [comment]
I would love this feature, it is essential for my workflow to have multiple floating panes opened, i need the ability to toggle their visibility with keybindings.
