### ISSUE TITLE
Hard crash after panel switch via Alt+h

### ISSUE THREAD

**Issue by laubblaeser** [zellij-org/zellij#288]
I've just started to try out zellij and encountered a hard crash.  
I had one wide panel on top row and two panels on bottom row. Bottom right was active and I wanted to switch to bottom left via `Alt+h`. This is the stacktrace:

```rust
Originating Thread(s):
1. stdin_handler_thread: AcceptInput
2. pty_thread: SpawnTerminal
3. stream_terminal_bytes: AsyncTask
4. screen_thread: HandlePtyBytes

Error: thread 'screen' panicked at 'called `Option::unwrap()` on a `None` value': /home/laubblaeser/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-0.5.0/src/client/panes/grid.rs:609
   0: zellij::common::errors::handle_panic
   1: std::panicking::rust_panic_with_hook
             at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:495:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /build/rust/src/rustc-1.51.0-src/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /build/rust/src/rustc-1.51.0-src/library/core/src/panicking.rs:92:14
   6: core::panicking::panic
             at /build/rust/src/rustc-1.51.0-src/library/core/src/panicking.rs:50:5
   7: vte::Parser::perform_action
   8: <zellij::client::panes::terminal_pane::TerminalPane as zellij::client::tab::Pane>::handle_pty_bytes
   9: std::sys_common::backtrace::__rust_begin_short_backtrace
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /build/rust/src/rustc-1.51.0-src/library/alloc/src/boxed.rs:1521:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /build/rust/src/rustc-1.51.0-src/library/alloc/src/boxed.rs:1521:9
      std::sys::unix::thread::Thread::new::thread_start
             at /build/rust/src/rustc-1.51.0-src/library/std/src/sys/unix/thread.rs:71:17
  12: start_thread
  13: clone
```

If you need any more info, I'd be glad to help out.

Edit: I use Konsole and zsh, if that's of any interest.

**Comment by imsnif** [comment]
Thanks for the report, and I'm sorry for this experience! I'm issuing a quickfix for this. I'm not sure what was running in the terminal, but this is likely an edge case that we did not handle well. Does this happen consistently?

**Comment by laubblaeser** [comment]
> not sure what was running in the terminal

Nothing special to be honest: Bottom right was running an idle Julia REPL, bottom left was running bare zsh in ~ at that moment iirc.

> Does this happen consistently?

I've tried to recreate that bug but couldn't make it happen so far, sorry.

By the way, my first impression with zellij (which is also the first time I actually try out a multiplexer after reading about them countless times) is pretty good. I like that there are a few hints on how to navigate and modify the panels. Everything feels pretty natural so far but it's still a bit weird because so far I was only every using the tabs in Konsole to do multiple terminal actions at the same time. So thank you, your work is much appreciated.

**Comment by imsnif** [comment]
My feeling is that this was very much a fluke, but it shouldn't happen again once we merge this fix.

I'm very happy to hear you like Zellij! Hopefully the experience will be smoother from here. :) With your permission may I close this issue?
