### ISSUE TITLE
Forgets old sessions exist?

### ISSUE THREAD

**Issue by Lamby777** [zellij-org/zellij#2892]
**Basic information**
Once in a while, I'll go back on my server to do crap and when I try to connect to a session or do `zellij ls`, it says there aren't any sessions open. The system reports no reboots or anything like that. I tried changing that one setting that prevents ssh users from having long-lasting sessions a while ago, and thought that fixed things, but the issue just happened again today. Really don't know where else to look for possible explanations, and as far as I can tell, GNU screen doesn't have this issue (could be wrong) so I think it may be a zellij problem.

To be clear, the sessions are still there. I see them on `htop` and when you visit the site in a browser, everything from the server is sent back the same as usual. It's just as if zellij has forgot that such a session exists.

Here's an htop pic for context (zellij session name is `sx` so it def still exists somewhere):
![image](https://github.com/zellij-org/zellij/assets/35111165/bcbc2c48-8bf7-4080-95b1-b811f9039bd3)

`zellij --version`: zellij 0.38.2
`stty size`: 42 174
`uname -av` or `ver`(Windows):
```Linux sheepytea 6.4.0-4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.4.13-1 (2023-08-31) x86_64 GNU/Linux```

List of programs you interact with as, `PROGRAM --version`:
Neovim:
```
NVIM v0.9.1 (used the appimage release)
```

Docker:
```Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:16 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Further information**
Absolutely no idea how to reproduce this, sadly, but it keeps happening occasionally. Will include more stuff if you guys have any ideas for getting it to happen consistently.

Edit: The old sessions don't show up in zellij's session manager (`<C-o>` + `w`).

**Comment by imsnif** [comment]
Off the top of my head, this sounds like the socket files (unix sockets used to communicate between a detached session and a virtual "client") are being deleted for some reason. Do you see them in your `XDG_RUNTIME_DIR` when this happens?

**Comment by imsnif** [comment]
This is how we keep track of them :)

But I see there seems to have been a version upgrade on the machine... Zellij cannot attach to sessions from an old version. Could this be the issue?

**Comment by Lamby777** [comment]
Probably. It says the last snap refresh was 24 days ago, which is within a reasonable time span (I don't log into this server much, only for occasionally messing around with web or MC server stuff). Thanks for picking up on that.

![image](https://github.com/zellij-org/zellij/assets/35111165/921f8a14-4014-4deb-9125-4e9dd2c2a713)

Closing, but will open if this ends up happening again on the same version. Also, I don't know how complicated this might be for zellij, but would it be possible to warn if folders for sockets on an older zellij version are found? Would really help others having this same issue, if there are any.
