### ISSUE TITLE
how can i paste from remote ssh

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [zellij-org/zellij#2895]
hi, my target os is debian, with xfce and xclip installed.

i did as https://zellij.dev/documentation/faq and https://zellij.dev/documentation/configuration#where-does-zellij-look-for-the-config-file

when i login to debian locally, i run

```sh
echo $XDG_SESSION_TYPE
x11
```

my zellij config

```kdl
copy_command: "xclip -selection clipboard"
```

it works fine.

but when i login with ssh

```sh
ssh root@xx.xx.xx.xx
```

```sh
echo $XDG_SESSION_TYPE
tty
```

zellij told me it has copied, not actually not successful.

my terminal emulator is "Terminator"

how can i paste from remote ssh?

my os is manjaro, remote target is debian

**Comment by romange** [comment]
@ziyouchutuwenwu  did you figure out how to copy from remote ssh?
