### ISSUE TITLE
Add close-on-exit option to keybinding actions "Run"

### ISSUE THREAD

**Issue by hellocode808** [zellij-org/zellij#2900]
in my `config.kdl` I have the following

```
session {
// ...
        bind "j" {
            Run "/Users/rafael/bin/zj" {
                floating true
            }
            SwitchToMode "Normal";
        }
}
```

The script `zj` runs a fzf prompt and opens up a new zellij tab with a layout depending on input. This runs fine. 

But my problem is that the floating pane stays open after the command is finished. Would it be possible to add an option like the `--close-on-exit`?

Also `--name` would be nice to have.

**Comment by astral-l** [comment]
You can add `close_on_exit true` to the run options underneath `floating true`:

```
session {
// ...
        bind "j" {
            Run "/Users/rafael/bin/zj" {
                floating true
                close_on_exit true
            }
            SwitchToMode "Normal";
        }
}
```

**Comment by hellocode808** [comment]
Great, thank you.
