### ISSUE TITLE
Feature(Config): Check XDG Config Directory on Mac

### ISSUE THREAD

**Issue by ocboogie** [zellij-org/zellij#291]
Most people on Mac wouldn't actually use the `~/Library/Application Support` directory but rather `~/.config` (see https://github.com/xdg-rs/dirs/issues/45). This allows people to use their dotfiles on Linux and Mac. We could either make a breaking change and not use `~/Library/Application Support` or we could check both directories for the config file. However, if we go the route of #283, there would have to be a decision to make: create the default config in  `~/Library/Application Support` or `~/.config`.

Related:
https://github.com/xdg-rs/dirs/issues/45
#283

**Comment by qballer** [comment]
I'm for r ~/.config

**Comment by a-kenji** [comment]
@ocboogie 

This check should be now on main, can you please confirm that it works? 
It checks after `/Users/Alice/Library/Application Support/org.Zellij-Contributors.zellij`,
so if you have that directory it will still load from there.
