### ISSUE TITLE
FR: Retain cwd when drop to shell

### ISSUE THREAD

**Issue by ichirou2910** [zellij-org/zellij#2910]
When a session is restored after machine shutdown, all panes with a running command (e.g. nvim) would become a command pane where the user is prompted to run again, drop to shell or exit. Is it possible to configure so that the "drop to shell" option would retain the cwd of the pending command instead of the default $HOME folder?

**Comment by andresatierf** [comment]
@imsnif This is not working as expected. Dropping to shell is going to the cwd where the session was open, not the cwd of the pending command. I think that the pending command cwd would be a better solution.
