### ISSUE TITLE
Can't attach to the session when getting the name programmatically

### ISSUE THREAD

**Issue by tukanoidd** [zellij-org/zellij#2912]
**Basic information**

`zellij --version`:  0.40.0 (using a nix flake that gets master)
`stty size`: ?
`uname -av` or `ver`(Windows): Linux zbook 6.5.9 #1-NixOS SMP PREEMPT_DYNAMIC Wed Oct 25 10:16:30 UTC 2023 x86_64 GNU/Linux

**Further information**
When using `zellij ls`, i get a list of sessions, including exited ones. I wrote a nushell snippet that would allow me to automatically attach an exited session if one found:

```
if not ('ZELLIJ' in $env) {
  let exited_sessions = zellij ls | split row "\n" | filter {|session| $session | str contains "EXITED"}

  if ($exited_sessions | is-empty) {
    zellij
  } else {
    let session_to_attach = $exited_sessions | get 0 | split row ' ' | get 0 | str trim
    zellij attach -c $session_to_attach
  }
}
```

When running those commands separately I get the right exited session name if one exists. But the problem is that zellij tells me that it can't find the session with exact same name (without -c flag) or creates a new session with exactly the same name (with -c flag), while running the command manually with the same name works just fine.

Example:
![image](https://github.com/zellij-org/zellij/assets/45230259/06a82bf3-df72-49bd-93dc-839aaca7b37e)
![image](https://github.com/zellij-org/zellij/assets/45230259/ebde0e90-f75a-4e0a-bccb-09458560c1f6)
![image](https://github.com/zellij-org/zellij/assets/45230259/0cf0b97a-db35-42ac-8ddc-7d824232c121)
----------------------------------------------
![image](https://github.com/zellij-org/zellij/assets/45230259/7cbb36e9-f295-44ee-adad-ad43960253b6)
![image](https://github.com/zellij-org/zellij/assets/45230259/f5c1a890-fa7f-4695-b67b-7f1b35736028)

I got no idea what im doing wrong, thanks for the help!

**Comment by tukanoidd** [comment]
Ok, sorry, my bad, apparently i had to append the command with [ansi strip](https://www.nushell.sh/commands/docs/ansi_strip.html) to get rid of the color codes that I didn't realize were there

**Comment by imsnif** [comment]
You could also use the `--no-formatting` flag and we'll do this for you :)

**Comment by tukanoidd** [comment]
> You could also use the `--no-formatting` flag and we'll do this for you :)

Oh, must've missed it, thanks for letting me know!
