### ISSUE TITLE
[Feature Request] Support prefix based key bindings

### ISSUE THREAD

**Issue by vihu** [zellij-org/zellij#2917]
Hello,

I actually really like zellij, but the one thing which keeps me from using it and stick to tmux is the keybindings. I understand I can easily remap all the keybindings but I was wondering if the team would consider having a prefix based keybind (similar to tmux basically). This way the transition (and muscle memory overhead) from tmux would be minimal, the keybinds won't conflict with the terminal/vim/nvim either.

Cheers!

**Comment by Ajlow2000** [comment]
Maybe add your thoughts here? #2890

**Comment by vihu** [comment]
Closing because #2890 raises the same concern.
