### ISSUE TITLE
Opening up lots of panes messes up the bottom bar

### ISSUE THREAD

**Issue by asg0451** [zellij-org/zellij#292]
hold down alt-n for a while to load up a bunch of panes, the bottom bar gets messed up. after deleting most of the new panes, it remains messed up
![image](https://user-images.githubusercontent.com/4358545/115479662-e6cb5e80-a216-11eb-95d9-9fd76b16ebe7.png)

![image](https://user-images.githubusercontent.com/4358545/115479737-0ebac200-a217-11eb-9edd-d68553194747.png)

Ubuntu 20.04, alacritty

**Comment by luqmanishere** [comment]
Can confirm this happens:
![2021-04-21_100307_xps-arch](https://user-images.githubusercontent.com/82690512/115486558-7e699500-a289-11eb-86d6-8eedb9b48f3d.png)

Here's after clearing all the panes and leaving only one:
![2021-04-21_101133_xps-arch](https://user-images.githubusercontent.com/82690512/115486839-0780cc00-a28a-11eb-8821-2752ac65a706.png)

Creating a new tab opens a tab with the statusline intact:
![2021-04-21_101340_xps-arch](https://user-images.githubusercontent.com/82690512/115486952-4282ff80-a28a-11eb-9892-35ee153bc706.png)

But the messed up tab remains messed up:
![2021-04-21_101526_xps-arch](https://user-images.githubusercontent.com/82690512/115487075-8249e700-a28a-11eb-83b3-92a569733f8d.png)

Arch Linux, kitty

**Comment by imsnif** [comment]
Thanks for the report, good catch!
I issues a fix for this: https://github.com/zellij-org/zellij/pull/314
I imagine we'll release a version with this fix and some other bug fixes sometime this week.

**Comment by asg0451** [comment]
no problem! I'm interested in what you guys are doing here -- I'm a tmux fanatic and a rust fanboy. I'm a little intimidated by the organization / newness of zellij's keybindings right now

anyway keep up the good work

**Comment by imsnif** [comment]
I can definitely relate! It is theoretically possible to configure Zellij to act just like tmux in regards to keybindings, though it might be a bit of work to create such a config file. We have an issue open for it: https://github.com/zellij-org/zellij/issues/225, so maybe someone will pick it up.

**Comment by imsnif** [comment]
Fixed in 0.5.1
