### ISSUE TITLE
Feature Request: Add option to pull focus onto pane by hovering over it within a tab

### ISSUE THREAD

**Issue by alexipeck** [zellij-org/zellij#2927]
As an example, I would link to the behavior within a workspace of the Sway Window Manager, where hovering over any pane in a workspace pulls focus.
It may not match the keyboard navigation of the program. But I would love to see it added.

**Comment by wis** [comment]
As far as I know, it is not possible for a terminal program like Zellj to listen for mouse move/hover events over a text area in the terminal, but clicks, it is possible for a terminal program like Zellj to detect.

**Comment by alexipeck** [comment]
This makes sense, I'll just continue using it as is then.
Thanks for following up

**Comment by imsnif** [comment]
To be fair it actually is possible with the AnyEvent variant of the xterm mouse-mode. I hope to add support for this in the future. There are probably other issues for this though...
