### ISSUE TITLE
Feature Request: Binary Space Partition option for NewPane

### ISSUE THREAD

**Issue by siukalov** [zellij-org/zellij#2932]
The NewPane command opens a pane in the largest available space when used without arguments. I propose adding an option, "BSP," for binary space partitioning similar to window managers([yabai](https://github.com/koekeishiya/yabai), [bspwm](https://github.com/baskerville/bspwm)).

**Comment by wis** [comment]
if you have `w` for example currently bound to open new pane, bind it to always open on the left `bind w { NewPane "Left"; }` and bind `W` to always open below `bind W { NewPane "Down"; }`,
then you can alternate each time you open a new pane between them to manually binary space partition yourself:

https://github.com/zellij-org/zellij/assets/9993663/99ec7cc8-3410-4556-9300-3e56eb6931a3

**Comment by siukalov** [comment]
@wis, this looks like a good enough solution to me, thanks
