### ISSUE TITLE
theming idea is really bad

### ISSUE THREAD

**Issue by gmate8** [zellij-org/zellij#2933]
current approach "logically forces" users assign specific colors to a set of colors. we all know that it definitely isn't a correct way to theme an app!

```kdl
themes {
    nord {
        fg "#D8DEE9"
        bg "#2E3440"
        black "#3B4252"
        red "#BF616A"
        green "#A3BE8C"
        yellow "#EBCB8B"
        blue "#81A1C1"
        magenta "#B48EAD"
        cyan "#88C0D0"
        white "#E5E9F0"
        orange "#D08770"
    }
}
```

all other apps apply the "label-based" theming approach which is much better and explicit to customize, i.e:

```kdl
themes {
   nord {
        main_fg "#D8DEE9"
        main_bg "#2E3440"
        
        statusline_fg "#D8DEE9"
        statusline_bg "#88C0D0"
        
        current_selected_item_fg "#D8DEE9"
        current_selected_item_bg "#A3BE8C"
        
        // other elements and parts for ui
        // ...
    }
}
```

**Comment by gmate8** [comment]
@imsnif

please check vim or vscode theme to know that i meant

**Comment by imsnif** [comment]
Duplicate of https://github.com/zellij-org/zellij/issues/2297

Also: please don't @ me unless it's urgent or I have previously participated in the discussion. There's a lot going on this repository and I need to be able to prioritize.
