### ISSUE TITLE
Very long compilation time for Zellij

### ISSUE THREAD

**Issue by ondrej-ivanko** [zellij-org/zellij#2942]
Hi,

I couldn't find similar issue here. I just noticed since I think v39.0, the compilation times for Zellij become unbearably long. From maybe 2-3 mins to about 13-15mins. I regularly update my Zellij, so this can be issue with latest releases.

I would like to know if anyone had the same experience. It might be that I'm compiling Zellij bin inside Zellij terminal, but I haven't had issue like this before.

**Comment by jaeheonji** [comment]
My current system is as follows.
* CPU: 13th Gen Intel i5-13600KF
* Memory: 32GB
* OS: Windows 11 WSL2

For me, compilation time on WSL's Arch system is about 1-2 minutes. As you already said. Unfortunately, I haven't seen any cases like yours. So, at this point I think there is a problem with your environment. 😓
