### ISSUE TITLE
simplified_ui not working?

### ISSUE THREAD

**Issue by ixzh** [zellij-org/zellij#2944]
Thanks for the recent update. Great to see it is getting better. 

However after updated to 0.39.1, I have these helping commands persistent regarless of the simplified_ui set to true on MacOS. Strangely on linux these are not shown. How can I hide them?

<img width="1139" alt="image" src="https://github.com/zellij-org/zellij/assets/14981695/3b6a4a84-6ec6-4701-8be2-700437431a8e">

**Comment by jaeheonji** [comment]
The `simplified_ui` is an option to disable specific glyphs such as triangle.
If you want to hide help message, there are two options.

1. change the pane size from 2 to 1 in `default.kdl`

**Comment by jaeheonji** [comment]
The `simplified_ui` is an option to disable specific glyphs such as triangle.
If you want to hide help message, there are two options.

1. change the pane size from 2 to 1 in `default.kdl`.
```
layout {
    pane size=1 borderless=true {
        plugin location="zellij:tab-bar"
    }
    pane

    // change this! 2 to 1
    pane size=2 borderless=true { 
        plugin location="zellij:status-bar"
    }
}
```

then you can hide only tips line.

2. Try to use `compact` layout. `zellij -l compact`

Hope this helps. If other problems occur, please reopen the issue or create a new one.
