### ISSUE TITLE
Session manager takes a lot of time to list sessions for a new zellij instance

### ISSUE THREAD

**Issue by inmny** [zellij-org/zellij#2946]
I open alacritty with zellij. It is attached to an active session. But it takes too long to list sessions for Session Manager(about a minute).

It is normal for the instance which has searched sessions before.

![image](https://github.com/zellij-org/zellij/assets/62230233/94e9e6d0-8d4b-44ab-8028-451e80eaa111)

Any more information needed?

**Comment by imsnif** [comment]
Thanks for reporting this! I just noticed this myself. It's a bug in 0.39.1 that I'll make a patch for probably next week.

For now, to get around this you can increase the frequency of the session_serialization in the config. eg. `session_serialization 1` will make it happen every 1 second and should solve this.

**Comment by inmny** [comment]
session_serialization true? It's the default value and it's boolean type. And I cannot find such a config item to increase the frequency of the session_serialization.

I attempted to set `session_serialization 1`. But it crashes Zellij with

```
 Failed to parse Zellij configuration
     ╭─[/home/inmny/.config/zellij/config.kdl:241:1]
 241 │ //
 242 │ session_serialization 1
     · ───────────┬───────────
     ·            ╰── Property session_serialization must be true or false, found 1
 243 │
     ╰────
```

**Comment by imsnif** [comment]
`serialization_interval 1` - sorry, my bad

**Comment by imsnif** [comment]
Sorry, I'm going to keep this open because while there is a workaround, this is still a bug.
