### ISSUE TITLE
Printing speed on msgcat --color=test

### ISSUE THREAD

**Issue by max-sixty** [zellij-org/zellij#295]
This project looks very exciting and I'm looking forward to seeing it develop.

I just installed it and attempted to run `msgcat --color=test`. It printed oddly slowly:

Zellij — 1.69s:
```
________________________________________________________
Executed in    1.69 secs      fish           external
   usr time   27.51 millis  103.00 micros   27.41 millis
   sys time   14.07 millis  911.00 micros   13.16 millis
```

No Zellij — 38.42ms. 
```
________________________________________________________
Executed in   38.42 millis    fish           external
   usr time   22.98 millis   90.00 micros   22.89 millis
   sys time   11.06 millis  712.00 micros   10.35 millis
```

FWIW on byobu-tmux it's also 40.44ms.

I'm using Alacritty on MacOS.

**Comment by imsnif** [comment]
Hey, for me (alacritty on arch) it's actually pretty fast with or without Zellij:
```
Executed in   16.16 millis    fish           external
   usr time    3.83 millis    0.00 micros    3.83 millis
   sys time   12.26 millis  653.00 micros   11.61 millis
```
Is this still slow for you in the latest version?

If so, could you test and see if the speed changes if you reduce the size of the terminal window?

**Comment by max-sixty** [comment]
It's remarkably consistent at 1.74s regardless of the window size. It's 1.71s on iTerm.

I'm using 0.10.0.

Could it be MacOS?


```
________________________________________________________
Executed in    1.74 secs      fish           external
   usr time   25.25 millis  116.00 micros   25.14 millis
   sys time   14.37 millis  767.00 micros   13.60 millis
```

**Comment by imsnif** [comment]
It might be quite a few things, tbh... Can I ask for your help debugging this? Could you follow the steps here and attach the all the log files? That way I can probably reproduce it on my machine: https://github.com/zellij-org/zellij/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by max-sixty** [comment]
For sure — happy to help.

Can I check I'm doing the right thing? I don't see any `zellij-1000` after running `zellij --debug`

```
❯ ll /tmp/zellij*                                                                                                                                         Sat May 15 11:29:15 2021
/tmp/zellij:
srwxr-xr-x 0 maximilian 14 May 21:48 ipc=
drwxr-xr-x - maximilian 14 May 21:46 zellij-log/

/tmp/zellij-501:
drwx------ - maximilian 15 May 11:29 0.10.0/
drwx------ - maximilian 15 May 11:26 zellij-log/

❯ zellij --version                                                                                                                                        Sat May 15 11:29:15 2021
zellij 0.10.0
```

**Comment by a-kenji** [comment]
If your `uuid` is 501, then everything should be fine.
If your `uuid` would be 1000 then that is the name of the logfile.

So I assume you are doing the right thing! Thank you.

**Comment by max-sixty** [comment]
Here's the log (though not much apart from the output): https://gist.github.com/max-sixty/34ab31b2c5fb5de2866aed80cd5e7960

And the other output requested:

```
$ zellij --version; tput lines; tput cols; uname -av
zellij 0.10.0
148
178
Darwin Maximilian_Roos_Remote_Access_v3_TM_C02CH19EMD6T 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64
```

**Comment by max-sixty** [comment]
At least on Alacritty on an M1 Max, this is now only about 20% slower. I'll close. Thanks!
