### ISSUE TITLE
Neovim theme isn't working with zellij

### ISSUE THREAD

**Issue by Hamza12700** [zellij-org/zellij#2953]
When even I open `nvim` with `zellij` the neovim theme is completely white!
![image](https://github.com/zellij-org/zellij/assets/72913359/5b53bbc2-ea9e-4070-beb5-875ebff47fd6)

Without `zellij`
![image](https://github.com/zellij-org/zellij/assets/72913359/ba89e0b2-e876-4cdc-874b-e50fda735b0d)

**Basic information**

`zellij --version`: zellij 0.39.1
`stty size`: 51 206
`uname -av`: Linux arch 6.6.1-arch1-1 SMP PREEMPT_DYNAMIC Wed, 08 Nov 2023 16:05:38 +0000 x86_64 GNU/Linux

`nvim --version`: NVIM v0.10.0-dev
`alacritty --version`: alacritty 0.12.3

**Comment by Hamza12700** [comment]
After restarting my laptop, the issue was fixed, which is quite interesting.

**Comment by Hamza12700** [comment]
It turns out that opening the terminal the first time with `zellij` the neovim theme works but whenever I opened a new terminal and opened `nvim` in that terminal, neovim theme is no longer working again.

**Comment by leet0rz** [comment]
Would just like to say that I do not experience this issue when using zellij and neovim. Wonder if it could be a configuration setting that could be causing this. Does it happen when you launch `nvim --clean` ?

**Comment by Hamza12700** [comment]
@leet0rz
No, it doesn't happen when I try to launch it with the `--clean` flag.
I use [LazyVim/Starter](https://github.com/lazyVim/starter) as my base config.
If you wanna look at my neovim config, [here you go](https://github.com/Hamza12700/Neovim)

**Comment by Hamza12700** [comment]
Thanks, @leet0rz, for your help. I am happy to report that the problem has been resolved.
