### ISSUE TITLE
ctrl+j is the same as pressing enter/return

### ISSUE THREAD

**Issue by APoniatowski** [zellij-org/zellij#2954]
**Basic information**

`zellij --version`: 0.39.1
`stty size`: full screen
`uname -av` or `ver`(Windows): Linux home-laptop 6.6.1-arch1-1

Hi there,

Yeah, it seems like there is an interesting bug (maybe on my side), where if I press ctrl+j,  it acts as enter/return in the active panel.

Also (maybe on my side), the clipboard does not transfer/paste over to my desktop (KDE), nor does it paste to itself, yet the highlighting disappears and it says "Text copied to system clipboard". I think there is an existing issue open for it, if not, let me know and I will create it

**Comment by amiorin** [comment]
I have tested nvim, tmux, wezterm, and zellij.

I can confirm that tmux distinguish between ctrl+j and ctrl+m/return while zellij does not.
In nvim using ctrl+v I see the correct control codes.
```
ctrl+m ^M
ctrl+j ^@
```

**Comment by Vinh-CHUC** [comment]
I can confirm I have the same issue, it works perfectly well in `tmux`

**Comment by ssipos90** [comment]
It's been tracked at #2679

**Comment by hiasr** [comment]
This is now fixed, the issue can be closed!
