### ISSUE TITLE
unwrap on none value in grid.rs

### ISSUE THREAD

**Issue by bomgar** [zellij-org/zellij#2966]
```
Error occurred in server:

  × Thread 'screen' panicked.
  ├─▶ Originating Thread(s)
  │     1. screen_thread: HandlePtyBytes
  │
  ├─▶ At zellij-server/src/panes/grid.rs:1424:46
  ╰─▶ called `Option::unwrap()` on a `None` value
  ```

**Basic information**

zellij 0.39.1
`stty size`: 70 343
`uname -av` or `ver`(Windows):  6.6.2-arch1-1

**Further information**
I could not reproduce it. But I assume it was a ssh session that hang in logout because the forwarded port still had traffic. I cannot reproduce it though.

**Comment by imsnif** [comment]
Fixed in https://github.com/zellij-org/zellij/pull/2972 - sorry for the experience and thanks for the report!
