### ISSUE TITLE
[refactor] Refactor Actions and Command to allow easier extensibility

### ISSUE THREAD

**Issue by f3fora** [zellij-org/zellij#2968]
The representation of the actions for NewPane (and also NewTab) looks redundant and also messy.
 
from: https://github.com/zellij-org/zellij/blob/42af4c5103a0f5bfb07aaa248d3f3424adf80dd8/zellij-utils/src/input/actions.rs#L156-L175

and eventually https://github.com/zellij-org/zellij/blob/42af4c5103a0f5bfb07aaa248d3f3424adf80dd8/zellij-utils/src/input/actions.rs#L241-L243

Moreover, the `RunCommandAction` is a totally unnecessary intermediate implementation, which is simply a copy of `RunCommand` with the addition of a `Option<Direction>` field and includes information about the behavior of the Pane UI. (https://github.com/zellij-org/zellij/blob/main/zellij-utils/src/input/command.rs)

A clever way to implement the `NewPane` action will be something like:
```rust
NewPane(TerminalAction, PaneOptions),
```
where `Terminal Action` is similar to 
```rust
#[derive(Debug, Clone)]
pub enum TerminalAction {
    OpenFile(OpenFile),
    RunCommand(RunCommand),
    // eventually
    RunPlugin(RunPlugin),
}

#[derive(Clone, Debug, Deserialize, Default, Serialize, PartialEq, Eq)]
pub struct RunCommand {
    #[serde(alias = "cmd")]
    pub command: PathBuf,
    #[serde(default)]
    pub args: Vec<String>,
    #[serde(default)]
    pub cwd: Option<PathBuf>,
    // Eventually allow to add other field such as environmental variables
    #[serde(default)]
    pub env: EnviromentalVariables,
}

#[derive(Clone, Debug, Deserialize, Default, Serialize, PartialEq, Eq)]
pub struct OpenFile {
    #[serde(default)]
    pub name: PathBuf
    #[serde(default)]
    pub line: Option<usize>,
    #[serde(default)]
    pub cwd: Option<PathBuf>,
    // Eventually allow to add other field such as environmental variables
    #[serde(default)]
    pub env: EnviromentalVariables,
}
```

and ` UIOptions` are similar to 

```rust 
#[derive(Debug, Clone)]
pub enum PaneOptions {
    Tile(TileOptions),
    Floating(FloatingOptions),
    InPlace(InPlaceOptions),
}

#[derive(Debug, Clone, Deserialize, Default, Serialize)]
pub struct TileOptions {
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub direction: Option<Direction>,
    #[serde(default)]
    pub hold_on_close: bool,
    #[serde(default)]
    pub hold_on_start: bool,
    // add other field such that
    #[serde(default)]
    pub move_focus: bool,
}

// and so on for the other fields of the enum
```

This refactor will lead to something similar to #1992 which in the end allow a straight forward solution of #1988 and #1987 and correctly manage the cwd for the EditFile Action.

**Comment by imsnif** [comment]
Hey, I very much appreciate your efforts but I think a little differently about the code base.

This code base does not have 100% test coverage and does not represent a stable application (we're still pre 1.0). Because of that, a lot of the things that can break are mostly stored in my head. I'd be willing to consider sweeping changes as long as they give us direct features that are in our roadmap (and even then, I'd rather see those features with as little changes as possible).

Thanks again, but these sorts of bare refactorings are something I'd like to save for when the app is more stable.
