### ISSUE TITLE
Feature: add brew formula

### ISSUE THREAD

**Issue by rjcoelho** [zellij-org/zellij#297]
This is important to increase adoption.
And I did not find one. 
Check fd or bat for inspiration. I can help also.
Great project btw

**Comment by imsnif** [comment]
Zellij is currently a beta... stable enough for everyday use if you are adventurous and like brand-new software. Is brew ok with things like that?

**Comment by nicomitchell** [comment]
@imsnif @rjcoelho You can check out the acceptable formulae documentation [here](https://docs.brew.sh/Acceptable-Formulae). 

According to the docs, a stable, non-beta version is required. I think this may have to wait until the project leaves beta.

**Comment by rjcoelho** [comment]
@nicomitchell i know, but we can create a brew tap repo

**Comment by a-kenji** [comment]
This seems addressed as far as I can tell.
https://formulae.brew.sh/formula/zellij
