### ISSUE TITLE
Enable user to execute a shell command and return to shell without closing the Zellij pane

### ISSUE THREAD

**Issue by smangels** [zellij-org/zellij#2970]
## Use Case

We would like to prepare a pane with sourcing a certain setting script (shell, bash) and return to shell after  execution without closing the pane the command has been executed in. So that the context is kept (env variables). This should be possible without pressing ESC key to drop to shell.

## Question
Did we miss a configuration option that could help to achieve this?

## Example Layout configuration
```kdl
layout {

  tab_template name="tab_nvim" {
    pane size=1 borderless=true {
      plugin location="zellij:tab-bar"
    }
    pane split_direction="vertical" {
      pane name="nvim" size="60%" command="nvim" start_suspended=false
      pane focus=true {
        pane name="term 1" command="env"
        children expanded=true
      }
    }
    pane size=1 borderless=true  {
      plugin location="zellij:status-bar"
    }
  }

  default_tab_template {
    pane size=1 borderless=true {
      plugin location="zellij:tab-bar"
    }
    pane  {
      pane name="rename me ..." size="50%"
      children
    }
    pane size=1 borderless=true  {
      plugin location="zellij:status-bar"
    }
  }

  tab_nvim name="IAC #1" focus=true cwd="${HOME}/projects"
}

```

**Comment by smangels** [comment]
Will this require massive refactory or is that more less a small change?

**Comment by igorrizhyi** [comment]
@smangels 
probably the same workaround as with [environment variables](https://github.com/zellij-org/zellij/issues/2988#issuecomment-1934920220) will suit your needs?

**Comment by imsnif** [comment]
I'm not 100% sure I understand the request here, but maybe something like:

```kdl
pane command="bash" {
    args "-ic" "my_source_script.sh && bash"
}
```

**Comment by smangels** [comment]
the approach above has been tested and is working correctly. Thanks @imsnif  for providing a solution.
