### ISSUE TITLE
Copy and paste issue

### ISSUE THREAD

**Issue by JokerQyou** [zellij-org/zellij#2990]
Thank you for taking the time to file this issue! Please follow the instructions and fill in the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

**In Case of Graphical or Performance Issues**

1. Delete the contents of `/tmp/zellij-1000/zellij-log`, ie with `cd /tmp/zellij-1000/` and `rm -fr zellij-log/` (`/tmp/` is `$TMPDIR/` on OSX)
2. Run `zellij --debug`
3. Run `stty size`, copy the result and attach it in the bug report
4. Recreate your issue.
5. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.

**Basic information**

`zellij --version`: `zellij 0.39.1`
`stty size`: `37 169`
`uname -av` or `ver`(Windows): `Linux dell 6.1.64-1-MANJARO #1 SMP PREEMPT_DYNAMIC Tue Nov 28 20:31:22 UTC 2023 x86_64 GNU/Linux`

List of programs you interact with:

`whoami --version`: `whoami (GNU coreutils) 9.4`

**Further information**

- OS: Manjaro Linux with KDE (X11, not wayland)
- Terminal emulator: `Yakuake 23.08.3` (also tested on `Konsole 23.08.3`, but they both came with KDE and is basically the same emulator)
- 
Behaves differently from #2400, zellij does not copy at all. The steps are as follows:

- fire up zellij with `zellij` in `Yakuake` (the global floating terminal on KDE systems)
- copy something from other programs. e.g.: type `AAA` in `Kate` and select them, press `Ctrl c` to copy into system clipboard.
- back into zellij, press `Ctrl v`, the text got correctly pasted.
- now in zellij, use mouse to drag over some text. e.g. I typed in `whoami` and run it, I then select the text `whoami`, zellij shows `Text copied to system clipboard`, but the clipboard manager got no new text (KDE has built-in clipboard manager on the tray icon area). If I go to Kate, press `Ctrl v`, it still pastes `AAA` I've copied.
- normally on KDE (or any other Linux desktops running X11), you'd expect to select some text, and directly paste the selection with the middle mouse button; the selection does not go into system clipboard. So I tried this too: select `whoami` in zellij, go to Kate, and press the middle mouse button, nothing happens.

Also when using zellij, the mouse cursor does not change into text selection cursor, it's always the arrow cursor, so it's kind of hard to see what text I'm selecting.

Here's the `/tmp/zellij-1000/zellij-log/zellij.log` file:
[zellij.log](https://github.com/zellij-org/zellij/files/13575641/zellij.log)

**Comment by JokerQyou** [comment]
This is actually discussed in #627 . I'd suggest to put together a list of terminal emulators that conflicts with mouse mode, though.

**Comment by JokerQyou** [comment]
Well, I mainly came here to look for an alternative to `byobu` to use the multi-tab support. For zellij I use it because it has keybindings listed just on the bottom, while I can't remember byobu's keybindings. I don't use other features, only multi-tab and multi-panel, so I'd like to spend as less time as possible to configure or testing it.
Maybe there's a way to use the copy-on-select feature with mouse mode enabled, but I don't see what additional features mouse-mode adds, so never mind, if disabling it brings back the native selection clipboard then I'm fine.

**Comment by Zykino** [comment]
If you quickly want to do it then use `Shift` while selecting your text. The mouse actions will be transferred to the underlying application, and if no one intercept it the terminal will (usually) take care of the selection.

The mouse permit to change panes and tabs (by clicking on them).
