### ISSUE TITLE
`zellij run` not respecting PATH

### ISSUE THREAD

**Issue by norman-zon** [zellij-org/zellij#3007]
# 2. Issues with the Zellij UI / behavior

## Issue description

`zellij run` does not seem to respect my `PATH` variable.

## Minimal reproduction

Put a binary in a non-standard path e.g by using `rtx` and try to call it with `zellij run`

```
❯ echo $PATH
/Users/norman/.local/share/rtx/installs/kubectl/1.24.13/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/norman/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

❯ which kubectl
/Users/norman/.local/share/rtx/installs/kubectl/1.24.13/bin/kubectl


❯ zellij run -- zsh -c "echo $PATH"
/Users/norman/.local/share/rtx/installs/kubectl/1.24.13/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/norman/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

❯ zellij run -- zsh -c "which kubectl"
kubectl not found
```

## Other relevant information

```
❯ zellij -V
zellij 0.39.2
```

```
❯ rtx version
2023.12.24 macos-arm64 (2023-12-12)
```

**Comment by rostamn739** [comment]
❯ zellij run -- zsh -c "echo $PATH"

this substitution uses the variable from the parent shell,
use `'` (single quotes) to pass the name of the variable to zellij/zsh

**Comment by norman-zon** [comment]
🙈 my bad. You are absolutely right. When using `'` it looks like this:

```
❯ zellij run -- zsh -c 'echo $PATH'
/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

So the underlying issue, is that `zellij run` does not start an interactive shell, which prevents `rtx` from altering the path.
Working around this should be possible using `rtx hook-env`.

On the other hand. Why is it not possible to start an interactive shell from `zellij`?

**Comment by norman-zon** [comment]
Nevermind. Of course I can use `zellij run -- zsh -ic` to start the shell interactively
