### ISSUE TITLE
`zellij run` not work out of session

### ISSUE THREAD

**Issue by chaopeng** [zellij-org/zellij#3010]
**Basic information**

`zellij --version`: v.0.39.2
`uname -av` or `ver`(Windows): Debian 6.5.6-1rodete4 x86_64 GNU/Linux

## Further information

Reproduction steps:

- `zellij` to create a new zellij session
- `ctrl-o d` detach the session
- `zellij list-sessions` find the session name
- `zellij --session [session-name] run -- echo hello`
- `zellij attach [session-name]`

Expect: zellij run a command inside the session with new pane
Actually: nothing in zellij

I also tried zellij run -f, still not luck. I somehow remember it works in previous version (maybe v0.39.1). But I did not verify.

Tried use run inside a session, it works.

**Comment by jlabbude** [comment]
Been facing the same issue on v0.40.1, `zellij run` (and for instance all commands related to interacting with a detached session, such as `zellij action` and what not) seems to only work if you have an active session.

**Comment by gibfahn** [comment]
Simple repro:

```shell
zellij delete-session --force test
zellij attach --create-background test
zellij --session test run --name one -- sleep 101
zellij --session test run --name two -- sleep 102
zellij --session test run --name three -- sleep 103
zellij --session test run --name four -- sleep 104
zellij attach test
```

Only shows the original pane and the first command run.

<img width="1727" alt="image" src="https://github.com/user-attachments/assets/be4f10cf-e84a-4082-b26e-cd32587cab81">

If you add `--in-place` to the first run command, you get:

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/7a04f5a7-df25-4ebf-b450-c0c6d71e0878">

So it looks like only the first run takes effect. If you attach then the run commands work as expected.
