### ISSUE TITLE
Serialize current session layout (expose machinery of resurrection)

### ISSUE THREAD

**Issue by thisismygitrepo** [zellij-org/zellij#3012]
Not sure if this is already doable, but Zellij can already `ressurrect` an old dead session, but the way this is done is black magic for the user. Can we please expose what was used to perform the resurrection?

* Use case
    I want to dump those commands to a file then I can back it up and load it on a different computer.

* Where should it go:
  I was intuitively expecting it @ `zellij setup --dump-current-session`

* The dumping/serialization of the current session would either return lines like

```shell
zellij --session myname action new-pane --direction down -- lf
zellij --session myname action resize - down
zellij --session myname action new-pane --direction left -- btop
etc etc

```

or, alternatively, it can return a layout. I'm not sure how the resurrection currently work, but both are okay.

* Why would this be lovely?
   Its the same reason why resurrect is nice. Its far easier for the user to build their layout in the current session on the fly, than learning all the syntax of layout (far more time-consuming).

I'm imagining that this is a low-hanging fruit.

Thank you.

**Comment by imsnif** [comment]
Hi yes, sorry - this is not documented yet (my bad!) but does exist. Check out: `zellij action dump-layout`
