### ISSUE TITLE
Implement functionality propagate (sync) all panes either type or paste text

### ISSUE THREAD

**Issue by marulinko** [zellij-org/zellij#302]
I would like to ask you to implement functionality propagate to all panes to type or paste text to all active
windows. It is usefull, when you have open multiple ssh session to systems and you want to execute same
command on all of them. It's similar as is implemented in tmux. 
[Here is example with video](https://blog.sanctum.geek.nz/sync-tmux-panes/)
Thank you.

**Comment by imsnif** [comment]
This is a cool idea!

**Comment by dantepippi** [comment]
I could give this a try!

**Comment by a-kenji** [comment]
@dantepippi 
That would be awesome!
If you have any questions, please feel free to ask them!

**Comment by ginolegigot** [comment]
Hello!
I'm on zellij 0.40.1, when i press control p i dont see the sync "s" option at teh bottom of my screen with the other keybindinds, i cant find it either in the doc nor in my local config (very near of default i just unbinded control q for alt q).
Is there still a way to achieve this or was it deprecated or something ? Or maybe i did miss it, so do you know where is it ? ^^

**Comment by imsnif** [comment]
It's in `TAB` mode. Try `Ctrl t` + `s`

**Comment by ginolegigot** [comment]
Neat! it works like a charm thanks!

**Comment by Borodkov** [comment]
Hello
is it difficult to add syncing only to some panes in TAB ?

i have 3 panes TAB (1 left half + 2 equal on right half) -> ssh server1 / ssh server2 on the right panes -> need to do the same on this servers, but no on my machine (1 left pane)
