### ISSUE TITLE
Zombie process after closing a pane command

### ISSUE THREAD

**Issue by alankritjoshi** [zellij-org/zellij#3024]
# 2. Issues with the Zellij UI / behavior

## Issue description

Quitting a tab doesn't end certain processes.

This happens specifically for a tab created by `zellij action new-tab -l layout.kdl` where the layout has a pane command

I noticed this when running a Golang hot reload tool called [air](https://github.com/cosmtrek/air).

## Minimal reproduction

1. Create a simple go program in `main.go`
    ```go
    package main
    
    import (
	    "time"
    )
    
    func main() {
	    time.Sleep(30 * time.Second)
    }
    ```
2. Install [air](https://github.com/cosmtrek/air)
3. Create a layout that specifies a pane command
    ```
    layout {
          pane command="air"
    }
    ```
4. Create a new tab using `action`
    ```sh
    zellij action new-tab -l layout.kdl
    ```
5. Quit the tab
6. Observe pid for the process name air
    ```sh
    pgrep -l air
    ```

### Without `air`

When the tab's pane command runs the binary execution directly (`go run main.go`) and then the tab is quit, it manages to successfully kill it. 

### With `air`

I am not sure what `air` is doing differently but my assumption is that it has something to do with how SIGTERM vs SIGHUP interact with it: https://github.com/zellij-org/zellij/pull/1320. 

To test this, I used the `kill` command with both flags on a running `air` process manually. SIGTERM killed it but SIGHUP didn't, left it in a broken but running state.

### Related Issue

Maybe not super relevant but I found a past issue on the `air` side: https://github.com/cosmtrek/air/issues/156

### Is this a bug?

If this isn't a Zellij bug (because `air` only quits with SIGTERM), any recommendation to get around this?

**Comment by imsnif** [comment]
Hey, thanks for reporting this. Can you please troubleshoot this further and find the exact Zellij issue if you think this is one? Specifically, please provide a reproduction without `air` (and for my sake, please with bash and not go - it will be easier for me to reproduce).

**Comment by alankritjoshi** [comment]
Closing this issue as this seems like an issue with air's handling of SIGHUPs. Most terminals typically send SIGHUPs, which I wasn't aware of.
