### ISSUE TITLE
lrzsz will be supported?

### ISSUE THREAD

**Issue by jkwroi24io9342fsdjklAdf** [zellij-org/zellij#3029]
As you know, sz, rz are the common tools for uploading and receiving files by ssh tunnel in terminal. Does zellij plan to support this?

**Comment by imsnif** [comment]
What's preventing you from using them inside Zellij?

**Comment by jkwroi24io9342fsdjklAdf** [comment]
When I use sz or rz to send or receive files, it freezes and doesn't succeed at all.

**Comment by imsnif** [comment]
Alright. I'd be happy to get to the bottom  of this, but we have issue templates for things like these. I'm closing this issue now, please open a new one and follow the instructions in the bug report issue template to provide a minimal reproduction. Thanks!
