### ISSUE TITLE
Problem with initial sizing?

### ISSUE THREAD

**Issue by Keruspe** [zellij-org/zellij#303]
Hi,

I'm the author of [Germinal](https://github.com/Keruspe/Germinal) which currently uses tmux as its startup command. I'm trying to use zellij as an alternative but I'm facing an issue with the initial sizing of the first pane.

Germinal launches a gtk window maximized, borderless, and launches its startup command in a VteTerminal. With a "classic" shell such as bash or zsh, and with tmux, all the space is correctly used. With zellij, the tab list is at the top, and the toolbar at the bottom, as expected, but the pane only uses ~25% at the bottom of the screen and I have to manually resize it for it to fill the available space

**Comment by Keruspe** [comment]
![germinal-zellij](https://user-images.githubusercontent.com/222942/115531451-15881a00-a295-11eb-8522-49d4f506c54c.png)

**Comment by Keruspe** [comment]
I can further debug this if you point me at the relevant sources

**Comment by imsnif** [comment]
This should be fixed in `0.5.1`. Thanks for reporting it!
