### ISSUE TITLE
way to detect that my session is already in zellij?

### ISSUE THREAD

**Issue by jokeyrhyme** [zellij-org/zellij#304]
Howdie, thanks so much for sharing this, exciting!

I'm looking to migrate from `tmux` to `zellij`, and one aspect of my current setup is that my shell profile will launch `tmux` if it hasn't already done so

```
if [ -z "${TMUX:-}" ]; then
  if command -v tmux >/dev/null 2>&1; then
    tmux
  fi
fi
```

This is possible because of the `TMUX` environment variable:

https://man.openbsd.org/OpenBSD-current/man1/tmux.1#GLOBAL_AND_SESSION_ENVIRONMENT

> `tmux` also initialises the `TMUX` variable with some internal information ...

It wouldn't necessarily have to be an environment variable, but it would be useful for my use case if there was a way for a script to check if it's already running inside a `zellij` environment

Cheers!

**Comment by a-kenji** [comment]
Cheers!
If you build from main now, you can check for the `$ZELLIJ` env variable.
It is set to 0.

**Comment by jokeyrhyme** [comment]
Wow, response times! :speedboat: :racehorse: 

Thanks so much! <3
