### ISSUE TITLE
[Bug] When attaching to a session the terminal size is reduced to the smallest window

### ISSUE THREAD

**Issue by ad-on-is** [zellij-org/zellij#3050]
I've noticed, when attached to a session, the **terminal size** is reduced down to the smallest window, even if they are larger.

https://drive.google.com/file/d/1t5_dFfGlnjls93B6-DZnkCMHM_4j3D-V/view?usp=sharing

Expected behavior 
Content should adapt to the window size

**Comment by Notarin** [comment]
This is a feature, are you asking for it to cut off the content in your smaller terminal?

**Comment by ad-on-is** [comment]
> This is a feature, are you asking for it to cut off the content in your smaller terminal?

I'd expect it to adapt the content of the window size.

**Comment by Notarin** [comment]
That is impossible, the program inside, your shell, simply does not work that way, when it adapts the content within to your terminal, it asks the containing terminal what its available space/constraints are, if it were given multiple responses it wouldn't know what to do with it.
The problem, is that the multiplexer does not "adapt" the content, the process inside does. So for example, btop, does no just throw out data and get reshapen and displayed by the terminal/multiplexer, instead, btop during its startup, asks the container, "hey, how big can I display my stuff? 87x34? cool!" and starts displaying at that resolution.
Not only is giving two responses not supported or possible, it wouldn't be able to do anything with it, as the display is one unified buffer, which is the whole point of the program. the buffer being displayed in both panes is the same identical buffer.

**Comment by ad-on-is** [comment]
aash, I see.... thx for the clarification. I just tried tmux and the behaviour is almost similar, with the difference that the content adapts to the width only if the window is in focus.

**Comment by Notarin** [comment]
If that resolves your issue it'd be best to close it, I am unable to do so for you.

**Comment by p1gp1g** [comment]
Is it possible to reopen this issue ?

When `mirror_session` is `false`, I expect zellij to work like tmux's session group (2 sessions created with -t: `tmux new-session -ttest`):
- Always use the size of the last focused window (not the smaller)
- Set size per tab. If a window focus on tab1 and another on tab2, it is possible to have tab1 the size of the first window and tab2 the one of the 2nd

**Comment by Notarin** [comment]
To me that sounds like a feature, try opening a new issue.
