### ISSUE TITLE
Copy does not work

### ISSUE THREAD

**Issue by MahirAbbas** [zellij-org/zellij#3052]
# 2. Issues with the Zellij UI / behavior / crash

## Issue description
trying to copy by selecting with mouse doesnt work inside Konsole (KDE) /yakuake with zellij 
## Minimal reproduction
unsure, if its a konsole or KDE issue

**Comment by msmafra** [comment]
On Wezterm, as it has its own copy mode I assume, I have the same problem: it does copy to the clipboard; On Konsole and Gnome Terminal, I'm usinge Gnome 45, it also doesn't work. Works on Alacritty.

**Comment by strobe** [comment]
seems case with Wezterm for me too (works on Alacritty & Kitty) but copying in Tmux works fine with Wezterm on same machine

**Comment by imsnif** [comment]
Sorry for everyone's troubles. Please see our FAQ on this: https://zellij.dev/documentation/faq#copy--paste-isnt-working-how-can-i-fix-this

**Comment by strobe** [comment]
thanks, that fixed it for me. 

But I'm wondering what is stopping it from being the default fallback behavior?  Is it possible to detect OSC 52 terminal support and then fail back to one of the options?

(I'm thinking about try to implement that later)

**Comment by imsnif** [comment]
I know of no way to reliably detect OSC 52 support. Please believe me that if there were a way to fix this without user intervention, we'd go for it before placing it in the FAQ :)

**Comment by MahirAbbas** [comment]
Yes this works thank you.

**Comment by msmafra** [comment]
> Sorry for everyone's troubles. Please see our FAQ on this: https://zellij.dev/documentation/faq#copy--paste-isnt-working-how-can-i-fix-this

Thanks, that works very well. 
I replaced with  xsel --input --clipboard instead since I use it a lot on terminals.
