### ISSUE TITLE
Strider does not work on MacOS Sonoma 14.2.1

### ISSUE THREAD

**Issue by jigypeper** [zellij-org/zellij#3064]
# Issues with the Zellij UI / behavior / crash

## Issue description
Cannot run strider plugin.

## Minimal reproduction
Steps:
1. install zellij via 'brew install zellij'
2. run 'zellij -l strider'
3. crashes with 'Received empty message from server'

## Other relevant information
I think it's just a strider issue. Tried on wsl2 with work laptop and had no issues, very odd and frustrating.

**Comment by jimmyjansen93** [comment]
yup can confirm, I have the same problem.

**Comment by mbhutton** [comment]
Same with macOS Ventura lastest (13.6.3) with lasted zellij (0.39.2).

`zellij --layout compact` always works, `zellij --layout strider` always exits within about 200ms with `Received empty message from server`. 

`zellij -d --layout strider` shows no additional output.

Possibly related issue: #2170 

Deleting the caches as suggested in that issue does not work as a workaround.

**Comment by bowentan** [comment]
Same issue here. Loading each plugin I got ran into a crash with message `Received empty message from server`.

**Comment by devsecopshomelearning** [comment]
Getting this issue also on Apple M3 Pro Sonoma 14.3

**Comment by devsecopshomelearning** [comment]
I just tested Zellij 0.38.2 and the issue is not present in that version. Strider loaded with no issues right away.

**Comment by jigypeper** [comment]
I've just tried the 0.38.2 binary and strider seems to work fine on that one...

**Comment by mbhutton** [comment]
Appears to be fixed in the newly released 0.40.0 on my Sonoma system. 
Was failing with Zellij 0.39.2, but now works fine.

**Comment by jigypeper** [comment]
Really!
I'll give that a shot tonight.
🤞

**Comment by jigypeper** [comment]
0.40.2 does appear to fix this issue :)
