### ISSUE TITLE
MoveFocusOrTab doesn't remember last focused split

### ISSUE THREAD

**Issue by oredaze** [zellij-org/zellij#3067]
The issue is very simple:
When I am focusing tabs with `MoveFocusOrTab` (Alt+h,l) the last focused split in the tab I am about to focus is not remembered, causing confusion (I some times use fully stacked layout, so I suddenly don't know where I am at visually, but it should be annoying even if that is not people's use case).

I would like for it to behave like `GoToTab`. That one remembers.

**Comment by marcghorayeb** [comment]
Is this a duplicate of https://github.com/zellij-org/zellij/issues/3006?

**Comment by oredaze** [comment]
It appears to be one, sorry.
