### ISSUE TITLE
cwd is lost when opening new pane with nushell

### ISSUE THREAD

**Issue by n8henrie** [zellij-org/zellij#3068]
# 2. Issues with the Zellij UI / behavior / crash

## Issue description

I am new to zellij and nushell both, so I apologize with my lack of familiarity with the territory.

In zellij, with my `default_shell` set to nushell, when I open a new pane, the new pane opens to my home directory instead of staying in the cwd, as expected after https://github.com/zellij-org/zellij/pull/691

If I change my default shell to bash, the pane opens into cwd as expected.

## Minimal reproduction

```console
> echo $env.NU_VERSION
0.88.1
> cd (mktemp -d)
> pwd
/private/tmp/tmp.f8WsBgKlrW
> # <C-p> n
> # in the new pane:
> pwd
/Users/n8henrie
```

**Comment by cristiand391** [comment]
I can't repro on this using nu 0.89.0 and zellij 0.39.2

a few questions:
1. what version of zellij are you using? `zellji --version`
2. do you have nushell in your PATH and set `default_shell` to `nu` **or** set `default_shell` to the path to the nu bin?
3. can you repro with zsh/bash?

**Comment by n8henrie** [comment]
Thanks for chiming in! Your comment that it worked for you prompted me to keep digging, and I can confirm that it is a problem specific to my environment. Specifically, I had configured my `default_shell` to be a script that first prepares some environment variables and then enters `nu`; clearly something about this messes up the PWD retention. Once I change `default_shell` to be the path to the `nu` binary directly, the behavior is normal.

Sorry for the false alarm issue.
