### ISSUE TITLE
Not opening tab's first pane in current directory location on opening new tab

### ISSUE THREAD

**Issue by lol-bruh** [zellij-org/zellij#3078]
`zellij --version`
zellij 0.39.2

`stty size on terminal` - 39 147
`stty size inside zellij` - 34 145

When I open a new tab of the project I am currently working on it opens the tab pane in `$HOME` this is kind of annoying because everytime I try to check a file I need to `cd` into last directory again and again. Same with run command, it opens helix file picker in home directory
```
        bind "t" { NewTab; SwitchToMode "Normal"; }
        bind "n" { NewTab; Run "hx" "."; SwitchFocus; CloseFocus; SwitchToMode "Normal"; }
```
I shouldn't have mentioned the second one because I just because of the same reason. But still it is also a problem while working

`uname -av`
Linux fedora 6.6.11-100.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jan 10 19:23:27 UTC 2024 x86_64 GNU/Linux

**Comment by cristiand391** [comment]
Please follow the bug report template so it's easier to help you:
https://github.com/zellij-org/zellij/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

IIRC, this specific bug was fixed in a release a few months ago so you migth just be using an old version.

**Comment by lol-bruh** [comment]
hey can you please tell me how to disable the status bar plugin?
I also opened a discussion here `https://github.com/zellij-org/zellij/discussions/3077`

**Comment by giyany** [comment]
Hi,

Please help us in working on the issues by using the bug report template and staying on-topic. If the previous answer was helpful, please close it. 
Configuring the look of zellij is covered in the documentation and you can use the compact layout: https://zellij.dev/tutorials/layouts/
if you need more help with zellij, you're very welcome to join us on discord on matrix.

**Comment by lol-bruh** [comment]
ok sorry for that!

**Comment by cristiand391** [comment]
Thanks @lol-bruh, you are on latest 

does it happen if you open a new tab/pane from the CLI?

1. `zellij action new-pane`
2. `zellij action new-tab`

also

3. what's your current `default` layout?

if you have a custom one you can get it by running:
```
cat $HOME/.config/zellij/layouts/default.kdl
```

**Comment by lol-bruh** [comment]
I tried the same its working but I didn't know how it happened

**Comment by lol-bruh** [comment]
idk what just happened, its happening the same!!

**Comment by kkrime** [comment]
I am also experiencing this issue, it would be great if there was a way to open a new tab in the current working directory of the previously opened tab
