### ISSUE TITLE
Detach zellij session

### ISSUE THREAD

**Issue by cswinter** [zellij-org/zellij#308]
Maybe I missed it, but there doesn't seem to be a way to detach/reattach sessions a la `tmux`/`screen`. Are there any plans to add this functionality?

**Comment by a-kenji** [comment]
You didn't miss it! 
It is currently being implemented  #69.

**Comment by cswinter** [comment]
Ah just learned that apparently https://github.com/zellij-org/zellij/pull/223 will enable this, keep up the good work! 🎉
Might be worth mentioning this explicitly in the roadmap, it's a pretty key feature and it's not obvious from the current roadmap description that you plan to support this.

**Comment by a-kenji** [comment]
Thank you, that is a good idea.
