### ISSUE TITLE
Feature(Config): Allow multiple `--config` flags

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#310]
Allow multiple `--config` flags, then use the latter.

More discussion in #290.

Might be worth it to wait untill clapv3 is out of beta, if I understand it correctly that should be handled reasonably well then.

**Comment by matthiasbeyer** [comment]
I think allowing multiple `--config` flags is not a good idea. The usecase described by @lilyball in #290 is a valid one, but I think that it is simply not the job of the software to handle such a case, but of the author implementing the wrapper!

@lilyball I'm also a user of nix(os) and could help you catch that case that you're talking about in #290 ... something like this comes to mind:

```bash
ARGS="$@"
echo "$ARGS" | grep -q -- "--config" || ARGS=" --config $NIX_STORED_CONFIG $ARGS"
zellij $ARGS
```

(just a mockup, not thinking about edge cases here)

**Comment by a-kenji** [comment]
That could introduce ambiguity I think. But what led me to believe this is can be a good idea [from](https://github.com/clap-rs/clap#features):

>POSIX Compatible Conflicts/Overrides - In POSIX args can be conflicting, but not fail parsing because whichever arg comes last "wins" so to speak. This allows things such as aliases (i.e. alias ls='ls -l' but then using ls -C in your terminal which ends up passing ls -l -C as the final arguments. Since -l and -C aren't compatible, this effectively runs ls -C in clap if you choose...clap also supports hard conflicts that fail parsing). (Thanks to Vinatorul!)

Maybe I misunderstood, but if that truly is a way to be a little more forgiving for many tools this is not such a bad thing. On the other hand it can be valuable to know the only config that gets passed in is your `--config`.

**Comment by lilyball** [comment]
It really is not the job of the wrapper to reimplement argument parsing for the wrapped utility. That puts a big burden on every single person who wants to wrap your utility, who will most likely not even consider this case or who will do it wrong. It's much easier for your utility to simply allow the last flag to win, which has plenty of precedent among unix utilities.
