### ISSUE TITLE
copy/paste selection from remote SSH does not work

### ISSUE THREAD

**Issue by romange** [zellij-org/zellij#3120]
## Issue description
Once I ssh into a remote linux server and run zellij there, when I try to select a pane area, zellij handles the mouse selection and says that it copied it to the system clipboard (see below)  

However, I fail to paste anything into my local machine. The `copy_command` is not defined on the remote machine. I am guessing it's a configuration issue but I have not found anything in the documentation that explains how to configure clipboard settings for connecting remotely with ssh.

## Other relevant information

![image](https://github.com/zellij-org/zellij/assets/3674760/08b1cb61-d23c-4584-98b7-e05c86c6f610)

**Comment by romange** [comment]
Ok, I figured out how to set it up. It's not related to zellij but I will explain here how it worked for me.
1. Make sure you can send text from a remote server to local one via x11 buffer.
    for me this `echo foo | xsel -b` did not work. Apparently I had to install `xauth` on my remote machine. Once I did that,
    I could ssh into this server with `ssh -X ...` and `echo foo | xsel -b` succeeded.
2. Change `copy_command` in zellij config to `xsel -b` and restart zellij. Once I did that zellij wrote `Text piped to external command` upon mouse selection.

The most important point is to make sure you can use x11 clipboard remotely without zellij. Once you do this, the rest is simple.

**Comment by hongquan** [comment]
You can just use modern terminals which support "OSC 52", like Kitty, WezTerm, Alacritty.
You can learn more tricks related with "termial to clipboard" here: [Effectly copy part of code file from remote machine](https://quan.hoabinh.vn/post/2024/8/effectly-copy-part-of-code-file-from-remote-machine).
