### ISSUE TITLE
More lightline like toolbars [Feature Request]

### ISSUE THREAD

**Issue by alexhallam** [zellij-org/zellij#313]
I have a very minimal set up.

When I open the multiplexer this is what my toolbar looks like.

![image](https://user-images.githubusercontent.com/9298693/115584999-3e121300-a299-11eb-910b-bec97580e684.png)

I would like to request a simplified version that does not have the font/glyph deps. Something like a light line option (see https://github.com/itchyny/lightline.vim)

![image](https://user-images.githubusercontent.com/9298693/115585527-b11b8980-a299-11eb-8654-09319b39f07e.png)

**Comment by a-kenji** [comment]
Thank you! Currently we have no configuration system for themes and plugins implemented yet, but the Font issue has come up often enough, that I think it is reasonable to try to build the bar with a more general font and include it by default, so people can switch it out in their default.yaml - as an intermediary fix. I am curious what other people think.

cc @imsnif

**Comment by keeslinp** [comment]
Worst case someone could just make a new wasm plugin and load a different layout right? (or just replace the `status-bar.wasm` file I guess)

**Comment by imsnif** [comment]
A relatively quick fix for this (in case users don't want to install new fonts) is:

1. Create versions of the default plugins (status-bar and tab-bar) as @keeslinp suggested, which do not include the arrow font (or include a different separator instead it, maybe a pipe?)
2. Create a "simplified.yaml" layout which is the copy of the default layout and loads them instead
3. Run: `zellij --layout simplified`

If anyone wants to work on this, I'd be happy to merge this PR. I think this would be valuable to include with Zellij.

Bonus points if you can come up with a better name than "simplified" :)

**Comment by alexhallam** [comment]
I can give this a try. But I have a couple questions first:

1. For new versions of `status-bar` and `tab-bar` I am guessing I just cp `default-plugins/status-bar/src/main.rs` and `./default-plugins/tab-bar/src/main.rs` to something like `default-plugins/status-bar-simple/src/main.rs` and `./default-plugins/tab-bar-simple/src/main.rs` and make the edits. From there I will have to read the docs.
2. I see `./example/default.yaml` I am just going to cp that to `./example/simplified.yaml` and make the edits.
3. I will have to dig in to find where command line args are called. So I can add the --layout flag.
4. I will skip the bonus points, but if someone else has a better name than simplified I am all ears. haha

**Comment by a-kenji** [comment]
Hey @alexhallam , that would be awesome!

>  For new versions of status-bar and tab-bar I am guessing I just cp default-plugins/status-bar/src/main.rs and ./default-plugins/tab-bar/src/main.rs to something like default-plugins/status-bar-simple/src/main.rs and ./default-plugins/tab-bar-simple/src/main.rs and make the edits. From there I will have to read the docs.

Yes!

> I see ./example/default.yaml I am just going to cp that to ./example/simplified.yaml and make the edits.

Almost, you want  `/assets/layouts/default.yaml` and can create an `/assets/layouts/simplified.yaml`

>I will have to dig in to find where command line args are called. So I can add the --layout flag.

You don't need to do that, when calling with the `--layout` flag zellij looks in the layout dir, or currently still the path you provide.
So you can test by providing the path to your current layout file, in this case
`--layout /assets/layouts/simplified.yaml`
If you overwrite the default layout, that zellij creates on startup for you, with the `simplified.yaml` then zellij would startup every time with the simplified version.

> I will skip the bonus points, but if someone else has a better name than simplified I am all ears.

I think its an apt name, but yes it is not very flashy.

If you have any more questions please don't hesitate with asking them!
