### ISSUE TITLE
Can we detach other users?

### ISSUE THREAD

**Issue by JerAguilon** [zellij-org/zellij#3134]
New user and big fan already. In tmux I had the ability to detach other users from a session:

https://stackoverflow.com/questions/22138211/how-do-i-disconnect-all-other-users-in-tmux

Is this possible in zellij?

**Comment by giyany** [comment]
This is not possible currently, however it's on the roadmap. Mentioned in #2913

**Comment by imsnif** [comment]
It's also been merged into `main` and will be available through the session-manager next version.

**Comment by JerAguilon** [comment]
Thanks all, closing.
