### ISSUE TITLE
Add a Command Mode

### ISSUE THREAD

**Issue by AbleArcher88** [zellij-org/zellij#3137]
Other terminal emulators have a command mode (tmux, screen). I have found this extremely helpful, as it allows for the editing of configuration on the fly. It also allows for a reduced number of default mappings, to maintain a working config

**Comment by jaeheonji** [comment]
Hi,  you can simulate the command mode using your own key combination as follows:

https://github.com/zellij-org/zellij/blob/eba597afc5373fc02062adf296be70db04ee9725/zellij-utils/assets/config/default.kdl#L124-L145

This is an example of zellij using Tmux's prefix key (ctrl + b).

If you have more questions, you can ask at Discussions Q&A. Thank you!
