### ISSUE TITLE
Opening lots of panes breaks zelliji and terminal

### ISSUE THREAD

**Issue by DianaNites** [zellij-org/zellij#315]
zellij 0.5.0, on Arch Linux, Fish shell, KDE Konsole

Holding `alt + N` until no more new panes can be created, and then holding `ctrl + D` to close the terminals, causes zellij to break and become unresponsive. On my terminal, doing this results in the final terminal in the lower right corner, and closing them works up until the lower left, but leaving space for the `Ctrl` part of the status line.

At this point it can no longer be closed normally, no longer accepts input in the shell or hotkeys, and doesn't respond to normal termination signals, requiring SIGKILL from another shell.

After killing it this way, it seems the terminal/shell/??? is left in an invalid state, most noticeable as scrolling no longer working properly, going through shell command history instead of.. scrolling. Unclear if this part is the terminal or shells fault, though.

**Comment by a-kenji** [comment]
Thank you!
Do you mind building from the current `main`, to check if that is still an issue?
If not, there should be a new release out in the coming days probably.

It is possible that  #314 Fixed your issue.
If not please reach out again!

**Comment by DianaNites** [comment]
Checked from main, issue does not occur!

**Comment by a-kenji** [comment]
Awesome, thanks!
