### ISSUE TITLE
Feature(Plugins): Make Plugins Configurable.

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#317]
This is an issue that has come up here and then.
Especially around theming the status-bar, as well as #313.

Depends on: https://github.com/zellij-org/zellij/issues/771

**Comment by spacemaison** [comment]
I submitted a [PR][pr] that makes it possible to pass configuration into plugins from the config file for Zellij.

[pr]: https://github.com/zellij-org/zellij/pull/660

**Comment by raphCode** [comment]
What is the current status of this issue? The PR got merged, and there is also this issue with a similar title: https://github.com/zellij-org/zellij/issues/661

**Comment by a-kenji** [comment]
There is no pr that fixes this issue that got merged.

**Comment by imsnif** [comment]
Implemented in #2646
