### ISSUE TITLE
Three Features I Would Like To See In Zellij

### ISSUE THREAD

**Issue by danieljaouen** [zellij-org/zellij#3177]
1. A "pane selection buffer" window, similar to tmux's "\<send-prefix> w".  And a way to move between selections using "j/k".
2. A way to test which OS Zellij is installed on, so I can use one config file on both my Linux and MacOS boxes (particularly useful for choosing between `copy_command`s).
3. A way to select text in scroll mode using keyboard-only shortcuts (similar to tmux's "\<send-prefix> [").

These are the only features stopping me from completely switching from tmux to Zellij, so if you implement them, you will gain at least one additional user.

Thanks!

**Comment by imsnif** [comment]
Hi, thanks for your thoughts. The issues in this repository are used to report bugs or request specific features. If you'd like to request specific features, please do so in an orderly fashion - and please read the issue template before doing so.

Cheers.

**Comment by danieljaouen** [comment]
@imsnif OK, that’s cool.  I just won’t use Zellij, then.

Cheers.

**Comment by imsnif** [comment]
Please use whichever software makes you happy.
