### ISSUE TITLE
Question: Autocompletion possible for layout KDL files in vscode?

### ISSUE THREAD

**Issue by joeskeen** [zellij-org/zellij#3181]
First off, I LOVE Zellij! It fills a huge need I had in my development workflow that TMUX failed at, namely repeatable layouts. And I'm happy that there is an extension for VSCode for authoring the kdl files. I'm also very happy that there are good docs for Zellij, including configuration.

I've grown accustomed to having autocompletion available when editing configuration files in VSCode, and for JSON and YAML files it works great via JSON schemas. Basically, if there is a `$schema` property defined, or VSCode can figure out the schema from the file name, it loads the schema and allows for validation and autocompletion throughout the file. I'm pretty new to KDL (I'm pretty new to Zellij and Zellij is the first time I was exposed to KDL). Is there a way to enable autocompletion for a Zellij configuration file? This could help developers like me more quickly understand the structure of these files, what properties are and aren't allowed, etc., and quickly identify and correct mistakes without having to go back and search through the docs every time.

**Comment by jaeheonji** [comment]
Hi, @joeskeen Thank you for loving zellij!

About the KDL autocomplete like JSON and YAML, This topic is related to KDL and VSCode Plugins. KDL is a really cool markup language, but unfortunately it is not yet as mature as JSON or YAML.

As far as I know, neither KDL nor VSCode (Official KDL Plugins) implement the features you want, at least not currently. 😭 

FYI, This is the official KDL repository (https://github.com/kdl-org/kdl)
