### ISSUE TITLE
Copy/Paste [Horror 😱 ] with Zellij

### ISSUE THREAD

**Issue by computersrmyfriends** [zellij-org/zellij#3185]
It was good all the way to use it.
I even used Alacritty to balance the act for copy/paste to work but unfortunately, I ended up frustrated because of the copy/paste having issues for remote connections and occasionally not working despite all the setup.

There's no default config which has to be manually created I guess. I tried that as well to use Xclip. It didn't work for me.

Finally, I am giving up on it. If only copy/paste didn't have issues, the product would at least be usable.

It's an amazing modern tool but the copy/paste limitations is extremely hard to bear with in today's world.

**Comment by imsnif** [comment]
I'm not really sure what this issue is about (as there is nothing actionable here and the issue template was ignored), but if you need support you are more than welcome to come and ask for it in one of our chat platforms. Copy/paste is working flawlessly for myself and countless others.

Cheers.

**Comment by computersrmyfriends** [comment]
Copy/paste works on linux on any terminal? Afaik,it only works on xterm and alacritty even as per your docs.

**Comment by giyany** [comment]
Copy+paste works well in some terminals and not in others. Limitations are the reality of any software, sorry to hear it's not working out for you. In the future, please do use the issue template - we get very many and this helps us manage them. Thank you
