### ISSUE TITLE
Reuse parts of layouts

### ISSUE THREAD

**Issue by mrdgo** [zellij-org/zellij#3186]
I haven't found anything related to this, so I hereby kindly request consideration of the following feature.
I use `dj95/zjstatus`. So I defined a statusbar to my likings. I currently have two layouts that should use the same bar. However, I can't find a way to define the config for the statusbar at one place and reuse it. I would love to have that ability.

**Comment by imsnif** [comment]
Hey, starting next version we'll be able to define "plugin aliases": https://github.com/zellij-org/zellij/pull/3157
So the gist of it is that you'll be able to define a plugin in one place and then use it in different layouts, from the CLI, etc. Will that work for your use case?
