### ISSUE TITLE
Some processes hang under zellij

### ISSUE THREAD

**Issue by jonjensen** [zellij-org/zellij#320]
I found that the program [glow](https://github.com/charmbracelet/glow) hangs when run under zellij, on macOS stock Terminal and Linux in Alacritty.

Likewise the Rust program [procs](https://crates.io/crates/procs) hangs when run under zellij on macOS stock Terminal, but oddly it works on Linux in Alacritty.

**Comment by a-kenji** [comment]
Thank you! 
I can reproduce a `glow` issue, does it also just hang initially once for you and then
once you hit enter it works?
That could have a lot of interactions.
One notable could be unhandled sequences.

If you want you can
`zellij --debug` and then run your programs, and look in
`cat /tmp/zellij/zellij-log/log.txt` and see if there is output there.
If there is please send us the file.

**Comment by jonjensen** [comment]
Yes, running `glow` hangs initially and after I hit enter *twice* then it runs.

What appears in the debug log is this, repeated a few times:

```
Unhandled csi: n->[6]
```

**Comment by a-kenji** [comment]
Thank you that is very helpful!

**Comment by nicoulaj** [comment]
Same issue for me when launching with zellij with strider layout in my home directory (`zellij --debug --layout strider`), it hangs forever:
```
Unhandled csi: t->[22, 0, 0]
```

**Comment by imsnif** [comment]
This is fixed in `0.10.0`. I tested with `glow` (which is a cool program! Thanks for introducing it to me :) ) - I think it's the same issue with procs (they were sending Zellij a signal which it was ignoring and so they waited indefinitely).

I'm closing this issue, but if anyone is still reproducing this with `0.10.0`, please tag me and I'll either re-open (if it's the same issue) or we can open a different issue if it's something else.

**Comment by jonjensen** [comment]
@imsnif I confirm that `0.10.0` fixes the problem with `glow`. Nice!

However, it's still not working with `procs`. It still waits till I press enter once. This time, sadly, there's nothing at all in the zellij debug log.

**Comment by imsnif** [comment]
@jonjensen - ah, damn! Must be a different problem with `procs`. For me it works, but it might be something particular to your setup.

The easiest way for me to debug this would be to get the pane logs. There are instructions on how to get them here: https://github.com/zellij-org/zellij/blob/main/.github/ISSUE_TEMPLATE/bug_report.md
If you would be willing to recreate the issue with procs and attach them, that would be a huge help. Thanks!

**Comment by jonjensen** [comment]
@imsnif Sure. I don't see anything useful there, but maybe you will. I posted them here so I can delete it later, if that's ok: https://jon.endpoint.com/tmp/zellij-procs-20210514.tar.gz

This is on a MacBook Air M1 2020, macOS 11.3, default macOS Terminal 2.11 (440), default zsh 5.8, procs 0.11.5 installed by Cargo, and zellij 0.10.0 installed by Cargo.

**Comment by imsnif** [comment]
Thanks @jonjensen - this was indeed helpful and I found the problem. There's another signal there that we're ignoring (it's requesting the terminal background color). This one might be a little trickier to implement, but I have some ideas. I'll take a gander at it at the beginning of next week and keep you posted.

**Comment by imsnif** [comment]
@jonjensen - this is fixed in `0.12.0` - for real this time ;P (if I'm lying again, please ping me and I'll re-open)

**Comment by jonjensen** [comment]
@imsnif Very nice! Works fine now for me with glow & procs, on Linux & macOS.
