### ISSUE TITLE
Crash switching tabs

### ISSUE THREAD

**Issue by vezult** [zellij-org/zellij#3204]
# 2. Issues with the Zellij UI / behavior / crash

## Issue description
```
  × Thread 'screen' panicked.
  ├─▶ Originating Thread(s)
  │     1. screen_thread: GoToTab
  │   
  ├─▶ At zellij-server/src/panes/tiled_panes/mod.rs:1574:50
  ╰─▶ called `Option::unwrap()` on a `None` value
  help: If you are seeing this message, it means that something went wrong.
```

This would have been version 0.39.2 on Debian 11 or 12, and running in a KVM virtual machine.

Apologies for the lack of precision. I apparently started this report several days ago, and I'm no longer sure which VM it was on.

## Minimal reproduction

I switch tabs frequently using either keybindings or mouse. I do not regularly encounter a crash when doing this.

I run zellij on the remote machine, and connect via ssh/mosh. My zellij instance runs 24/7, and I frequently connect and disconnect from the remote host.

In this case, I was unexpectedly disconnected due to a power failure on my local machine. I connected, attached to my zellij session, and when I attempted to switch tabs, I encountered this crash.

## Other relevant information

The zellij log did not appear to record the crash. This seems strange to me, and makes me wonder if I was looking at log from the wrong VM. I did look through logs on various machines, and couldn't find any crash that precisely matches this. I guess take the details, apart from the scenario above and the crash message itself, with a grain of salt.

**Comment by imsnif** [comment]
Hey, thanks for the report and apologies for the experience.

This was fixed in https://github.com/zellij-org/zellij/pull/3166 - will be released with the next version.

**Comment by vezult** [comment]
Excellent. Thanks!
