### ISSUE TITLE
Runtime Option to enable/disable borders for easier copy/paste operations

### ISSUE THREAD

**Issue by xjvs** [zellij-org/zellij#3215]
Dear Zellij Developers,

I've been using Zellij with great satisfaction and truly appreciate the functionality and improvements it brings to terminal multiplexing. It's been a fantastic tool in my daily work.

I've encountered a minor inconvenience that I wanted some help. When copying and pasting multiple lines of commands using the mouse, the pane borders are also copied. This requires me to copy and paste lines individually to avoid including the border characters, which can be somewhat cumbersome.

As a temporary solution, I've configured my layout to set panes as borderless by using `borderless=true` in the layout configuration, like so:

```
layout {
    pane size=1 borderless=true {
        plugin location="zellij:tab-bar"
    }
    pane split_direction="vertical" {
        pane borderless=true
    }
}
```
This approach works initially but encounters limitations when opening new panes within the tab. Newly opened panes display with borders, and, interestingly, after closing these new panes, the original pane's borderless setting seems to revert, displaying borders once again.

To enhance user experience and streamline the copy/paste process, would it be possible to introduce a feature allowing users to enable or disable pane borders dynamically at runtime? Such a feature would provide tremendous convenience, enabling temporary border removal for seamless copy/paste operations without affecting the overall layout or necessitating configuration adjustments.

**Comment by cristiand391** [comment]
> When copying and pasting multiple lines of commands using the mouse, the pane borders are also copied.

By default this shouldn't happen, could you follow the issue template? maybe it's something with your config or terminal being used.
https://github.com/zellij-org/zellij/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

> To enhance user experience and streamline the copy/paste process, would it be possible to introduce a feature allowing users to enable or disable pane borders dynamically at runtime? 

You can set a keybind for that using the `TogglePaneFrames` action:
https://zellij.dev/documentation/keybindings-possible-actions#togglepaneframes

and can also disable borders by default:
https://zellij.dev/documentation/options.html?highlight=pane_frames#pane_frames

**Comment by xjvs** [comment]
> > When copying and pasting multiple lines of commands using the mouse, the pane borders are also copied.
> 
> By default this shouldn't happen, could you follow the issue template? maybe it's something with your config or terminal being used. https://github.com/zellij-org/zellij/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

@cristiand391 thank you for your response, I realized my description of the issue was vague and unclear. While copying and pasting, I'm using the combination of "SHIFT + <left mouse select>" for copying and "SHIFT + <middle mouse click>" for pasting. When SHIFT is used, the border of pane will also copied, while left mouse select won't. So I can use <left mouse select > and <CTRL+SHIFT+v> to copy&paste text, I was not aware of this, thanks.

I can't recall why I always use SHIFT + <mouse select> to copy text, probably it's the only way to use middle mouse to paste text in zellij.

Since I have an alternative solution (<mouse select> -> CTRL+SHIFT+v, probably the "SHIFT" behavior described in this issue is expected, I'm closing this issue. Thank you again.

> 
> > To enhance user experience and streamline the copy/paste process, would it be possible to introduce a feature allowing users to enable or disable pane borders dynamically at runtime?
> 
> You can set a keybind for that using the `TogglePaneFrames` action: https://zellij.dev/documentation/keybindings-possible-actions#togglepaneframes
> 
> and can also disable borders by default: https://zellij.dev/documentation/options.html?highlight=pane_frames#pane_frames

Thank you, these options work for me.
