### ISSUE TITLE
Multiple crates missing `repository` field

### ISSUE THREAD

**Issue by paolobarbolini** [zellij-org/zellij#3241]
Hi! As part of our efforts to verify that crates.io releases are reproducible [^1], we have discovered that one or more crates hosted in this repo are missing the `repository` field [^2] in `Cargo.toml`.

The `repository` field helps users and automated tools find the link to the git repository hosting the source code. While not required by crates.io, we believe it should always be set.

We ask that the `repository` field be configured for **every crate** published to crates.io. Thank you very much.

[^1]: https://github.com/M4SS-Code/cargo-goggles/issues/11
[^2]: https://doc.rust-lang.org/cargo/reference/manifest.html#the-repository-field

**Comment by imsnif** [comment]
Hey - just so everyone's on the same page here, who is "we"?

**Comment by paolobarbolini** [comment]
Sorry for the confusion. What I meant by "we" is the contributors to https://github.com/M4SS-Code/cargo-goggles

**Comment by imsnif** [comment]
So... a [commercial company](https://github.com/M4SS-Code)?

**Comment by paolobarbolini** [comment]
I'm sorry. I think I get what you mean and you're right. I started this wanting to help the community and not annoying it and I think I did just that by going around opening issues.

**Comment by imsnif** [comment]
Yes. A full disclosure in the original message would be appropriate IMO. In general, my opinion on this is that if you're creating a commercial product and intend to make money off of open-source in a direct or indirect way - let the people who create the content you're making money off of know about it and decide for themselves.

Good luck to you, in any case. I do respect your self reflection.
