### ISSUE TITLE
ui(compact-bar): mode indicator not centered

### ISSUE THREAD

**Issue by cristiand391** [zellij-org/zellij#3248]
# 2. Issues with the Zellij UI / behavior / crash

## Issue description

I noticed the mode indicator isn't correctly centered when the mode name length > 6, you can see in this video how when switching to renametab/renamepane  the text isn't padded (IIRC it's not noticeable on the left side because the `Zellij (session-name)` section includes a whitespace).
[Screencast from 04-06-2024 05:32:06 PM.webm](https://github.com/zellij-org/zellij/assets/6853656/40e8096b-d4db-4cd0-88c6-ffdb1f7079f9)

This is how I improved the padding in my fork of compact-bar, you can see the mode name is always centered (even short ones like `pane`):
[Screencast from 04-06-2024 05:44:54 PM.webm](https://github.com/zellij-org/zellij/assets/6853656/eeaf4a3d-b5bb-4773-8262-bf8854b447a0)

https://github.com/cristiand391/zj-status-bar/commit/2de3d60446dfe8fe9d9037122d77daf927be8d7d

If the current padding behavior in zellij's compact-bar isn't the intended and the maintainer agrees, I'm happy to contribute the fix upstream.

## Minimal reproduction

save this as layout
```
layout {
  pane size=1 borderless=true {
    plugin location="zellij:compact-bar"
  }
  pane
}
```
switch to renametab or any mode name > 6:
```
zellij action switch-mode renametab
```

![image](https://github.com/zellij-org/zellij/assets/6853656/4c7e742c-f915-4534-91b3-0524f2319373)

## Other relevant information
```
zellij --version
zellij 0.39.2

stty size
35 159
```

**Comment by Zykino** [comment]
Love that fix, looks elegant to me. Not sure what maintainers would think of it.

**Comment by cristiand391** [comment]
> Just thinking about it, another/easier fix would be: let mode_part_padded = format!(" {} ", mode_part); isn’t it?

ha, yes that should work too, good catch. I probably went with the aligment solution because I read that was a thing in the docs 😄 
https://doc.rust-lang.org/std/fmt/index.html#fillalignment

**Comment by Zykino** [comment]
Yup, and the starting code you had was like this, so I think I would have done the same at first too ^^.

**Comment by jaeheonji** [comment]
That's great, I love it too. If possible, can you make a PR?

**Comment by cristiand391** [comment]
@jaeheonji 
Here it is: https://github.com/zellij-org/zellij/pull/3260
with @Zykino's suggestion to just use whitespaces instead of dynamic alignment  :)
