### ISSUE TITLE
Ctrl-p is already a key combo in bash

### ISSUE THREAD

**Issue by ijt** [zellij-org/zellij#326]
I'm used to using ctrl-p to get the previous line of input in bash. Now in zellij, that key combination brings up pane-related options instead. It may be tough to go against this muscle memory, so I would like to suggest an alternative key binding for pane things, for example alt-p.

**Comment by horasal** [comment]
It's able to make your own keybinds [through a config file](https://zellij.dev/documentation/keybindings.html).
Try modify `example/default.yaml` and run `zellij --config example/default.yaml` for a quick taste.

**Comment by imsnif** [comment]
Also, if you don't want to modify keys, you can use `ctrl-g` to lock the interface and then all keys (except another ctrl-g) will pass through to the terminal.

**Comment by qballer** [comment]
default alt+p for the mac people might be an issue.

**Comment by jsoo1** [comment]
I would love to try zellij but the defaults conflict with too many standard key bindings and the styling is too opinionated by default. I would love if zellij provided a minimal set of defaults instead.

**Comment by c02y** [comment]
I already comment out this following part which activates Pane mode in my config.kdl file
```
    // shared_except "pane" "locked" {
    //     bind "Ctrl p" { SwitchToMode "Pane"; }
    // }
```
But `Ctrl-p` still activate the Pane mode, so as other bindings such as Resize/Session/Scroll/... modes.

And I'm using fish, `Alt-p` is a builtin binding in fish shell, but `Alt-p` in fish+zellij doesn't work at all, and other bindings I defined for fish shell are also not working.

So there are serious binding issues in zellij code.

**Comment by imsnif** [comment]
@c02y - please see the first line of the dumped config file, there is a commented out line there with an explanation on how to solve this situation and why it happens.

For everyone else, please see: https://zellij.dev/documentation/faq#zellij-overrides-certain-key-combinations-that-i-use-for-other-apps-what-can-i-do

**Comment by c02y** [comment]
Yeah, sorry, my bad, ignored the first line of the file. Since it is the default config, I thought if I delete it then it will not work.
