### ISSUE TITLE
Unable to open directory from strider - filepicker

### ISSUE THREAD

**Issue by matiux** [zellij-org/zellij#3267]
stty size: 57 202
zellij: 0.40.0
uname -av: Linux iuxhome 6.8.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 11 Apr 2024 01:47:33 +0000 x86_64 GNU/Linux
zsh --version: 5.9 (x86_64-pc-linux-gnu)
ohmyzsh
powerlevel10k

Step to reproduce:

Add key binding
```
bind "Alt f" {
   LaunchPlugin "filepicker" {
      close_on_selection true
   };
}
```

Press Alt + f to open the filepicker, than,navigate to desired folder:

![Screenshot_20240416_152742](https://github.com/zellij-org/zellij/assets/821668/a3a3e98f-b691-4c5d-bb1f-33605607726f)

Press TAB to select desired folder, in my example zellij:

![Screenshot_20240416_153034](https://github.com/zellij-org/zellij/assets/821668/7e69d8af-4fbd-489d-b23f-1439ac88a8bc)

Press enter to open folder in the right panel, but nothing happens. The position in the right panel doesn't change. Is this behavior correct?

P.s. However, if I select a file, it opens without problems

**Comment by cyayon** [comment]
hi,
same issue here

**Comment by quanhua92** [comment]
I am using Ubuntu 22.04 and having this issue as well

**Comment by imsnif** [comment]
To those experiencing this issue: if you set the `default_shell` in the [config](https://zellij.dev/documentation/configuration) to something (eg. `bash`) and then start a new session, does it work?

**Comment by quanhua92** [comment]
@imsnif Setting `default_shell` fixes the bug for me. My `$SHELL` is `/bin/bash`, I set the `default_shell` to `bash`

**Comment by imsnif** [comment]
Thanks @quanhua92, I'll fix this in a patch soon. For now, at least we have a temporary workaround.

**Comment by matiux** [comment]
@imsnif tryed with `default_shell "zsh"` and `default_shell "/usr/bin/zsh"` but it stil doesn't work form me. 

```
echo $SHELL
/usr/bin/zsh
```

**Comment by matiux** [comment]
maybe problem with zsh / oh-my-zsh / powerlevel10k ?

**Comment by matiux** [comment]
I've just discovered that even though I'm using zsh, setting `default_shell "bash"` solves my problem... Is it correct?

**Comment by matiux** [comment]
@imsnif seems to be some problems with zsh. At the top of my zsh config file I have this, I don't know if it could matter:

```
if [[ ! -v ZELLIJ || ( -v ZELLIJ && $ZELLIJ -eq 1 ) ]]; then
	zellij attach --create default-session
fi
```

to attach zellij to a specific existing session. 

setting `default_shell "bash"` obviously makes me lose zsh when I open panels. On the other hand setting `default_shell "zsh"` introduces a strange behavior. Please, see attached video. As you can see, pressing enter to open a folder, closes the filepicker and breaks the layout. (with default_shell "zsh")


[Screencast_20240417_192108.webm](https://github.com/zellij-org/zellij/assets/821668/213f545a-0a2c-4f0f-b8cf-5203be36dc54)

**Comment by rockboynton** [comment]
default_shell "fish" works as a workaround for me

**Comment by matiux** [comment]
@rockboynton are you using zsh?

According to the documentation, fish should be the default shell. Even when commented out, the behavior should remain the same.

**Comment by rockboynton** [comment]
@matiux no, I have my `$SHELL` set as `fish` and the filepicker (strider) worked before v0.40 without setting this config, but now I have to explicitly set it for it to work

**Comment by matiux** [comment]
@rockboynton the problem seems to be related to zsh. I would like to have more feedback with zsh besides my own

**Comment by matiux** [comment]
There seems to be no clear solution. Or maybe I don't understand how

**Comment by matiux** [comment]
Hi @imsnif, any news or suggestion ?

**Comment by matiux** [comment]
My apologies for tagging you. I just thought you might have a better understanding of the project. By the way, to lunch zellij, I simply put this at the beginning of the ~/.zshrc file

```
if [[ ! -v ZELLIJ || ( -v ZELLIJ && $ZELLIJ -eq 1 ) ]]; then
        zellij attach --create default-session
fi
```

is it a wrong approach?

**Comment by matiux** [comment]
Thanks. Hope this patch will fix also for zsh
