### ISSUE TITLE
action rename-tab not functioning

### ISSUE THREAD

**Issue by burgessa23** [zellij-org/zellij#3269]
## Issue description

`zellij action rename-tab` does not change tab name 

## Minimal reproduction

1. open a new tab
2. run `zellij action rename-tab "alice the cat"`
3. notice that the tab name has not changed

## Other relevant information
zellij version 0.4.0

**Comment by tmerse** [comment]
For me `zellij action rename-tab` will change the tab name to empty string after upgrading to 4.0.

Anyhow congrats and thanks for the 4.0 release!

**Comment by Segaja** [comment]
I can confirm this issue and this also affects `zellij action rename-pane "test"` which just doesn't do anything.

For neither of these commands is anything written to the log.

**Comment by marmeladema** [comment]
Hi!
I am hitting this bug with 0.40.0, would it be possible to tag a new release?
Or is the appropriate thing to do is to use the main/master branch?

**Comment by imsnif** [comment]
Please be patient, a patch will come when it's ready. You are more than welcome to use main if you like.
