### ISSUE TITLE
strange behavior when setting `[shell]` in Alacritty

### ISSUE THREAD

**Issue by burgessa23** [zellij-org/zellij#3270]
# 2. Issues with the Zellij UI / behavior / crash

## Issue description
Setting zellij as the default program in alacritty config yields differing results depending on how Alacritty is launched.
I'm not sure if this is even an issue with zellij, but opening this for awareness

## Minimal reproduction
This is quite strange, I'm not sure what the difference is between opening an app via its icon vs. via the `open` cli command

1. in alacrity.toml set 
```
[shell]
program = "zellij"
args = ["-l", "welcome"]
```
   as per https://zellij.dev/tutorials/session-management/#setting-up-the-welcome-screen-to-open-on-terminal-startup

2. launch alacritty by clicking the icon in finder 
3. notice alacritty fails to open
4. open terminal
5.  launch alacritty via `open` command 
6. notice it opens as expected

## Other relevant information
zellij 0.4.0

**Comment by burgessa23** [comment]
Another interesting development... using a `precmd` hook in .zshrc that calls a function:
```
function zellij_autostart() {
    exec zellij -l welcome
}
```
works as expected.

**Comment by TheKissOfDragon** [comment]
my Alacritty can't launch agin,when i set the config as below later
[shell]
program = "zellij"
args = ["-l", "welcome"]

**Comment by imsnif** [comment]
So - while I totally believe you, I am not reproducing this. Anything in the logs? Either Zellij or Alacritty? In linux the logs are in `/tmp/zellij-log` - I'm not sure offhand where they are in mac (it's a system setting)

**Comment by imsnif** [comment]
Some more guesses (though I could really use info either from the Zellij or the Alacritty logs):
1. If you set the shell in alacritty to the absolute path of Zellij, does it work?
2. Is Alacritty running from the same user as Zellij is installed as?

**Comment by NyxAlexandra** [comment]
I'd imagine the difference is due to not having `zellij` on path when running without your shell setting the env first

**Comment by TheKissOfDragon** [comment]
Thank you for the explanation. Regarding the specific absolute path of Zellij, it is working fine for me. That's great! I have encountered a small issue, which may or may not be a problem, as shown in the second picture.
<img width="1514" alt="image" src="https://github.com/zellij-org/zellij/assets/12746438/dc094014-83d0-4edd-a16c-25b50aa821dd">
<img width="1137" alt="image" src="https://github.com/zellij-org/zellij/assets/12746438/31d6930a-3161-4ae2-9db4-34811ac8b3ed">

**Comment by imsnif** [comment]
That's not a problem - it's art. ;)

Glad it's sorted!

**Comment by burgessa23** [comment]
> 1. If you set the shell in alacritty to the absolute path of Zellij, does it work?
That was it, Thanks
