### ISSUE TITLE
right-click to paste with windows terminal

### ISSUE THREAD

**Issue by Blues-star** [zellij-org/zellij#3271]
## Issue description
When using Zellij with Windows Terminal, the current mouse interactions for copy and paste are not intuitive and do not align with common expectations. Specifically, left-click selects and automatically copies text, but right-click does not paste the copied text unless combined with keyboard shortcuts (CTRL+V or SHIFT+INSERT). Ideally, I would like the ability to configure mouse interactions such that:
- Left-click selects text.
- Right-click after selection copies the selected text.
- Right-click without a previous selection pastes the last copied text.

## Minimal reproduction
1. Open Windows Terminal with Zellij.
2. Select text using the mouse left-click.
3. Attempt to copy with right-click (no effect).
4. Attempt to paste with right-click (no effect, requires keyboard shortcuts).

## Other relevant information
This behavior is not consistent with many other terminal emulators where mouse interactions are more flexible and intuitive. Enhancing mouse support in Zellij could significantly improve usability, especially for users frequently interacting with the terminal for copy-paste operations.

**Comment by giyany** [comment]
Surprised by this issue as currently Zellij does not offer Windows support (cut hopefully in the future, #2926)

**Comment by Blues-star** [comment]
I find that if I hold down the shift key, the above behavior works normally. I'm not too clear on the key forwarding principle of the terminal multiplexer, but I'm very curious as to why this is the case.

**Comment by ianyepan** [comment]
I believe if you do normal left click and right click, Zellij receives the mouseclick (and perform Zellij-defined actions, which doesn't include right click for copy/paste). When you hold 'shift' + mouse click, only the terminal app receives it so you can use them for actions you're used to. The mouseclicks don't get passed to Zellij when you hold down 'shift'.

**Comment by ianyepan** [comment]
This guy explains it better: https://github.com/zellij-org/zellij/issues/3159#issuecomment-1964874095

**Comment by tamir-bahar** [comment]
Is there a way to make it work without holding `shift`?
