### ISSUE TITLE
compact-bar: changing modes causes the tab list to shift

### ISSUE THREAD

**Issue by LechintanTudor** [zellij-org/zellij#3276]
The tab list shifts its position based on how long the mode string is. Changing the mode from "NORMAL" to "TMUX" causes the tab list to shift to the left because "TMUX" has 2 characters less than "NORMAL".

![Screenshot from 2024-04-18 17-58-36](https://github.com/zellij-org/zellij/assets/52962370/d8096944-a36c-40cb-a23e-5cac820c03b2)
*NORMAL mode*

<br />

![Screenshot from 2024-04-18 17-58-41](https://github.com/zellij-org/zellij/assets/52962370/41ef99bd-5d27-420a-94f0-fd11038d0c4e)
*TMUX mode*

**Comment by cristiand391** [comment]
Hey, this was done to fix the inconsistent padding behavior:
https://github.com/zellij-org/zellij/pull/3260

the tab list shift was already happening before the change on mode names > 8 (see the "before" gif in the linked PR).

One way to avoid the shift could be to always fill the mode section with whitespaces, length equal to the largest mode then center it, but that might look "weird" on short names.

**Comment by LechintanTudor** [comment]
Thanks for the explanation, I see that this is working as intended.

Still, is it possible to change the mode text displayed in the bar? I would like to add some padding so that the tab list doesn't shift.

**Comment by cristiand391** [comment]
> Still, is it possible to change the mode text displayed in the bar? I would like to add some padding so that the tab list doesn't shift.

no, you would have to fork the default compact-bar plugin to do that.
