### ISSUE TITLE
`previous-swap-layout` doesn't work when loading a layout from a file

### ISSUE THREAD

**Issue by nando-digital** [zellij-org/zellij#3290]
# 2. Issues with the Zellij UI / behavior / crash

## Issue description
`previous-swap-layout` and `next-swap-layout` do not work when zellij was started with a layout located in a file. When executing `zellij action next-swap-layout` inside zellij nothing happens (no error) even though the split direction should change. I noticed this because the `ALT [` keybinding didn't work.

## Minimal reproduction
1. Start zellij with `zellij --layout default`
2. Open a second pane
3. Run `zellij action next-swap-layout` (or `ALT ]` when using default shortcuts)
4. Notice how the split direction changed
5. Run `zellij setup --dump-layout default > someFile` inside a new terminal
6. Start zellij again with `zellij --layout /path/to/someFile`
7. Open a second pane
8. Run `zellij action next-swap-layout` (or `ALT ]` when using default shortcuts)
9.  Notice how the split direction **has not** changed

Even though the exact same layout is used the behavior is different.

## Other relevant information
It doesn't matter whether the layout is specified in the zellij config or with the `--layout` argument
I use zellij 0.40.0 on Arch Linux (WM: Hyprland, Terminal: foot)

**Comment by imsnif** [comment]
You'll need to include `swap_layouts` in the custom layout file for this to work: https://zellij.dev/documentation/swap-layouts

**Comment by imsnif** [comment]
I agree - the swap layouts are not one of my best ideas. I hope to improve upon them in the future.
