### ISSUE TITLE
Layout's exact file location are not exposed to plugins. `NewTabsWithLayout` only takes ready made layout data.

### ISSUE THREAD

**Issue by CraigglesO** [zellij-org/zellij#3291]
Currently, the API has a function `NewTabsWithLayout` that requires a layout to be passed in. However, each session stores layouts as `LayoutInfo` which gives the name but not the file location. The best case for me is to either add another function or update `NewTabsWithLayout` to use the name and grab the layout information from the file for the plugin.

**Comment by imsnif** [comment]
Implemented in https://github.com/zellij-org/zellij/pull/3305 - thanks for your feedback!

**Comment by CraigglesO** [comment]
You both exposed `new_tabs_with_layout_info` AND `layout_dir` really quickly. Wow sir you are awesome. TYSM.
