### ISSUE TITLE
Control + Shift combination doesn't work on nvim

### ISSUE THREAD

**Issue by elferherrera** [zellij-org/zellij#3306]
**Basic information**

`zellij --version`: 0.40.0

`stty size`: 75 292

`uname -av` or `ver`(Windows): Darwin

I have defined keybindings in nvim that use the ctrl + shift combination. When using zellij in lock mode, those keybindings no longer work. 

Is there a way to get this working?

**Comment by cristiand391** [comment]
could you share a bit more about your setup?
specifically:
1) which terminal (and version) are you using with zellij?
2) does that keybind work on the same terminal when running outside of zellij?

I haven't tried using ctrl + shift on neovim but this posts mention you need to configure alacritty for it to work:
https://www.reddit.com/r/neovim/comments/mbj8m5/how_to_setup_ctrlshiftkey_mappings_in_neovim_and/?rdt=41558

**Comment by elferherrera** [comment]
@cristiand391 sorry I didn't replied before but I found that it isn't possible to do that with zellij. I changed my keybindings to accommodate to this limitation. I'll close this issue
