### ISSUE TITLE
Generating completion rather than keeping it in the repo?

### ISSUE THREAD

**Issue by matthiasbeyer** [zellij-org/zellij#331]
Maybe this would be a nice idea, which would reduce maintenance burden here?

I might be able to file such a PR, if this is something that would be merged. :+1:

**Comment by a-kenji** [comment]
I think that would be very welcome. 
Ill cc people that have more to do with the build process.
@qballer @TheLostLambda @henil 

On a somewhat related note, I want to use crate modules in the `cli.rs`, but currently that would break the `build.rs` `include!()` would what you propose allow something like that?
Everything solution I seem to otherwise find for that is either bundle it in a different crate, or duplicate effort.

**Comment by matthiasbeyer** [comment]
The `include!()` is only necessary because the completions are generated in the `build.rs`. If that should be kept, we'd need to solve that issue.

What I do in my binaries is that the binary itself has a `TOOL generate-completions <shell>` subcommand and users can simply generate their own. Not sure whether this is wanted by you guys here. Distributors of the tool can still generate completions and ship with distro packages, of course.

**Comment by a-kenji** [comment]
I am all for this solution, lets see what the other people say.

**Comment by matthiasbeyer** [comment]
I'd love to PR this, if the others give me a "go"! :smile:

**Comment by TheLostLambda** [comment]
> What I do in my binaries is that the binary itself has a `TOOL generate-completions <shell>` subcommand and users can simply generate their own

Works for me! We could even do some fancy auto-installing if we're feeling brave. The binary already installs a set of configuration and data files on first run, so I'm all for this if we can implement it cleanly!

**Comment by matthiasbeyer** [comment]
Okay, I'll file a PR this weekend I guess! :rocket: 

> We could even do some fancy auto-installing if we're feeling brave. 

That's another discussion entirely (one that I have very strong feelings about, so if you start a Issue on this I'd love to be part of the discussion).

**Comment by a-kenji** [comment]
> That's another discussion entirely (one that I have very strong feelings about, so if you start a Issue on this I'd love to be part of the discussion).

 We have one already on the config section, since that was a very often requested issue, #283
I would love more input on it. I am also not sure if that is the way to go so more opinions are very welcome.

**Comment by a-kenji** [comment]
Thank you for implementing this, sorry for the too eager merge!
