### ISSUE TITLE
scroll like a pager

### ISSUE THREAD

**Issue by bladrome** [zellij-org/zellij#333]
The shortcuts of zellij are amazing, it makes zellij as a multiplexer out of box. But the j/k in scroll is TOO slow when the output is huge. C-v, M-v, or PageUp PageDown is badly needed. 
![20210423_174345](https://user-images.githubusercontent.com/16330525/115853350-a90b4780-a45b-11eb-8d9a-cff2560f9d50.jpg)

**Comment by a-kenji** [comment]
Hey! Thank you. as of `0.5.1` there should be a pager like feature included. Do you mind trying it out? Is that screenshot a bug? What happened?

**Comment by bladrome** [comment]
> Hey! Thank you. as of `0.5.1` there should be a pager like feature included. Do you mind trying it out? Is that screenshot a bug? What happened?

Thanks very much, I just try `0.5.1`, PageUp/PageDown is good. The screenshot is a bug (when I first hit a bunch of keys), but I can't repeat it at `0.5.1` .   Thank you for you kindness and wish zellij a great success.

**Comment by a-kenji** [comment]
Awesome! Thank you for the wishes!
