### ISSUE TITLE
"your terminal doesn't support cursor position requests (CPR)" message when running pgcli

### ISSUE THREAD

**Issue by fabiomargarido** [zellij-org/zellij#334]
First of all, thank you very much for the very promising software. Have been using it for a few days and very much looking forward for detach support so I can replace tmux with it 🙂 

In my tests I've noticed an issue when running [pgcli](https://github.com/dbcli/pgcli) under Zellij. Right after connecting to a database, I get the message:

> WARNING: your terminal doesn't support cursor position requests (CPR).

I'm guessing because of this, I can't paste a multiline SQL query into pgcli because it'll be interpreted line by line.

Please let me know if I can provide further info, and thanks again.

**Comment by imsnif** [comment]
Hey, this should be fixed in `0.10.0` - could you please check?

**Comment by fabiomargarido** [comment]
Hey @imsnif I'm very sorry I missed this message and took so long to reply...

I can confirm the warning message is no longer there (tested with 0.11), thanks for looking into this.

However, the behavior I described in the original issue, where multiline text is executed line by line when pasted is still there. Should I open a separate issue for that?

**Comment by imsnif** [comment]
That would be great, thanks @fabiomargarido !
