### ISSUE TITLE
feature request: help window with keybindings

### ISSUE THREAD

**Issue by depeo10** [zellij-org/zellij#3348]
Hi,
I like Zellij but I don't think I'll ever learn all the keybindings. 

Would it be possible to add some kind of floating help window that can be accessed with ctrl +h or whatever, where all keybindings are presented?

That would be great.
This would help new users as well.

**Comment by imsnif** [comment]
The keybindings appear out of the box by default on the bottom line. If you'd like them in a dedicated window (for example if you're using the compact layout), checkout [zellij forgot](https://github.com/karimould/zellij-forgot).

**Comment by depeo10** [comment]
Oh thats great,  I'll look at that plugin also.
