### ISSUE TITLE
Compiling from source

### ISSUE THREAD

**Issue by happysalada** [zellij-org/zellij#335]
I'm trying to compile from source for NixOS. 
I am using the crate to get the source, is that the right way?
I noticed that the source code for the crate doesn't include the Makefile.toml.
I also get a fail when running the tests.
```
error: couldn't read src/common/input/./unit/keybinds_test.rs: No such file or directory (os error 2)
   --> src/common/input/keybinds.rs:474:1
    |
474 | mod keybinds_test;
    | ^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `zellij`

To learn more, run the command again with --verbose.
error: builder for '/nix/store/wnzpf94kchjjz6bzk8afbfyaaxgmq1qa-zellij-0.5.1.drv' failed with exit code 101;
       last 10 log lines:
       >    --> src/common/input/keybinds.rs:474:1
       >     |
       > 474 | mod keybinds_test;
       >     | ^^^^^^^^^^^^^^^^^^
       >
       > error: aborting due to previous error
       >
       > error: could not compile `zellij`
       >
       > To learn more, run the command again with --verbose.
```

`cargo build --release --all-features` runs successfully.
Then I'm running a simple `cargo test` and that gives the above error

I'm wondering if it is advised to compile from the source in the github repo instead.

I'm trying to compile version 0.5.1

**Comment by a-kenji** [comment]
Try to build it with the devshell from https://github.com/a-kenji/zellij-nix .
If you have issues, please don't hesitate to ask.
It should support 
`nix run`, `nix build` and installing through `nix-env -if . `

**Comment by a-kenji** [comment]
Ah, nvm. I didn't realize you were going from crates. Since the wasm plugins are in their own workspaces cargo alone doesn't currently build the project correctly, so I am guessing that is the problem. If you want to get it from crates and build, I think you will want the `Makefile.toml`, but I am not sure. If that is required I think we can add it back, though I believe there might be more required.

cc @TheLostLambda

**Comment by happysalada** [comment]
I just checked and the source I get from the crate doesn't include some unit test folder. This is why I am getting this error.

I guess, I will need to get the source from the github. No problem.

You have flake! Amazing!
Just curious though, why did you not put some nix stuff directly in this repo?
You didn't want to make it too crowded?

Thanks for the quick reply!

**Comment by a-kenji** [comment]
> I just checked and the source I get from the crate doesn't include some unit test folder. This is why I am getting this error.

Ah, yes we just recently excluded these files from export.

>You have flake! Amazing!
Just curious though, why did you not put some nix stuff directly in this repo?
You didn't want to make it too crowded?

I guess I need to be more persuasive!
