### ISSUE TITLE
zellij action rename-tab

### ISSUE THREAD

**Issue by n8henrie** [zellij-org/zellij#3359]
## Issue description

Sorry for the premature submission -- fatfinger.

I'm trying to rename a tab from within zellij, but it's telling me I don't have an active session for some reason.

The docs make it seem like this should work: https://zellij.dev/documentation/cli-actions.html#rename-tab

Am I doing something wrong?

## Minimal reproduction

```console
$ sw_vers
ProductName:            macOS
ProductVersion:         14.4.1
BuildVersion:           23E224
$ zellij --version
zellij 0.40.1
$ zellij action rename-tab foo
There is no active session!
```

## Other relevant information

<img width="919" alt="Screenshot 2024-05-17 at 16 56 29" src="https://github.com/zellij-org/zellij/assets/1234956/1f45cc11-6766-4cbc-ac67-92803e938741">

**Comment by imsnif** [comment]
What are you getting with `echo $ZELLIJ_SESSION_NAME`?

**Comment by n8henrie** [comment]
```console
$ zellij action rename-tab foo
There is no active session!
$ echo $ZELLIJ_SESSION_NAME
main
```

**Comment by n8henrie** [comment]
Hmm, also other commands:

```console
$ zellij plugin -- file:~/.config/zellij/plugins/room.wasm
There is no active session!
```

**Comment by n8henrie** [comment]
Hmmm, detaching from the session and restarting the session seems to have resolved the issue (I can now rename tabs).

Unfortunately it also lost all my carefully named and organized tabs (trying to migrate from tmux). My named `main` session appears nowhere in the session manager (including the `Resurrect Session` tab). No idea what happened there.

**Comment by Zykino** [comment]
Maybe you started your session in 0.40.0 and then upgraded to 0.40.1? Zellij cannot upgrade session from one version to another.

**Comment by n8henrie** [comment]
That could be!
