### ISSUE TITLE
Detach single users

### ISSUE THREAD

**Issue by EntilZha** [zellij-org/zellij#3362]
I'm currently alternating work between two computers, attached to the same zellij session. E.G., one computer at home, then go to office where I work as well.

Is there a way to force detach of specific users? E.G., if while at office, I forgot to detach the session from home (whether it is "active" or "dormant" from closed laptop), so the window panes are using the sizes of that still attached user.

I looked at: session -> session manager, and can see there are 2 connected users, but don't see a way to force a disconnect.

Thanks!

**Comment by imsnif** [comment]
Yeah sure - check out in the session manager, in the `Attach to Session` section (should be the default one when opening), you can do `Ctrl x` do disconnect others.

**Comment by EntilZha** [comment]
Great! I wasn't on the latest version so missed that, but see it now that I've upgraded. Thanks!
