### ISSUE TITLE
Glitches with Powerlevel10K Instant Prompt

### ISSUE THREAD

**Issue by danisztls** [zellij-org/zellij#337]
Only happens when using  the [instant prompt](https://github.com/romkatv/powerlevel10k#instant-prompt) feature.

![Screenshot from 2021-04-23 09-49-29](https://user-images.githubusercontent.com/13279154/115873362-39746880-a419-11eb-868a-8e692db46c2d.png)

**Comment by lbcnz** [comment]
Which is bypassable on the user side by adding the conditional  `&& ! [ $ZELLIJ ]` to the invocation IF clause at the top of `.zshrc `.

**Comment by a-kenji** [comment]
Thank you for the report and the bypass action.

Thank you! That could have a lot of interactions.
One notable could be unhandled sequences.

Do you mind investigating the problem?
zellij --debug and then run your zsh, and look in
cat /tmp/zellij/zellij-log/log.txt and see if there is output there.
If there is please send us the file. Also in this case since there is graphical messes please attach the other logfiles if you are comfortable with that.

**Comment by lbcnz** [comment]
I don't know exactly what Instant Prompt does but I guess it preloads a mock that is replaced later by the real thing. 

from the top of `.zshrc`
```sh
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
```

Just running `zellij --debug` a single time, doing nothing and exiting, created 3 logs.

![Screenshot from 2021-04-23 10-41-12](https://user-images.githubusercontent.com/13279154/115879860-7ee86400-a420-11eb-8deb-285338448b0d.png)

![Screenshot from 2021-04-23 10-41-18](https://user-images.githubusercontent.com/13279154/115879862-80199100-a420-11eb-8390-3bd1a867fcaf.png)

![Screenshot from 2021-04-23 10-41-26](https://user-images.githubusercontent.com/13279154/115879863-80b22780-a420-11eb-87da-43425995896d.png)

**Comment by a-kenji** [comment]
Thank you, that is very helpful! Can you please also attach the logs as files?

**Comment by lbcnz** [comment]
[zellij-3.log](https://github.com/zellij-org/zellij/files/6366169/zellij-3.log)
[zellij-4.log](https://github.com/zellij-org/zellij/files/6366170/zellij-4.log)
[zellij-7.log](https://github.com/zellij-org/zellij/files/6366171/zellij-7.log)

**Comment by imsnif** [comment]
@danisztls - I want to look at this feature, but tbh since I'm not familiar with Powerlevel10K it's hard for me to understand what the issue here is. Could you maybe share a screenshot in and outside of Zellij so I know how it's supposed to act?

(Also, there have been quite some terminal fixes in Zellij in the past couple of weeks - might be that this is already fixed... could you check the latest version?)

**Comment by danisztls** [comment]
Powerlevel10k is a comestic plugin for zsh shell. Instant prompt is a feature that loads a compiled subset of it to reduce the delay between opening a window and accepting user input.

It is solved on 7d553bb.

I could't test an earlier commit because building failed.

**Comment by a-kenji** [comment]
@danisztls 
Thank you for checking it out!
Do you remember why the build failed?

**Comment by danisztls** [comment]
@a-kenji Something related to generate completions. I installed zellij-git from AUR. I guess the PKGBUILD is outdated.

I'm on a low end machine. Please don't ask me to debug build. 😄

**Comment by a-kenji** [comment]
No problem, then I know what was wrong. Thanks for the heads up! Well try to get it fixed soon.

**Comment by danisztls** [comment]
The error message was:
```
error: Found argument 'generate-completion' which wasn't expected, or isn't valid in this context
```

zellij 0.10.0-1 built sucessfully but displayed warning on a clean build

```
Compiling zellij v0.10.0 (/var/cache/aur/build/zellij/src/zellij-0.10.0)
warning: unused imports: `ZELLIJ_PROJ_DIR`, `install::populate_data_dir`
  --> src/server/mod.rs:20:35
   |
20 |     setup::{get_default_data_dir, install::populate_data_dir},
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
21 |     thread_bus::{ChannelWithContext, SenderType, SenderWithContext},
22 |     utils::consts::{ZELLIJ_IPC_PIPE, ZELLIJ_PROJ_DIR},
   |                                      ^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: function is never used: `populate_data_dir`
  --> src/common/setup.rs:27:12
   |
27 |     pub fn populate_data_dir(data_dir: &Path) {
   |            ^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

fwarning: 2 warnings emitted

    Finished release [optimized] target(s) in 10m 14s
```
```
Compiling zellij v0.10.0 (/var/cache/aur/build/zellij/src/zellij-0.10.0)
warning: unused import: `SYSTEM_DEFAULT_CONFIG_DIR`
 --> src/common/setup.rs:2:5
  |
2 |     SYSTEM_DEFAULT_CONFIG_DIR, SYSTEM_DEFAULT_DATA_DIR_PREFIX, VERSION, ZELLIJ_PROJ_DIR,
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `interprocess::local_socket::LocalSocketListener`
 --> src/server/mod.rs:3:5
  |
3 | use interprocess::local_socket::LocalSocketListener;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `path::PathBuf`
 --> src/server/mod.rs:7:11
  |
7 | use std::{path::PathBuf, sync::mpsc::channel};
  |           ^^^^^^^^^^^^^

warning: unused imports: `ZELLIJ_PROJ_DIR`, `install::populate_data_dir`, `set_permissions`
  --> src/server/mod.rs:17:23
   |
17 |     os_input_output::{set_permissions, ServerOsApi},
   |                       ^^^^^^^^^^^^^^^
...
20 |     setup::{get_default_data_dir, install::populate_data_dir},
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
21 |     thread_bus::{ChannelWithContext, SenderType, SenderWithContext},
22 |     utils::consts::{ZELLIJ_IPC_PIPE, ZELLIJ_PROJ_DIR},
   |                                      ^^^^^^^^^^^^^^^

warning: unused variable: `result`
    --> src/client/panes/grid.rs:1349:17
     |
1349 |             let result = debug_log_to_file(format!("Unhandled csi: {}->{:?}", c, params));
     |                 ^^^^^^ help: if this is intentional, prefix it with an underscore: `_result`
     |
     = note: `#[warn(unused_variables)]` on by default

warning: constant is never used: `CONFIG_LOCATION`
 --> src/common/setup.rs:9:1
  |
9 | const CONFIG_LOCATION: &str = ".config/zellij";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: function is never used: `populate_data_dir`
  --> src/common/setup.rs:27:12
   |
27 |     pub fn populate_data_dir(data_dir: &Path) {
   |            ^^^^^^^^^^^^^^^^^

warning: function is never used: `xdg_config_dir`
  --> src/common/setup.rs:87:8
   |
87 | pub fn xdg_config_dir() -> PathBuf {
   |        ^^^^^^^^^^^^^^

warning: function is never used: `home_config_dir`
  --> src/common/setup.rs:95:8
   |
95 | pub fn home_config_dir() -> Option<PathBuf> {
   |        ^^^^^^^^^^^^^^^

warning: constant is never used: `SYSTEM_DEFAULT_CONFIG_DIR`
  --> src/common/utils/consts.rs:14:1
   |
14 | pub const SYSTEM_DEFAULT_CONFIG_DIR: &str = "/etc/zellij";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: 10 warnings emitted

    Finished release [optimized] target(s) in 5m 49s
     Running unittests (target/release/deps/zellij-8f3ab5cd8c236abb)
```
All tests were ok.

**Comment by a-kenji** [comment]
The shell completion has now moved to `setup --generate-completion [shell]`
