### ISSUE TITLE
Reloading the config at runtime

### ISSUE THREAD

**Issue by jaeheonji** [zellij-org/zellij#3386]
This Feature organizes tasks for the end goal of allowing users to modify and reload zellij configuration files at runtime.

The following features are subsets of this feature and must be included in implementation:

- #1405 
- #2249 
- #2645 

This also requires distinguishing whether each option allows changes at runtime. For example, It is difficult to apply ​​to options such as `default_mode` or `mirror_session` when reloading. Instead, I think we can handle like UI related options such as `simplified_ui` or `pane_frames`

**Comment by jaeheonji** [comment]
https://github.com/zellij-org/zellij/pull/3422

This PR will help to implement this feature.

**Comment by pencilcheck** [comment]
Right now I have to literally quit zellij to reload, what should I do now before this is merged?

**Comment by HirschBerge** [comment]
> Right now I have to literally quit zellij to reload, what should I do now before this is merged?

Learn Patience, my child 
![Oogway_Profile.jpg](https://github.com/user-attachments/assets/780720cb-99d5-4426-9a67-49071f957169)

**Comment by AesaraB** [comment]
Alternatively build from source

**Comment by jaeheonji** [comment]
This can now be considered almost complete. #3564 

Although some improvements remain, we believe the basic functionality has been implemented and the issue is closed.
