### ISSUE TITLE
zellij 0.40.1 source compile error on Debian WSL2 distro

### ISSUE THREAD

**Issue by vurso** [zellij-org/zellij#3401]
Hi,

I downloaded the latest source code for zellij: [source](https://github.com/zellij-org/zellij/archive/refs/tags/v0.40.1.tar.gz) and after extracting it to a folder (and installing cargo) I ran the command `cargo install --locked zellij` wich resulted in the following error:

```
   Compiling zellij-utils v0.40.1
error[E0658]: `let...else` statements are unstable
    --> /home/trevor/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-utils-0.40.1/src/input/layout.rs:1258:17
     |
1258 | /                 let Some(home) = home else {
1259 | |                     return Layout::stringified_from_default_assets(layout);
1260 | |                 };
     | |__________________^
     |
     = note: see issue #87335 <https://github.com/rust-lang/rust/issues/87335> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `zellij-utils` due to previous error
error: failed to compile `zellij v0.40.1`, intermediate artifacts can be found at `/tmp/cargo-install0VrdQq`
```

Thanks in advance.

**Comment by imsnif** [comment]
Hi,

`cargo install --locked zellij` will install Zellij from crates.io (the rust online repository). This is probably not working because you need a newer rust version (try `rustup update`).

If you'd like to install from source, please follow the instructions in `CONTRIBUTING.md`.
