### ISSUE TITLE
Ctrl Left/Right moves to previous or next tab

### ISSUE THREAD

**Issue by agentzhao** [zellij-org/zellij#3432]
```
normal {
        bind "Ctrl Left" { GoToPreviousTab; }
        bind "Ctrl Right" { GoToNextTab; }
}
```

Is it possible to bind arrow keys to Ctrl so that I can move to the previous and next tab like so?

**Comment by xG0Ian** [comment]
This feature was already supported by this PR #3383.

Compile from source code and u can bind "Ctrl Right" like this `bind "Ctrl Right" { GoToNextTab; SwitchToMode "Normal"; }` now.

**Comment by agentzhao** [comment]
> This feature was already supported by this PR #3383.
> 
> Compile from source code and u can bind "Ctrl Right" like this `bind "Ctrl Right" { GoToNextTab; SwitchToMode "Normal"; }` now.

Thank you so much!
