### ISSUE TITLE
Session manager no longer respects Enter key

### ISSUE THREAD

**Issue by Jimmyscene** [zellij-org/zellij#3438]
# 2. Issues with the Zellij UI / behavior / crash

## Issue description
When opening the session-manager plugin, pressing enter no longer seems to be respected. Pressing it during the session switcher "tab" does nothing, as does pressing enter after typing a new session name in the new session "tab"

## Minimal reproduction
I was about to repro this on master inside a docker container. I looked into it git bisect and the first commit that introduced this problem seems to be 62c37a87cca5aaa8b0e580b973b93513ed616dba

I'm looking into this in my spare time but thought I'd log it in case someone more familiar with the codebase can fix it easily

**Comment by imsnif** [comment]
Hey, thanks for this! I am aware of the issue. Just to stress: this only happens on the unreleased git version.
It's very much not recommended to use Zellij directly from the git version as that's for development.

It's best to use the release versions. This and other issues will be fixed before the next release.

Thanks for the report!
