### ISSUE TITLE
hlk keys inside nvim not working

### ISSUE THREAD

**Issue by DRKolev-code** [zellij-org/zellij#3442]
**Basic information**

`zellij --version`:  `fa110515aa672ff47b61fd69090da46a3c28d103`

`stty size`: `61 234`

`uname -av`: `Linux PW013WQH 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

## Issue description
The cursor does not seem to get updated when pressing `hkl` until either `j` is pressed or a key that would edit text such as `x`.

## Minimal reproduction
Tested on Windows Terminal and iterm2
1. Start a `zellij` session: `zellij attach -c temp`.
2. Open `nvim`: `nvim`
3. Press `hkl`
4. Press either `j` or `x` to update the cursor position

**Comment by DRKolev-code** [comment]
An update. This happens when [noice](https://github.com/folke/noice.nvim) is installed. I will do some further testing. It still triggers only with the new version of zellij.

**Comment by imsnif** [comment]
Could you check with latest `main` to see if this is resolved?

**Comment by DRKolev-code** [comment]
It is working. Thanks.

A comment. When I switched to  the main branch from the specific git commit and rebuild with `cargo xtask install ~/.local/bin/` the result was a non-functional build. I am not sure if that was related to having this status before rebuilding

```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   zellij-utils/assets/plugins/compact-bar.wasm
        modified:   zellij-utils/assets/plugins/fixture-plugin-for-tests.wasm
        modified:   zellij-utils/assets/plugins/session-manager.wasm
        modified:   zellij-utils/assets/plugins/status-bar.wasm
        modified:   zellij-utils/assets/plugins/strider.wasm
        modified:   zellij-utils/assets/plugins/tab-bar.wasm
```

I had to delete the local repository and clone it again. Then when I build it it worked.
