### ISSUE TITLE
What shell does scrollback_lines_to_serialize support?

### ISSUE THREAD

**Issue by sgon00** [zellij-org/zellij#3463]
Hi, the doc doesn't say what shell `scrollback_lines_to_serialize` support. I found out the bash shell scrollback could be restored,  but my nushell scrollback were not restored. Just to check if it only supports Bash shell and any other shells? if so, the doc should be updated about this info. Thanks a lot.

**Comment by imsnif** [comment]
All shells are supported as long as they use the native terminal scrollback (afaik all shells do this).

**Comment by sgon00** [comment]
I type `nu` to enter nushell. When I restore session, the pane only asks me to re-run the command `nu`. That's all. I lost all nushell scrollback history. So what should I do to restore nushell? Thanks a lot.

**Comment by Zykino** [comment]
You should not "start `nu`" manually. It should be your default shell. Either true default (but I’m not sure they advertise for that for the same reason fish does not advertise for that) or by configuring `nu` as the default in zellij:

In "~/.config/zellij/config.kdl", set
> // Choose the path to the default shell that zellij will use for opening new panes
> // Default: $SHELL
> //
> default_shell "nu"

**Comment by sgon00** [comment]
Thanks for the tip. I tried to set nushell as default_shell. The scrollback restore works randomly and partially. I don't know how to express the problem clearly and actually I don't know the problem pattern either. It seems the first resotre works, but the second resotre only works in the first pane. Something like that. Anyway, I am closing this issue for now.
