### ISSUE TITLE
Bug: Fullscreened pane in a tab prevents MoveFocusOrTab to navigate to another tab

### ISSUE THREAD

**Issue by kabeero** [zellij-org/zellij#3481]
## Issue description

I am facing an issue when I have a tab with multiple panes, and a pane is fullscreened, I cannot `MoveFocusOrTab "Left"` or `MoveFocusOrTab "Right"` beyond the panes that are in this tab

## Minimal reproduction

1. new zellij session `zellij -l default -s test`
2. create two tabs ("here.pane1" + "there.pane1")
3. create another pane in one of the tabs ("here.pane2")
4. toggle fullscreen on a pane in the tab with multiple panes ("here.pane1")
5. try to use hotkey for `MoveFocusOrTab` to navigate to a pane on the other tab ("there.pane1")

## Other relevant information

Maybe I am misunderstanding the fullscreen feature, I don't believe it should keep me constrained to one tab's worth of panes?

**Comment by Jimmyscene** [comment]
Duplicate of https://github.com/zellij-org/zellij/issues/3434 i think
