### ISSUE TITLE
View port space goes unused under the status bar

### ISSUE THREAD

**Issue by venkatb-zelar** [zellij-org/zellij#3492]
Hi, i use compact layout. I'd like to have the status bar but i do not like the space it's taking, especially the space below the status bar. I tried to customise it but it's not allowing me to go below 1 or "1%"(which seems to be the default). Is there a way to customise it? Thanks.

```sh
zellij --version
zellij 0.40.1

stty size
40 16

 uname
Linux
```

![Screenshot from 2024-07-12 18-37-39](https://github.com/user-attachments/assets/2014e54a-5a16-4681-af16-1748602c5be4)

**Comment by imsnif** [comment]
This is the last line of the terminal window - I'd recommend looking at the settings of your terminal emulator or window manager, could be some sort of padding is added there. There's not much anything running in the terminal (eg. Zellij) can do about this, unfortunately.

**Comment by venkatb-zelar** [comment]
ah, you are right. Thanks so much.

This is the default gnome terminal that comes by default for ubuntu 20. Not sure how to fix. Please let me know if you know anything. I'm closing this issue. Again, thanks for this tool.
