### ISSUE TITLE
Changing default shell

### ISSUE THREAD

**Issue by gbaranski** [zellij-org/zellij#352]
Hi, how do I change default shell? I'm mainly using fish but I've got bash as a default. Tmux have option like that to change it:
```bash
set -g default-shell /bin/fish
```

**Comment by a-kenji** [comment]
Cheers! That is not implemented yet. But I think that would be a welcome addition.

**Comment by gbaranski** [comment]
> Cheers! That is not implemented yet. But I think that would be a welcome addition.

Hmm, I think I can try implementing this.

**Comment by gbaranski** [comment]
From what I see it launches `SHELL` variable, https://github.com/zellij-org/zellij/blob/5d876bfcdbe0543db005cf7db6c9762b14a68f85/src/common/os_input_output.rs#L138

So I can just set SHELL variable in my terminal emulator, for example in Alacritty by adding
```yaml
env:
  SHELL: /bin/fish
```

I think in this case adding another configuration option is not needed. If someone wants to have different shell for zellij, it can be changed by doing something like that:
```bash
SHELL=/bin/bash zellij
```
Or even aliasing `zellij`  command: 
```bash
alias zellij="SHELL=/bin/sh $(which zellij)"
```
or in fish:
```fish
alias zellij="SHELL=/bin/sh "(which zellij)
```

**Comment by a-kenji** [comment]
Thank you for the investigation!
 I am not opposed to having this as an option, to preventing the need to alias this.

But that is not a priority!

**Comment by fdzuJ** [comment]
For anyone finding this issue looking for option - current option is `default_shell`

**Comment by CrixuAMG** [comment]
I've both tried the default_shell in the config.kdl and the `options --default_shell=` with both the absolute path of zsh and zsh, but zellij always defaults to /bin/bash. Running zsh as a command within zellij works as expected and running `echo $SHELL` returns the path to zsh.
Am I still missing something in my configuration perhaps?
