### ISSUE TITLE
tcpdump command not outputting in Zellij

### ISSUE THREAD

**Issue by darkvpier** [zellij-org/zellij#3529]
1. Graphical issue inside a terminal pane (eg. something does not look as it should or as it looks outside of Zellij)

**Basic information**

`zellij --version`:  `zellij 0.40.1`

`uname -av`:` Linux kali 6.8.11-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.8.11-1kali2 (2024-05-30) x86_64 GNU/Linux`

`qterminal 1.4.0`

Using zellij default configuration

## Issue description
 I'm unable to see any output when running tcpdump inside a Zellij pane. The command runs without errors but no packets are displayed. This issue occurs consistently across different network interfaces.

## Minimal reproduction
`tcpdump -h`
### Expected:
![image](https://github.com/user-attachments/assets/91a74589-1aa0-475e-9726-96c00d6823ac)

### Error in zellij:
![image](https://github.com/user-attachments/assets/c7382f53-88d9-4a98-93c3-1e7127c007ae)

**Comment by Zykino** [comment]
I don’t know what to say, tcpdump show its output for me on pop-os > alacritty.
![image](https://github.com/user-attachments/assets/8c671569-2e91-4669-918f-391e9c034a5a)

**Comment by darkvpier** [comment]
Issue resolved. The problem was due to insufficient permissions when installing from the Snap Store. Necessary permissions have been granted, and the issue is now fixed.


> I don’t know what to say, tcpdump show its output for me on pop-os > alacritty. ![image](https://private-user-images.githubusercontent.com/3809938/352869791-8c671569-2e91-4669-918f-391e9c034a5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzEwOTksIm5iZiI6MTcyMjIzMDc5OSwicGF0aCI6Ii8zODA5OTM4LzM1Mjg2OTc5MS04YzY3MTU2OS0yZTkxLTQ2NjktOTE4Zi0zOTFlOWMwMzRhNWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjlUMDUyNjM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTUxNDA1YzFlNWViMDA1Y2U4ZWI2ZWVjZTViNjI3YjllMjAxZTIzOGM5OGJiYjBkYWYxNjhjMDE5OWNjMDM1ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JEm0gYF1vkte9yJdMp6xHNaza6F6FQSWgTpPicMqQ3o)

Issue resolved. The problem was due to insufficient permissions when installing from the Snap Store.
