### ISSUE TITLE
Progress bar not working (e.g. apt upgrade)

### ISSUE THREAD

**Issue by weinbrenner** [zellij-org/zellij#353]
I was just running an `apt upgrade` command in Zellij. It seems it cannot handle the shell progress bar:
![unknown](https://user-images.githubusercontent.com/5902988/115949077-a4ce4100-a4d2-11eb-999d-7b6ff8e8061b.png)

Version: zellij 0.5.1

**Comment by a-kenji** [comment]
Thank you for submitting this issue!

That could have a lot of interactions.
One notable could be unhandled sequences.

Do you mind investigating the problem?
zellij --debug and then run your apt-command, and look in
cat /tmp/zellij/zellij-log/log.txt and see if there is output there.
If there is please send us the file. Also in this case since there is a graphical mess please attach the other logfiles, if you are comfortable with that.

**Comment by weinbrenner** [comment]
Here is the debug log:

```
$ cat /tmp/zellij/zellij-log/log.txt
Unhandled csi: f->[43, 0]
Unhandled csi: f->[43, 0]
Unhandled csi: f->[43, 0]
Unhandled csi: f->[43, 0]
Unhandled csi: f->[43, 0]
Unhandled csi: f->[43, 0]
Unhandled csi: f->[43, 0]
Unhandled csi: f->[43, 0]
Unhandled csi: f->[43, 0]
Unhandled csi: f->[43, 0]
Unhandled csi: f->[43, 0]
Unhandled csi: f->[43, 0]
Unhandled csi: f->[43, 0]
```

This means 13 lines of log. It is exactly corresponding to the 13 repetitions of the progress bar in the zellij terminal:

```
Fortschritt: [  0%] [.......................................................................................................................................] Fo
rtschritt: [  8%] [##########.............................................................................................................................] Entp
acken von firefox (88.0+build2-0ubuntu0.20.10.1) über (87.0+build3-0ubuntu0.20.10.1) ...                                                                        
Fortschritt: [ 15%] [####################...................................................................................................................] Vo
rbereitung zum Entpacken von .../firefox-locale-de_88.0+build2-0ubuntu0.20.10.1_amd64.deb ...                                                                   
Fortschritt: [ 23%] [###############################........................................................................................................] En
tpacken von firefox-locale-de (88.0+build2-0ubuntu0.20.10.1) über (87.0+build3-0ubuntu0.20.10.1) ...                                                            
Fortschritt: [ 31%] [#########################################..............................................................................................] Vo
rbereitung zum Entpacken von .../firefox-locale-en_88.0+build2-0ubuntu0.20.10.1_amd64.deb ...                                                                   
Fortschritt: [ 38%] [###################################################....................................................................................] En
tpacken von firefox-locale-en (88.0+build2-0ubuntu0.20.10.1) über (87.0+build3-0ubuntu0.20.10.1) ...                                                            
Fortschritt: [ 46%] [##############################################################.........................................................................] fi
refox (88.0+build2-0ubuntu0.20.10.1) wird eingerichtet ...                                                                                                      
Fortschritt: [ 54%] [########################################################################...............................................................] Pl
ease restart all running instances of firefox, or you will experience problems.                                                                                 
Fortschritt: [ 62%] [###################################################################################....................................................] fi
refox-locale-en (88.0+build2-0ubuntu0.20.10.1) wird eingerichtet ...                                                                                            
Fortschritt: [ 69%] [#############################################################################################..........................................] Fo
rtschritt: [ 77%] [#######################################################################################################................................] fire
fox-locale-de (88.0+build2-0ubuntu0.20.10.1) wird eingerichtet ...                                                                                              
Fortschritt: [ 85%] [##################################################################################################################.....................] Fo
rtschritt: [ 92%] [############################################################################################################################...........]
```

**Comment by a-kenji** [comment]
Thank you for that. That will be very helpful!

**Comment by saintphaenixos** [comment]
I am getting the same issue with V0.6.

**Comment by a-kenji** [comment]
@saintphaenixos 
Thank you for checking!

**Comment by weinbrenner** [comment]
just verified: still there with current version 0.9.0

**Comment by imsnif** [comment]
@weinbrenner - could you please follow the instructions here and add the logs (especially the pane logs eg. `zellij-3.log`): https://github.com/zellij-org/zellij/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

That way I can easily debug it and fix it.

**Comment by weinbrenner** [comment]
@imsnif - here are the example logs (recorded with current zellij 0.10.0)
[zellij-log.tar.gz](https://github.com/zellij-org/zellij/files/6506114/zellij-log.tar.gz)

**Comment by imsnif** [comment]
@weinbrenner - I've been trying to fix this issue, but unfortunately I don't know which size terminal you were using and so it's basically a lot of guess work for me with the log file :) Could you please provide the output of `tput lines` and `tput cols`? I know it's been a while, so if you don't remember I hope it's not too much trouble to reproduce this again and provide the output? I've been trying to guess the terminal size for the better part of an hour now and not succeeding...

Thanks!

**Comment by weinbrenner** [comment]
@imsnif size actually doesn't matter! It happens with every size. You can use for example lines: 48, cols: 160.

**Comment by imsnif** [comment]
@weinbrenner - I understand, but I couldn't find a way to reproduce this on my machine (I don't have apt, and this didn't happen to me inside a debian/ubuntu docker container). And in order to use your example I have to have the exact size, otherwise this is not reproduced (since this probably has to do with line-wrapping, and so size is super important down to the column :) ). Thanks - I'll try it with these measurements!

**Comment by imsnif** [comment]
@weinbrenner - I was not able to reproduce it with 48/160 using the zellij-logs you attached. Looking through their output, it seems like they at least refer to line 58 in the viewport - so I think maybe the measurements for the logs are a little different?

In order to be able to use the logs, I need to know exactly what size pane they were taken in. I really want to solve this issue, but I can't reproduce it. I'm doing a lot of guesswork here and not getting anywhere.

If you could:
1. reproduce this issue inside a zellij pane (zellij running with the `--debug` flag)
2. inside that same pane, do a `tput lines` and `tput cols` - write those measurements here
3. attach the log files here

that would be really helpful. Then I would be able to reproduce this issue and solve it.

Thanks in advance!

**Comment by weinbrenner** [comment]
I have tested again with zellij 0.16.0 - #656 doesn't fix the issue. It seems to render without line-overflows, so looking much nicer, but the progress bar ist not standing on the bottom of the terminal like in a classic terminal, instead redrawn over and over.

Here is my test results:
```
$ tput lines
34
$ tput cols
114
```

[zellij-log.tar.gz](https://github.com/zellij-org/zellij/files/7109232/zellij-log.tar.gz)

![2021-09-04_07-02](https://user-images.githubusercontent.com/5902988/132083261-35eb86fe-85a1-49c7-82b8-f7f2fbe7daa0.png)

**Comment by imsnif** [comment]
@weinbrenner - thanks for the great info. Thanks to it I managed to find the issue and I think I solved it. Could you please check with the new version `0.18.0`? Thanks!

**Comment by julian-klode** [comment]
FWIW, this issue still happens to me in 0.43.0 with apt 3. I *think* the calculations I do in apt are right, but we might not have the most straightforward escape sequences. Particularly the issue happens around resizes: APT should get a SIGWINCH and then it updates its internal states, moves cursor to start of last line and draws it, but _somehow_ zellij ends up with all lines being written into the last one.

Also the scrollback buffer is completely shot once we start doing this, which is problematic; we do want to be able to scroll back while showing progress bars at the bottom.

But I need to do some more digging and recording and it's probably best to track this in 1-2 new bugs,

**Comment by imsnif** [comment]
Hey @julian-klode - I'd be happy to look more into this (I guess given the age of this issue that this might indeed be something entirely different). Could you maybe tell me which ANSI instructions you're sending to make this happen (eg. are you initializing a scroll region)? I think that would be the easiest path forward.
