### ISSUE TITLE
Session Manager doesn't work when running latest commit

### ISSUE THREAD

**Issue by sc0** [zellij-org/zellij#3542]
# 2. Issues with the Zellij UI / behavior / crash

## Issue description
When trying to do anything with Session Manager on the latest commit (47caeb66a6c5b8b229c1227ce823defcdccf31b8) I get the following error:
```rs
Loading Panic!.
ERROR: ‹NO PAYLOAD>
PanicInfo {
    payload: Any { .. },
    message: Some (
        called "Result: :unwrap()' on an 'Err' value: "invalid_key",
    ),
    location: Location {
        file: "default-plugins/session-manager/src/main.rs",
        line: 51,
        col: 1,
    },
    can_unwind: true,
    force_no_backtrace: false,
}
ERROR IN PLUGIN - check logs for more info
```

Relevant part of logs:
```
8224   │ ERROR  |zellij_server::plugins::z| 2024-08-05 01:34:00.748 [async-std/runti] [zellij-server/src/plugins/zellij_e
       │ xports.rs:1433]: PANIC IN PLUGIN!
8225   │ ^M<NO PAYLOAD>
8226   │ ^MPanicInfo {
8227   │     payload: Any { .. },
8228   │     message: Some(
8229   │         called `Result::unwrap()` on an `Err` value: "invalid_key",
8230   │     ),
8231   │     location: Location {
8232   │         file: "default-plugins/session-manager/src/main.rs",
8233   │         line: 51,
8234   │         col: 1,
8235   │     },
8236   │     can_unwind: true,
8237   │     force_no_backtrace: false,
8238   │ }
8239   │ ERROR  |zellij_server::plugins::w| 2024-08-05 01:34:00.748 [async-std/runti] [zellij-server/src/plugins/wasm_bri
       │ dge.rs:610]: Failed to apply event to plugin 1
8240   │
8241   │ Caused by:
8242   │     0: error while executing at wasm backtrace:
8243   │            0: 0x83699 - <unknown>!<wasm function 611>
8244   │            1: 0x39173 - <unknown>!<wasm function 279>
8245   │            2: 0x83c97 - <unknown>!<wasm function 617>
8246   │            3: 0x83bc6 - <unknown>!<wasm function 616>
8247   │            4: 0x2719d - <unknown>!<wasm function 196>
8248   │            5: 0x719d - <unknown>!<wasm function 33>
8249   │            6: 0x1de74 - <unknown>!<wasm function 117>
8250   │            7: 0x77dbc - <unknown>!<wasm function 570>
8251   │     1: wasm trap: wasm `unreachable` instruction executed
```

Also here's the video of this happening

https://github.com/user-attachments/assets/e3d85c78-5711-422d-b864-52083f38d9ed

## Minimal reproduction

Simply install Zellij from HEAD (47caeb66a6c5b8b229c1227ce823defcdccf31b8) and try doing anything with Session Manager. It works correctly in v0.40.1

## Other relevant information

I'm running Zellij on MacOS 14.5 inside WezTerm (20240203-110809-5046fc22).
Installed Zellij from the latest commit with `brew install --HEAD zellij`

**Comment by imsnif** [comment]
Try clearing the cache, this works correctly for me. Here's its location in various systems: https://docs.rs/directories/5.0.1/directories/struct.ProjectDirs.html#method.cache_dir

**Comment by mario-areias** [comment]
I've got the same issue and have the same error after deleting the cache folder. The folder I deleted on my Mac: 
`/Users/<myuser>/Library/Caches/org.Zellij-Contributors.Zellij`

A bit more info in case it helps: 

- `zellij --layout <pre-defined-layout>` works and it creates the session as expected. 
- It also works when trying to renaming via the command line such as `zellij action rename-session <new-session-name>`. 
 
But trying to rename sessions or create new ones using the session-manager plugin I get the same errors as the author of this issue. Let me know if you need more logs or if there is another information I can provide.

**Comment by imsnif** [comment]
How did you install/run from main?

**Comment by mario-areias** [comment]
Same as the author of this post using homebrew: `brew install --HEAD zellij`. I am using Alacritty instead though.

I was using the released version `0.40.1` but changed to `main` so I could get the fix for #3208.

**Comment by imsnif** [comment]
I don't know how the brew installation works, but my guess is that it doesn't run through the build system and you're getting an older version of the plugins. I'd recommend using `cargo x install`. More info here: https://github.com/zellij-org/zellij/blob/main/CONTRIBUTING.md#building

**Comment by sc0** [comment]
Hi, @imsnif, I did remove the cache but it didn't fix the issue. I also updated for #3208. Will try building form source as you suggest and come back to you

**Comment by sc0** [comment]
Ok, I can confirm that when building from source Session Manager works as expected. That means there seem to be some kind of issue with the way homebrew builds and/or installs zellij.

**Comment by imsnif** [comment]
Glad it's sorted @sc0 !

I don't think this is a homebrew issue. This probably means homebrew builds with vanilla cargo, which is totally fine for releases - since then all the updated assets are placed in the repo properly - but not for development builds, where it doesn't make sense to update the assets for each change, so things get out of sync.

To prevent these sorts of errors in the future when building the pre-release development code, I recommend following the build instructions in CONTRIBUTING.md.

**Comment by sc0** [comment]
Ah, that makes sense! Thanks so much for your help, I can close the issue now :)
