### ISSUE TITLE
Both panes take same input

### ISSUE THREAD

**Issue by OuiDelaportas** [zellij-org/zellij#3595]
## 2. Issues with the Zellij UI / behavior / crash

**Basic information**

`gnome-terminal`: 3.52.2-1.1

`zellij --version`: 0.40.1-1

`helix --version`: 24.07-2.1

## Issue description
I have 2 panes open and at random moments whatever I type into one pane gets typed into the other as well. Thus far this has only hapenned when using helix. Even if I close helix it still goes on recording my input for both panes regardless of which is focused. Closing and reopening the pane seems to "fix" the issue until it happens again. 

## Minimal reproduction
I haven't found a way to reproduce this problem yet.

**Comment by Zykino** [comment]
Are you syncing the tab inadvertently? `Ctrl t, s` by default.
This should add the following in the tab name.
![image](https://github.com/user-attachments/assets/2b3a2532-4a77-44df-b9a8-ef5b8c72f29a)

**Comment by OuiDelaportas** [comment]
I don't remember if the `(Sync)` text popped up but since this reproduces exactly was I was facing I will assume this was it. Thanks. Seems like I need to check the commands in more detail next time. Cheers
