### ISSUE TITLE
Ctrl Q still makes zellij quit even I unbind it in config.kdl

### ISSUE THREAD

**Issue by sangshuduo** [zellij-org/zellij#3627]
zellij 0.40.1
stty size: 72 380
`stty size`:
OS: macOS 14.6.1 (23G93)

## Issue description
Ctrl Q still makes zellij quit even I unbind it in config.kdl and replace it with Alt Q. Now Alt Q will make zellij quit but Ctrl P also works as well. I wish only Alt Q work rather than both work.
 
## Minimal reproduction
modify .config/zellij/config.kdl

```
// If you'd like to override the default keybindings completely, be sure to change "keybinds" to "keybinds clear-defaults=true"
keybinds {
    unbind "Ctrl p"
    unbind "Ctrl q"
...
    shared_except "locked" {
        bind "Alt g" { SwitchToMode "Locked"; }
        bind "Alt q" { Quit; }
...
```

**Comment by Jimmyscene** [comment]
Can you try like this instead? 
```
// If you'd like to override the default keybindings completely, be sure to change "keybinds" to "keybinds clear-defaults=true"
keybinds {
    unbind "Ctrl p" "Ctrl q"
... 
```

**Comment by sangshuduo** [comment]
> Can you try like this instead?
> 
> ```
> // If you'd like to override the default keybindings completely, be sure to change "keybinds" to "keybinds clear-defaults=true"
> keybinds {
>     unbind "Ctrl p" "Ctrl q"
> ... 
> ```

thanks. it works great!
