### ISSUE TITLE
Better documentation on configuring, and maybe using something that makes more sense than KDL?

### ISSUE THREAD

**Issue by abraxas86** [zellij-org/zellij#3629]
I was trying to follow along with the documentation on setting things up, but I got absolutely lost.  KDL is making absolutely no sense to me and I don't see why anybody would pick this over JSON or the like.

Trying to find how to write a config was tricky as it was, I ended up here though: https://zellij.dev/documentation/creating-a-layout.html?highlight=config#panes 

So I thought - perfect, we'll start by learning how to get a basic layout going...

```
layout {
    pane // panes can be bare
    pane command="htop" // panes can have arguments on the same line
    pane {
        // panes can have arguments inside child-braces
        command "exa"
        cwd "/"
    }
    pane command="ls" { // or a mixture of same-line and child-braces arguments
        cwd "/"
    }
}
```

No mention at all in there on how to name a panne (that comes way later than it should in the document, but I digress).

It's already kinda silly that sometimes we use "=" to set values and other times we don't, but after reading a bit though the page it seemed like if we're setting values outside of the node, we use = such as `pane command = "htop"` and if we're in a node we don't nneed the =, such as `command "exa"`

But then you get a bit further down and you see this:

```
    pane split_direction="vertical" {
        pane size="80%"
        pane size="20%"
```
So... now we do need an "=" in there sometimes?  I don't see what this is set to resolve that JSON wouldn't  do a thousand times easier lol.  What am I missing?

**Comment by imsnif** [comment]
A (configuration) format would not be a good one if at least some people didn't passionately hate it. :)

If you'd like to learn more about the KDL syntax, you can look at the website. They have some great explanations: https://kdl.dev/

If you don't like the layout documentation, you can also check out the screencast/tutorial: https://zellij.dev/tutorials/layouts/

**Comment by abraxas86** [comment]
Thanks! Sorry for being so crusty yesterday.

I'm sure it's at least partially a "me" problem... I checked the KDL site, and their explanations made even less sense to me, but I think that's maybe mostly down to a differing of opinions.  I'll dive into that layouts tutorial papge and have another crack at it.

I really do want to love Zellij.  It looks like it might be the closest competition tmux has.
