### ISSUE TITLE
Zellij memory when detached?

### ISSUE THREAD

**Issue by adudenamedruby** [zellij-org/zellij#3646]
Hi. I'm pretty new to zellij, coming from tmux, and I've set it up so it works great for me. I'm switching because, honestly, the borders around the panes, lol. I'm a sucker for great visual aesthetics. Hoping ya'll can provide some context or me. So I'm in my base terminal, detached from either zellij or tmux, with the following state

<img width="760" alt="Screenshot 2024-10-05 at 6 58 46 AM" src="https://github.com/user-attachments/assets/b7eed0fc-e2d5-4cd4-ab73-faebc0e64a4e">

In both multiplexers, I've made all windows/tabs and panes/splits be at the cli, not running anything in the background. And if I check out activity monitor, I get the following

<img width="892" alt="Screenshot 2024-10-05 at 7 02 21 AM" src="https://github.com/user-attachments/assets/e010d3c0-0aff-4fba-8e7f-e6f50eb7f8ec">
<img width="881" alt="Screenshot 2024-10-05 at 7 02 38 AM" src="https://github.com/user-attachments/assets/9b0aa60d-b215-4f2e-a27d-4f4bc641f9fd">

Why the vast difference in memory footprint & threads when I'm detached and not running anything? Is this expected?

versioning:
zellij 0.40.1
tmux 3.5
wezterm 20240203-110809-5046fc22
macOS 14.7

**Comment by giyany** [comment]
Zellij and tmux are different pieces of software and naturally will have different memory footprints. I'm not sure what the question is otherwise, nothing here seems unusual or like a problem unless I'm misunderstanding.

**Comment by adudenamedruby** [comment]
Totally fair. Just a new piece of software to me, and I'm asking questions to better get to know it. It just seemed big given where I'm coming from. I'll often have 20-30 sessions open at a time for stuff, and having 2-3G gone just for having a session open, not even having processes running in them, seemed odd to me. But if this is the expected behaviour, no worries.

**Comment by giyany** [comment]
Yeah, that's fair. There's work on improving memory usage and of course resolving memory leaks, like #1625. It's the "why is this software not another software" that has no straightforward answer. If you want to learn about the inner workings of zellij, there are good discussions on the Discord/Matrix (and also good vibes!).

**Comment by imsnif** [comment]
Also, if I may add: Zellij is a runtime. Runtimes tend to take up more memory. As the issue template says, it's a different app with different goals that behaves differently.

A tip about memory utilization monitoring in this context (if I may): be sure you're measuring the right thing (eg. resident vs. virtual). The rust allocator tends to be a bit greedy when releasing memory, but this should not actually affect your system. More on this in the issue linked by @giyany above.
