### ISSUE TITLE
Tests failing on a read only file system (context: packaging for nixpkgs)

### ISSUE THREAD

**Issue by happysalada** [zellij-org/zellij#366]
I am currently trying to package this for nixpkgs.
the tests are currently failing when the Os is readonly.

It fails on https://github.com/zellij-org/zellij/blob/main/src/common/install.rs#L36

I'm guessing the tests fail because of a missing environment variable that defines where the data_dir should be?
Here is what I am testing at the moment to run before cargo test
```
    export CARGO_TARGET_DIR=$TMPDIR;
    mkdir -p "$TMPDIR/target";
    export target_dir="$TMPDIR/target";
    export asset_dir="$PWD/assets";
    mkdir -p "$TMPDIR/data_dir";
    export data_dir="$TMPDIR/data_dir";
```
based on env vars found https://github.com/zellij-org/zellij/blob/74cc48fc500f7f81a867394e8d6550562500d14f/Makefile.toml#L43

If you already know exactly which env vars are needed and the kind of thing they should be pointing to, It could save some time.

**Comment by happysalada** [comment]
For reference here is the default.nix file I am using
```
{ lib
, stdenv
, rustPlatform
, fetchFromGitHub
, libiconv
}:

rustPlatform.buildRustPackage rec {
  pname = "zellij";
  version = "0.5.1";

  src = fetchFromGitHub {
    owner = "zellij-org";
    repo = "zellij";
    rev = "v${version}";
    sha256 = "sha256-jciowXHhMWN88PW/wOlwXpdCo6FMm15vLqD/qyzhX4A=";
  };

  cargoHash = "sha256-pYau4uLmOaacVLBW5rP795Z3KkuaA6wwFM1YBSDTLog=";

  buildInputs = lib.optionals stdenv.isDarwin [ libiconv ];

  cargoBuildFlags = [ "--all-features" ];

  preCheck = ''
    export CARGO_TARGET_DIR=$TMPDIR;
    mkdir -p "$TMPDIR/target";
    export target_dir="$TMPDIR/target";
    export asset_dir="$PWD/assets";
    mkdir -p "$TMPDIR/data_dir";
    export data_dir="$TMPDIR/data_dir";
    echo $target_dir
    echo $asset_dir
    echo $data_dir
  '';

  meta = with lib; {
    description = "Zellij is a workspace aimed at developers, ops-oriented people and anyone who loves the terminal. At its core, it is a terminal multiplexer (similar to tmux and screen), but this is merely its infrastructure layer.";
    homepage = "https://zellij.dev/";
    maintainers = with maintainers; [ happysalada ];
    license = with licenses; [ mit ];
  };
}
```

**Comment by happysalada** [comment]
On a different note. Adding some print statement around those syscalls in install.rs would make debugging easier in case the syscalls fail.

**Comment by a-kenji** [comment]
Thank you for making this issue! From looking at it for now sadly I can't say that I would do anything different from you, but I am also very familiar with the `cargo-make file`. 
CC @TheLostLambda 

I will try to investigate it a little more in the future.

**Comment by a-kenji** [comment]
@happysalada 
Is this issue maybe of help?
https://github.com/NixOS/nixpkgs/pull/120101

**Comment by happysalada** [comment]
It relies on the HOME variable. I should have tried that!
Anyways, thanks for pointing me out to this PR!
