### ISSUE TITLE
Ability to include keybindings in a layout file

### ISSUE THREAD

**Issue by brandondrew** [zellij-org/zellij#3670]
It would be useful to be able to include keybindings in a layout files, so that we could easily have project-specific keybindings.

This would also make sense to use with name-based tab switching: #3669, since the layout is where the names of tabs are often defined, and so any keybinding that relates to the name would only make sense there.

**Comment by cristiand391** [comment]
This is already supported, see:
https://zellij.dev/documentation/layouts-with-config

**Comment by brandondrew** [comment]
Thanks!  I missed that in the docs, and my experiments failed to use the right structure.
