### ISSUE TITLE
Feature: Ability to have initial set of tabs and panes

### ISSUE THREAD

**Issue by psibi** [zellij-org/zellij#370]
Right now when I start zellij, it comes with one tab and one pane.

Instead, I would like to configure it such that:

- It starts with a "n" number of tabs which I have configured. Ability for each tab to given a custom name would be nice!
- Each tab can be additional configured to have "x" number of panes

I have been using zellij for a day and it looks quite nice. Thanks for the work!

**Comment by SaintFenix** [comment]
This issue #349 may be twins.

**Comment by a-kenji** [comment]
@psibi, thank you for taking the time opening this issue!
This is a great idea.
Currently you can open zellij with mulitple panes https://zellij.dev/documentation/configuration.html,
but it is more limited, than what you propose.

**Comment by a-kenji** [comment]
@psibi this is now implemented in the latest release.
Here is a description of how it works now: https://zellij.dev/documentation/layouts-templates.html .

**Comment by psibi** [comment]
Thank you!
