### ISSUE TITLE
Pane Names In Status Bar

### ISSUE THREAD

**Issue by Jazztache** [zellij-org/zellij#3705]
Hello!

I would like it if we had the option to show pane names in the statusbar.

This would be nice as an aesthetic thing, with some practical uses.

Currently I think of three good places where this could be displayed without being too intrusive.
- `title`: Replaces the 'Zellij' title with the pane name. This would make the far left of the screen read '<pane> (<session>)' as opposed to 'Zellij <session>'.
- `tabbar`: Replaces the tab name (Usually 'Tab # 1') with the focused pane name.
- `right`: Adds (not replaces) text to the right side of the statusbar with some text with the pane name in its own > chevron >, left of the '> VERTICAL >' or '> HORIZONTAL > indicator'.
- `off`: The current Zellij behaviour. You can also not specify the option and it defaults to this.

`title` would let you repurpose an ordinarily static space for a useful pace of information.

This allows the user to see the name of the pane regardless of whether pane frames are disabled or not.
It also works very well with the disable panes request I made previously #3704.
I think it would also look very nice.

I would personally find a way to disable the title and use `tabbar` so I can keep track of what pane my other tabs are on.
`right` is useful for if you want to use some of the dead space on the right whilst still having the layout stay the same.

The option would be set out in the config like so:
```
ui {
  status_bar {
    pane_readout "off" // Disable pane readout on statusbar like Zellij currently does.
    pane_readout "title" // Replace the title with the name of the current pane.
    pane_readout "tabbar" // Replace the tab names with the pane names.
    pane_readout "right" // Show the current tab name in it's own chevron on the right side.
  }
}
```
Thanks for your consideration!

**Comment by imsnif** [comment]
Hi, thanks for your suggestion! The Zellij way of doing these sorts of things is through the plugin system. The status-bar itself is implemented as a plugin, so you could even fork it as a starting point if you like.

Also in your case I'd recommend to check out the excellent [zjstatus](https://github.com/dj95/zjstatus) - a configurable status-bar for Zellij.

**Comment by Jazztache** [comment]
Looks awesome. Thanks!
