### ISSUE TITLE
The filepicker is  not to  be closed as expected

### ISSUE THREAD

**Issue by nocatsnolife** [zellij-org/zellij#3714]
`zellij --version`: 0.40.1

`stty size`:  34 147

`uname -av` or `ver`(Windows): Linux fedora 6.11.5-300.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Oct 22 20:11:15 UTC 2024 x86_64 GNU/Linux

## Minimal reproduction
1.Open zellij
2.Type alt+f  twice,2 filepicker shows(it's ok)
3.Select a file and type enter,the newer filepicker is closed
4.Type alt+f once, 2 filepick shows(how to close the old one?)

## Other relevant information
Screenshot:
![Pasted image](https://github.com/user-attachments/assets/741bb094-2ebf-4c16-9c42-0e77c0f25cea)

My config:
```
    shared_except "locked" {
        bind "Ctrl g" { SwitchToMode "Locked"; }
        bind "Ctrl q" { Quit; }
        bind "Alt n" { NewPane; }
        bind "Alt i" { MoveTab "Left"; }
        bind "Alt o" { MoveTab "Right"; }
        bind "Alt h" "Alt Left" { MoveFocusOrTab "Left"; }
        bind "Alt l" "Alt Right" { MoveFocusOrTab "Right"; }
        bind "Alt j" "Alt Down" { MoveFocus "Down"; }
        bind "Alt k" "Alt Up" { MoveFocus "Up"; }
        bind "Alt =" "Alt +" { Resize "Increase"; }
        bind "Alt -" { Resize "Decrease"; }
        bind "Alt [" { PreviousSwapLayout; }
        bind "Alt ]" { NextSwapLayout; }
        bind "Alt f" {
            LaunchPlugin "filepicker" {
                floating true
                close_on_selection true
            }
        }
    }
```

**Comment by imsnif** [comment]
You can close it like any other pane with `Ctrl p` + `x`.

**Comment by nocatsnolife** [comment]
> You can close it like any other pane with `Ctrl p` + `x`.

Thanks!
