### ISSUE TITLE
ssh connection terminate when macbook goes to sleep

### ISSUE THREAD

**Issue by pdeva** [zellij-org/zellij#3716]
## Issue description
all ssh connections terminate in zellij session if macbook goes to sleep. i thought the whole point was to keep connections alive..

## Minimal reproduction
1. create a zellij session
2. in it, ssh to some server
3. let your macbook go to sleep
4. when you come back to your macbook, the ssh connections are disconnected
![Screenshot 2024-11-01 at 8 00 42 AM](https://github.com/user-attachments/assets/f561bf76-c0bc-4c91-99a9-e40a2464bdb1)

**Comment by Zykino** [comment]
> i thought the whole point was to keep connections alive..

What made you think this is the point of zellij?

Is it the "session" feature? In zellij sessions are "bundle" of tabs (that each contains panes). Multiple terminal can connect to it as different "users", but only 1 linux user.

Zellij does not manage the shell’s behavior, nor know about SSH.

**Comment by tgulacsi** [comment]
@pdeva - you must use zellij on the REMOTE side of the ssh connection, to persist your session on that server.
(This is very easy as zellij is statically linked).
This way anytime you ssh into your remote server, your tabs and panes will wait for you.

**Comment by pdeva** [comment]
@tgulacsi ah. got it. very helpful! thank you :)
