### ISSUE TITLE
Documentation: What are the possible keybinds for the .yaml configurations?

### ISSUE THREAD

**Issue by SaintFenix** [zellij-org/zellij#372]
As spoken about in Pull Request #362 and mentioned by @a-kenji there is currently little to no documentation on what keybinds are functioning in the .yaml configuration files, and what keybinds are possible to be used.

currently though we do know that in issue #357 that some keybinds are non-functional.

It would be wonderful to have a list of what keybinds can be used.

Currently it seems that any modifier keys will not function with any non-alphanumeric keys, and notably, that sequences of keybinds can be used. Currently only alternatives can be listed.

Documentation explaining these limits would be invaluable to users who wished to customize their experience, and allow them a more powerful way to interact with complicated functions in Zellij.

**Comment by a-kenji** [comment]
Thanks for tracking this!
https://zellij.dev/documentation/keybindings-keys.html
a subsection that would document limitations of our keybinds could be good.

**Comment by SaintFenix** [comment]
This Documentation should reference this also #351

**Comment by har7an** [comment]
There's a new section in the [docs][1] (Introduced [here][2]), so I think this can be closed now. :)

[1]: https://zellij.dev/documentation/keybindings-keys.html#valid-character-combinations
[2]: https://github.com/zellij-org/zellij-org.github.io/pull/95
