### ISSUE TITLE
Question mark symbols in the UI on macOS

### ISSUE THREAD

**Issue by lgarron** [zellij-org/zellij#3729]
1. Graphical issue inside a terminal pane (eg. something does not look as it should or as it looks outside of Zellij)

# 1. Graphical issue inside a terminal pane (eg. something does not look as it should)

1. Delete the contents of `/tmp/zellij-1000/zellij-log`, ie with `cd /tmp/zellij-1000/` and `rm -fr zellij-log/` (`/tmp/` is `$TMPDIR/` on OSX)
2. Run `zellij --debug`
3. Run `stty size`, copy the result and attach it in the bug report
4. Recreate your issue.
5. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.

`zellji` did not write anything in `/tmp/` when I did this.

**Basic information**

`zellij --version`: 0.41.1

`stty size`: `28 100`

`uname -av` or `ver`(Windows): Darwin Germain 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000 arm64

## Issue description

The arrow icons in the UI are replaced with question marks.

![clipboard](https://github.com/user-attachments/assets/9ec2fbc8-96d3-464d-8df0-880264c5615a)

(Some of my prompt is also not rendering correctly, I suspect that's unrelated but I don't know.)

## Minimal reproduction

Start `zellij` and look at the screen.

## Other relevant information

This happens for me in macOS `Terminal.app`, iTerm, and the VS Code terminal. Changing the font doesn't make a difference.

Apologies if this is a well-known issue. I was not able to find any information about it.

**Comment by Zykino** [comment]
Hello everything is explained here: https://zellij.dev/documentation/faq#i-see-broken-characters-in-the-default-ui-how-can-i-fix-this
There is also infos on how to get the `Alt` key working on macOS as a next question.

**Comment by lgarron** [comment]
> Hello everything is explained here: https://zellij.dev/documentation/faq#i-see-broken-characters-in-the-default-ui-how-can-i-fix-this

Thank you! The UbuntuMono Nerd Font immediately got the job done! 🤩

**Comment by lgarron** [comment]
For what it's worth, I think I would have found that FAQ if it included "question mark" somewhere in it. But perhaps this issue will already be sufficient for anyone searching in the future.

**Comment by Zykino** [comment]
Yeah, on gnome-terminal, if I try with a non-nerd font, I have this:
![image](https://github.com/user-attachments/assets/02025947-53b8-45eb-9010-cfb87baec444)

I suppose it depends on the OS, the terminal and/or the font.
