### ISSUE TITLE
ncmpcpp ui lines are displayed as `q`

### ISSUE THREAD

**Issue by wucke13** [zellij-org/zellij#373]
This is what I see in `zellij`:
![image](https://user-images.githubusercontent.com/20400405/116005504-87e75a00-a607-11eb-9ed3-c2d96b0f7aa0.png)

And this is how it should look like:
![image](https://user-images.githubusercontent.com/20400405/116005514-933a8580-a607-11eb-97e1-5e2f195c398a.png)

**Comment by a-kenji** [comment]
Thank you for taking the time to file a report!
Related to #285.

**Comment by wucke13** [comment]
Ah, I searched a bit but could not find a related issue. Sorry for making a new one, shall I close this in favor of #285 ?

**Comment by a-kenji** [comment]
No problem and I don't see a reason you would need to. Maybe people can find it better now.

**Comment by a-kenji** [comment]
@wucke13 

Im closing this, should be fixed by `0.6.0`, if that is not the case for you please reach out again!

**Comment by wucke13** [comment]
Unfortunately not for me:
![image](https://user-images.githubusercontent.com/20400405/116607366-2f2efe80-a932-11eb-957e-fc46a68d9f63.png)

**Comment by a-kenji** [comment]
@wucke13 
Thank you for testing it out so quickly!

**Comment by a-kenji** [comment]
@wucke13
Do you mind checking again, if the recent main fixes this issue for you?

**Comment by wucke13** [comment]
@a-kenji 

![image](https://user-images.githubusercontent.com/20400405/116933344-b7c7da80-ac63-11eb-8155-3dcb88f4a30a.png)

Thank you for the quick fix - problem solved :smile: .

**Comment by a-kenji** [comment]
I am glad that it fixed it for you!
But it was @imsnif that fixed it :+1: .
