### ISSUE TITLE
Alt+f keybinding in v0.41.0 breaks CLI navigation

### ISSUE THREAD

**Issue by dashmage** [zellij-org/zellij#3730]
With v0.41.0, the `Alt+f` keybinding is now [mapped to `ToggleFloatingPlanes`](https://github.com/zellij-org/zellij/blob/4b806795c3485a247929cbb55db0cdb0b6fd9bed/example/default.kdl#L164) in the default config file. But this breaks the behaviour of moving forward by one word when navigating through commands on the terminal. I believe this functionality should be using another non-conflicting keybinding.

I've currently disabled this behaviour by adding adding `unbind "Alt f"` in the `normal` block.

**Comment by imsnif** [comment]
While I very much hear you about the colliding nature of `Alt f` and can understand it's frustrating to have keys collide even in the "non-colliding" preset, there are no keys that will not collide for anyone. 

To bypass this though, you don't even need to edit the config file like you did. You can remap the leader keys (in this case the `Alt` key) in the configuration screen (the same one used to change keybinding presets). Open it with `Ctrl o` + `c` (or `Ctrl g` + `o` + `c`) and then choose a different leader than Alt (eg. `Ctrl-Alt`, `Alt-Shift`, `Super`, etc.)

**Comment by dashmage** [comment]
I totally understand, will look into the leader key remap as well.

Thanks for the super quick response and for all the good work you've put into zellij. Can't imagine my terminal experience without it now 😄 

Since I'm able to make things work with `unbind` itself currently, and there's a way to choose a different leader, I'll go ahead and close the issue.
