### ISSUE TITLE
New command NewTabWithIndex

### ISSUE THREAD

**Issue by Sh4d1** [zellij-org/zellij#3736]
Hello! So I'm trying zellij (great work by the way!), and I still heavily have a tmux muscle memory where I could change/create tabs with `Alt + <number>`, which is very handy imho! 

I was quickly reading through the code, and it seems it would be quite easy to add as the core functionalities seems to already be implemented. 
Would you be open to a `NewTabWithIndex` action that creates a new tab with the given index. If yes, I could try to implement it, it is "just" adding the command and payload to the proto, modify the server & client to use that, and the docs? Or am I missing something?

**Comment by Zykino** [comment]
In the previous version (0.40.1), I had this bindings in config that helped me navigate quickly between tabs:

```kdl
    normal {
        // uncomment this and adjust key if using copy_on_select=false
        // bind "Alt c" { Copy; }
        bind "Alt 1" { GoToTab 1; }
        bind "Alt 2" { GoToTab 2; }
        bind "Alt 3" { GoToTab 3; }
        bind "Alt 4" { GoToTab 4; }
        bind "Alt 5" { GoToTab 5; }
        bind "Alt 6" { GoToTab 6; }
        bind "Alt 7" { GoToTab 7; }
        bind "Alt 8" { GoToTab 8; }
        bind "Alt 9" { GoToTab 9; }
        bind "Alt 0" { GoToTab 10; }
    }
```

Creating the 10’s tab when I only have 2 seems strange, or maybe I missed something in you explanation?
You can also modify the keybindings as `bind "Alt 1" { NewTab; GoToTab 1; }`… but that would create a new tab each time. Maybe with some change in leader key it works better like `bind "Ctrl Alt 1" { NewTab; GoToTab 1; }` (I did not test.)

**Comment by Sh4d1** [comment]
No you're right in your understanding, like I could have tab 1, 6 and 10 only. But then by playing a bit with the tabs in zellij, I can find myself having tab 3, 5 and 7 open too, so it's not that weird I guess?

**Comment by Zykino** [comment]
If you only have "Tab #3", "Tab #5" and no others, then you access them with `Alt 1` and `Alt 2`. You can rename them "Foo" and "Bar" if you want, that will not change the way you access them.

And I just tested: `NewTab` already switch to that tab. So `Ctrl + t, n` create a new tab and switch to it.

**Comment by Sh4d1** [comment]
Indeed my bad, I was convinced I tested it but you're right it will reset the index! 

And yes, it's just that it is (at least for me but I get it if it's not common 😄), practical to just use alt + number to create and switch betweens tabs!

**Comment by Zykino** [comment]
I think there is no way to do exactly what you want. But you should be able to do it with a plugin. See the API here: https://docs.rs/zellij-tile/latest/zellij_tile/shim/index.html

**Comment by Sh4d1** [comment]
Thanks I'll take a look and update here if I end up somewhere 😄 I'll close then!
