### ISSUE TITLE
save command history when kill the session 

### ISSUE THREAD

**Issue by Cosss7** [zellij-org/zellij#3741]
Maybe something I miss, when I kill the session, delete the session, their command history can't be saved. 

my issue is like https://github.com/zellij-org/zellij/issues/2437

but basiclly, only when quit from zellij session, save all command history

if this feature somebody mentioned or already exist, or the maintainer don't consider to achive this, LET ME KNOW

THANKS

**Comment by Zykino** [comment]
This has to do with how your shell (fish? bash? zsh? nu? or any other) react when it is exited from outside. Maybe there is some config for that in there, but zellij does not know how the shell you use work, and it does not interact with the command’s "history".

**Comment by Cosss7** [comment]
OK, I see
