### ISSUE TITLE
`Ctrl + j` seems to be hijacked by Zellij after update

### ISSUE THREAD

**Issue by eyevanovich** [zellij-org/zellij#3744]
# 2. Issues with the Zellij UI / behavior / crash

## Issue description

MacOS 14.7.1
WezTerm 20240203-110809-5046fc22
Zellij v0.41.1
Helix Editor 24.7

I just updated to Zellij v0.41.1 and it seems while I'm using it with Helix the Ctrl + j command doesn't work like it used to. I've narrowed it down to Zellij by opening the editor in another terminal window and the behavior works as intended. I typically have Zellij locked by default and I have no keybindings in Zellij set to Ctrl + j.

## Minimal reproduction

1. Helix Editor with keybinding set to:
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

Essentially this just moves the line you are on up (Ctrl + k) or down (Ctrl + j)

2. Open Helix in blank Wezterm terminal window and try to use the above bindings.
3. Open a new terminal session and activate a Zellij session using the `default` layout.
4. Open Helix in the session and try the above key bindings

I've attached a screen capture here demonstrating the problem.

https://github.com/user-attachments/assets/49bb1fbb-62b6-49d7-8c0b-50abe8b0daf6

**Comment by eyevanovich** [comment]
In my search to an answer on this it appears that Zellij is translating `Ctrl + j` to `return` for some reason. Seems a bit odd that it started doing this after the update.

**Comment by micdahl** [comment]
This behaviour messes up my neovim config. 'C-J' as a keymap is not working in neovim when running Zellij any more.

**Comment by pkarlovsek** [comment]
Same here, on Win 11, Windows Terminal, WSL2, Zellij 0.41.1.

**Comment by Senzaki** [comment]
I had the same problem (Ubuntu 24.04, Zellij 0.41.1, C-j did not work in neovim).

I can confirm https://github.com/zellij-org/zellij/pull/3746 fixes it for me.

**Comment by eyevanovich** [comment]
This has been fixed in `v0.41.2`
