### ISSUE TITLE
Hello, what is zellij?

### ISSUE THREAD

**Issue by lukassup** [zellij-org/zellij#3784]
I've tried to read the readme but it doesn't say if it's a shell or a multiplexer or what it is... so what is this?

```
What is this?

[Zellij](https://github.com/zellij-org/zellij#origin-of-the-name) is a workspace <...>

Zellij is designed around the philosophy <...>

Zellij is geared toward <...>
```

**Comment by tranzystorekk** [comment]
See https://zellij.dev/about/ for more info

**Comment by TheButlah** [comment]
There a video that shows what it is, and in the second sentence of the README it says its a terminal multiplexer. Not sure what more clarification can be given than that.

**Comment by lukassup** [comment]
Thanks, this clears things up. Looks like a great project btw!
