### ISSUE TITLE
paths for system wide config and plugin dir

### ISSUE THREAD

**Issue by darix** [zellij-org/zellij#380]
We are working on a package for opensuse and it seems so far it only searches for plugins in the user home dir but not in a system path yet? same for the system wide config. which path should be used there?

**Comment by darix** [comment]
While we are at it ... from the strace it looks like it tries to deploy the files from the assets directory into paths? like zsh completion. is there an option to turn that off at build time?

**Comment by a-kenji** [comment]
@darix, Thank you for taking the time opening this issue! 

>We are working on a package for opensuse and it seems so far it only searches for plugins in the user home dir but not in a system path yet?

Yes, currently we only respect the HOME variable in configuration/data directories and XDG. Where would you expect that directory to be? `/etc/opt/zellij/config` and `/etc/opt/zellij/data` ? 
Would that be something that could be valuable to specify at build time?

>While we are at it ... from the strace it looks like it tries to deploy the files from the assets directory into paths? like zsh completion. is there an option to turn that off at build time?

Currently not, though I am working on that.
I hope I will have it ready in about a week - it shouldn't try to deploy assets unprompted anymore. 
On current main it doesn't try to deploy the completions anymore, but still the plugins and layouts.

**Comment by darix** [comment]
well anything that doesnt need modification from user `/usr/share/zellij/{plugins,layouts}`

for the config `/etc/zerllij/config.yaml`

**Comment by a-kenji** [comment]
Thank you for the input.

**Comment by darix** [comment]
I enjoy packaging and integrating things into a distribution. So I am happy to share the experience gained from that. :)

**Comment by a-kenji** [comment]
It looks for the config now also in `/etc/zerllij/config.yaml`

**Comment by a-kenji** [comment]
@darix 
Do you mind giving some input on #455? 
What would be a good way for you to handle manpages from a distribution point of view.

**Comment by darix** [comment]
are you talking about the generation part of the install part?

**Comment by Adhalianna** [comment]
I should probably mention that the way I made `cargo make` install the manpage was by invoking `sudo cp` which is not really a portable solution (sudoers rights may vary, not sure how much, what I needed then was access to `/usr/share/man`) and I can image that being asked for password might create some issues in distributions' install scripts. I removed it after realising that. I believe it is package manager's fake root that handles things like this.

**Comment by darix** [comment]
1. you cant assume that you can do sudo.
2. you need DESTDIR support. packagers never do install into the actual directory but we use DESTDIR (%{buildroot} in the spec file below.)
3. requiring the generation tool is fine i suppose we have to ship a few ones already. so why not this one as well.

our opensuse spec file (which can be make work on fedora easily if wanted:

https://build.opensuse.org/package/view_file/home:darix:apps/zellij/zellij.spec?expand=1

in general if the project is interested i can help you setup linux package builds through the build.opensuse.org. we can do deb, rpm and arch linux and it can be hooked up to github easily. for main branch builds e.g. .

**Comment by a-kenji** [comment]
@darix 
Thanks for the input again!
I hope I have zellij in a state soon that we can turn off the automatic installation at compile time.
As well as giving a prefix for the configuration and data dirs.

>     2\. you need DESTDIR support. packagers never do install into the actual directory but we use DESTDIR (%{buildroot} in the spec file below.)

Meaning in the `Install Makefile, right?`

**Comment by darix** [comment]
yes.

**Comment by darix** [comment]
why are there precompiled wasm files in the assets directory?

**Comment by a-kenji** [comment]
If I recall correctly that has something to do with our cargo publish action, but we are hoping in the future to omit the checking of the compiled wasm plugins into git.
Maybe @TheLostLambda  has more input on this.

**Comment by TheLostLambda** [comment]
@darix Yeah, it's because `cargo-install` can't run our custom build system (as far as I'm aware), so the WASM assets need to be shipped with the crate or you'll get compiler-errors when it fails to `include_bytes!` the default plugins.

Essentially, we need to ensure that plugins are compiled to WASM then optimized and copied to the correct location *before* Zellij itself is compiled, but `cargo install` doesn't really offer a way to do this, so we ship the release assets from the outset. It's a touch odd, but the only thing working at the moment.

**Comment by darix** [comment]
I thought wasm  was a normal rust target

**Comment by a-kenji** [comment]
Wasm is a normal rust target. And that is also not our problem. It has to do with right now shipping generated assets from a different workspace is not something we have a clear path for yet. And we want to ship them at least in the cargo version to have an easy setup experience. Our aim is to not have them checked in - in the future.

I could make our assets completely optional. It would be a feature that the install feature would depend on, so distributions could also decide, if they wanted the assets shipped at all with the binary - or not.
Do you think that would be a good idea cc @TheLostLambda .
