### ISSUE TITLE
Zellij crashes if '/' is used at the session name

### ISSUE THREAD

**Issue by diegobernardes** [zellij-org/zellij#3805]
## Issue description
Zellij crashes if the character `/` is used at the session name.

## Minimal reproduction
At the default configuration, go to `Session`, and then create a new session with `/` at the name, e.g., `projects/api`. This will crash zellij.

**Comment by imsnif** [comment]
Hey, I issued a fix for this: https://github.com/zellij-org/zellij/pull/3839

Thanks for the report and my apologies for the experience!

**Comment by diegobernardes** [comment]
Thanks for the work you've put into Zellij.
