### ISSUE TITLE
Feature: ability to create layout file from current layout

### ISSUE THREAD

**Issue by wheresvic** [zellij-org/zellij#381]
Hello and thank you for making Zellij! Looks awesome and I'm looking to start using it daily.

One thing that would certainly make my life easier is if I could configure zellij layout and then export the layout file so I have the same layout on my work system.

Cheers!

**Comment by a-kenji** [comment]
Thank you for the suggestion, this would be awesome!

**Comment by AjiBuster499** [comment]
Hi, I'm a CS student looking to get some Rust experience, and I would like to take this on, if that is okay. I think I know of a way to solve the issue at hand.

**Comment by a-kenji** [comment]
The `DumpScreen` action doesn't interact with the layout, it is a misnomer. It doesn't dump the screen, it dumps the content of the currently specified pane (not the screen) inside of a specified file. It is not bound by default, because it depends heavily on the usecase, if it is useful for you.

**Comment by vodrazka** [comment]
This would be awesome

**Comment by min2sia** [comment]
Just spent an hour trying to figure out how to lay out my current session with 3 tabs into a .kdl file :)
This export would come very handy.

**Comment by Lockszmith-GH** [comment]
Chiming in on this as well. This would be a great feature.

**Comment by franalbani** [comment]
Read https://zellij.dev/documentation/session-resurrection#session-files-in-the-cache and try `find ~/.cache/zellij/ -iname '*.kdl'`.

**Comment by Lockszmith-GH** [comment]
Almost there. Instead of automated, having it on-demand would be awesome.

I would prefer to have the auto-generate/caching feature turned off, and be able to call zellij with a command line action to that would dump the current layout into the file of my choice.

**Comment by imsnif** [comment]
This is possible with `zellij action dump-layout` since `0.39`, sorry - I still need to document it.
