### ISSUE TITLE
Zellij handling "Alt Shift" incorrectly/inconsistently in Alacritty

### ISSUE THREAD

**Issue by bcspragu** [zellij-org/zellij#3817]
# 2. Issues with the Zellij UI / behavior / crash

## Issue description

I've observed some odd behavior for using "Alt Shift" in terminal applications, where the whole key combo is either swallowed or the "Shift" key is ignored.

## Minimal reproduction

For example, in [Helix](https://helix-editor.com/):

- Pressing `Alt-Shift-k` (i.e. `Alt-K`)
  - [Not in Zellij] Triggers the "remove selections matching regex" command
  - [In Zellij] Does nothing
 
- Pressing `Alt-Shift-j` (i.e. `Alt-J`)
  - [Not in Zellij] Triggers the "join lines and select the spaces" command
  - [In Zellij] Does nothing
 
- Pressing `Alt-Shift-;` (i.e. `Alt-:)
  - [Not in Zellij] Triggers the "Ensure selection is at the end" command
  - [In Zellij] Triggers the command mapped to `Alt-;` (e.g. the command you'd execute if not pressing `Shift`)

All of these tests done with `zellij setup --clean`. I'm not sure why `;/:` behaves differently, could be because there's no Zellij binding for those?

## Other relevant information

I tried `unbind "Alt Shift k" "Alt K"`, but the behavior was the same.

Note: after testing this, I tried some other terminals, and they all behaved differently :upside_down_face: 

- **xterm** - `Alt-Shift-*` bindings don't work in _or_ out of Zellij
- **rxvt-unicode** - `Alt-Shift-*` bindings work correctly in _and_ out of Zellij

So that's odd, but I'm still inclined to call this a Zellij issue (i.e. as opposed to an Alacritty issue) because the behavior changes when using Zellij

**Comment by v0idh4nd** [comment]
Disabling
`support_kitty_keyboard_protocol false`
solves the problem

**Comment by bcspragu** [comment]
> Disabling `support_kitty_keyboard_protocol false` solves the problem

I can confirm it does! No idea what other implications there are for this change (I don't think Alacritty supports anything from Kitty), but it definitely fixes the issue, thanks!

Marking this one as closed in favor of #3789

**Comment by blixenkrone** [comment]
> Disabling `support_kitty_keyboard_protocol false` solves the problem

Disabling this in Alacritty, or what is this reference?

**Comment by bcspragu** [comment]
> Disabling this in Alacritty, or what is this reference?

In Zellij, e.g. in `~/.config/zellij/config.kdl`:

```kdl
keybinds clear-defaults=true { ... }

// other stuff

support_kitty_keyboard_protocol false
```

**Comment by blixenkrone** [comment]
> > Disabling this in Alacritty, or what is this reference?
> 
> In Zellij, e.g. in `~/.config/zellij/config.kdl`:
> 
> ```
> keybinds clear-defaults=true { ... }
> 
> // other stuff
> 
> support_kitty_keyboard_protocol false
> ```

Aw man you just fixed the issue I raised in https://github.com/zellij-org/zellij/issues/3789.
I'll update the thread, cheers!
