### ISSUE TITLE
crash on moving between panes and tabs.

### ISSUE THREAD

**Issue by brunbjerg** [zellij-org/zellij#3842]
# 2. Issues with the Zellij UI / behavior / crash

## Issue description
I think that the error from the terminal is pretty descriptive. 

The error occured while opening my shell contents in my $EDITOR and moving between tabs and panes.

## Minimal reproduction
I will update the issue if it happens again. I do cannot reproduce it manually. 

Any guidance for trouble  shoot if possible is welcome.

## Other relevant information
```
[ 10:33:10 ] ❄ fsh > zellij  --version
zellij 0.41.1
```

Error occurred in server:
```bash
[zellij-error-log-50000-lines.txt](https://github.com/user-attachments/files/18036772/zellij-error-log-50000-lines.txt)

  × Thread 'screen' panicked.
  ├─▶ Originating Thread(s)
  │     1. stdin_handler_thread: AcceptInput
  │     2. screen_thread: MoveFocusRightOrNextTab
  │
  ├─▶ At zellij-server/src/panes/tiled_panes/mod.rs:1623:73
  ╰─▶ called `Option::unwrap()` on a `None` value
  help: If you are seeing this message, it means that something went wrong.

        -> To get additional information, check the log at: /tmp/zellij-1001/zellij-log/zellij.log
        -> To see a backtrace next time, reproduce the error with: RUST_BACKTRACE=1 zellij [...]
        -> To help us fix this, please open an issue: https://github.com/zellij-org/zellij/issues
```

**Comment by imsnif** [comment]
Thanks for the report and my apologies for the experience! This was fixed in version 0.41.2 (specifically https://github.com/zellij-org/zellij/pull/3776).
