### ISSUE TITLE
Kakoune doesn’t render well in Zellij

### ISSUE THREAD

**Issue by alexherbo2** [zellij-org/zellij#385]
https://github.com/mawww/kakoune/issues/4164

**Comment by a-kenji** [comment]
Thanks for the issue! 
Possbly related #353.

**Comment by Glaeqen** [comment]
My kakoune is suffering in a different way :D 
![image](https://user-images.githubusercontent.com/20447270/116125764-305bf380-a6c6-11eb-8f84-4e6aa870c07b.png)
![image](https://user-images.githubusercontent.com/20447270/116125775-32be4d80-a6c6-11eb-9495-6cf6022a7ea7.png)
I'm using built-in gruvbox theme.
Normally, it looks like this
![image](https://user-images.githubusercontent.com/20447270/116126181-a1031000-a6c6-11eb-929a-6be6b7d110cc.png)
![image](https://user-images.githubusercontent.com/20447270/116126047-7913ac80-a6c6-11eb-8faa-e1cb9aa80029.png)
Not sure if I should have created a separate issue but here I am.

**Comment by alexherbo2** [comment]
@Glaeqen It’s because master still uses ncurses.  Try with the [builtin-terminal-ui] branch.

[builtin-terminal-ui]: https://github.com/mawww/kakoune/tree/builtin-terminal-ui

**Comment by Glaeqen** [comment]
> @Glaeqen It’s because master still uses ncurses. Try with the [builtin-terminal-ui](https://github.com/mawww/kakoune/tree/builtin-terminal-ui) branch.

Thanks. Now I got to your problem :P But, does it mean that every TUI app based on ncurses is going to be broken in Zellij?

**Comment by alexherbo2** [comment]
Kakoune uses palette changes.

See [FAQ – I’m using tmux and colors look weird].

[FAQ – I’m using tmux and colors look weird]: https://github.com/mawww/kakoune/blob/master/doc/pages/faq.asciidoc#im-using-tmux-and-colors-look-weird

**Comment by bensleveritt** [comment]
Looks like @mawww has some idea why this is happening: https://github.com/mawww/kakoune/issues/4164#issuecomment-826403203

**Comment by imsnif** [comment]
Hey, I made quite some terminal fixes recently and right now kakoune seems to render well for me in Zellij. Though it might be an issue with a specific version or setup. Could you please try with the latest version (0.7.0) and see if it works well?

**Comment by imsnif** [comment]
@alexherbo2 - everything here should not be fixed (in version 0.9.0). Can you please check?
