### ISSUE TITLE
Unable to use `--session` and `--layout` flags simultaneously. 

### ISSUE THREAD

**Issue by fidiego** [zellij-org/zellij#3868]
## Issue description

Unable to use `--session` and `--layout` flags simultaneously. 

## Minimal reproduction

```bash
$ zj -s new -l compact
Session 'new' not found. The following sessions are active:
...
```

```bash
$ zj -l compact -s new
Session 'new' not found. The following sessions are active:
...
```

```bash
$ zj --layout compact --session new
Session 'new' not found. The following sessions are active:
...
```

I can use one flag, or the other. Just not both.

## Other relevant information

```bash
zj -V
zellij 0.41.2
```

M3 MacBook Pro

**Comment by imsnif** [comment]
Try `--new-session-with-layout` instead of `--layout`

**Comment by fidiego** [comment]
@imsnif that works for me. thanks!
