### ISSUE TITLE
Top bar size is wrong if running terminal emulator in kiosk

### ISSUE THREAD

**Issue by wucke13** [zellij-org/zellij#389]
## In Case of Graphical, or Performance Issues

Please run `zellij --debug` and then recreate your issue.

Please attach the files that were created in

`/tmp/zellij/zellij-log/`

__To reproduce__, run `zellij` in `alacritty` in `cage`:
`cage -- alacritty --command zellij --debug`

## Information

`zellij 0.5.0`

## Screenshots

![image](https://user-images.githubusercontent.com/20400405/116223214-99d41480-a74f-11eb-8547-7cf1e1207667.png)

The problem is only in the first tab.

![image](https://user-images.githubusercontent.com/20400405/116223248-a2c4e600-a74f-11eb-947a-31f5b2ede2e9.png)

[log.txt](https://github.com/zellij-org/zellij/files/6383682/log.txt)

**Comment by imsnif** [comment]
This should be fixed in `0.5.1` - could you please try?

**Comment by wucke13** [comment]
Can confirm, sorry for the noise.
