### ISSUE TITLE
shift-alt combinations not working after 0.41.1 (macos / alacritty / helix)

### ISSUE THREAD

**Issue by n8henrie** [zellij-org/zellij#3897]
# 2. Issues with the Zellij UI / behavior / crash

## Issue description

I'm at the limits of my ability to debug this, but I understand it may be a tough repro from others -- thanks for any help you can provide. I'm on macos, I use alacritty + zellij, with helix as my primary editor.

In zellij 0.41.1 and 0.41.2, <kbd>shift</kbd><kbd>alt</kbd> keyboard shortcuts in Helix stopped working . They work find if I downgrade to 0.40.1.

Two examples that keep catching me:

https://docs.helix-editor.com/keymap.html

- `Alt-C` (copy_selection_on_prev_line)
- `Alt-J` (join_selections_space)

`Alt-C`, for example, should extend the selection upwards (vertically), but instead it acts just like `Alt-c`.

I have tried completely removing my config file and using all defaults. I've also tried unbinding everything.

This behavior even shows up in locked mode.

Oddly, this behavior resolves if I use helix in zellij in Terminal.app (instead of Alacritty), or if I use helix in Alacritty (without zellij), or (as noted) if I downgrade zellij:

 - older zellij + alacritty + helix = works
 - newer zellij + Terminal.app + helix = works
 - Alacritty + helix = works
 - newer zellij + alacritty + helix = broken

## Minimal reproduction

As per above. Also, I have `option_as_alt = "Both"` set in my Alacritty config. (This is not new.)

## Other relevant information

```
$ zellij --version
zellij 0.41.2
$ alacritty --version
alacritty 0.14.0
$ sw_vers
ProductName:            macOS
ProductVersion:         15.2
BuildVersion:           24C101
```

**Comment by imsnif** [comment]
Hey, this is an issue on the Helix side. More info: https://github.com/zellij-org/zellij/issues/3789

**Comment by n8henrie** [comment]
Wow, what an amazing thorough thread (full of open-source collaboration). Thanks!

For other readers:

- `support_kitty_keyboard_protocol false` as a short-termworkaround workaround
- follow https://github.com/zellij-org/zellij/issues/3789
