### ISSUE TITLE
Color scheme support

### ISSUE THREAD

**Issue by mrckndt** [zellij-org/zellij#390]
Hi,
Are there any plans on adding support for color scheme settings? I'm using a light terminal color scheme and the bright green characters in the Tips e.g. are really hard to read on a white (or other light) terminal background.

**Comment by TheLostLambda** [comment]
Yup! Things are currently being worked on by @denismaxim0v in #239 ! Hopefully this will be ready soon :)

**Comment by kingdido999** [comment]
Hi, just wondering what is the status of the color scheme support right now? Looks like #239 has been merged, but I don't see related documentation. Could you show me how to change the color scheme? Thanks!

**Comment by proudmuslim-dev** [comment]
> Hi, just wondering what is the status of the color scheme support right now? Looks like #239 has been merged, but I don't see related documentation. Could you show me how to change the color scheme? Thanks!

Seconded

**Comment by a-kenji** [comment]
@proudmuslim-dev 

While that is true, the functionality is currently not active, but we are looking at including it
in the near future, then there will also be a note in the docs about it.

**Comment by imsnif** [comment]
I think if someone wants to work on this, it shouldn't be too hard to support configurable themes, right @a-kenji ? Not taking it from anywhere, just providing a config file with colors? We already have the infrastructure for this to populate to all the plugins iirc

**Comment by a-kenji** [comment]
@imsnif  - Yes, the most basic theming functionality should be quite straightforward to implement,
if I understand it correctly.

**Comment by imsnif** [comment]
Awesome. I put a `help wanted` and  `good first issue` labels on this if anyone's interested in giving this a go. It might be a little on the less trivial side of "good first issue" though - so heads up, and feel free to reach out for guidance. :)

**Comment by proudmuslim-dev** [comment]
> @proudmuslim-dev
> 
> While that is true, the functionality is currently not active, but we are looking at including it
> in the near future, then there will also be a note in the docs about it.

@a-kenji Ah, thank you for letting me know

**Comment by talios** [comment]
Since this was merged I'm getting:

```
zellij --debug
Error occured in server:
Originating Thread(s):
1. ipc_server: NewClient
2. pty_thread: NewTab
3. screen_thread: ApplyLayout
4. plugin_thread: Update

Error: thread 'wasm' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeError { source: Trap(UnreachableCodeReached), wasm_trace: [FrameInfo { module_name: "<module>", func_index: 144, function_name: None, func_start: SourceLoc(90092), instr: SourceLoc(92528) }, FrameInfo { module_name: "<module>", func_index: 191, function_name: None, func_start: SourceLoc(104805), instr: SourceLoc(104968) }, FrameInfo { module_name: "<module>", func_index: 190, function_name: None, func_start: SourceLoc(104758), instr: SourceLoc(104798) }, FrameInfo { module_name: "<module>", func_index: 85, function_name: None, func_start: SourceLoc(60947), instr: SourceLoc(61019) }, FrameInfo { module_name: "<module>", func_index: 72, function_name: None, func_start: SourceLoc(53446), instr: SourceLoc(53494) }, FrameInfo { module_name: "<module>", func_index: 66, function_name: None, func_start: SourceLoc(52657), instr: SourceLoc(52778) }, FrameInfo { module_name: "<module>", func_index: 249, function_name: None, func_start: SourceLoc(119765), instr: SourceLoc(121581) }, FrameInfo { module_name: "<module>", func_index: 290, function_name: None, func_start: SourceLoc(146667), instr: SourceLoc(146668) }], native_trace:    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
 }': zellij-server/src/wasm_vm.rs:121
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: zellij_utils::errors::handle_panic
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_handler::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: _rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: zellij_server::wasm_vm::wasm_thread_main
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: std::sys::unix::thread::Thread::new::thread_start
  13: __pthread_start
```

when running zellij - my only custom config is a single key remapping.

This also happens when deleting everything from `/Users/amrk/Library/Application Support/org.Zellij-Contributors.Zellij`.

**Comment by a-kenji** [comment]
@talios 
Thank you for communicating this issue!
I will look into it.

**Comment by a-kenji** [comment]
@talios 
Does it happen when running with `cargo make run`, or do you install it with `cargo make install` and then run zellij?

**Comment by talios** [comment]
Installing via `cargo install --path . --force` which I've nominally always used. Tho I just noticed in the README the mention of `cargo-make` which I was unaware of.

Just tried building `main/HEAD (d7f12ea58c3e93)` with `cargo make install` but `status-bar` failed to build:

```
/Users/amrk/IdeaProjects/upstream/zellij
[cargo-make][2] INFO - Project: status-bar
[cargo-make][2] INFO - Build File: Makefile.toml
[cargo-make][2] INFO - Task: build-release
[cargo-make][2] INFO - Profile: development
[cargo-make][2] INFO - Execute Command: "cargo" "build" "--release"
   Compiling itoa v0.4.7
   Compiling lazy_static v1.4.0
   Compiling strum v0.20.0
   Compiling atty v0.2.14
   Compiling ansi_term v0.12.1
   Compiling ryu v1.0.5
   Compiling serde v1.0.125
   Compiling serde_json v1.0.64
error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-wasi` target may not be installed

error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-wasi` target may not be installed

error: aborting due to previous error

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
For more information about this error, try `rustc --explain E0463`.
error: could not compile `itoa`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-wasi` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error[E0463]: can't find crate for `std`
  |
  = note: the `wasm32-wasi` target may not be installed

error[E0463]: can't find crate for `std`
  |
  = note: the `wasm32-wasi` target may not be installed

error[E0463]: can't find crate for `std`
  |
  = note: the `wasm32-wasi` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error[E0463]: can't find crate for `std`
  |
  = note: the `wasm32-wasi` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: build failed
[cargo-make][2] ERROR - Error while executing command, exit code: 101
[cargo-make][2] WARN - Build Failed.
[cargo-make][1] ERROR - Error while executing command, exit code: 1
[cargo-make][1] WARN - Build Failed.
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
```

Going back to this commit I seem to get the same build issue. Hrm.

**Comment by a-kenji** [comment]
If the plugins get changed it can be harder to build from an unreleased main from source -
especially if one doesn't have the toolchain setup yet.

If we don't have a release soon I will commit the changed plugins, I think that should alleviate this
particular problem.

**Comment by a-kenji** [comment]
@talios 
I committed the recent plugins to the repository,
do you mind checking if it works for you now?

**Comment by talios** [comment]
@a-kenji I see the commits and plugin changes but seem to have the same problem after running  `git pull && git submodule update`.

`wasm32-wasi` target is installed as is the beta toolchain:

```
~/I/u/zellij on  main ↦  rustup target list | grep installed
wasm32-wasi (installed)
x86_64-apple-darwin (installed)
~/I/u/zellij on  main ↦  rustup toolchain list
stable-x86_64-apple-darwin
beta-x86_64-apple-darwin (override)
```

**Comment by a-kenji** [comment]
@talios 
Which same problem do you still have?

The one where `cargo make install` doesn't work, because it can't find the 
target, or the original problem with the wasm thread?

If it is the original problem, please try to delete your `data-dir` again,
since the version hasn't changed most likely the old plugins are still 
in there.

**Comment by talios** [comment]
@a-kenji Ahh sorry, should have clarified - the `cargo make install` one about the `wasm32-wasi`` target still plauges me.

**Comment by a-kenji** [comment]
@talios
No problem! I have been trying to understand what has been going on here
but I am not really sure.

Did you install the target and toolchain with the toolchain file?
If not, maybe that could help - but it seems that you have everything installed
correctly to me.

If you happen to use nix, maybe a shell could help:
```
git clone https://github.com/a-kenji/zellij-nix
nix develop
```
Warning: The shell builds binaryen from source.
