### ISSUE TITLE
Let a user know why the configuration is invalid

### ISSUE THREAD

**Issue by yykamei** [zellij-org/zellij#414]
Hi,

I'm curious whether Zellij can load a config file before calling [`start`](https://github.com/zellij-org/zellij/blob/b5d38e95c876f231a1c52ab2bcf805f65958d56c/src/common/mod.rs#L123). When I deliberately write an invalid configuration, Zellij exits with the status code 1 without any output. It would be inconvenient for a Zellij user, at least me, because the user should want to know why Zellij does not launch.

```console
$ cat config.yaml
keybinds: invalid
$ zellij --debug --config config.yaml
(Nothing appears)
```

I guess this is because the config loading starts **after** Zellij enters an alternative screen buffer. The most straightforward way to solve this might be just to disable an alternative screen buffer when Zellij detects the passed configuration is invalid. However, I think Zellij can load configuration before calling `start`, and it's more reasonable as Zellij doesn't have to set up the terminal when the config file is wrong. If it's good, I'm going to open a PR.

FYI, this is output after disabling the alternative screen buffer:

```console
$ zellij --version  --debug --config config.yaml; echo -e '\e[?1049l'
There was an error in the config file:
Deserialisation error: keybinds: invalid type: string "invalid", expected struct KeybindsFromYaml at line 1 column 11

```

By the way, it'll get even better to provide a feature to let users reload a configuration, but it's out of scope so far.

## Information

`zellij --version`: `0.7.0` (commit: b5d38e95c876f231a1c52ab2bcf805f65958d56c)

**Comment by a-kenji** [comment]
Thank you for taking the time writing this issue!
Yes, that is a problem and I have been thinking about how to tackle it.
Currently it tells you what is wrong with your configuration after you try to start it twice - but that is definitely  not wanted.
I like your proposed solution and would be happy about a pr.

> By the way, it'll get even better to provide a feature to let users reload a configuration, but it's out of scope so far.

I agree. We need to have some more changes in order to have that feature make sense. 
If you want you can also already open an issue on that.

**Comment by yykamei** [comment]
Thank you! I'll address this issue first :muscle: 

> > By the way, it'll get even better to provide a feature to let users reload a configuration, but it's out of scope so far.
> 
> I agree. We need to have some more changes in order to have that feature make sense.
> If you want you can also already open an issue on that.

OK, I'll open an issue later.
