### ISSUE TITLE
Command prompt input shifts right on first character

### ISSUE THREAD

**Issue by TheAlgorythm** [zellij-org/zellij#421]
As I type the first character, the curser shifts right but the character also appears under the curser. In short the added character appears one position right of the position of the curser while typing.

## In Case of Graphical, or Performance Issues

[zellij-3.log](https://github.com/zellij-org/zellij/files/6407721/zellij-3.log)

## Information

`zellij --version`: 0.5.1

It happens on Manjaro with ZSH (v5/[oh-my-zsh](https://ohmyz.sh)) and [Alacritty](https://github.com/alacritty/alacritty)/KDE Konsole and Powerlevel10k/[Starship](https://starship.rs) as a command prompt. I haven't tried any other permutation.
On macOS it worked with the same ZSH config.

If I should try anything, please let me know.

**Comment by imsnif** [comment]
I think this is the same issue as https://github.com/zellij-org/zellij/issues/429

Sorry about this - it's a priority for us. A workaround for now (if you're interested) can be not to have wide-characters (eg. the duck icon) in the prompt.

**Comment by TheAlgorythm** [comment]
@imsnif I don't think so as the exact same prompt on macOS does work. Later I will try it with another prompt.

**Comment by imsnif** [comment]
@TheAlgorythm - version `0.12.0` which we just released supports wide-characters properly. Want to see if this solves the issue for you?

**Comment by TheAlgorythm** [comment]
Now it works! Thank you 😊
