### ISSUE TITLE
Feature: version zellij executable

### ISSUE THREAD

**Issue by wheresvic** [zellij-org/zellij#438]
Hi,

As zellij gets updated regularly, it would be great to have the releases versioned, i.e. `zellij-0.6.0` instead of plain zellij. This way we can make a symlink to the latest version and rollback in case of any errors :)

**Comment by imsnif** [comment]
The .tar.gz archive is intentionally not versioned to make it easier to make a web link to the latest release... are you talking about that or about the executable itself inside that file?

**Comment by wheresvic** [comment]
If the the executable itself could be versioned that would be great.

This way I could have multiple zellij versions and symlink `zellij` to the latest release. Makes rollback in case of issues easier :).

**Comment by chessmango** [comment]
Sorry to bump a very quiet thread, but @wheresvic you might be interested in [asdf](https://asdf-vm.com/) for version management.

I've written a [plugin for Zellij](https://github.com/chessmango/asdf-zellij) which should help to keep track of versioning without each binary or archive needing to be named carefully. :)
It's fairly rudimentary but it gets the job done quite well.

**Comment by har7an** [comment]
Closing because a solution has been proposed. If this isn't satisfactory for you, feel free to reopen it!
