### ISSUE TITLE
Bug: Resize with `ctrl+R` only switches between panes and does not resize with arrow keys (v0.6.0)

### ISSUE THREAD

**Issue by wheresvic** [zellij-org/zellij#440]
With the latest release 0.6.0, hit `alt+n` to create a new pane. Then `ctrl+R` to jump into resize mode. Then hitting the arrow keys only switches between panes and does not actually resize.

Bug on linux x86_64 (Ubuntu 20.04).

**Comment by a-kenji** [comment]
Thanks for taking the time opening this issue!
This should be fixed in the next version.
