### ISSUE TITLE
running layout with strider causes terminal to hang

### ISSUE THREAD

**Issue by yhung119** [zellij-org/zellij#442]
Environment: Mac, zsh
Version: v0.6.0

Issue: When running `zellij --layout strider`, the terminal hangs and doesn't respond. Deleting the wasm file and rerunning `zellij` didn't fix the issue. Eventually, it was resolved by re-installing the entire zellij (uninstall and then install). Creating this Issue to track what exactly happened and, hopefully, to help those who might be in the same shoes as I did.

Installation that leads to the issue:
- First tried installing with `cargo install zellij` but got an error from tracing-core about `use of unstable library feature 'matches_macro'`. Same error as https://github.com/ClementTsang/bottom/issues/136. 
- Installed from downloading from Github released page.
- Fixed the cargo install issue and installed again with `cargo install zellij`
- Encountered the strider issue.

**Comment by horasal** [comment]
> First tried installing with cargo install zellij but got an error from tracing-core about use of unstable library feature 'matches_macro'

try `rustup update` 
this feature is stablized at 1.42.0 https://blog.rust-lang.org/2020/03/12/Rust-1.42.html

**Comment by a-kenji** [comment]
@yhung119 
Is that still a problem for you?

**Comment by raphCode** [comment]
No answer probably means no, or lost interest

I think we might close this.
