### ISSUE TITLE
kakoune: cursor is not shown on focus, but without focus it is visible

### ISSUE THREAD

**Issue by matu3ba** [zellij-org/zellij#444]
### Expected

Cursor should be always visible and especially on focus.

### Actual

Cursor is only visible, if focus is not on zellij.

In a clean terminal
`tput lines`: 43
`tput cols`:  158
Inside zellij
`tput lines`: 38
`tput cols`:  158

## Information

Linux, EndeavourOS (Arch derivate), KDE Plasma X11

alacritty 0.7.2 (5ac8060b), zellij 0.6.0 and kakoune (master)

### Focus

![focusOnZellij_cursorHidden](https://user-images.githubusercontent.com/13089667/116877340-1b2f1980-ac1e-11eb-97d2-d9a01943ae77.png)

### No focus

![focusNotOnZellij_cursorVisible](https://user-images.githubusercontent.com/13089667/116877363-22eebe00-ac1e-11eb-8181-67274e413292.png)

[log.txt](https://github.com/zellij-org/zellij/files/6414860/log.txt)
[zellij-3.log](https://github.com/zellij-org/zellij/files/6414861/zellij-3.log)
[zellij-4.log](https://github.com/zellij-org/zellij/files/6414862/zellij-4.log)
[zellij-7.log](https://github.com/zellij-org/zellij/files/6414863/zellij-7.log)

**Comment by matu3ba** [comment]
possibly related #385

**Comment by imsnif** [comment]
Hey, for me this seems fixed in 0.7.0, but it could be a matter of coloring or kakoune versions.
Can you please test with zellij 0.7.0 to see if this still happens?

If it still does, I might need some help with the logs, because it's a little hard for me to use them. What I see is this:
```
$ cat zellij-3.log
[misterspoon@pc src]$ kak Compilation.zig
[misterspoon@pc src]$
```
If you could please do the following:
1. Delete all the zellij log files in /tmp/zellij
2. Reproduce the bug inside Zellij with the `--debug` flag
3. Quit Zellij immediately with ctrl-q (don't quit kakoune)
4. Attach the zellij log files again (specifying the lines and columns of the Zellij pane)

If you like, you can cat the file to make sure it works :)

**Comment by matu3ba** [comment]
@imsnif Indeed. You are correct. Sorry for the inconvenience.

I think a checklist for bug requests and having the essential logs folded (but also including all log files) would be helpful.
Also I think that we can assume users are able to use the terminal with commands provided in the bug template.

Firejail (they support alot Linux distros with user issues) have the following template:

Write clear, concise and in textual form.

**Bug and expected behavior**
- Describe the bug.
- What did you expect to happen?

**No profile and disabling firejail**
- What changed calling `firejail --noprofile /path/to/program` in a terminal?
- What changed calling the program by path (e.g. `/usr/bin/vlc`)?

**Reproduce**
Steps to reproduce the behavior:
1. Run in bash `firejail PROGRAM`
2. See error `ERROR`
3. Click on '....'
4. Scroll down to '....'

**Environment**
 - Linux distribution and version (ie output of `lsb_release -a`, `screenfetch` or `cat /etc/os-release`)
 - Firejail version (output of `firejail --version`) exclusive or used git commit (`git rev-parse HEAD`)

**Additional context**
Other context about the problem like related errors to understand the problem.

**Checklist**
 - [ ] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
 - [ ] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
 - [ ] I have performed a short search for similar issues (to avoid opening a duplicate).
 - [ ] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.
 - [ ] Used `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 PROGRAM` to get english error-messages.
 - [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
 - [ ] This is not a question. Questions should be asked in https://github.com/netblue30/firejail/discussions.


<details><summary> debug output </summary>

```
OUTPUT OF `firejail --debug PROGRAM`
```

</details>

**Comment by matu3ba** [comment]
This was fixed somewhere between release 0.6 and 0.7.

**Comment by imsnif** [comment]
Thanks for checking this out, @matu3ba . I updated the issue template to include more accurate instructions now, thanks for the input! I'm not sure what you meant by "I think that we can assume users are able to use the terminal with commands provided in the bug template" - so I hope I didn't offend you in any way?

**Comment by matu3ba** [comment]
@imsnif Thanks for the changes. What I mean is that it might be simpler like this:

Thank you for taking the time to file an issue! Please follow the instructions and fill the missing parts below the instructions.
Try to be brief and concise.

<details><summary> Instructions </summary>

In Case of Graphical, or Performance Issues

1. Delete the contents of `/tmp/zellij/zellij-log`, ie with `cd /tmp/zellij/` and `rm -fr zellij-log/`
2. Run `zellij --debug`
3. Recreate your issue.
3. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

Please attach the files that were created in `/tmp/zellij/zellij-log/` to the extent you are comfortable with.

</details>

`zellij --version`: 
`tput lines`: 
`tput cols`: 
`uname -av` or `ver`(Windows): 
 
List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`nvim --version`: NVIM v0.5.0-dev+1299-g1c2e504d5  (used the appimage release)
`alacritty --version`: alacritty 0.7.2 (5ac8060b)
