### ISSUE TITLE
Proposal: change the config loading algorithm by removing `--config-dir` and `oprtion --clean`

### ISSUE THREAD

**Issue by yykamei** [zellij-org/zellij#446]
Sorry, this proposal has breaking changes.

`--config-dir` is used to specify where directory Zellij should find a config file. However, Zellij also has another option, `--config`. Perhaps, users might be confused about which option they should use. In my opinion, it's sufficient to provide only the `--config` option, so how about removing `--config-dir`?

In addition, I wonder Zellij could also remove the `option --clean` argument. According to this comment, `option --clean` disables the loading config from the default location, which is `$XDG_CONFIG_HOME/zellij/config.yaml` or `/etc/zellij/config.yaml`. However, I can get the same result without any `config.yaml` and command-line options. I think the default behavior of Zellij is the same as `option --clean`, so that's why I think `option --clean` could be removed.

https://github.com/zellij-org/zellij/blob/570ee31888368d292ac6b43d86c3fbb24148a136/src/cli.rs#L52

If this proposal is implemented, the config will be determined by this order.

1. Use the specified config with `--config`
2. Use `$XDG_CONFIG_HOME/zellij/config.yaml` if it exists
3. Use `/etc/zellij/config.yaml` if it exists
4. Use the default config

I will withdraw this proposal if any downvotes exist. Please comment your opinions here :smiley:

**Comment by a-kenji** [comment]
Thank you for taking the time writing this proposal down!

> `--config-dir` is used to specify where directory Zellij should find a config file. However, Zellij also has another option, `--config`. Perhaps, users might be confused about which option they should use. In my opinion, it's sufficient to provide only the `--config` option, so how about removing `--config-dir`?

At the moment it is redundant yes, sadly we don't have all the information at one location yet, but we are working towards having the `layout dir` and the `plugin dir` a subdir of `config dir`, so it is more accessible to users, maybe even a 'themes dir'. We are not sure about that yet.

> In addition, I wonder Zellij could also remove the `option --clean` argument. According to this comment, `option --clean` disables the loading config from the default location, which is `$XDG_CONFIG_HOME/zellij/config.yaml` or `/etc/zellij/config.yaml`. However, I can get the same result without any `config.yaml` and command-line options. I think the default behavior of Zellij is the same as `option --clean`, so that's why I think `option --clean` could be removed.

I would like to keep the `clean` option, but I agree the naming might not be the best. Yes it loads the default configuration, but it loads it even if there is already a `config` file. Especially if configuration options get more powerful and involved I think it is better to be able to try if a configuration messed the program up, or if its something else - easily. Without relocating, or renaming the whole configuration directory.

**Comment by yykamei** [comment]
Thanks for your reply!

> At the moment it is redundant yes, sadly we don't have all the information at one location yet, but we are working towards having the `layout dir` and the `plugin dir` a subdir of `config dir`, so it is more accessible to users, maybe even a 'themes dir'. We are not sure about that yet.

It makes sense :+1:  I was not aware of the other types of directories. I see, there are `layout dir`, `plugin dir`, and `config dir`. it looks good to have the option as it is.

> I would like to keep the `clean` option, but I agree the naming might not be the best. Yes it loads the default configuration, but it loads it even if there is already a `config` file. Especially if configuration options get more powerful and involved I think it is better to be able to try if a configuration messed the program up, or if its something else - easily. Without relocating, or renaming the whole configuration directory.

That's understandable. Let's keep the option, too.

Sorry for bothering you. I close this issue.
Thanks,

**Comment by a-kenji** [comment]
No problem. And thank you for opening this issue! It is always good clarifying those things. Maybe it was an oversight on our part, maybe it lets us find out more cool things!
