### ISSUE TITLE
navigation bars look strange using PuTTY

### ISSUE THREAD

**Issue by fansari** [zellij-org/zellij#451]
When I use PuTTY the navigation bars at top and bottom look strange. 

I have the same issue with Windows cmd or PowerShell.

**Comment by fansari** [comment]
[zellij-putty.docx](https://github.com/zellij-org/zellij/files/6419500/zellij-putty.docx)

**Comment by imsnif** [comment]
Hey, this looks like a font that needs to be patched. I'm not sure how to fix this in putty, but maybe you can get some inspiration from our docs? https://zellij.dev/documentation/compatibility.html

**Comment by fansari** [comment]
OK - things get complicated now. Maybe I will wait with zellij until you have a working version.

**Comment by imsnif** [comment]
Our version is working, it's still a beta though. :)

**Comment by fansari** [comment]
I have now installed "Cousine NF Regular" and selected this font in PuTTY.

This works!

**Comment by imsnif** [comment]
> I have now installed "Cousine NF Regular" and selected this font in PuTTY.
> 
> This works!

I'm happy to hear that! Thanks for the update. Hopefully this will also help others happening upon this issue :)
