### ISSUE TITLE
Zellig starts XQuartz on MacOS

### ISSUE THREAD

**Issue by talios** [zellij-org/zellij#452]
I've noticed Zellig starts running XQuartz ( X11 server ) when running on MacOS - is there any reason a console app is kicking in X?

Is it required somewhere?

**Comment by talios** [comment]
Note this is from a fresh HEAD build from git.

**Comment by a-kenji** [comment]
Thanks for taking the time writing this issue!
The current head uses `xrdb` in order to set themes according to the xresources file. 
It is not yet very well compartmentalized. I think this is something that should be looked in to. 

Maybe you can give feedback as how x is used on the Mac?

Does it make sense to include this module, or would it make sense to include it with conditional compilation?

**Comment by talios** [comment]
> Maybe you can give feedback as how x is used on the Mac?

Currently - it's not :) This a recently fresh OSX install and I don't use any X11 apps, but XQuartz was installed, but dormant.

When I started using Zellig I found XQuartz running with a "please upgrade" message, which I thought was just an automated update after a recent Big Sur upgrade - but must have been related to Zellig starting the process.

For now It's just something that sits in the task list to alt-tab over.

**Comment by imsnif** [comment]
I'm actually just working on patching some stuff related to this. I think for this release I'm going to put it behind a flag. Something like `--use-x-colors` until we can examine its implications further. Thanks for reporting this!

**Comment by a-kenji** [comment]
Thank you for the feedback! That makes sense.

> I'm actually just working on patching some stuff related to this. I think for this release I'm going to put it behind a flag. Something like `--use-x-colors` until we can examine its implications further. Thanks for reporting this!


I think that is a very reasonable approach. Once we support themes in the config people could opt in to that flag there.

**Comment by imsnif** [comment]
We ended up not including this feature, so it should be fine now. :) Thanks for reporting this!
