### ISSUE TITLE
No Build for Apple Darwin x86_64 in Version 0.7.0

### ISSUE THREAD

**Issue by saintphaenixos** [zellij-org/zellij#454]
I'm not sure if this was an oversight, however there is currently no build for Apple Darwin x86_64 after v.0.6.0.

I was hoping to test it out after seeing the release.

**Comment by imsnif** [comment]
I think you are certainly quicker than our CI ;P Check now? (I'm still in the middle of the release though, so haven't even had a chance to manually check stuff)

**Comment by saintphaenixos** [comment]
@imsnif 

oh lol, I think I just timed myself poorly. There it is!

Thank you!
