### ISSUE TITLE
Visual / full window mode for copy

### ISSUE THREAD

**Issue by haoadoresorange** [zellij-org/zellij#456]
Hello,
When using TM very often I run into the problem of having to copy something, intuitively I do that with my mouse and because of pane the select part just spread out across panes.
In Tmux you can go to visual mode and select copy like vim but I find that annoying too, not very much expected.
One solution I think of is to have shortcut to go full window mode in that you temporary detach all except the current pane, and then back.
Would it be something reasonable ? I might help with that.

**Comment by imsnif** [comment]
Hey, if I understand you correctly I think Zellij already has something similar? `ctrl-p` + `f`... is that what you're after?

**Comment by haoadoresorange** [comment]
> Hey, if I understand you correctly I think Zellij already has something similar? `ctrl-p` + `f`... is that what you're after?

Oh I didn't know about that ! thanks ! I close this thread here then.
