### ISSUE TITLE
can't upgrade to 0.7.0

### ISSUE THREAD

**Issue by barkanido** [zellij-org/zellij#459]
## Information

`zellij --version`: zellij 0.5.1
```
$ cargo install zellij

    Updating crates.io index
  Installing zellij v0.7.0
error: failed to compile `zellij v0.7.0`, intermediate artifacts can be found at `/tmp/cargo-install2Nuxct`

Caused by:
  failed to select a version for the requirement `zellij-tile = "^1.2.0"`
  candidate versions found which didn't match: 0.7.0, 0.6.0, 0.5.0
  location searched: crates.io index
  required by package `zellij v0.7.0`
```

**Comment by a-kenji** [comment]
@barkanido
Thank you for taking the time writing this issue!

@imsnif 
Maybe we need to release a new version on crates as soon as possible?
Since it points to a dependency that is not there in a form that can get ingested anymore.

**Comment by a-kenji** [comment]
@barkanido 
Sorry for the inconvenience. 
We restructured a little, which explains this breakage.

If you have the time can you please check if the process works now? It works for us at the moment, but it still could be some cached dependencies.

**Comment by barkanido** [comment]
yea.

works for me now!

thanks for the fast resolution.

**Comment by a-kenji** [comment]
Glad it works!
Thanks for checking!
