### ISSUE TITLE
Feature: navigating left/right should switch tabs if there's no pane

### ISSUE THREAD

**Issue by lilyball** [zellij-org/zellij#464]
When using the normal mode Alt+h/l binds to switch panes, it would be really convenient if I could use it to switch tabs if there is no pane in the selected left/right direction. This probably shouldn't apply to the pane mode movement, just to the normal mode keys (which I guess means it needs a new action, something like `MoveFocusOrPreviousPane: Left`). This would handle the common case of tabs with only one pane, or tabs with only vertically-stacked panes.

**Comment by a-kenji** [comment]
Thanks for taking the time writing this request! I think this would be great.
