### ISSUE TITLE
Don't change the names of "unnamed" tabs when closing/opening tabs

### ISSUE THREAD

**Issue by khs26** [zellij-org/zellij#474]
Currently, if I have e.g. four tabs open:
- `foo`
- `Tab #2` (unnamed)
- `Tab #3` (unnamed)
- `bar`

If I close tab `foo`, then the following changes occur:
- `foo` -> `<dead>`
- `Tab #2` -> `Tab #1`
- `Tab #3` -> `Tab #2`
- `bar` -> `bar`

The renaming of the numbered tabs is quite confusing. We should probably treat the numbers as automatically generated names, that are retained for the lifetime of the tab.

**Comment by AdaShoelace** [comment]
I'm currently working on implementing this but it has me asking some questions.
Lets say that we have three tabs open e.g `Tab #1`, `Tab #2` and `Tab #3`. We then decide to close `Tab #2`, which will leave us with `Tab #1` and `Tab #3`. In the case that we open a new tab will it fill the "hole" or just get appended as `Tab #4` and leave the list with a "hole" at index 1?

**Comment by imsnif** [comment]
> Lets say that we have three tabs open e.g `Tab #1`, `Tab #2` and `Tab #3`. We then decide to close `Tab #2`, which will leave us with `Tab #1` and `Tab #3`. In the case that we open a new tab will it fill the "hole" or just get appended as `Tab #4` and leave the list with a "hole" at index 1?

My vote goes for leaving a hole and opening `Tab #4`. I find the other behaviour a little surprising as a user "What? I just opened a tab, where is it?" - but maybe that's just me :)

**Comment by khs26** [comment]
Yeah, I'd agree with just appending to the list of tabs and leaving a hole.

**Comment by AdaShoelace** [comment]
Great, I agree with leaving a "hole" aswell.
Know I just need to understand the relationship between the name and rendering the text. From what I can gather the tab itself will have an empty string for a name if it is unnamed but still get rendered as `Tab #<num>`. 
Judging from this discussion this is not the way we want it to behave. But rather that it has a generated name.

**Comment by a-kenji** [comment]
This should be adressed by #554.
