### ISSUE TITLE
Long command/text overwrites the current line instead of going to a new line

### ISSUE THREAD

**Issue by kunalmohan** [zellij-org/zellij#481]
**In Case of Graphical or Performance Issues**
![zellij](https://user-images.githubusercontent.com/44079328/117717193-1f4bd000-b1f8-11eb-9e2b-a30e794da04f.gif)

1. Delete the contents of `/tmp/zellij-1000/zellij-log`, ie with `cd /tmp/zellij-1000/` and `rm -fr zellij-log/`
2. Run `zellij --debug`
3. Recreate your issue.
3. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.
[zellij-19.log](https://github.com/zellij-org/zellij/files/6454697/zellij-19.log)
[zellij-18.log](https://github.com/zellij-org/zellij/files/6454698/zellij-18.log)
[zellij-14.log](https://github.com/zellij-org/zellij/files/6454699/zellij-14.log)
[zellij-13.log](https://github.com/zellij-org/zellij/files/6454700/zellij-13.log)
[zellij-12.log](https://github.com/zellij-org/zellij/files/6454701/zellij-12.log)

**Basic information**

`zellij --version`: zellij 0.9.0 (latest main)
`tput lines`: 45
`tput cols`: 192
`uname -av`: Linux kunal-X510UNR 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

List of programs you interact with as, `PROGRAM --version`:
`alacritty --version`: alacritty 0.9.0-dev (8f4b752)

**Further information**
Long command/text overwrites the current line instead of going to a new line. Also it appears that text is wrapped to a new line quite early, even when there is space for more characters.
This is on alacrity with bash.
Same issue was encountered earlier https://github.com/zellij-org/zellij/issues/105, but was fixed back then.

cc @imsnif

**Comment by kunalmohan** [comment]
If I resize the pane to the right, the overwrite issue is fixed but the characters are still not written until the end. If I resize to left, both the issues exist.
A point to note is that both the issues exist only for the first line. For the second line(or the first line when the characters are being overwritten), characters are written till the end and 3rd line starts normally (there is no overwrite on second line)

**Comment by imsnif** [comment]
@kunalmohan - my issue is that this issue happens to me with the log file you provided (zellij-19.log) even when I `cat` it outside of Zellij. :) A little weird.
If you try to reproduce this issue, but type `reset` inside the terminal pane before reproducing it - does it still happen?

**Comment by kunalmohan** [comment]
Looks like it's not a zellij issue. I, too, can reproduce it outside zellij. It happens with me outside zellij in both alacritty as well as the gnome-terminal.
Sorry for the confusion. I didn't try to reproduce it outside zellij earlier.

**Comment by imsnif** [comment]
No worries :) Thanks for being vigilant
