### ISSUE TITLE
Zellij doesn't support bracketed paste mode

### ISSUE THREAD

**Issue by lilyball** [zellij-org/zellij#491]
When I paste into Zellij, it behaves as though I typed it instead, meaning it interprets key bindings. This is especially problematic when I'm in a separate mode as regular characters (such as "x") often do destructive actions, versus normal mode where I (by default at least) need control or alt characters. But even in normal mode, I can certainly have control/alt characters in my pasteboard.

Zellij really needs to enable bracketed paste mode and handle that. During a paste it should disable all key bindings and just pass the pasted text on to the active process (regardless of mode). Beyond that, it also presumably needs to handle requests from the process in each pane for bracketed paste mode (so it knows whether to pass the paste start/stop control sequences to the process or to strip them), though that can be implemented separately if needed.

**Basic information**

`zellij --version`: zellij 0.9.0
`tput lines`: 24
`tput cols`: 80
`uname -av` or `ver`(Windows): Darwin King-Triton-3 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

I'm using macOS Terminal.app as my terminal. The program running in Zellij doesn't matter.

**Further information**

A simple way to test this with default keybindings is to copy the word "excellent", put Zellij into Tab mode, and paste. Zellij should promptly close the current tab.

**Comment by imsnif** [comment]
Hey, good find! I made the adjustment to Zellij itself as you suggested and merged it to main. I'm leaving this issue open for the other part (handling requests from terminal panes themselves). I'll put a "Help Wanted" on it if you or anyone else wants to pick this up. Otherwise I'll likely get to it sometime in the near future.

**Comment by imsnif** [comment]
All of this has been implemented
