### ISSUE TITLE
Support nightly features?

### ISSUE THREAD

**Issue by fsevenm** [zellij-org/zellij#543]
Hi, I managed to install v0.11.0. Then, just recently new version was here v0.12.x, then I tried to update the crate. 
I run `cargo install zellij` like what I did when installing it. I got this:
```console
❯ cargo install zellij
    Updating crates.io index
error: failed to download `zellij v0.12.1`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/fsevenm/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-0.12.1/Cargo.toml`

Caused by:
  feature `resolver` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["resolver"]` to enable this feature

```
I want to temporarily fix the issue, but don't know where to add `cargo-features = ["resolver"]`. Any suggestions? and will it, the nightly features be supported.

Rust check:
```console
❯ rustup check
stable-x86_64-unknown-linux-gnu - Update available : 1.49.0 (e1884a8e3 2020-12-29) -> 1.52.1 (9bc8c42bb 2021-05-09)
beta-x86_64-unknown-linux-gnu - Up to date : 1.53.0-beta.3 (82b862164 2021-05-22)
nightly-x86_64-unknown-linux-gnu - Update available : 1.51.0-nightly (c97f11af7 2021-01-10) -> 1.54.0-nightly (1c6868aa2 2021-05-27)
```

**Comment by imsnif** [comment]
Hmm, this is a bit odd. Could be a rust version? Can you maybe try `rustup update`?

**Comment by fsevenm** [comment]
Ahh yeah, updating rust fixes the issue. I added pre-update rust version to the desc.

**Comment by armak** [comment]
I have this issue as well. Running `rustup update` doesn't help.
