### ISSUE TITLE
Zellij Needs a Proper Logging System

### ISSUE THREAD

**Issue by TheLostLambda** [zellij-org/zellij#561]
Zellij needs a central logging bus that captures the `stderr` from plugins, the client, and the server. Information coming over these channels should be tagged with it's location of origin (e.g. thread / plugin name) and timestamped.

Ideally, using `dbg!()` or something extraordinary similar with "just work", with the values being `dbg!()`ed appearing in the logs. 

This is a mentored issue, so if you'd like to take this on, you can count on some extra help and guidance from some of our maintainers.

**Comment by qepasa** [comment]
Looks like a cool issue. I'd like to give this one a go.

**Comment by TheLostLambda** [comment]
Awesome! Do you have any particular approach in mind or do you need any help understanding the codebase? If you need anything, just let us know!

**Comment by qepasa** [comment]
Some ideas for followup:
- change logging level to more verbose when zellij is started with --debug parameter
- custom log writer that would write to file with colors

**Comment by imsnif** [comment]
This has already implemented. Thanks @qepasa! if you want to make the followups into new issues that can be great.
