### ISSUE TITLE
Opening a new pane with the current pane directory

### ISSUE THREAD

**Issue by alexherbo2** [zellij-org/zellij#563]
Zellij doesn’t use the current pane directory when opening a new pane.

**Comment by a-kenji** [comment]
Thank you for taking the time in creating this issue!
This would be an awesome feature!

This is related to : #102.
And if someone wants to take a closer look at the pr: #277.

**Comment by fsevenm** [comment]
People start to take this up since it's the default behaviour we have in almost all terminals. So I think that feature might need a high priority right now.

**Comment by imsnif** [comment]
> People start to take this up since it's the default behaviour we have in almost all terminals. So I think that feature might need a high priority right now.

Zellij is an open source project run by unpaid enthusiasts. Everyone works on what they are passionate about and feel is most important.

**Comment by fsevenm** [comment]
Yeah, it should be the highest one.

**Comment by imsnif** [comment]
This has been implemented

**Comment by kkrime** [comment]
This doesn't seem to be working on OSX @imsnif can this issue be reoped?

**Comment by CretaceousConstructor** [comment]
> This doesn't seem to be working on OSX [@imsnif](https://github.com/imsnif) can this issue be reoped?

Did you find a way to tackle this? I'm using zellij windows version with windows terminal as my default terminal, and it's not working. I asked AI with source code, and it says some modifactions needed.

**Comment by kkrime** [comment]
> > This doesn't seem to be working on OSX [@imsnif](https://github.com/imsnif) can this issue be reoped?
> 
> Did you find a way to tackle this? I'm using zellij windows version with windows terminal as my default terminal, and it's not working. I asked AI with source code, and it says some modifactions needed.

Nope, still dosen't work for me

**Comment by kkrime** [comment]
@imsnif I'm happy to try and look into this myself and see if I can fix the issue, but would you mind pointing me in the right direction as to where in the code the changes would be needed to be made?

**Comment by CretaceousConstructor** [comment]
> [@imsnif](https://github.com/imsnif) I'm happy to try and look into this myself and see if I can fix the issue, but would you mind pointing me in the right direction as to where in the code the changes would be needed to be made?

Hi, kkrime. I found the solution here: https://github.com/zellij-org/zellij/issues/5052#issuecomment-4373009050. 
AI tells me do this:
```
function prompt {
    $p = $executionContext.SessionState.Path.CurrentLocation
    if ($p.Provider.Name -eq "FileSystem") {
        [System.Environment]::CurrentDirectory = $p.ProviderPath
    }

    "PS $p> "
}
```

**Comment by kkrime** [comment]
@CretaceousConstructor appreciated, but I think the solution is Microsoft specific, I'm on OSX, but thanks all the same though
