### ISSUE TITLE
[Request] Display session name in Zellij

### ISSUE THREAD

**Issue by techhazard** [zellij-org/zellij#573]
I usually have at least two sessions open for Zellij; 1 for work (Work), and 1 for personal things (Personal). Sometimes I open other sessions for specific projects.

I'd like to be able to view the name of the session somewhere in Zellij, instead of having to do `env | grep -i zellij`.
Perhaps in the top-left, which currently reads "Zellij", or the top right.
Or perhaps somewhere in the bottom bar, just like in Tmux.

I know I can have a different theme for each session, and I'm looking into that, but I like to be able to read the name as well.

Would this be possible?

**Comment by imsnif** [comment]
Definitely possible! I'd go for top left, something like `Zellij (session-name)`

Shouldn't be too hard to implement, if you or anyone else wants to give it a go?

**Comment by imsnif** [comment]
Awesome. Feel free to reach out here or on our discord if you want help/guidance.

**Comment by techhazard** [comment]
I tried to get the session name in `default-plugins/tab-bar` by using `std::env::var`. Because in `zellij-client/src/lib.rs` I saw `std::env::set_var` being used.
- https://github.com/zellij-org/zellij/blob/7f67e6d97f158a00d1f2c21326fe320388ec8446/zellij-client/src/lib.rs#L122
- https://github.com/zellij-org/zellij/blob/7f67e6d97f158a00d1f2c21326fe320388ec8446/zellij-client/src/lib.rs#L128

But that does not work, because it is not being set. is it because plugins are WASM and are run as separate binaries (and therefor with a different environment?)

**Comment by imsnif** [comment]
Yeah, I think we don't share the environment variables with the plugins. We use exported WASM functions to communicate with them, and IMO that's the best way to go with this.

Atm we don't send the plugins any info on startup and rather have them subscribe to events that we send them every time there's been a change (correct me if I'm wrong @TheLostLambda ?). A good example can be seen with the tabs that subscribe to events here: https://github.com/zellij-org/zellij/blob/main/default-plugins/tab-bar/src/main.rs#L30

And these events are defined here: https://github.com/zellij-org/zellij/blob/c65987a285b32658de935d92b61d2186f4548982/zellij-tile/src/data.rs#L31-L36

So I think if you add an event (something like `SessionNameUpdate` maybe?) and mimic the behaviour of the 'TabUpdate` event, it should do the trick. Makes sense?

**Comment by TheLostLambda** [comment]
Heya! Figured I'd jump in here! There is actually an easier way to go about this, I think! The `ModeUpdate` event is guaranteed to be sent to every plugin at load time at least once, so I think the best way to go about this would be to add a `String` containing the session name to `ModeInfo`. Then it will be passed to the plugin on load!

Normally @imsnif is right about how we communicate with plugins, but the `ModeInfo` has the special status of an "initialization event" as well as its usual role. Adding a field to `ModeInfo` also avoids creating anything like `SessionNameUpdate` which is a touch misleading since I don't think the session name changes during runtime? I could be wrong about that though.

**Comment by imsnif** [comment]
> Normally @imsnif is right about how we communicate with plugins, but the `ModeInfo` has the special status of an "initialization event" as well as its usual role. Adding a field to `ModeInfo` also avoids creating anything like `SessionNameUpdate` which is a touch misleading since I don't think the session name changes during runtime? I could be wrong about that though.

I think it might be nice to allow changing the session name at runtime at some point - but for now it indeed doesn't change. Thanks for the suggestion! Could you point out a good place for @techhazard to get started on this?

**Comment by TheLostLambda** [comment]
`ModeUpdate` can also accommodate for changes at runtime so we should be able to eventually handle that change :)

As for where to start, I'd point @techhazard to:
https://github.com/zellij-org/zellij/blob/7f67e6d97f158a00d1f2c21326fe320388ec8446/zellij-tile/src/data.rs#L145-L151

Personally, I'd add a field like `session_name: String`, then follow the compiler errors to find all of the places `ModeInfo` is constructed or consumed! 

Putting things in the top-left would then mean using the `ModeInfo` saved in the `tab-bar` on this line: https://github.com/zellij-org/zellij/blob/7f67e6d97f158a00d1f2c21326fe320388ec8446/default-plugins/tab-bar/src/main.rs#L35

Eventually (I think) you'll want to pass the session name into this function: https://github.com/zellij-org/zellij/blob/7f67e6d97f158a00d1f2c21326fe320388ec8446/default-plugins/tab-bar/src/line.rs#L167

You should be able to render it from within there? Good luck and let me know if you run into any issues!
