### ISSUE TITLE
No mouse support in neovim

### ISSUE THREAD

**Issue by PhML** [zellij-org/zellij#579]
**Basic information**

`zellij --version`: 0.13.0
`tput lines`: 68
`tput cols`: 256
`uname -av` or `ver`(Windows): Linux PO19258LX 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

List of programs you interact with:
`nvim --version`: neovim-0.5.0+ubuntu2+git202106170012-c78816eb6-d569569c9
`alacritty --version`: alacritty 0.8.0

**Further information**

When I edit a file with neovim in Zellij the mouse is not captured by neovim (visual selection etc). 

I don’t know if it should be reported in #448

**Comment by imsnif** [comment]
@PhML - thanks for reporting this... could you provide some more info about how to reproduce this? Is this a specific plugin or version, or? Because when I try to reproduce this with my local neovim and try to mark things with the mouse outside Zellij, it marks them normally through the terminal emulator... am I missing something or doing something differently?

**Comment by a-kenji** [comment]
I have similar issues (I think), but I assume that will be resolved once the mouse support is finished. The terminal emulator gets the mouse selection, but neovim itself doesn't seem to get all the events.

**Comment by dantepippi** [comment]
I use neovim daily and don't have any issues with clicks or text selection. Only issue I have is with mouse scrolling on hover pop-ups.

**Comment by dantepippi** [comment]
> @PhML - thanks for reporting this... could you provide some more info about how to reproduce this? Is this a specific plugin or version, or? Because when I try to reproduce this with my local neovim and try to mark things with the mouse outside Zellij, it marks them normally through the terminal emulator... am I missing something or doing something differently?

I can select text on Neovim but can't click to go to a certain position or scroll  when there's some floating window with long text.
