### ISSUE TITLE
Allow plugins to react to mouse events

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#607]
Allow plugins to react to mouse events.

For example in order to switch tabs, in the `tab-bar`.

**Comment by qepasa** [comment]
Hey, I'd love to give this one a try after we merge the PR with logging #592 :smiley:

**Comment by a-kenji** [comment]
Awesome @qepasa, please feel free to reach out if you need some input!

**Comment by a-kenji** [comment]
This has been implemented, thanks @qepasa, this is awesome!
