### ISSUE TITLE
Kakoune editor shows incorrect colors

### ISSUE THREAD

**Issue by chrisboyce** [zellij-org/zellij#613]
When using [kakoune](https://kakoune.org/) from within a `zellij` instance, the terminal does not show the expected colors. Attached towards the bottom are screenshots of kakoune without zellij (the tan color) and within zellij (the dark blue).

Debug Logs
[zellij-15.log](https://github.com/zellij-org/zellij/files/6792050/zellij-15.log)
[zellij-10.log](https://github.com/zellij-org/zellij/files/6792051/zellij-10.log)
[zellij-9.log](https://github.com/zellij-org/zellij/files/6792052/zellij-9.log)

**Basic information**

`zellij --version`: 0.15.0
`tput lines`: 34
`tput cols`: 119
`uname -av` or `ver`(Windows): `Linux blamblam 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`kak -version`: `Kakoune v2020.09.01-578-gcac946b4`
`alacritty --version`: `0.8.0`

**Further information**
Screenshot of kakoune from an alacritty terminal without zellij
![image](https://user-images.githubusercontent.com/1100198/125093677-64b93c00-e087-11eb-8955-d2cc98226787.png)

Screenshot of kakoune from an alacritty terminal with zellij
![image](https://user-images.githubusercontent.com/1100198/125093749-78fd3900-e087-11eb-8483-bbce5ffbbfd5.png)

From the kakoune Discord chat:
>  Kakoune by default uses a palette-switching method to get true colors (outside 256 terminal ones), which might not be working well with zellij. There is an alternative branch builtin-terminal-ui that uses 24-bit color sequences directly, assuming that the terminal supports it. Last I saw it mentioned (https://github.com/zellij-org/zellij/issues/385) it is supposed to be working well with zellij, so you can give it a try.

If I build kakoune from the `builtin-terminal-ui` branch as suggested, `zellij` does show the expected colors.

**Comment by chrisboyce** [comment]
Looking through the commit history, I think that #453 fixed the issue for some people. However if I check out 1f88b342e2a381b958da4bebd852b73e42db1a8c I'm still seeing the issue, so I don't think this is a regression.

**Comment by imsnif** [comment]
Hey @chrisboyce - this is now fixed in main. Thanks for the report! I hope to release a next version with this sometime next week. Will close this now - if this still happens to you in the next release, please ping me and I'll re-open.
