### ISSUE TITLE
interrupting a process spawned by `nushell` closes the pane

### ISSUE THREAD

**Issue by midnightexigent** [zellij-org/zellij#615]
**Basic information**

`zellij --version`: zellij 0.14.0
`tput lines`: 47
`tput cols`: 170
`uname -av`: Linux desktop-776A 5.12.14-artix1-1 SMP PREEMPT Thu, 01 Jul 2021 20:51:04 +0000 x86_64 GNU/Linux

**Programs to interact with**

`nu --version`: 0.34.0 (with default features)

**Steps to reproduce**

- from any `tty` run, `env SHELL=nu zellij setup --clean`
-  in the shell, run any interruptible command (example: `sleep 10sec`)
- `ctrl-c` to interrupt the process
- the pane will be closed

**Comment by a-kenji** [comment]
Hello @midnightexigent thank you for taking the time
filing this report!

I can reproduce the problem.

**Comment by midnightexigent** [comment]
Hello, thanks for looking into this ! 

So this is an actual bug, right ?

**Comment by a-kenji** [comment]
Yes, this is definitely an actual bug.
I just wanted to underline that it can be reproduced, so it
is likely not happening solely on your end.
