### ISSUE TITLE
cursor disappears after leaving some TUI session within `ranger`

### ISSUE THREAD

**Issue by LovecraftianHorror** [zellij-org/zellij#617]
Thank you for taking the time to file this issue! Please follow the instructions and fill the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

**In Case of Graphical or Performance Issues**

1. Delete the contents of `/tmp/zellij-1000/zellij-log`, ie with `cd /tmp/zellij-1000/` and `rm -fr zellij-log/`
2. Run `zellij --debug`
3. Recreate your issue.
3. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.

All the log files:

[log.txt](https://github.com/zellij-org/zellij/files/6826928/log.txt)
[zellij-7.log](https://github.com/zellij-org/zellij/files/6826929/zellij-7.log)
[zellij-8.log](https://github.com/zellij-org/zellij/files/6826930/zellij-8.log)
[zellij-9.log](https://github.com/zellij-org/zellij/files/6826931/zellij-9.log)

**Basic information**

`zellij --version`: `zellij 0.14.0` (also able to reproduce on current `main` 3df0210647e65170576f1ea97328cce26c211a43)
`tput lines`: `27`
`tput cols`: `113`
`uname -av` or `ver`(Windows): `Linux ai 5.12.15-arch1-1 #1 SMP PREEMPT Wed, 07 Jul 2021 23:35:29 +0000 x86_64 GNU/Linux`

List of programs you interact with as, `PROGRAM --version`:
- `alacritty --version`: `alacritty 0.8.0-dev (3ed0430)`
- `ranger --version`: `ranger 1.9.3`

**Further information**
Reproduction steps, noticable behavior, related issues etc

I can reproduce this consistently, so let me know if you want any more info. To reproduce I open `ranger` within `zellij` then launch some TUI program from ranger (issue reproducible with `ranger`, `bottom`, `vim`, and `nvim` and probably more).

Also this seems to be localized to the pane it's done in since doing the steps above in one pane while two are open will cause the cursor to not appear in the effected pane, but switching back to the other pane causes the cursor to appear fine there.

Gif showing the bug:

![zellij-cursor-bug](https://user-images.githubusercontent.com/30302768/125874571-f13e33a6-cecb-470c-b7b7-0e7a72363640.gif)

**Comment by a-kenji** [comment]
Maybe this could be related:

https://github.com/neovim/neovim/issues/14652

**Comment by LovecraftianHorror** [comment]
I know that I'm very likely missing out on its use, but applying the following patch to never have the cursor be hidden fixes the issue with no ill effect in the above demo

```patch
diff --git zellij-server/src/panes/grid.rs zellij-server/src/panes/grid.rs
index df9b7a9..7529df2 100644
--- zellij-server/src/panes/grid.rs
+++ zellij-server/src/panes/grid.rs
@@ -1015,7 +1015,7 @@ impl Grid {
         }
     }
     pub fn hide_cursor(&mut self) {
-        self.cursor.is_hidden = true;
+        self.cursor.is_hidden = false;
     }
     pub fn show_cursor(&mut self) {
         self.cursor.is_hidden = false;
```

I don't really have any knowledge on what `csi_dispatch` does, so I'm not sure how to properly fix the issue

**Comment by a-kenji** [comment]
@LovecraftianHorror 
Could you please confirm, if that is still happening?

**Comment by LovecraftianHorror** [comment]
Just checked on the current main (29d1ccfdfe06fdf9f355b8c934c37b54cd579aeb) and the reproduction in the video has the same effect for me still

**Comment by a-kenji** [comment]
Thank you for checking again!
