### ISSUE TITLE
Messed up layout after opening tabs in close succession

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#621]
After opening many tabs in succession the layout seems somewhat messed up, for certain tabs.

`zellij --version`: 15
`tput lines`: 120
`tput cols`: 31
`uname -av`: Linux ezra 5.10.48 144 SMP Wed Jul 7 12:27:50 UTC 2021 x86_64 GNU/Linux

**Further information**
`alacritty --version`: 0.8.0

**Reproduce**:
- Open tabs in succession
```
        - action: [NewTab , NewTab , NewTab , NewTab , NewTab , NewTab , NewTab , NewTab , NewTab , NewTab , NewTab , NewTab , NewTab , NewTab , NewTab , NewTab , NewTab , NewTab , NewTab , NewTab , NewTab , NewTab , NewTab , NewTab , NewTab , NewTab , ]
          key: [F: 5,]

```
- Select a tab with the artifacts (see screenshot)
- Close pane in the tab

Screenshots:
![image](https://user-images.githubusercontent.com/65275785/126380803-74fa7dc4-41e5-4f8d-85f2-fda814ce57bc.png)
![image](https://user-images.githubusercontent.com/65275785/126380932-ae55cc6a-5bae-4a09-aa58-5e5da61bfb18.png)

Logs:
[zellij-9.log](https://github.com/zellij-org/zellij/files/6850667/zellij-9.log)
[zellij-13.log](https://github.com/zellij-org/zellij/files/6850669/zellij-13.log)
[zellij-14.log](https://github.com/zellij-org/zellij/files/6850670/zellij-14.log)
[zellij-15.log](https://github.com/zellij-org/zellij/files/6850671/zellij-15.log)
[zellij-16.log](https://github.com/zellij-org/zellij/files/6850672/zellij-16.log)
[zellij-17.log](https://github.com/zellij-org/zellij/files/6850673/zellij-17.log)
[zellij-18.log](https://github.com/zellij-org/zellij/files/6850674/zellij-18.log)
[zellij-19.log](https://github.com/zellij-org/zellij/files/6850675/zellij-19.log)
[zellij-20.log](https://github.com/zellij-org/zellij/files/6850676/zellij-20.log)
[zellij-21.log](https://github.com/zellij-org/zellij/files/6850677/zellij-21.log)
[zellij-22.log](https://github.com/zellij-org/zellij/files/6850678/zellij-22.log)
[zellij-23.log](https://github.com/zellij-org/zellij/files/6850679/zellij-23.log)
[zellij-24.log](https://github.com/zellij-org/zellij/files/6850680/zellij-24.log)
[zellij-25.log](https://github.com/zellij-org/zellij/files/6850681/zellij-25.log)
[zellij-26.log](https://github.com/zellij-org/zellij/files/6850683/zellij-26.log)
[zellij-27.log](https://github.com/zellij-org/zellij/files/6850684/zellij-27.log)
[zellij-28.log](https://github.com/zellij-org/zellij/files/6850685/zellij-28.log)
[zellij-29.log](https://github.com/zellij-org/zellij/files/6850686/zellij-29.log)
[zellij-30.log](https://github.com/zellij-org/zellij/files/6850687/zellij-30.log)

cc @imsnif

**Comment by a-kenji** [comment]
On my machine it seems waiting 250 milliseconds before opening a new Tab
fixes this issue.

**Comment by a-kenji** [comment]
This only seems to happen on layouts that load plugins,
with solely normal panes I can't reproduce this issue.

cc @TheLostLambda, maybe you have more input here.

**Comment by imsnif** [comment]
> On my machine it seems waiting 250 milliseconds before opening a new Tab
> fixes this issue most of the times.

Just my quick 2 cents: my gut tells me this is an atomicity issue that we can solve with `CommandIsExecuting` - but maybe I'm wrong here. Haven't looked deeply into this.
