### ISSUE TITLE
Project governance: how should the arbiter be removed?

### ISSUE THREAD

**Issue by imsnif** [zellij-org/zellij#630]
When this project was started, the maintainers decided on a governance model outlined [here](https://github.com/zellij-org/zellij/blob/main/GOVERNANCE.md).

As part of that model, one member is designated as "Arbiter" - empowered to both break ties and have veto powers. This model was meant to provide us with fair and agreed upon mechanisms that would allow for expediency on the one hand and transparency on the other in a relatively young age of the project.

While to this day, the maintainers have always managed to reach consensus, we are aware that things and people might change in the future. A healthy organization needs ways to rid itself of an all powerful dictator, benevolent or otherwise, if the need arises. For this reason, we agreed that once the organization reaches 10 maintainers, we will decide upon a process to get rid of the arbiter. We have very recently reached this point, and so I'm starting this discussion.

My personal thoughts are that a maintainer vote with a two-thirds majority should be able to replace the arbiter with another candidate who agrees to it. I feel this would make it possible to get rid of an arbiter that clearly does not have the project's best interests in mind (eg. violates or protects violations of our [Code of Conduct](https://github.com/zellij-org/zellij/blob/main/CODE_OF_CONDUCT.md)) and on the other hand not make it very easy to use such a "no-confidence" vote as a decision-making tool (eg. if the arbiter broke a tie someone doesn't like, they can vote them out with a simple majority).

I would very much like to hear more opinions from current maintainers (in no particular order): @5c077m4n, @a-kenji, @dantepippi, @denismaxim0v, @henil, @khs26, @kunalmohan, @qballer, @TheLostLambda

**Comment by khs26** [comment]
Sounds sensible to me - the only thing I think worth clarifying is if we
round partial people up or down. :)

We should also presumably exclude the arbiter themselves from the list of
people included in the vote.

**Comment by dantepippi** [comment]
Coming from the current Arbiter this shows great consideration for the future of the project.

**Comment by a-kenji** [comment]
I agree with @khs26 points.

**Comment by imsnif** [comment]
According to the reactions it seems like most of us are in agreement with my suggestion and @khs26's corrections. I'm going to bring this to a vote in our next meeting, just FYI.

As for partial people: in my mind if we need two thirds of maintainers for something, and that number happens to include a partial person, then it's rounded up (since less than that number is not two thirds). But if this is accepted I'll definitely clarify that :)

**Comment by khs26** [comment]
Sounds good to me. If I don't make it to the meeting, consider my vote in
favour.

**Comment by imsnif** [comment]
Also, another addition: to change this rule, one would need this special majority as well. Otherwise it's kind of moot :)

**Comment by imsnif** [comment]
At yesterday's meeting, this rule (with some stipulations and future-proofing) has been accepted. I updated GOVERNANCE.md - thank you all!
