### ISSUE TITLE
how can remove plugins padding line?

### ISSUE THREAD

**Issue by cossonleo** [zellij-org/zellij#637]
How can remove plugins padding line
![图片](https://user-images.githubusercontent.com/20379044/128325866-616b5e6d-0d27-470b-a00c-d03ace1a33db.png)

**Comment by imsnif** [comment]
I am fixing this as we speak! I hope it will be ready very soon :)

**Comment by a-kenji** [comment]
@cossonleo 
Thank you for taking the time in creating this issue!
@imsnif actually fixed it in the most recent release.
