### ISSUE TITLE
Zellij slow mouse input processing in Wezterm

### ISSUE THREAD

**Issue by eaglgenes101** [zellij-org/zellij#639]
Thank you for taking the time to file this issue! Please follow the instructions and fill the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

**In Case of Graphical or Performance Issues**

1. Delete the contents of `/tmp/zellij-1000/zellij-log`, ie with `cd /tmp/zellij-1000/` and `rm -fr zellij-log/`
2. Run `zellij --debug`
3. Recreate your issue.
3. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.

The logfile that results from this operation is essentially empty, containing only the text of the original prompt. 

**Basic information**

`zellij --version`: 0.15.0
`tput lines`: 47
`tput cols`: 192
`uname -av` or `ver`(Windows): Linux eaglgenes101-Blade-Stealth 5.12.0-19.4-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.12-30ubuntu1~hirsute (2021-08-04) x86_64 x86_64 x86_64 GNU/Linux

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`nvim --version`: NVIM v0.5.0-dev+1299-g1c2e504d5  (used the appimage release)
`alacritty --version`: alacritty 0.7.2 (5ac8060b)
`wezterm --version`: wezterm 20210806-105352-4a4f2df2
`alacritty --version`: alacritty 0.9.0 (fed349aa)
`konsole --version`: konsole 21.04.3

**Further information**
Reproduction steps, noticable behavior, related issues etc

From a fresh (release) build of Zellij running in Wezterm, hold the mouse button with the mouse at one corner, and drag it swiftly to the opposite corner. Zellij lags behind the mouse movement by about 0.5 seconds. Doing further mouse drags back and forth causes Zellij to fall even further behind. If key inputs are entered immediately after dragging the mouse around, the mouse actions are handled, then only after they are fully handled, the keystrokes are handled. 

This only happens with Wezterm for me. Alacritty and Konsole with Zellij running on them both have no trouble keeping up with them. And Wezterm by itself, not running Zellij, has no trouble keeping up with my actions either. This only happens for me in Wezterm, running Zellij.

**Comment by imsnif** [comment]
Thanks for the detailed issue, @eaglgenes101 ! I'm going to delve more deeply into it the next time I do a batch of `compatibility` issues (likely in a couple of weeks), and will ping you if I need help reproducing it.
