### ISSUE TITLE
Feature: indicate to the user when text is copied to the clipboard

### ISSUE THREAD

**Issue by imsnif** [zellij-org/zellij#640]
Right now, whenever you mark text with the mouse, Zellij copies it to the system clipboard immediately. This behaviour is great, but it's not very clear to the user that this is happening.

We should:
1. Change the "tip" line in the status bar to "Text copied to clipboard." whenever this happens
2. Any input from the user after the above message appears should reset the message to the usual "tip" line.

**Comment by tlinford** [comment]
Have a wip version of this, will hopefully finish it up soon.
