### ISSUE TITLE
Feature: add command `kill-session` like tmux

### ISSUE THREAD

**Issue by jaeheonji** [zellij-org/zellij#644]
Hi, zellij 👋 

Maybe I missed it, but currently there doesn't seem to be a feature to close **individual** or **all** sessions via terminal commands.

Are there any plans to add that feature? If there is a plan, I would like to contribute.

**Comment by imsnif** [comment]
I'd be happy to accept such a contribution :) Feel free to reach out here or on discord if you want help/guidance.
