### ISSUE TITLE
Inconsistent Tab Bar Behaviour at small window sizes

### ISSUE THREAD

**Issue by TheLostLambda** [zellij-org/zellij#668]
These sorts of UI bugs seem best explained with a video, but the gist is that, as the terminal width is reduced, the tab bar exhibits unexpected (and arguably buggy) behavior.

https://user-images.githubusercontent.com/6251883/131230830-0828ce2f-bc40-47b9-ab31-0a7a20bd1f64.mp4

**Comment by imsnif** [comment]
Definitely an issue, but somewhat of an edge case (very small window). This has a lot to do with the responsiveness logic of the tab plugin. I'm putting a `help wanted` tag on this for now, and if no one picks it up we can get it fixed sometime in the near future.

**Comment by prscoelho** [comment]
Trying to tackle this. There's a bunch of weird edge cases, but what is the expected behavior if there's no space for left_more + active tab + right_more?

**Comment by imsnif** [comment]
> Trying to tackle this. There's a bunch of weird edge cases, but what is the expected behavior if there's no space for left_more + active tab + right_more?

Do the best we can :) What information would you like to see in this case? IMO the most important information is to leave the focused tab. wdyt?
