### ISSUE TITLE
Pane frames reset between switching tabs.

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#677]
When specifying `no_pane_frames: true` and then switching tabs 
the pane frames get in to a weird state:

Reproduce:
- open `zellij options --no-pane-frames`
- open a new tab
- open panes in the new tab
- switch between tabs and panes

![image](https://user-images.githubusercontent.com/65275785/131408074-41d0e181-d6ef-434b-8c1a-39e5af4d1951.png)

cc @imsnif

**Comment by TheLostLambda** [comment]
Heya! I'm about 60% sure I fixed this in #673? Let me know if that fixes it for you!

**Comment by a-kenji** [comment]
Hey @TheLostLambda, I am not sure. 
I thought I had a more recent version, but I can't check for
a little while now.
