### ISSUE TITLE
Close 1st tab, all other tabs got frozen

### ISSUE THREAD

**Issue by jheroy** [zellij-org/zellij#678]
**Basic information**

`zellij --version`: 0.15.0
`tput lines`:54
`tput cols`:254
`uname -av` or `ver`(Windows):Linux 211 3.13.0-170-generic #220-Ubuntu SMP Thu May 9 12:40:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by imsnif** [comment]
Hey @jheroy - I *think* I can reproduce this issue but I'm not 100% sure. Do you mean that when you close the tab, its contents "stick" to the screen? Like in this case, if you do this and then press "ENTER" a few times in the new tab, is it solved?

**Comment by raphCode** [comment]
should be fixed with that PR, can be closed.
