### ISSUE TITLE
Pane Frame fragment persists on switching tabs

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#682]
There is a single '|' divider still left after switching tabs, if using
`no_pane_frames: true`

`tput  lines`: 30
`tput rows`: 120

Steps:
* open zellij
* open a tab
* open a pane that divides vertically
* switch tabs

![image](https://user-images.githubusercontent.com/65275785/131522637-f489d06d-ddfe-4d49-be8e-b285f6bcd635.png)
![image](https://user-images.githubusercontent.com/65275785/131522664-1e4e8fe3-6a14-4055-9892-2563285a2006.png)
Logs:
[zellij-10.log](https://github.com/zellij-org/zellij/files/7084763/zellij-10.log)
[zellij-12.log](https://github.com/zellij-org/zellij/files/7084764/zellij-12.log)
[zellij-15.log](https://github.com/zellij-org/zellij/files/7084765/zellij-15.log)

**Comment by TheLostLambda** [comment]
This looks like a miscalculation of the viewport here. I'll keep looking into it!

**Comment by TheLostLambda** [comment]
This is (hopefully) fixed in master now! Let me know if it works for you @a-kenji !

**Comment by a-kenji** [comment]
@TheLostLambda 
This is indeed fixed now for me! Cheers.
