### ISSUE TITLE
Opening too many frames (spawm alt+N)

### ISSUE THREAD

**Issue by ETKNeil** [zellij-org/zellij#685]
Error: thread 'pty' panicked at 'called `Option::unwrap()` on a `None` value': zellij-server/src/pty.rs:288

**Comment by imsnif** [comment]
Pretty weird. I'm not reproducing this, but I have a suspicion why this is happening. Can you reproduce it every time?

**Comment by raphCode** [comment]
@ETKNeil, is this still a problem in recent zellij versions?

**Comment by ETKNeil** [comment]
It's not a bug anymore, It didn't happened again for the last 2 months, and I updated to 0.28.1 one week ago and it seem very stable in this release.

**Comment by raphCode** [comment]
Great to hear!
