### ISSUE TITLE
terminal window broken in v0.16 when switching tabs

### ISSUE THREAD

**Issue by fansari** [zellij-org/zellij#687]
In v0.16 I noticed when I switch to another tab the window is broken.

In the left corner I see "Panel #1" but the pane is completely empty. I don't see the bash anymore.

This is the second issue now in the new version: I will switch back to v0.13. This is the latest version usable for me.

**Comment by imsnif** [comment]
@fansari - since I can't reproduce this issue myself, can I ask a few questions to try and understand what's wrong?

1. Does this happen to you 100% of the time?
2. Does it happen when you switch to any tab?
3. If you press ENTER a few times when this happens, do you see the prompt?

**Comment by fansari** [comment]
I cannot reproduce this right now. But it never happened before so I thought this is some new issue.

I will try again with 0.16 and check whether this issue is repeating.

**Comment by raphCode** [comment]
@fansari Did it happen to you again, maybe even in recent versions?

**Comment by fansari** [comment]
This does not happen with the current version (0.28.1). I have not experienced this anymore.
