### ISSUE TITLE
Zellij attach should also accept options (eg. disable-mouse-mode)

### ISSUE THREAD

**Issue by imsnif** [zellij-org/zellij#688]
As pointed out in https://github.com/zellij-org/zellij/issues/671 - when detaching and reattaching a session that was started with `--disable-mouse-mode`, the flag is essentially lost and there's no way to bring it back. One should be able to `disable-mouse-mode` when attaching to an existing session (as well as other options that might be relevant).

**Comment by fansari** [comment]
In my opinion the default behaviour should be that the reattachment uses the same options as the command which has started the session.

**Comment by TheLostLambda** [comment]
In my personal opinion, I don't think `options` should be a subcommand either. I think all of Zellij's flags should be available at the top-level. Some subcommands obviously make sense, like the `setup` commands, but I think the runtime options should always be available, attaching or not.

@fansari 's suggestion is also a good one, but once the `attach --create` feature is merged, we will need to get rid of the `options` subcommand anyways to pass flags to any newly-created session.

If I'm being entirely honest, I think that `setup` is the only subcommand we need – listing and attaching to sessions could also just be flags. Let me know what you think!

**Comment by imsnif** [comment]
As far as I remember, this was done in order to distinguish options that can be configured through a file from other flags. But I'm honestly not sure. What you're saying makes sense, @TheLostLambda, but I wonder if there were other considerations here. @a-kenji - do you have any thoughts?

**Comment by a-kenji** [comment]
@imsnif , @TheLostLambda 
I am strongly in favor of keeping the `options` subcommand, for one it has the distinguishing feature @imsnif already mentioned.
But also I think it is a better ui, if I want to see what zellij can do I am not immediately overloaded when typing `zellij --help`, but at the same time I can type `zellij options --help` and I can immediately see just the configuration options, which I am interested in. 

If that is also possible with a flag, for example `--options` / `-o`, and that also taking the configuration options I would be OK with that as well. But I would be opposed to every single option being a flag itself. I think that hinders the discoverability of possible options.

**Comment by imsnif** [comment]
@a-kenji - how do you think the UI for this should be? Should `--options` be a flag of `attach`? I think that might make things a little confusing (in one place it's a sub-command, in another it's a flag?)
But on the other hand, if it's a flag it's not very discoverable (at least in --help) right? Do you have any thoughts or ideas?

**Comment by TheLostLambda** [comment]
I think `structopt` / `clap` allows for a short-help on `-h` and a longer one on `--help`. Programs like ripgrep seem to make use of that to keep the help tidy but have all of the options as flags. I'm fine with however this is resolved, though I have my reservations about putting any sort of general configuration behind subcommands (which, as I understand, are mutually exclusive).

**Comment by a-kenji** [comment]
If the subcommands are really mutually exclusive then we do need to resolve this with flags at the top level I believe.

I think this could work though:
```
zellij attach options
```
and have options as a subcommand for attach, since attach would be the only subcommand relying on such
functionality?
A short version could be:
```
zellij a o
```.

Also if that is true:
```
If I'm being entirely honest, I think that setup is the only subcommand we need – listing and attaching to sessions could also just be flags. Let me know what you think!
```
Then `options` could still be a subcommand, and work as they would right now.
It wouldn't be the end of the world if we decide to get rid of the `options` subcommand either,
though I do believe the compartmentalization is beneficial - especially when searching for a specific option.
