### ISSUE TITLE
Feature: Implement persistent sessions

### ISSUE THREAD

**Issue by imsnif** [zellij-org/zellij#69]
Mosaic should be able to run in the background regardless of whether a terminal window is open or not. New terminal windows should be able to 'attach' to existing sessions or create new ones.

**Comment by kunalmohan** [comment]
## Persistent Sessions
We propose a client-server architecture for this purpose. The client would be the "frontend" which interacts with the user and the server is the "backend" where all the magic happens.

**Client-** Client would have the Screen thread (for rendering) and an input thread (for taking user inputs).

**Server-** Server would have the PtyBus thread (one per session, if needed) and a main listener thread that listens for new and existing client messages. This is a daemon that would run as long as there is at least one client present.

### Establishing a communication channel
On startup, the presence of `--daemon` argument will determine whether this is a daemon or a client session and will call the appropriate methods accordingly. By default, a client would be run and check whether a server is running by trying to connect to a configured socket file ("/tmp/mosaic/ipc" by default). There are two possibilities now-
* A server is already running- The connection is successful; Nothing else to do.
* Server is not running- The connection is refused so the client spawns a new mosaic process using `std::process::Command` along with the `--daemon` argument.

Once the connection is established, the client creates new `(IpcSender<T>, IpcReceiver<T>)` and sends over the sender to server in a "Hello" message. The server assigns a uniqueId to the client and stores its sender. The server will respond to the client with the sender to PtyBus thread. All communications, except the Client to main server thread, will happen with [`IpcChannel`s](https://docs.rs/ipc-channel/0.14.1/ipc_channel/index.html).

### Startup
**Server-** On startup, the server will call the [`daemon()`](https://docs.rs/nix/0.19.1/nix/unistd/fn.daemon.html) method to detach itself from the controlling terminal and run as a daemon. If we have a single PtyBus thread, the server will spawn it at startup and will listen to incoming messages using `UnixListener` on the main thread. If we have one PtyBus thread per client, then the PtyBus threads will be spawned on new connection requests.

**Client-** A client would first check for and accordingly spawn the Server process and establish a connection with it. If the user has requested to open an existing session, it will request the server for relevant information (The Screen, Tab, TerminalPane objects) and then would continue to spawn a Screen thread and listen for user input on the main thread.

### General functioning
This will remain more or less same as the current flow- Input thread sends the messages to the PtyBus or the Screen thread. PtyBus would spawn new terminals and send over the `RawFd` to the Screen for writing to the stdin of the tty(s). Async tasks under PtyBus thread would listen to stdout of the tty(s) and send over the message to Screen thread for rendering.

The server would exit when the last client closes and there as no sessions to be stored.

### Points yet to be considered/discussed
* The exact information that the server needs to store- Probably not the entire struct; we'll probably create new channels everytime the user re-attaches.
* How to send over the existing session information. The information would include details of screen, all tabs under the screen, all panes under each tab and the scrollbuffer of each pane. This may amount to a big number of bytes that may exceed the channel capacity. We may have to establish a protocol for handling this.
* When the a client is detached, there is no longer a Screen thread. But a process running in a TerminalPane may be writing to stdout which the tasks in PtyBus thread will be listening to and be willing to send to the screen. How do we deal with this?
    - Kill the tasks and don't listen to the stdout when detached. The stdout event would then be read and handled when the session re-attaches.
    - Spawn a psuedo-Screen thread on server side that handles these events. This thread would just handle the event (store the character in scrollbuffer) and would render nothing.
    - Store a `Vec<VteEvent>` on server-side; tasks would push the event to this vector. These will be processed when the session re-attaches.

**Comment by imsnif** [comment]
Hey, thanks for the very thorough and thought out description. My thoughts:

Just to make sure, the `--daemon` flag is internal, right? The user can use it if they want to explicitly start a daemon, but otherwise things "just work"? (eg. if the daemon is not running, when starting mosaic a daemon will be created and detached, and then a client will connect to it for the first session?)

Otherwise, as I understand it, the only thing we have to think about is caching and re-establishing the session. I think you have everything else well under control.

What do you think about keeping a `Screen` struct for each session on the server as a sort of "session storage" layer, updating both it and the one on the client whenever there is a need and then when a client re-attaches, the handshake will include a serialized version of this `Screen` from which it can create its own `Screen` struct? 

Something like `let my_screen = Screen::from(serialized_screen_I_got_on_IPC)`.

Also just a note: I would recommend abstracting all the methods that have to do with IPC, daemonization and other things that interact with the OS into our `os_input_output` file, so that it would be easier to port this functionality to other OSs (mostly windows) when the time comes.

**Comment by imsnif** [comment]
Released in 0.12.0

**Comment by dclong** [comment]
How can I use this feature? Is there any doc on this?

**Comment by dclong** [comment]
Thank you so much! That's an awesome feature!

**Comment by dclong** [comment]
I observe inconsistent behaviors of zellij session persistent on remote and local servers. 

1. After I logged into a remote Linux server (requires 2FA), I start zellij and then just close the terminal. The zellij session is not persisted as `zellij ls` shows no sessions after I log into the server again. Manually detach the zellij session on the remote Linux server makes it persistent. 

2. I start zellij in a local terminal (macOS) and then just close the terminal and the zellij session is persistent.

Is this as expected or is it a bug?

**Comment by colemickens** [comment]
Sounds like systemd/linger issues.

**Comment by v0d1ch** [comment]
It would be nice if sessions were preserved when you reboot the machine.

**Comment by caferen** [comment]
is there a way to run zellij in daemon mode and send a command to it or detach using the cli to imitate this behaviour?

**Comment by danielo515** [comment]
> I observe inconsistent behaviors of zellij session persistent on remote and local servers.
> 
> 1. After I logged into a remote Linux server (requires 2FA), I start zellij and then just close the terminal. The zellij session is not persisted as `zellij ls` shows no sessions after I log into the server again. Manually detach the zellij session on the remote Linux server makes it persistent.
> 2. I start zellij in a local terminal (macOS) and then just close the terminal and the zellij session is persistent.
> 
> Is this as expected or is it a bug?

I am also interested in the first case. I often get my remote session disconnected because random network issues, and having to maully to detach in order for zellij to persist the session is quite useless in that scenerio.

**Comment by iroedius** [comment]
I would appreciate it so much if there was a way to start it in the background, such as in a .service file on boot.

**Comment by msharran** [comment]
> is there a way to run zellij in daemon mode and send a command to it or detach using the cli to imitate this behaviour?

I am using a script to create sessions for every project using TMUX (inspired by @theprimeagen's tmux-sessionizer). So when I press `Ctrl-f` inside a session, it would list all my projects using `fzf` and I can pick one and this scripts creates new session for me.

When I tried to do the same thing using zellij, the sessions were being nested inside each sessions. I couldn't find a way to detach from a session using the CLI. Is there a way to detach a session from CLI before attaching/creating a session? 

References:
1. script that creates [tmux sessions](https://github.com/msharran/.dotfiles/blob/main/.local/bin/tmux-sessionizer)
2. New script that creates [zellij sessions](https://github.com/msharran/.dotfiles/blob/main/.local/bin/zellij-sessionizer.sh)



```

**Comment by bamonroe** [comment]
@msharran I found this issue for a totally unrelated reason to yours, but had the same question as you months ago. I made this wrapper around zellij:

```
#!/bin/bash

zellij $@

zfile="/tmp/zellij_last_session" 
sleep .1
while [ -f "$zfile" ] ; do
	last_session="$(/bin/cat $zfile)"
	rm "$zfile"
	new_session="$(zellij list-sessions -n -s | fzf)"
	if [[ "$new_session" == "" ]] ; then
		new_session="$last_session"
	fi
	zellij a "$new_session"
	sleep .1
done

```
I have these two keybindings in my `config.kdl` under the normal mode (note the absolute path needed to your layouts):
```
        bind "Alt d"       { Detach; }
        bind "Alt s" { 
					NewTab {
						layout "/home/bam/.config/zellij/layouts/switch_session.kdl"
					};
					SwitchToMode "Normal";
					Detach;
				}
```
And the following layout called `switch_session.kdl` in the layouts folder:
```
layout {
	pane command="bash" {
		args "-c" "echo $ZELLIJ_SESSION_NAME > /tmp/zellij_last_session"
		close_on_exit true
	}
}

```

It's a hack-y way around the issue that you mention, but it allows me to use `Alt d` to truly detach, and `Alt s` to switch to a different session picked with fzf.

I would personally prefer there to be some kind of mainlined code that allows a simple `SwitchSession` command, but that's not related to the issue here.

**Comment by markalanevans** [comment]
@imsnif  is the ctrl +o,  d documented anywhere? I searched the docs and it's not there.

**Comment by erikh** [comment]
my experience:

- zellij reattaches if I manually detach and reattach
- up until the point I disconnect from ssh and reconnect; then the session is gone and I need to restart everything
- if ssh loses connection, see above

it'd be really nice if this behaved more like tmux and screen; it's literally the only reason I want to switch back. starting a download, closing my laptop, and going to the bathroom means I get to restart the process after I get out the bathroom.

**Comment by erikh** [comment]
nevermind, I guess tmux is doing it too. I'm presuming lennart poettering is to blame for this
