### ISSUE TITLE
Zellij v0.16.0 throws Deserialization error with empty config

### ISSUE THREAD

**Issue by conveen** [zellij-org/zellij#714]
Thank you for taking the time to file this issue! Please follow the instructions and fill the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

**In Case of Graphical or Performance Issues**

1. Delete the contents of `/tmp/zellij-1000/zellij-log`, ie with `cd /tmp/zellij-1000/` and `rm -fr zellij-log/`
2. Run `zellij --debug`
3. Recreate your issue.
3. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.

**Basic information**

`zellij --version`:  `zellij 0.16.0`
`tput lines`: `46`
`tput cols`: `189`
`uname -av` or `ver`(Windows): `Linux <hostname> 5.11.0-7633-generic #35~1630100930~20.04~ae2753e-Ubuntu SMP <timestamp>  x86_64 x86_64 x86_64 GNU/Linux`

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`nvim --version`: NVIM v0.5.0-dev+1299-g1c2e504d5  (used the appimage release)
`alacritty --version`: alacritty 0.7.2 (5ac8060b)

**Further information**

To reproduce, run the following:

```bash
 ❯ cp ~/.config/zellij/config.yaml ~/.config/zellij/config.yaml.bak    # remove existing config if it exists
 ❯ touch ~/.config/zellij/config.yaml    # create empty config file
 ❯ zellij -s session-name                # create new sesion
Deserialization error: EOF while parsing a value
```

**Comment by a-kenji** [comment]
Thank you @conveen  for taking the time filing this issue!
Do you believe that we should ignore this error?
Since an empty file is invalid `yaml` we we don't hande that yet.
