### ISSUE TITLE
URLs are not clickable

### ISSUE THREAD

**Issue by thomaseizinger** [zellij-org/zellij#719]
**Basic information**

`zellij --version`: zellij 0.16.0
`tput lines`: 44
`tput cols`: 189
`uname -av` or `ver`(Windows): Linux thomas-thinkpad 5.10.61-1-MANJARO #1 SMP PREEMPT Thu Aug 26 20:36:54 UTC 2021 x86_64 GNU/Linux

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:

- `alacritty 0.9.0 (fed349aa)`

**Further information**
Reproduction steps, noticable behavior, related issues etc

Links within the terminal are not clickable.
For example, pushing a new branch to GitHub renders something like this:

```
❯ gp -u upstream
Enumerating objects: 84, done.
Counting objects: 100% (84/84), done.
Delta compression using up to 8 threads
Compressing objects: 100% (58/58), done.
Writing objects: 100% (63/63), 18.27 KiB | 935.00 KiB/s, done.
Total 63 (delta 44), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (44/44), completed with 15 local objects.
remote:
remote: Create a pull request for 'provide-cli' on GitHub by visiting:
remote:      https://github.com/comit-network/hermes/pull/new/provide-cli
remote:
To github.com:comit-network/hermes.git
 * [new branch]      provide-cli -> provide-cli
Branch 'provide-cli' set up to track remote branch 'provide-cli' from 'upstream'.
```

In plain alacritty, I can click the link `https://github.com/comit-network/hermes/pull/new/provide-cli`.
Within zellij, I cannot.

**Comment by a-kenji** [comment]
@thomaseizinger 
Thank you for taking the time in creating this issue!
We are trying to improve this situation, 
in the meantime it is possible to press the 
`SHIFT` key and then have the terminal interact with the mouse.

**Comment by thomaseizinger** [comment]
>  `SHIFT` key and then have the terminal interact with the mouse.

Thanks for mentioning that! That works for me :)

**Comment by a-kenji** [comment]
This should also be now fixed:
https://github.com/zellij-org/zellij/pull/822

In the next release.

**Comment by ginolegigot** [comment]
Could this issue https://github.com/zellij-org/zellij/issues/3436 be attached here ?
