### ISSUE TITLE
Copy `default.yaml` config from `assets` to `example` in the release process

### ISSUE THREAD

**Issue by qwerty01** [zellij-org/zellij#733]
The repository contains a default.yaml  in the example directory, however it seems to be out of date with the current defaults (it still has ctrl+r for resize and doesn't have a bind for switching to session mode).

For anyone looking for an up-to-date default config.yaml, `zellij setup --dump-config` with no configuration file works.

**Comment by a-kenji** [comment]
Thank you for filing this issue! 
Do you think we should remove, or rename the file?
It is in the example directory, so it shows some examples in how you could
configure zellij.

The actual default config file is here: https://github.com/zellij-org/zellij/blob/main/zellij-utils/assets/config/default.yaml .

Maybe we could even copy the default config file to the examples directory once a version is released?

**Comment by qwerty01** [comment]
If it's just an example, maybe renaming would be the best option, otherwise copying the default config when a version is released would probably be better.

I'd personally prefer copying the default file on a new release, since it's a great starting point for a new config.

**Comment by a-kenji** [comment]
I agree this could be a good solution,
I will change the title of the issue to make it more actionable.

- Add copying the `default.yaml` from the `assets/config` directory to the  `example/config` directory
  to the release process (Makefile)

**Comment by qwerty01** [comment]
Oh another small note if this is ever revisited and the decision is changed to renaming the file: the documentation for keybinds (https://zellij.dev/documentation/keybindings.html) points to that file for the default keybinds, so it would need to be changed
