### ISSUE TITLE
Update keybind tip when changed from defaults

### ISSUE THREAD

**Issue by qwerty01** [zellij-org/zellij#734]
When keybinds are changed from their default configurations, the UI's cheat sheet at the bottom no longer reflects the current configuration (for example, after changing resize to ctrl+r, the bottom tip text still shows ctrl+n).

It might not be easy to add since someone could significantly change keybind layouts from the default (such as trying to emulate a tmux configuration), but maybe it could work for small changes.

**Comment by a-kenji** [comment]
Thank you for taking the time writing this issue!
For anyone wanting to pick this up:

- There is a starting point as a pr:  #319
- There is an issue talking about it:  #246

**Comment by har7an** [comment]
This should be fixed with #1242. If you still miss some particular aspect about "dynamically" updating the keybindings, don't hesitate to reopen this issue!
