### ISSUE TITLE
Mouse selection is laggy and behaving strangely

### ISSUE THREAD

**Issue by cenwangumass** [zellij-org/zellij#749]
After entering a command, e.g. `ls`, using mouse to select the output text is laggy and unresponsive. This problem shows up in the 0.18 version but not 0.17. My operating system is Fedora 34.

**Comment by imsnif** [comment]
Hi, good find! I can confirm and am reproducing this. I'm going to take a look at it tomorrow and issue a hotfix. Will update this issue.

**Comment by imsnif** [comment]
Fixed in `0.18.1`
