### ISSUE TITLE
standard cargo install fails

### ISSUE THREAD

**Issue by aplatypus** [zellij-org/zellij#755]
Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.

* No log available.  We never go to that stage.

**Basic information**

`zellij --version`: v0.18.1
`tput lines`: n/a
`tput cols`:  n/a
`uname -av`:  Linux woodypear 5.11.0-36-generic #40-Ubuntu SMP Fri Sep 17 18:15:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linu

**Further information**
Reproduction steps, noticable behavior, related issues etc

I just wanted to install the release version, used command from Github README page:
```
cargo install zellij
```

The output surprised me wih.  Essentially it "reads" to me that I need to on the bleeding-edge.  I have installed a few apps with `cargo` and none invited me to visit the _dark side_. 

```
 $ cd zellij/projects/zellij
william zellij $ cargo install zellij
    Updating crates.io index
  Downloaded zellij v0.18.1
error: failed to parse manifest at `/home/william/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-0.18.1/Cargo.toml`

Caused by:
  feature `resolver` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["resolver"]` to enable this feature
```

I think you ought to caution people that the `cargo install zellij` is not a "release" version.  At the very least.

**Comment by aplatypus** [comment]
Oppz ... As you were.  My version of cargo was out of date:
``` 
rustup update
```

* Now the install command works.
* Beg your pardon for the mix-up.

**Comment by a-kenji** [comment]
Thank you for taking the time in creating this issue!

Did you try updating through rustup?
How did you install cargo?

> The output surprised me wih. Essentially it "reads" to me that I need to on the bleeding-edge.

I don't think it does.

> I think you ought to caution people that the cargo install zellij is not a "release" version. At the very least.

Zellij is a beta, that is what the zero versioning means.
 But I think you possibly mean that we are not on the stable channel, but we are afaik, this is our channel file:

https://github.com/zellij-org/zellij/blob/main/rust-toolchain

**Comment by a-kenji** [comment]
@aplatypus 
No problem, that happens! Thanks for reaching out.
