### ISSUE TITLE
"Deserialization error: EOF while parsing a value" when generating initial config file

### ISSUE THREAD

**Issue by dunmatt** [zellij-org/zellij#756]
Thank you for taking the time to file this issue! Please follow the instructions and fill the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

**Further information**
Just installed Zellij via Cargo and tried to create the config file, but it barfed:

```
➜ mkdir ~/.config/zellij
~
➜ zellij setup --dump-config > ~/.config/zellij/config.yaml
Deserialization error: EOF while parsing a value
~
❯ bat .config/zellij/config.yaml
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .config/zellij/config.yaml   <EMPTY>
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
~
➜ zellij setup --dump-config
Deserialization error: EOF while parsing a value
~
❯ zellij --version
zellij 0.18.1
~
➜
```

**Comment by a-kenji** [comment]
Hey! Thanks for reaching out.

Do you mind telling us what programs you interacted with?

If you didn't try it yet, would you be so kind trying to run the second command with either
bash, zsh, or the fish shell?

**Comment by dunmatt** [comment]
All of the commands above were run in zsh 5.8 in alacritty 0.10.0-dev .  I think the problem is that the shell is creating the yaml file first, then launching zellij.  Zellij then sees the (empty) file and tries (and fails) to parse it.  I worked around the issue by:

```
~
➜ zellij setup --dump-config > config.yaml
~
➜ mv config.yaml .config/zellij
```
but a better fix would be to not attempt to read/parse size 0 config files.

**Comment by a-kenji** [comment]
Thank you, yes that seems to be happening! 

I was unsure if we should allow empty config files and planned initially
to improve the error that was displayed, since empty files are not valid yaml files.
This issue changed my mind!

Thank you! And please don't hesitate reaching out in the future.

**Comment by a-kenji** [comment]
This should be fixed in the next release!

**Comment by dunmatt** [comment]
Thanks for your speedy work!
