### ISSUE TITLE
Deserialization error when trying to dump config

### ISSUE THREAD

**Issue by ngirard** [zellij-org/zellij#758]
Using the latest precompiled binary on Ubuntu 21.04.

`zellij setup --dump-config` fails with the following error message:

> Deserialization error: EOF while parsing a value

**Comment by a-kenji** [comment]
Hello! Thank you for reaching out. What happens if you use a valid config file?

**Comment by ngirard** [comment]
When using a valid config file it works flawlessly.

Cheers

**Comment by a-kenji** [comment]
Awesome, thanks for checking! 
Dumping to stdout directly is fixed on main and should be included in the next release.
Please don't hesitate reaching out in the future!

**Comment by ngirard** [comment]
Nice, thank you very much !
