### ISSUE TITLE
Bug: Deserialization Error: EOF when parsing a value

### ISSUE THREAD

**Issue by Theory-of-Everything** [zellij-org/zellij#760]
## Basic information
**zellij --version**: zellij 0.18.1
**tput lines**: 65
**tput cols**: 235
**uname -av** or **ver**(Windows): 5.14.8-arch (Archlinux)

## Issue:
I have issues starting up Zellij after installation.
Error `Deserialization error: EOF while parsing a value` occurs when starting up Zellij with an empty config file or when attempting to dump the default configuration. 
Zellij will run normally **ONLY** when a config file doesn't exist in `~/.config/zellij`, and this same error will occur (regardless of whether there is a config file or not) when dumping the default configuration.
Because of this zellij will not open up in a terminal, but will just spit out this error.

#### **Relevant log file:**
```
INFO   |zellij_client            | 2021-10-02 22:17:38.382 [main      ] [/home/theorytoe/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-client-0.18.1/src/lib.rs:107]: Starting Zellij client! 
INFO   |zellij_server            | 2021-10-02 22:17:38.386 [main      ] [/home/theorytoe/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.18.1/src/lib.rs:174]: Starting Zellij server! 
INFO   |zellij_server::wasm_vm   | 2021-10-02 22:17:38.437 [wasm      ] [/home/theorytoe/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.18.1/src/wasm_vm.rs:73]: Wasm main thread starts 
INFO   |zellij_client            | 2021-10-02 22:17:47.529 [main      ] [/home/theorytoe/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-client-0.18.1/src/lib.rs:370]: Bye from Zellij! 
```

## Further information
- Install zellij and build from source via cargo `cargo install zellij`
- Create empty config file in `~/.config/zellij/config.yaml`
- Attempt to run.
OR
- Install zellij and build from source via cargo `cargo install zellij`
- Dump default configuration `zellij setup --dump-config > ~/.config/zellij/config.yaml`

I have tried to provide as much information as I can that is relevant to this issue, so if there is anything else needed please let me know.

**Comment by a-kenji** [comment]
This is fixed in the current main. In the meantime you can dump it to a different location and copy it to the correct one.
