### ISSUE TITLE
Replace yaml with KDL

### ISSUE THREAD

**Issue by imsnif** [zellij-org/zellij#771]
[KDL](https://kdl.dev/) is a new document language that supports nesting, custom type annotations and more. It is Human-readable, easy to pick up and is actively maintained through a [living specification](https://github.com/kdl-org/kdl/blob/main/SPEC.md).

A Zellij layout KDL configuration might look something like this:

```KDL
layout "template" {
  direction "Horizontal"
  parts {
    layout {
      direction "Vertical"
      borderless true
      split_size Fixed=1
      run plugin=true location="zellij:tab-bar"
    }
    layout "body" {
      direction "Vertical"
    }
    layout {
      direction "Vertical"
      borderless true
      split_size Fixed=2
      run plugin=true location="zellij:status-bar"
    }
  }
}

layout "tabs" {
  direction "Vertical"
}
```

A Zellij configuration might look something like this:

```KDL
keybinds unbind=true {
  normal {
    action SwitchToMode="Locked" key {
       Ctrl "g"
    }
    action SwitchToMode="Pane" key {
      Ctrl "p"
    }
    action SwitchToMode="Resize" key {
      Ctrl "n"
    }
    action SwitchToMode="Tab" key {
      Ctrl "t"
    }
    action SwitchToMode="Scroll" key {
      Ctrl "s"
    }
    action SwitchToMode="Session" key {
      Ctrl "o"
    }
    action Quit key {
      Ctrl "q"
    }
    action NewPane key {
       Alt "n"
    }
    action MoveFocusOrTab="Left" key {
       Alt "h"
    }
    action MoveFocusOrTab="Right" key {
       Alt "l"
    }
    action MoveFocus="Down" key {
       Alt "j"
    }
    action MoveFocus="Up" key {
       Alt "k"
    }
    action FocusPreviousPane key {
       Alt "["
    }
    action FocusNextPane key {
       Alt "]"
    }
  }
  locked {
    action SwitchToMode="Normal" key {
      Ctrl "g"
    }
  }
  // ... (yes, it supports comments!!)
}
```

The only blocker I see right now is that there is no Serde support, but it looks like it's in the works: https://github.com/kdl-org/kdl-rs/issues/17

Would love to hear thoughts on this. Pinging some people of interest (though I'd love to hear anyone's take on this!) @a-kenji , @TheLostLambda, @spacemaison

**Comment by TheLostLambda** [comment]
I **strongly** agree with @tailhook 's flipping of the key and action nesting. I think it's much nicer and more natural to have `key "..." {... actions ...}` than the other way around. It should also allow for several actions per keypress more easily!

I'm also likely playing with KDL for another project soon, so I'll see how much of a pain-point no serde really is!

**Comment by har7an** [comment]
Hello,

this is now implemented in zellij 0.32.0 and up. Enjoy your new configs!

**Comment by Lilja** [comment]
If i'm allowed to put on my product-manager hat for a bit: 

Can someone bring more context as to why this change was introduced? What was the issue with YAML? Why would you not use a more established configuration language that has existed for longer?

I've never heard of KDL, looking into it it doesn't look very mature or established. No syntax highlighting support for vim, to name one example.
Is YAML support expected to be removed in a future release?

**Comment by imsnif** [comment]
You can find out more about the reasoning here:
https://zellij.dev/news/config-command-layouts/#addendum-why-did-we-choose-kdl

And the vim syntax highlighting here: https://github.com/imsnif/kdl.vim
