### ISSUE TITLE
Zellij freezes when one core is running at full capacity

### ISSUE THREAD

**Issue by happysalada** [zellij-org/zellij#773]
When one core of my machine is running at full capacity (I'm running some build or something in another tab and it's taking the full core), the ui can become very sluggish and freeze completely. Operation like select with the mouse to copy are particularly expensive (the ui will lag behind several seconds). Scrolling up and down will have some noticeable delay.

I've tried to recreate the bug and get the logs but I get some completely garbled logs. I've attached the logs before and after zellij completely freezes (the logs before are readable, it's just building `git`, the logs after are garbled)

**Basic information**

`zellij --version`: zellij 0.18.1
`tput lines`:
`tput cols`:
`uname -av` or `ver`(Windows): Darwin yt 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE
_X86_64 x86_64

`alacritty --version`: alacritty 0.9.0

**Further information**
Reproduction steps, noticable behavior, related issues etc

If you try to build git, it should max out one of your cores, try playing around with zellij and it will struggle (like some queue is getting full and is taking a long time to process).

[zellij-10.log](https://github.com/zellij-org/zellij/files/7312132/zellij-10.log)
[zellij-14.log](https://github.com/zellij-org/zellij/files/7312136/zellij-14.log)

**Comment by ikai104** [comment]
Not sure the same things, but `zellij`'s session freezes completely when I'm running `cargo install xh --version 0.15.0` in halfway. After a while `cargo install` completed and successful but zellij session still frozen.

Note: It look like only freezes the session I'm using. When I try to connect the same session again the terminal no show anything and no response. But I can use `zellij attach -c new-session` to create a new session and working good.

## System Info

- MacOS Monterey 12.2.1
- alacritty 0.9.0 (also try re-attach with MacOS builtin `Terminal.app` as above desc)
- zellij 0.25.0

**Comment by raphCode** [comment]
@happysalada does this still happen to you?

@ikai104 this might be a different issue, but can you test if it is fixed by https://github.com/zellij-org/zellij/pull/1351?
You can also wait for the next release, the fix will be included.

**Comment by happysalada** [comment]
This happened to me a couple of days ago.
Let me test and come back. (It's hard to test for the absence of something, but I'll report if I don't see anything within a month).

**Comment by ikai104** [comment]
@raphCode Sorry for late.

I'm already try to build a lot of things to run out all CPUs for a while in newest zellij (`0.29.1`) and not found any frozen at all at least for now. Pretty thanks.

**Comment by happysalada** [comment]
This just happened to me right now. It looks like it's not fixed. Sorry for the bad news :-(

**Comment by imsnif** [comment]
> This just happened to me right now. It looks like it's not fixed. Sorry for the bad news :-(

Does this happen to you maybe when you're entering a lot of text in STDIN, eg. pasting something large? Might be similar to a different issue we're fixing: https://github.com/zellij-org/zellij/pull/1383

**Comment by happysalada** [comment]
I've got that problem too :-)
The problem I'm talking about here though, has nothing to do with STDIN. It usually happens when I'm in my editor and one CPU intensive task is running. If I try to move a little too fast in the editor everything freezes. Now that you mention it, maybe those are related.
I'll be testing both for sure and will be happy to update if it is fixed.

**Comment by salkin-mada** [comment]
@happysalada was this fixed / issue went away? Maybe close issue?
