### ISSUE TITLE
Half-page scroll actions

### ISSUE THREAD

**Issue by tailhook** [zellij-org/zellij#794]
I would like to propose adding half-page scroll actions. In `less` they are bound to `Ctrl+u`/`Ctrl+d` shortcuts. I think these shortcuts can also be used in scroll mode, but at least actions will be useful (if shortcuts are occupied by something).

It's important because it allows to keep track of what is going on when scrolling (i.e. eyes can match half-screen text shifted, and it's easier to find out if something you're looking for would be on the edge of the screen if scrolling by page). Line-wise scrolling is too slow. Alternative might be something like "scroll up 10 lines" (with configurable number of lines), but usually half-page serves as a good number.

**Comment by a-kenji** [comment]
This is now in `v20.0`, thanks @oromate
