### ISSUE TITLE
ZelliJ crashes when run at home

### ISSUE THREAD

**Issue by duongdominhchau** [zellij-org/zellij#804]
## Description

Don't laugh at my silly title, it actually happens. You can see it here:

https://user-images.githubusercontent.com/56427890/138713571-0c4b4600-30a6-4d9f-bff1-cbe974ed71fd.mp4

## Information

- `zellij --version`: `zellij 0.19.0`
- `tput lines`: `40`
- `tput cols`: `159`
- `uname -av`: `Linux chau-laptop 5.14.14-arch1-1 #1 SMP PREEMPT Wed, 20 Oct 2021 21:35:18 +0000 x86_64 GNU/Linux`
- `/tmp/zellij-1000/zellij-log/zellij.log`:

```
INFO   |zellij_client            | 2021-10-25 21:19:29.051 [main      ] [zellij-client/src/lib.rs:107]: Starting Zellij client!
INFO   |zellij_server            | 2021-10-25 21:19:29.066 [main      ] [zellij-server/src/lib.rs:178]: Starting Zellij server!
INFO   |zellij_server::wasm_vm   | 2021-10-25 21:19:29.120 [wasm      ] [zellij-server/src/wasm_vm.rs:74]: Wasm main thread starts
```

**Comment by har7an** [comment]
Hello,

does this still occur with current releases of zellij?

**Comment by duongdominhchau** [comment]
Sorry, I forgot to update on this one. Right now I'm using zellij 0.31.4 and this problem does not happen anymore.
