### ISSUE TITLE
Questions from a tmux user

### ISSUE THREAD

**Issue by theniceboy** [zellij-org/zellij#841]
Hi! First of all, thank you for creating this amazing tool. I tried it out and it was blazing fast compared to tmux. I'm a long-time tmux user and I've been looking for an alternative because tmux is too slow. This project looks like the exact thing I need. There are just a couple of things I couldn't figure out with zellij:
 - How can I move a pane into another tab?
 - How do I customize the statusbar?

Thank you!

**Comment by imsnif** [comment]
Hey @theniceboy - really happy you like the tool! Unfortunately both of these things are not yet possible. But we are indeed planning in that direction with https://github.com/zellij-org/zellij/issues/811 and https://github.com/zellij-org/zellij/issues/196

**Comment by theniceboy** [comment]
Thank you! That sounds great! I'm gonna close this issue since this is a duplicate. I'll watch those two issues. Thank you for your response and the work!
