### ISSUE TITLE
Feature: add name to panes

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#850]
Give the option to give panes a name.

Currently the pane title is shown in the pane frame, but we can't give the pane an arbitrary name yet.

-  [ ] optionally show the pane name in the pane frame

**Comment by kunalmohan** [comment]
Hey @a-kenji! I want to take this up if no one's already working on it.
Just for clarification, I'm guessing that the users should be able to name panes by specifying them in the layout and would also have the ability to rename them at runtime (like tabs).
Also, would pane title be different from pane name?

**Comment by a-kenji** [comment]
@kunalmohan,
That would be awesome!

> Just for clarification, I'm guessing that the users should be able to name panes by specifying them in the layout and would also have the ability to rename them at runtime (like tabs).

Yes!

> Also, would pane title be different from pane name?

Yes, the pane title is something we get from the shell, I think it would make sense to have them be distinct.
