### ISSUE TITLE
Feature: add focus attribute to the layout

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#852]
Add a `focus` or `focused` attribute to the layout, to specify which tab, or pane should have the focus,
once the layout is fully loaded.

**Comment by jaeheonji** [comment]
Hi! @a-kenji 
I am currently interested in this feature. I'd like to contribute to the implementation if possible, but I have a questions.

Is it correct that the focus is set for each tab? or Only have one of all the tabs and Pane?

Ex) If there are 3-tabs and the 4th pane of the 2nd tab is focussed, zellij shows the foucs on the 4th pane of 2nd tab on the first start screen.

**Comment by a-kenji** [comment]
> If there are 3-tabs and the 4th pane of the 2nd tab is focussed, zellij shows the foucs on the 4th pane of 2nd tab on the first start screen.

Yes, that is how I would imagined it! Thanks for the pr, I'll look at it soon!
