### ISSUE TITLE
zellij 0.20 unusable with PuTTY because of copy&paste issues

### ISSUE THREAD

**Issue by fansari** [zellij-org/zellij#854]
Today I have built zellij 0.20.0 on my system (Fedora 34 Core OS). 

I use PuTTY on Windows 10.

First I noticed that when copy&paste passwords to "ssh-add" the passwords were claimed as wrong. After some checking I found that this is again a copy&paste issue with zellij.

Next I tried what happens when I do copy&paste into the nano editor. I found that most time (not always) after the copy the nano editor becomes stuck. I cannot enter anything also commands with Ctrl key are not accepted anymore.

My config.yaml contains these lines:

```
  no_pane_frames: true
  disable_mouse_mode: true
```

I will go back to zellij 0.18 because version 0.20 is unusable for me.

**In Case of Graphical or Performance Issues**

1. Delete the contents of `/tmp/zellij-1000/zellij-log`, ie with `cd /tmp/zellij-1000/` and `rm -fr zellij-log/`
2. Run `zellij --debug`
3. Recreate your issue.
3. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.

**Basic information**

`zellij --version`: zellij 0.20.0
`tput lines`: 67
`tput cols`: 237
`uname -av` or `ver`(Windows):  Linux xxx 5.14.11-200.fc34.x86_64 #1 SMP Sun Oct 10 14:39:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`nvim --version`: NVIM v0.5.0-dev+1299-g1c2e504d5  (used the appimage release)
`alacritty --version`: alacritty 0.7.2 (5ac8060b)

**Further information**
Reproduction steps, noticeable behavior, related issues, etc
[zellij.log](https://github.com/zellij-org/zellij/files/7511499/zellij.log)
[zellij-9.log](https://github.com/zellij-org/zellij/files/7511500/zellij-9.log)

**Comment by imsnif** [comment]
This should be fixed in 0.20.1 - sorry for the regression. I don't have this exact setup, so couldn't test exactly - but I'm pretty sure I fixed it. Could you ping me if it persists?

**Comment by fansari** [comment]
Yes - in 0.20.1 this is fixed. Thank you!
