### ISSUE TITLE
Unable to build 0.20.1 with Nix (NixOS)

### ISSUE THREAD

**Issue by Lillecarl** [zellij-org/zellij#872]
First off i just want to say, nice work on the project. Second I wanna say that I'm not a Nixlang expert and can't seem to figure out how to change the rust version a derivation is built with in Nixpkgs/NixOS.

Anyways, I'm seeing this output when trying to update the package to 0.21.1

```
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/gj65wikzmgsmlbfps198miqfxhzybr5w-zellij-0.20.1-vendor.tar.gz.drv
  /nix/store/76rd3lmhkk382wq7730qr9rmxiaxs2dg-zellij-0.20.1.drv
  /nix/store/4qimpnhlvx0g40c6lx7m0sdbd7dw3csi-system-path.drv
  /nix/store/38mw5igzyvpd70i1yzw21nm43pfdzwsq-unit-systemd-fsck-.service.drv
  /nix/store/ny1k0a8m1k92bvqp9gqagr7ayaj0cchq-system-crontab.drv
  /nix/store/53zhmci8sni7x9cihfg15757bkbkqid0-crontabs.drv
  /nix/store/qlxvqpz8lq67g31hanpklvqz761pijkg-dbus-1.drv
  /nix/store/c5cx4xx093q11kfjzbzfkpsyljswd58w-unit-dbus.service.drv
  /nix/store/h63nj3n4p1c16h5lfjl52y7iz3mfbz51-unit-polkit.service.drv
  /nix/store/7vwm0fkrdsr34h8irmqhs9sbmhy5z5hr-system-units.drv
  /nix/store/g75xvgjnym6r7yxbf9pzfnp5qf49rcny-unit-dbus.service.drv
  /nix/store/cy1cgcxmjf9q4b9njab3py2b95zsw9l7-user-units.drv
  /nix/store/xigm5ln5s48nsvl1h5jx6rwzsymmai4y-etc.drv
  /nix/store/bvafjq1kq4klpvgn133sd9c5ic593ffk-nixos-system-lemur-21.05.4114.195d5816cdd.drv
building '/nix/store/gj65wikzmgsmlbfps198miqfxhzybr5w-zellij-0.20.1-vendor.tar.gz.drv'...
unpacking sources
unpacking source archive /nix/store/6591bihkl8r8na5rh7b3n27wk1pyzyxa-source
source root is source
patching sources
configuring
no configure script, doing nothing
building
error: failed to parse manifest at `/build/source/Cargo.toml`

Caused by:
  feature `edition2021` is required

  The package requires the Cargo feature called `edition2021`, but that feature is not stabilized in this version of Cargo (1.55.0).
  Consider adding `cargo-features = ["edition2021"]` to the top of Cargo.toml (above the [package] table) to tell Cargo you are opting in to use this unstable feature.
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2021 for more information about the status of this feature.
Traceback (most recent call last):
  File "/nix/store/0bw8an9nvabm51rpnjfvy87pawqd0xf5-cargo-vendor-normalise/bin/.cargo-vendor-normalise-wrapped", line 42, in <module>
    main()
  File "/nix/store/0bw8an9nvabm51rpnjfvy87pawqd0xf5-cargo-vendor-normalise/bin/.cargo-vendor-normalise-wrapped", line 17, in main
    assert list(data.keys()) == ["source"]
AssertionError
builder for '/nix/store/gj65wikzmgsmlbfps198miqfxhzybr5w-zellij-0.20.1-vendor.tar.gz.drv' failed with exit code 1
cannot build derivation '/nix/store/76rd3lmhkk382wq7730qr9rmxiaxs2dg-zellij-0.20.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/4qimpnhlvx0g40c6lx7m0sdbd7dw3csi-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/bvafjq1kq4klpvgn133sd9c5ic593ffk-nixos-system-lemur-21.05.4114.195d5816cdd.drv': 1 dependencies couldn't be built
error: build of '/nix/store/bvafjq1kq4klpvgn133sd9c5ic593ffk-nixos-system-lemur-21.05.4114.195d5816cdd.drv' failed
```

This seems to indicate that we just need to add ```cargo-features = ["edition2021"]``` to Cargo.toml and call it a day, but this is just my interpretation as a non-rust developer.

Would it be this simple? (I figured I don't open a PR subitting things i know nothing about, but open discussion as it'd be cool to have bleeding zellij releases in nix unstable.

I'm still researching how to use a more up2date rust version to build with Nix, but it seems like it isn't entirely simple. (Weirdly enough)

**Comment by a-kenji** [comment]
@Lillecarl 
Thanks for taking the time to reaching out!


> This seems to indicate that we just need to add cargo-features = ["edition2021"] to Cargo.toml and call it a day, but this is just my interpretation as a non-rust developer.

It is already in the `staging-next` `branch`, because of the `edition2021`. It should be built soonish on `unstable`. 
So the pr in nixpkgs for unstable is already merged for `0.20.1`.

> I'm still researching how to use a more up2date rust version to build with Nix, but it seems like it isn't entirely simple.

It got much much more simple especially during the past year. When targeting such new rust releases it is often simpler using an overlay.

You can check out how I build zellij:
https://github.com/a-kenji/zellij-nix

* If you clone it you can `nix-env -if .` to install it quickly,
* or use `niv add a-kenji/zellij-nix`
* or add it as a flake `zellij.url ="github:a-kenji/zellij-nix"; `

**Comment by Lillecarl** [comment]
@a-kenji Thanks for the very quick response!

If we're this close to hitting unstable I'll be patient and wait until it lands there, I should've searched commits first. But since the current unstable package was on 0.11 i figured it wasn't maintained (i was wrong).

Thank you for the great work! :)

Should we close this?

**Comment by a-kenji** [comment]
Thanks for the kind words!
No problem! Sure, we can close it.
You can check out the progress here:
https://nixpk.gs/pr-tracker.html?pr=145388

Were currently in the `Zero Hydra Failures` period,
after that the current unstable -> stable.
Usually packages are not backported, unless there are security implications.

Please don't hesitate in reaching out in the future!
