### ISSUE TITLE
Nvim shows keystroke which shouldn't be visible

### ISSUE THREAD

**Issue by mkubasz** [zellij-org/zellij#873]
**Performance Issues**
Nvim lag when a keystroke is triggered and show it at the nvim tab. 

Versions:
zellij 0.20.1
alacritty 0.9.0 (fed349aa)
NVIM v0.5.1

This is the video with this issue [video](https://drive.google.com/file/d/11b7ZpTQWJLJX1zMOV4cuNqpAbokuNWc0/view?usp=sharing)
Look at the right bottom corner.

Files:
[zellij-11.log](https://github.com/zellij-org/zellij/files/7547565/zellij-11.log)
[zellij.log](https://github.com/zellij-org/zellij/files/7547566/zellij.log)

Probably this is related with [544](https://github.com/zellij-org/zellij/issues/544)

**Comment by raphCode** [comment]
Hey, can you check if this still is a problem in current zellij versions?
I don't see it happening on my side.

**Comment by SirAlador** [comment]
I am able to reproduce this with Zellij 0.30.0 and NeoVim 0.7.0.

It doesn't affect usability, but it does introduce some latency with unnecessary redraws. Holding down J to move my cursor down (not scrolling the nvim buffer, just moving the cursor) is noticeably slower under Zellij than under Tmux. Konsole also does not display my cursor moving, as if there is no downtime between redraws. Not sure how much of this is from this particular issue or from my larger terminal size.

My setup:
Zellij 0.30.0
Neovim 0.7.0
Fish shell 3.4.1
Konsole 22.04.2
Terminal size: 61 rows, 236 cols
