### ISSUE TITLE
Plugin: Add action that can send data to a plugin

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#874]
Add an action that can send structured/unstructured data to a plugin.

**Comment by TheLostLambda** [comment]
Hi @a-kenji ! Are you thinking of sending something like an event? 

This sort of thing? https://github.com/zellij-org/zellij/blob/639566df1540b2a80f6fdf27d7eb2ce823fa03e5/zellij-tile/src/data.rs#L46-L55

**Comment by a-kenji** [comment]
Hey @TheLostLambda,
Yes!
For example:
```
SendJson(Json),
SendText(String),
```

So that zellij could send clipboard contents, output of commands, input of commands, or the pane contents to plugins.

**Comment by hiasr** [comment]
I think this would be very helpful to enable useful background plugins and would be willing to implement this. Do we just want to enable unstructured text to be sent, or also allow plugins to register their own actions? The first is more flexible, the latter is more consistent and is the most similar to other systems.

**Comment by imsnif** [comment]
This has been implemented with [pipes](https://zellij.dev/documentation/plugin-pipes).
