### ISSUE TITLE
Zellij requires "root" privileges to launch on macOS

### ISSUE THREAD

**Issue by niilz** [zellij-org/zellij#879]
**Basic information**

`sudo zellij --version`: 0.20.1
privileges: `ls -la ~/.cargo/bin/zellij`: -rwxr-xr-x  ...
`tput lines`: 49
`tput cols`: 157
`uname -av`: 21.1.0 Darwin Kernel Version 21.1.0 RELEASE_X86_64 x86_64

`macOS Monterey 12.0.1`
`alacritty --version`: alacritty 0.9.0 (fed349a)
`fish --version`: fish, version 3.2.2

**Further information**
When I try to start `zellij` I immediately get the following error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /Users/niilz/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-utils-0.20.1/src/logging.rs:20:41
```

I've tried giving `~/.cargo/bin/zellij` full-disc-access (via macOS System Settings).
But it did not help.
Only when I enter `sudo zellij` inside my terminal, it actually launches.

After it has launched I am logged in as 'root'.
I can switch back to my user after launching. But I can not do much then (no file creation or `cargo test`, for example)

This might of course be a config problem on my end
But I could not find a fix so far.

**Comment by a-kenji** [comment]
@niilz 
Thank you for reaching out.
How did you install zellij?

Could you please check:
```
ls -la ~/.local/share/zellij
```
If that is your data directory?

**Comment by niilz** [comment]
@a-kenji
Thank you for the quick response

I used cargo (`cargo install zellij`)

Zellij is not in `~/.local/share`
As far as I can tell it is only under `~/.cargo/bin/zellij`

`ls -la ~/.cargo/bin/zellij`:  `-rwxr-xr-x ...`

**Comment by a-kenji** [comment]
The permissions of the zellij binary itself seem ok to me,
though I am not familiar with darwin systems.

Can binaries on darwin create files in `/tmp/` ? Because that is what the logger attempts. Specifically `/tmp/zellij-[USERID]/`
And zellij itself tries to create a data directory in `~/.local/share/zellij` or similar platform specific directories.

**Comment by niilz** [comment]
I've just wrote this little test-script (as my regular user):
```
use std::io::Write;

fn main() {
    let mut file = std::fs::File::create("/tmp/zellij-test.txt").unwrap();
    let _ = file.write_all(b"This is a privileges test");
}
```

And it also gives a permission error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/main.rs:7:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So I assume it is not regulary ok for binaries to create files above `~/` on Darwin.

**Comment by a-kenji** [comment]
Oh, that is good go know, thanks!
Weird that is has not been an issue for other darwin users yet.

Can you as a workaround create the `/tmp/zellij-[USERID]`
directory yourself and give it permissions?
I think we will want to fix that relatively soon.

Is there a good directory darwin would expect log files to go?

**Comment by niilz** [comment]
`/tmp/zellij-0` gets created when I run `sudo zellij`
it then has only `root` privileges: `drwx------`

But giving it  more rights with `sudo chmod 755` (`drwxr-xr-x`) still requires zellij to be launched with `sudo`.

I've also tried to create the following directories as you suggested (`id` returns *[numerical-user-id]*):
```
drwxr-xr-x   2 root   wheel    64B Nov 18 22:39 zellij-[numerical-user-id]
drwxr-xr-x   2 root   wheel    64B Nov 18 22:22 zellij-myusername
```
Still: running just `zellij` (without `sudo`) gives me the privileges error.

Interesting observation:
**`ls -la /tmp`** displays: `lrwxr-xr-x@ 1 root  wheel  11 Oct 18 05:30`**`/tmp -> private/tmp`**
So `/tmp` is actually a link to **`private/tmp`**
Also,  I can not simply create a folder under `/tmp` without `sudo`.

Unfortunately I am not certain about the *typical* or *best-practice* directory for logs on Debian.

**Comment by a-kenji** [comment]
Thank you again for checking this!

Is it possible to maybe try to switch the owner to you for this directory, as opposed to root?
```
drwxr-xr-x   2 root   wheel    64B Nov 18 22:39 zellij-[numerical-user-id]
```

> Interesting observation:
That is indeed very interesting! Thanks for the heads up!

> Unfortunately I am not certain about the typical or best-practice directory for logs on Debian.

Oh, that is no problem - I was asking about darwin systems. On debian `/tmp` is an OK place for logs, better would be the recently released  `XDG_STATE_DIR`, but not everyone is aware of that yet.

**Comment by a-kenji** [comment]
@niilz 
I got some feedback from a darwin user and he asked if you
gave your terminal access to the area?

Also he gave me this link here:
https://superuser.com/questions/1133065/unable-to-write-to-tmp-directory-in-macos-unable-to-correct-permissions-oper

**Comment by niilz** [comment]
Very sorry, I actually meant *Darwin*, where I don't know the go-to log-directory.

I've changed group to `staff` and owner to `myuser` on the following log-files under `/tmp/`:
```
drwxr-xr-x   3 myuser  staff   96 Nov 19 19:14 zellij-[numerical-user-id]
drwxr-xr-x   2 myuser  staff   64 Nov 18 22:22 zellij-myuser
```
Unfortunately that still result in the permission-error when I run `zellij`.

**Comment by a-kenji** [comment]
Ah, no problem. Oh weird - I would have thought that could have been a possible solution.

Did you try the solutions that are shown in the link?

**Comment by niilz** [comment]
@a-kenji
I have not tried the procedure that the link describes, yet.
Mostly because I would like to understand what it does first and whether there are any implications one should be aware of.

But it certainly sounds like it should work.
So I think I can close the issue, right.

Thanks for all your efforts and immediate responses.

**Comment by a-kenji** [comment]
@niilz 
Sure, no problem.
I will close the issue. Please do reach out again if in the future!

I would suggest starting with trying to give your terminal the necessary rights:

> It turned out I needed to add my terminal app to the Settings.app "Security & Privacy" > "Full Disk Access"
(I added both terminal.app and iTerm.app)

(this is from the link)

And then go to the more hacky looking solutions, if they are needed.
