### ISSUE TITLE
Support for hex-colors

### ISSUE THREAD

**Issue by fedoranvar** [zellij-org/zellij#880]
Good day to you!

Is there support for hex-colors in `theme`-section?

 like: 
```yaml
green: '#102030'
```
^tried that for 'green' component - it shows error

Thank you!

**Comment by imsnif** [comment]
Not yet! I would love to merge something like this.

**Comment by ramonGonzEdu** [comment]
The PR was merged. just use colors like `"#FF0000"` in config

**Comment by a-kenji** [comment]
Thank you @ramonGonzEdu.
