### ISSUE TITLE
Support esc-key in the same way as the enter-key

### ISSUE THREAD

**Issue by jovandeginste** [zellij-org/zellij#887]
Intuitively, I hit the ESC key when I want to escape other modes than the "normal" mode. This is probably because vim is my main editor.
Is it doable to have ESC behave identical to ENTER where reasonable and feasable?

**Comment by a-kenji** [comment]
Hey!
Thank you for reaching out. 
Sure, you can add the `Esc` key to your configuration, 
where you want to switch to the desired mode.

**Comment by jovandeginste** [comment]
OK; also remapped:

```
- action: [CloseFocus,]
  key: [Ctrl: 'x',]

- action: [CloseTab,]
  key: [ Ctrl: 'x',]
```

and for ergonomics:

```
- action: [Detach,]
  key: [Char: 'd', Ctrl: 'd']
```

**Comment by imsnif** [comment]
IMO this should be part of the default btw. I also find myself in the same situation as a vim user :)

**Comment by a-kenji** [comment]
I like the idea of having this a a default!

**Comment by jovandeginste** [comment]
Thanks! What about my other suggestions?

**Comment by a-kenji** [comment]
I like the idea of limiting possible destruction,
but I think we might go a different route in preventing them.

Currently the plan is:

- check for running programs
- if it is not an interactive shell, then prompt for the closing
- this could be overwritten
