### ISSUE TITLE
Bug: Prevent zellij from attaching to itself (the already running session)

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#905]
Found in #904 :

`zellij --version`: `0.20.1` & `7cb165f0c232fd8fffea31b19fd38cf1b29908e4`

# Steps:
- `zellij a -c main`
- `zellij a -c main`

Now zellij is locked up, since it tried to attach to itself,
I think it would be good to forbid this action with an 
appropriate error message.

**Comment by jaeheonji** [comment]
For reference, I leave a comment on how `TMUX` works.

* `TMUX` rejects nested sessions by default. (`new-session`, `attach`)
*  If it remove the `$TMUX` environment variable, itcan forcibly use nested sessions.

But, funnyly, `TMUX` also has a bug that breaks the UI if nested attach is allowed 🤣

**Comment by jaeheonji** [comment]
@a-kenji Could the example be a typo? :)
(from `zellij -a c main` to `zellij a -c main`)

**Comment by a-kenji** [comment]
@jaeheonji 
You are right, thanks for noticing that!
