### ISSUE TITLE
options --clean not working

### ISSUE THREAD

**Issue by mkastner** [zellij-org/zellij#910]
macos Monterey 12.0.1
iterm 3.4.12
zellij(homebrew) 0.20.1

When invoking:

`$ zellij --options clean`

like mentioned in the [documentation](https://zellij.dev/documentation/configuration.html), I obtain:

`error: Found argument '--options' which wasn't expected, or isn't valid in this context`

Also, when I enter

$ zellij setup

or

$ zellij options

zellij simply starts.

I can neither, as described in the SUBCOMMANDS-section of `zellij --help`, "_Change the behaviour of zellij_" (when using `zellij options`) nor can I "_Setup zellij and check its configuration_" (when using `zellij setup`).

### Addendum

I ran

`zellij setup --check`

and it returned:

```
[Version]: "0.20.1"
[CONFIG DIR]: "/Users/myusername/Library/Application Support/org.Zellij-Contributors.Zellij"
[CONFIG FILE]: "/Users/myusername/Library/Application Support/org.Zellij-Contributors.Zellij/config.yaml"
[CONFIG ERROR]: IoError: No such file or directory (os error 2), File: /Users/myusername/Library/Application Support/org.Zellij-Contributors.Zellij/config.yaml
[DATA DIR]: "/Users/myusername/Library/Application Support/org.Zellij-Contributors.Zellij"
[PLUGIN DIR]: "/Users/myusername/Library/Application Support/org.Zellij-Contributors.Zellij/plugins"
[LAYOUT DIR]: "/Users/myusername/Library/Application Support/org.Zellij-Contributors.Zellij/layouts"
[SYSTEM DATA DIR]: "/usr/share/zellij"
[ARROW SEPARATOR]: 
 Is the [ARROW_SEPARATOR] displayed correctly?
 If not you may want to either start zellij with a compatible mode 'zellij options --simplified-ui'
 Or check the font that is in use:
 https://zellij.dev/documentation/compatibility.html#the-status-bar-fonts-dont-render-correctly
'
[FEATURES]: []
[DOCUMENTATION]: zellij.dev/documentation
```

So it looks like there is a [CONFIG ERROR] due to a missing default config file

 **/Users/myusername/Library/Application Support/org.Zellij-Contributors.Zellij/config.yaml**

It should have been created upon homebrew install but it wasn't, so maybe this is a homebrew package problem and not so much a problem of zellij itself.

Maybe someone can give me hint.

**Comment by a-kenji** [comment]
Hello @mkastner,
thank you for taking the time creating this issue!

> When invoking:
> 
> `$ zellij --options clean`
> 
> like mentioned in the [documentation](https://zellij.dev/documentation/configuration.html), 

`options` is a [subcommand](https://zellij.dev/documentation/commands.html), meaning it is invoked without `--`.
 
> Also, when I enter
> 
> $ zellij setup
> 
> or
> 
> $ zellij options
> 
> zellij simply starts.

That might be a good way to change? The empty `setup` command is still a placeholder,
but maybe we should reject an empty `options` subcommand.

To override the configuration file you would use this syntax:
```
zellij options --simplified-ui true
```
and to start without reading from a configuration file:
```
zellij setup --clean
```


> It should have been created upon homebrew install but it wasn't, so maybe this is a homebrew package problem and not so much a problem of zellij itself.

It seems that everything is OK with your installation.
There is just no configuration file at the default configuration,
so it is not read from there.

Do you think the documentation is unclear here?

**Comment by mkastner** [comment]
Well, to _me_ it was not clear. But now, in hindsight, I must confess that the README.md documentation _is_ pretty clear about the config file: "Alacritty doesn't create the config file for you".

Upon installation I followed my intuition (which is always a bad thing) and expected a kind of default config would have been created.

For ignorants like me, it would me nice, if there'd either a minimal default config provided or a big fat message showing up saying: "Alacritty starting without a config file. Create one."

Having that said (i.e. written) I'd like to make sure, that alacritty is absolutely awesome and works extremely well. I love the config file which is much than iterms menu maze. Thanks!!!
