### ISSUE TITLE
Plugin colors changed

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#912]
`zellij --version`:  `0.21` & `485b9e4f9833f9aa2ab08721f99bccd695a209c0`
`system`: `Linux 5.10.81 #1-NixOS SMP Sun Nov 21 12:46:37 UTC 2021 x86_64 GNU/Linux`

The plugin colors have changed, I don't think that is intentional.

![zellij-plugin-color](https://user-images.githubusercontent.com/65275785/144008434-665fddc8-3aa6-4d67-b4e7-3e22b723d6b8.png)

**Comment by imsnif** [comment]
This is a bug fix, actually :) Sorry I didn't mention it in the changelog. `cyan` is now `cyan` instead of gray. I fixed it in the default plugins, I think it should be a fairly simple fix in custom plugins as well?

**Comment by a-kenji** [comment]
Ah, thanks for the quick answer.
In that case, maybe we need to change the default theme?

It is very hard to read it currently
![zellij-contrast](https://user-images.githubusercontent.com/65275785/144009491-48187eea-159c-488d-8ed3-549b7db187cc.png)
.

**Comment by imsnif** [comment]
I'm not sure what you mean? You shouldn't be seeing cyan. It was just a bug that displayed cyan as gray instead of gray as gray. The default plugins (afaict) appear normally. You just need to change the coloring in your plugin to use gray instead of cyan. Unless I'm misunderstanding?

**Comment by a-kenji** [comment]
Ah, then I misunderstood!
Then maybe this is a different issue.
This should be the default plugin.

**Comment by imsnif** [comment]
This is the change in the default plugins: https://github.com/zellij-org/zellij/pull/897/files#diff-d399b68ca69ed46dafc739c294bd26f4ac45b7421b4df54dc9523e01f9721ce8R79-R127

**Comment by a-kenji** [comment]
Ah, I am using main right now.
Maybe the plugins got merged back in after the release?

**Comment by imsnif** [comment]
But you are using your custom plugin, aren't you? At least that's what I see in the screenshot.

**Comment by a-kenji** [comment]
@imsnif,
Ah I think I built pre https://github.com/zellij-org/zellij/commit/7722a21248dd98fc113e72a99ac39ff3e930859d, that could explain the mismatch.

**Comment by imsnif** [comment]
Does your custom plugin have these color changes?

**Comment by a-kenji** [comment]
That is the default `tab-bar` currently.

> Does your custom plugin have these color changes?

No, not yet.

**Comment by imsnif** [comment]
I see, my mistake... so maybe it's indeed the build from before the update as you mentioned?

**Comment by a-kenji** [comment]
@imsnif ,
Rebuilding from main fixed it.
Thanks for answering so quick!

**Comment by tw4452852** [comment]
I encountered the same issue even after rebuilding from the main branch. 
BTW, I also added `gray` into my theme.

**Comment by imsnif** [comment]
Is it exactly the same issue @tw4452852 - with the default plugins? How are you running zellij exactly?

**Comment by a-kenji** [comment]
@tw4452852,
Does #914 solve your issue?

**Comment by tw4452852** [comment]
@a-kenji @imsnif 
With #914, it works back again. Thanks!

**Comment by a-kenji** [comment]
Glad it works!
