### ISSUE TITLE
WSL: wslview messes with zellij's display

### ISSUE THREAD

**Issue by tranzystorek-io** [zellij-org/zellij#924]
This is related to `wslview`, an utility from the https://github.com/wslutilities/wslu toolset.

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.
[zellij.log](https://github.com/zellij-org/zellij/files/7653727/zellij.log)
[zellij-9.log](https://github.com/zellij-org/zellij/files/7653728/zellij-9.log)

**Basic information**

`zellij --version`: zellij 0.21.0
`tput lines`: 30
`tput cols`: 120
`uname -av`: Linux MSI 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 GNU/Linux
`winver`: Windows 11 Version 21H1 Build 22000.348

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`wslview --version`: wslu v3.2.3-1; wslview v10

**Further information**
To reproduce:

1. Make shure wslu is installed on your WSL distro
2. Open any file with wslview, e.g. `wslview file.txt`

Example after running:
![obraz](https://user-images.githubusercontent.com/5671049/144705483-5fa03ae0-4d4d-4a85-9ad4-e6bb077e0443.png)

Fixes itself when doing ctrl+L

**Comment by tranzystorek-io** [comment]
No longer reproduces on zellij 0.30.0 and wslview 3.2.4

**Comment by a-kenji** [comment]
Thank you for checking @tranzystorek-io !
