### ISSUE TITLE
can't remove zellij 'Tip'

### ISSUE THREAD

**Issue by garyteofanus** [zellij-org/zellij#927]
I have already read through the docs and config files but I don't think there's an option to remove the tip. Is this possible to do?

By tip I mean this,

![screenshot-20211208-030325](https://user-images.githubusercontent.com/40825899/145098196-7e0ed698-4d36-42be-a3d6-5272ad4a3222.png)

**Comment by jaeheonji** [comment]
It is impossible to remove only 'Tip'. It's hardcoded into the `status-bar` plugin. Instead, you can disable plugins.

Currently, there is a discussion in the community about individual settings of the plugin.So, the function of removing only the tip later may be implemented.

**Comment by garyteofanus** [comment]
Okay, thank you for the information. Closing.
