### ISSUE TITLE
Window title not transfered to terminal emulator

### ISSUE THREAD

**Issue by pando85** [zellij-org/zellij#931]
Hello guys, thank you for this program.

I'm experiencing some issues related with window title: 
- when I execute some command that changes the window title I expect to see window titled modified.
- when multiple panes or tabs are opened I expect to see the window title from the focus pane.

I came from terminator and this functionality would be very appreciated.
What do you think? Is it possible to implement? I could also help on that if you give me some tips. 

Thanks!

**Comment by imsnif** [comment]
Hey, this is totally possible to implement and I would love to see this feature. What would you think about prefixing it with the Zellij name (eg. `Zellij - my title`) to make it clearer?

**Comment by a-kenji** [comment]
Hey! Thanks for taking the time opening this issues.

This is related to #883.
