### ISSUE TITLE
Recursive attach

### ISSUE THREAD

**Issue by raphCode** [zellij-org/zellij#935]
While I find the ability to nest zellij sessions useful (please keep it that way), there are some edge cases which should probably not be allowed. One of these is a recursive attach:
1. start new `zellij` session
2. enter `zellij attach <name of this session>`

The pane shrinks to minimal size, glitches and/or the scrollback buffer begings to fill. Also, upon detaching sometimes a server process spinning on the CPU is left behind.

While I agree that this is a very stupid edge case to try on purpose, accidentally triggering this in a productive session will likely make the session unuseuseable und unrecoverable, maybe leading to loss of unsaved data.

**Comment by imsnif** [comment]
Hey, I think this should be fixed in: https://github.com/zellij-org/zellij/pull/911
Which will hopefully be released very soon. I wanted to release it over the weekend but there's one small bug in main that I want to fix before. Fingers crossed, will release in the next day or two.

**Comment by raphCode** [comment]
Aw dang, I just searched through the open issues and did not realize it was already reported.

**Comment by imsnif** [comment]
All good! Better to report a duplicate than not to report :) Let's close this when we release the version and you can confirm it's fixed, ok?

**Comment by raphCode** [comment]
Updated through Arch package, bugfix is included!

Thanks for the great work :)
