### ISSUE TITLE
Zellij loses track of panes when switching tabs

### ISSUE THREAD

**Issue by jovandeginste** [zellij-org/zellij#940]
I updated to `0.22.0`
I have several panes on several tabs
I make one pane "full screen" on one tab
I switch back & forth between tabs
At some point, zellij loses track of which pane is full screen

**Comment by imsnif** [comment]
I'm reproducing this, but not consistently. I'll try to take a deeper look soon. If you happen to find a consistent way to reproduce this, it would be a great help.

**Comment by jovandeginste** [comment]
I'll try tomorrow

**Comment by jovandeginste** [comment]
Can you provide a binary? I have no idea how to compile it....

**Comment by jovandeginste** [comment]
I just tried to build myself, but got this error:

```
[...]
[cargo-make][1] INFO - Execute Command: "cargo" "build"
error: failed to parse manifest at `/home/jo/Documenten/Projects/zellij/zellij-client/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest
[cargo-make][1] ERROR - Error while executing command, exit code: 101
[cargo-make][1] WARN - Build Failed.
[cargo-make] ERROR - Error while running duckscript: Source: Unknown Line: 4 - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
```

**Comment by jovandeginste** [comment]
(Probably rustc from apt is too old - I'm installing rust from the rust site now)

**Comment by imsnif** [comment]
Yes, that's probably it. I'm happy to compile a binary for you though assuming you're on linux? (otherwise it'll be a little harder)

**Comment by jovandeginste** [comment]
I managed to build it, but it is now depending on my version of GLIBC (but I run zellij on a different system, so it's not compatible ...)

**Comment by imsnif** [comment]
HEre's a generic linux musl compiled binary, if you're running linux it should work:
[zellij.txt](https://github.com/zellij-org/zellij/files/7711446/zellij.txt)

(I had to add a .txt suffix to appease github, remove it and chmod it to be an executable and it should work)

If you'd rather compile the generic version yourself, you can use `cargo make build-e2e` and then find it in ./target/x86_64-unknown-linux-musl/release/zellij

**Comment by jovandeginste** [comment]
I'm running this now, see what happens today

**Comment by jovandeginste** [comment]
No problems so far....

**Comment by imsnif** [comment]
Cool. The case I saw to reproduce this is:
1. Open a new pane
2. Make it fullscreen
3. Focus a different tab
4. Focus back to the previous tab

**Comment by jovandeginste** [comment]
More or less what I described :smile:

**Comment by jovandeginste** [comment]
(good work, btw!)

**Comment by imsnif** [comment]
Thanks!

And yeah, very similar. :D What was throwing me off is the first part. It didn't happen if the full screen pane was the "first" pane in the tab.

Cool - so I'll close this and release a version. Thanks for the quick report and follow up!
