### ISSUE TITLE
zellij v0.22.1: config.yaml file is ignored

### ISSUE THREAD

**Issue by fansari** [zellij-org/zellij#945]
After updating from v0.20.1 to v0.22.1 I found that ~/.config/zellij/config.yaml is ignored.

This is even the case when I pass the config explicitly with --config to zellij.

This makes this version unusable for me. I switched back to v0.20.1.

My config.yaml looks like this:

```
---
  no_pane_frames: true
  disable_mouse_mode: true
```

**Comment by jaeheonji** [comment]
Hi! @fansari 

Its usage has changed. Would you like to try this?

```yaml
---
  pane_frames: false
  mouse_mode: false
```

**Comment by fansari** [comment]
Yes - this is workinkg. I did not know about these changes.

**Comment by matu3ba** [comment]
@fansari Keep in mind that zellij is pre 1.0, and expect breaking changes. Can this be closed?

**Comment by fansari** [comment]
Yes - this can be closed.
