### ISSUE TITLE
attach/create session 

### ISSUE THREAD

**Issue by wcasanova** [zellij-org/zellij#946]
there is a useful command in tmux, to attach or create a session, if it does not exist it creates the session, if it already exists, it is attached
tmux new -A -s name-session

https://stackoverflow.com/a/49134974

**Comment by imsnif** [comment]
I think Zellij already has this ability... Do you mean something like `zellij attach --create my_session_name`?

**Comment by jovandeginste** [comment]
Very useful feature indeed, I use it all the time (with zellij)!

**Comment by wcasanova** [comment]
> I think Zellij already has this ability... Do you mean something like `zellij attach --create my_session_name`?

perfect, if that.
Thank you
