### ISSUE TITLE
Feature Request: Config keybinds for every mode

### ISSUE THREAD

**Issue by whusnoopy** [zellij-org/zellij#948]
There is an `unbind: true` for every mode, but no way to bind a common shortcut for all modes.

For example, in the default config, `Ctrl` + `g` will switch to lock mode, but needs to config for every mode many times.

So, is it possible to add an `all` mode or `any` mode for keybinds config?

**Comment by matu3ba** [comment]
As workaround you can delete many modes and shrink them together as I did [in my config](https://gist.github.com/matu3ba/d38ed15802640a12879b97c260a7d7d7).

**Comment by JCallicoat** [comment]
I think this is https://github.com/zellij-org/zellij/pull/701

**Comment by a-kenji** [comment]
This would be awesome, but we would need a way to specify which modes should get this keybinding and action, since if you for example would bind it to every mode, you can't switch modes anymore.

**Comment by a-kenji** [comment]
This will be addressed in  #1036.
