### ISSUE TITLE
Viuer hanging inside zellij

### ISSUE THREAD

**Issue by LordMZTE** [zellij-org/zellij#969]
**Basic information**

`zellij --version`: `zellij 0.24.0` (I'm running the git version, commit `0863e74`)
`tput lines`: `36`
`tput cols`: `134`
`uname -av` or `ver`(Windows): `Linux mzte 5.15.10-arch1-1 #1 SMP PREEMPT Fri, 17 Dec 2021 11:17:37 +0000 x86_64 GNU/Linux`

`viu --version`: `1.4.0`
`alacritty --version`: `alacritty 0.9.0 (fed349aa)`

**Further information**
[Viuer](https://github.com/atanunq/viuer) is a tool/library for displaying images on the terminal. It works just fine inside alacritty & tmux, however it hangs indefinetely inside zellij.

This behaviour can be reproduced by installing viuer and then using `viu someimage.png` to display an image. This command will hang only inside zellij.

**Comment by imsnif** [comment]
Hey, I can't reproduce this with the same version of Alacritty and `Viu` - for me it works great (well, not great because Zellij doesn't yet have image support - but it at least doesn't hang).

Does it happen only with a specific image maybe?

**Comment by LordMZTE** [comment]
Looks like this isn't actually a zellij thing. After investigating some more, it looks like the issue is with viuer incorrectly believing that the kitty image protocol is available, because I'm using the kitty term info. The reason it worked inside tmux is that tmux apparently overwrote it with another one. Sorry about that!

**Comment by imsnif** [comment]
Btw - this is still a bug in Zellij. We shouldn't be advertizing capabilities we don't have.

**Comment by LordMZTE** [comment]
How so? This isn't zelij. I set the term info to xterm-kitty, not zellij. And viuer is incorrectly assuming that that means that kitty image support is present.

**Comment by imsnif** [comment]
Aha! Did you set it manually?

**Comment by LordMZTE** [comment]
Yeah. It's the only terminfo I know that actually works well, and didn't give me some issue or another working out truecolor support.
