### ISSUE TITLE
Plugin getting incorrect color palette

### ISSUE THREAD

**Issue by LordMZTE** [zellij-org/zellij#971]
**Basic information**

`zellij --version`: `zellij 0.24.0` (I'm running the git version, commit `0863e74`)
`tput lines`: `40`
`tput cols`: `264`
`uname -av` or `ver`(Windows): `Linux mzte 5.15.10-arch1-1 #1 SMP PREEMPT Fri, 17 Dec 2021 11:17:37 +0000 x86_64 GNU/Linux`
`alacritty --version`: `alacritty 0.9.0 (fed349aa)`

**Further information**
![image](https://user-images.githubusercontent.com/28735087/147290545-0b055805-0287-4ce7-bd60-02ff2c19589a.png)

This image shows my config at the top and my plugin at the bottom. My plugin is debug-printing the color palette it got through the `ModeUpdate` event.

The problem is, that the background in my config is different from the background the plugin got. Instead, it seems like the plugin also got the foreground in place of the background.

**Comment by imsnif** [comment]
Hey, good find! I think this bug happens because of a typo here: https://github.com/zellij-org/zellij/blob/main/zellij-utils/src/input/theme.rs#L81

Would you be interested in giving this fix a try and issuing a PR?

**Comment by LordMZTE** [comment]
Sure!
