### ISSUE TITLE
Panic when child process is killed externally

### ISSUE THREAD

**Issue by berkus** [zellij-org/zellij#974]
Thank you for taking the time to file this issue! Please follow the instructions and fill in the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

**Basic information**

`zellij --version`: zellij 0.23.0
`tput lines`: 37
`tput cols`: 138
`uname -av` or `ver`(Windows): Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64

List of programs you interact with as, `PROGRAM --version`:
`QEMU emulator version 6.2.0`

**Further information**

```
zellij --layout-path emulation/layout.zellij

Originating Thread(s):
1. stdin_handler_thread: AcceptInput
2. screen_thread: ClearScroll
3. ipc_server: Render

Error: thread 'router' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })': /Users/berkus/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-utils-0.23.0/src/ipc.rs:168
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: zellij_utils::errors::handle_panic
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_handler::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: _rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: <zellij_client::os_input_output::ClientOsInputOutput as zellij_client::os_input_output::ClientOsApi>::recv_from_server
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: std::sys::unix::thread::Thread::new::thread_start
  13: _pthread_from_mach_thread_np
error: Recipe `zellij` failed on line 4 with exit code 1
```

This happens when I have to kill QEMU process launched from zellij, then zellij hangs itself and after I kill it - it prints this upon exit.

**Comment by imsnif** [comment]
So, just to make sure I understand - what happens is:

1. You kill QEMU
2. Zellij hangs (you can't do anything, even move focus to another pane?)
3. You kill Zellij and only then you see this trace?

**Comment by berkus** [comment]
Correct.

**Comment by imsnif** [comment]
@berkus - I'm not managing to reproduce this with `htop`... could you share your layout?

**Comment by berkus** [comment]
It's [the same](https://github.com/metta-systems/vesper/blob/feature/chainboot/emulation/layout.zellij).

The biggest issue is probably to get QEMU in that same half-zombie state that killing it with macOS "Force close" doesn't clean up some resources perhaps?

We could try with a debug build of zellij if it does trace some of the PTY juggling as it goes.

**Comment by raphCode** [comment]
Fixed by https://github.com/zellij-org/zellij/pull/1351
