### ISSUE TITLE
Kill all sessions failed to work

### ISSUE THREAD

**Issue by alekspickle** [zellij-org/zellij#978]
**Basic information**
`zellij --version`: zellij 0.23.0
`tput lines`: 60
`tput cols`: 125
`uname -av`: Linux pickle 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

`cargo 1.56.0 (4ed5d137b 2021-10-04)`
`rustc 1.56.1 (09c42c458 2021-10-18)`
`git version 2.33.0`
`zsh 5.8 (x86_64-ubuntu-linux-gnu)`

**Further information**
I don't know how to reproduce it, but `zellij kill-session\kill-all-sessions` was simply not working. I don't know why, It stuck in simple `git status`
When I tried to kill sessions it gave my terminal two empty outputs as if I was running `echo ""` but when I tried to start new session with the same name it refused to start because of conflict and returned it in `list-sessions`.

 Nothing useful in `/tmp/zellij-0/zellij-log/zellij.log `

**Comment by jaeheonji** [comment]
It is difficult to determine what the problem is because there is no detailed information. 

Zellij must access the ipc socket folder to kill the session. it is normally located the `$XDG_RUNTIME_DIR/zellij/VERSION`. If the session did not kill even after executing the `kill-session command`, it may mean that the socket file could not be deleted normally. (assuming that there is no visible error)

Of course, this is just my assumption, and it may not be correct.

if you find more information, please leave a comment on this issue :)

**Comment by alekspickle** [comment]
Thx for advice. I'll explore this directory if I stumble on it again!

**Comment by imsnif** [comment]
It could also be that the Zellij instance was deadlocked and could not even respond to the kill session command. If this happens again, maybe we can try and figure out what happened to make it stuck?

**Comment by alekspickle** [comment]
I am stumbling on this occasionally, so if you can point me on what to check I'd appreciate it.

**Comment by imsnif** [comment]
When this happens, is this after you did something specifically in one pane? Run a specific command? Resized a pane, or?

**Comment by alekspickle** [comment]
Yeah, mostly it happens after a specific command. Also our CLI uses some crates that work with terminal (console, dialoguer, ansi_term), but I doubt they are the reason. This happened even after git commands.

**Comment by raphCode** [comment]
Since I just found a lot of issues that had the symptom of hanging/freezing and sometimes crashing afterwards, I strongly believe this issue is related as well.
We fixed it with https://github.com/zellij-org/zellij/pull/1351.

Should we close this?

**Comment by alekspickle** [comment]
Haven't seen it in a while 👌

**Comment by raphCode** [comment]
Good :)
Please notify us if this happens again with the next release and onwards!
