### ISSUE TITLE
Panic when switching tabs with a mouse click

### ISSUE THREAD

**Issue by neurocyte** [zellij-org/zellij#983]
Clicking a second tab with the mouse in a second attached client caused the following panic:

```
Error occurred in server:
Originating Thread(s):
1. stdin_handler_thread: AcceptInput
2. screen_thread: LeftClick
3. plugin_thread: Render
4. screen_thread: GoToTab

Error: thread 'screen' panicked at 'called `Option::unwrap()` on a `None` value': zellij-server/src/screen.rs:284
   0: zellij_utils::errors::handle_panic
   1: std::panicking::rust_panic_with_hook
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:628:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:519:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
   4: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   5: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   6: core::panicking::panic
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:50:5
   7: zellij_server::screen::Screen::switch_active_tab
   8: zellij_server::screen::screen_thread_main
   9: std::sys_common::backtrace::__rust_begin_short_backtrace
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys/unix/thread.rs:106:17
  12: start_thread
  13: __GI___clone
```

**Basic information**

`zellij --version`: zellij 0.24.0 (855413c)
`tput lines`: 58
`tput cols`: 189
`uname`: Linux 5.15.12-1-MANJARO x86_64

Running at time of crash:
`tig --version`: 2.5.4
`fish --version`: 3.3.1
`wt.exe --version`: 1.12.3472.0 (Windows Terminal Preview via ssh)

**Further information**
The panic happened when clicking on a tab with the mouse. Two clients were connected to the session. The mouse click occurred in the zellij instance that performed the attach.

I attempted to reproduce with --debug, but was unsuccessful. Switching tabs with the mouse (in either client) did not produce another panic. Selecting a tab with the mouse often causes the wrong client to switch tabs.

zellij.log:
```
INFO   |zellij_client            | 2022-01-03 11:15:39.049 [main      ] [zellij-client/src/lib.rs:118]: Starting Zellij client!
INFO   |zellij_server            | 2022-01-03 11:15:39.052 [main      ] [zellij-server/src/lib.rs:185]: Starting Zellij server!
INFO   |zellij_server::wasm_vm   | 2022-01-03 11:15:39.104 [wasm      ] [zellij-server/src/wasm_vm.rs:86]: Wasm main thread starts
INFO   |zellij_client            | 2022-01-03 11:15:54.395 [main      ] [zellij-client/src/lib.rs:342]: Bye from Zellij!
INFO   |zellij_client            | 2022-01-03 11:16:08.001 [main      ] [zellij-client/src/lib.rs:118]: Starting Zellij client!
ERROR  |zellij_server::tab       | 2022-01-03 11:20:36.069 [screen    ] [zellij-server/src/tab.rs:2302]: Failed to vertically resize the tab!!!
INFO   |zellij_server::wasm_vm   | 2022-01-03 11:20:36.070 [wasm      ] [zellij-server/src/wasm_vm.rs:168]: Bye from plugin 2
INFO   |zellij_server::wasm_vm   | 2022-01-03 11:20:36.070 [wasm      ] [zellij-server/src/wasm_vm.rs:168]: Bye from plugin 3
INFO   |zellij_client            | 2022-01-03 11:24:45.771 [main      ] [zellij-client/src/lib.rs:118]: Starting Zellij client!
INFO   |zellij_server::wasm_vm   | 2022-01-03 11:28:06.590 [wasm      ] [zellij-server/src/wasm_vm.rs:223]: wasm main thread exits
```

**Comment by jaeheonji** [comment]
Thank you for reporting! 

I don't know if it is directly related to panic, I found the reason why tabs do not move normally when mouse clicks in multiple user. After the bug is fixed, if you find any errors like this, please report it :)

**Comment by neurocyte** [comment]
I tried your fix (e3a1447) and I don't think it fixes the strange mouse tab switching behavior. I made a video (with the fix) to show you what I mean.

https://user-images.githubusercontent.com/1552770/147945556-1d4c31b6-4a5f-421b-a3ec-4b88d5156199.mp4

**Comment by jaeheonji** [comment]
@neurocyte Your right! I also found the same issue. very wired.. It seems to be a problem when different users are on the same tab and then move to another tab. 

I'm really sorry, but could you please make an issue again with the video?

**Comment by imsnif** [comment]
Hey @jaeheonji  and @neurocyte - I think I found the issue. I'm debugging it now, will keep you posted ASAP!

**Comment by imsnif** [comment]
Okay, I think I fixed it. I merged my fix to main just now, @neurocyte - can you check and see if it works for you?

**Comment by neurocyte** [comment]
> Okay, I think I fixed it. I merged my fix to main just now, @neurocyte - can you check and see if it works for you?

Yep. It works perfectly now. 👍

**Comment by imsnif** [comment]
Amazing, thanks for reporting and testing! And thanks @jaeheonji for the first half of the fix :) will release this next version.
