### ISSUE TITLE
Crash after opening a pane if located inside deleted path.

### ISSUE THREAD

**Issue by alekspickle** [zellij-org/zellij#993]
**Basic information**
`zellij --version`: zellij 0.23.0
`tput lines`: 60
`tput cols`: 125
`uname -av`: Linux pickle 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

`cargo 1.56.0 (4ed5d137b 2021-10-04)`
`rustc 1.56.1 (09c42c458 2021-10-18)`
`git version 2.33.0`
`zsh 5.8 (x86_64-ubuntu-linux-gnu)`

**Further information**
Created a session, navigated to a directory, then in another pane deleted that directory and create one with the same name.
After that if you <Ctrl + T> + <N> it panics with the same error #979 does.

**Comment by jaeheonji** [comment]
This error seems to be caused by creating a terminal in a non-existent folder. Since a new pane or tab is created based on the currently focused pane, the same error occurs not only in the tabe but also in the pane.

I seem to be aware of the problem with this. I'll try to fix it.
