### ISSUE TITLE
Copying on select doesn't copy (Wayland?)

### ISSUE THREAD

**Issue by jacksongoode** [zellij-org/zellij#994]
**Basic information**

`zellij --version`: 0.2.4
`tput lines`: Any
`tput cols`: Any
`uname -av` or `ver`(Windows): Fedora 35

**Further information**
Not sure if there needs to be some clipboard interaction but Wayland uses [wl-clipboard](https://github.com/bugaevc/wl-clipboard). Otherwise, I can help debug this issue if there are some other issues at play.

**Comment by tlinford** [comment]
what terminal emulator does this happen with?

**Comment by jacksongoode** [comment]
Ah, interestingly this works on foot, but it doesn't like GNOME terminal or the terminal I use that is based on VTE. So this really might be an issue with that framework.
