### ISSUE TITLE
vim not presenting/ freezing in a new pane

### ISSUE THREAD

**Issue by giyany** [zellij-org/zellij#997]
Hi guys,

Working with zellij 0.20.1 on Ubuntu 20.04.2 . When I ssh into a computer cluster and open vim, sometimes the pane would freeze, presenting only an ascii character (▽). If I 'fight' a bit and click a few keys, it'll refresh after ~10 seconds and present fine. This seems to be more common on a new tab, but the rule to this behaviour isn't clear to me.
Attached are the files from from running zellij with --debug

$tput lines 
61
$pout cols 
240
$uname -av
Linux Oxalis-triangularis 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cheers

[zellij-log.zip](https://github.com/zellij-org/zellij/files/7832920/zellij-log.zip)

**Comment by auronandace** [comment]
There have been quite a few changes since 0.20.1. Have you tried the latest release?

**Comment by giyany** [comment]
Hi, 
I'll update and see if it still occurs. Thanks!

**Comment by giyany** [comment]
Updating that since using the latest version, I have not encountered this bug. Suggesting to close the issue and re-open if it occurs.
