### ISSUE TITLE
Feature: rename an existing session

### ISSUE THREAD

**Issue by rednaz1337** [zellij-org/zellij#998]
First of all, thanks a lot for this great project!
Currently it's only possible to set the name when creating the session. The possibility to rename an existing session would be great though.

**Comment by jaeheonji** [comment]
Hi, @rednaz1337! Thank you for good suggestion!
This feature seems to be similar to Tmux's `rename-session`

> rename-session [-t target-session] new-name
                   (alias: rename)
             Rename the session to new-name.

So it would be good to classify this issue as Tmux Compatibility!

**Comment by tcoopman** [comment]
Now that we have the session manager, it would be nice to rename from the session manager as well

**Comment by tgross35** [comment]
Just to throw an idea out there, I would almost prefer to have editable session descriptions than session renaming - not that I wouldn't like to have both. But if there was a way to add a quick blurb "rustc box<dyn> rework" that shows up with `zellij ls`, that seems more useful to me than putting that information into a whitespace-free name.

**Comment by imsnif** [comment]
This has already been implemented: https://zellij.dev/news/session-resurrection-ui-components/

**Comment by imsnif** [comment]
There are 700+ issues open in this repo. I wish I had a whole team to deal with them so that everyone can stay up to date, but I'd rather spend my time developing the project :)

**Comment by chirag03k** [comment]
@reed9999 I'm reading the docs right now, and I actually I have no idea which session it's trying to rename or how to specify. How did you figure out what to do when there are multiple sessions that could potentially be renamed? (I have multiple terminals open with multiple Zellij sessions, to manage different workspaces for different projects)

```
❯ zellij action rename-session project-1-workspace
Please specify the session name to send actions to. The following sessions are active:
arcadian-newt [Created 1day 19h 59m 30s ago]
splendid-rustacean [Created 1day 21h 43m 39s ago]
likable-pheasant [Created 5days 1h 22m 55s ago]
```
